fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Take5__c/Take5__c.object-meta.xml
<CustomObject>
    <label>Take5</label>
    <nameField>
        <label>Take5 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Take5s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Take5__c/fields/Qualified_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Business_Unit__c</fullName>
    <label>Qualified Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anesthesia/Respiratory</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Cross BU</fullName>
            </value>
            <value>
                <fullName>Interventional Access</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Latin America Distributor</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/RetUrlSearchController.cls
public class RetUrlSearchController {
 public String nameQuery {get; set;}
 public List<User> Users {get; set;}
 public List<Note> assets {get; set;}
 public Take5__c take5;
 public User currentUser;
 public string bu {get;set;}
  
 public PageReference executeSearch()
 {
  String queryStr='%' + nameQuery + '%';
  If(queryStr.length() < 4){
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Must contain at least 2 characters'));
      Users=null;
      return null;
  }
  Users=[select id, Name, SmallPhotoUrl
            from User
            where name like :queryStr];
            
  return null;
 }
  
 public RetUrlSearchController()
 {
  // if query appears in URL, execute it
  String urlQuery=ApexPages.currentPage().getParameters().get('query');
   
  if ( (null!=urlQuery) && (0!=urlQuery.length()) )
  {
   nameQuery=urlQuery;
   executeSearch();
  }
 }

 public List<Note> getAssets() {
  currentUser = [select Business_Unit__c FROM User where Id=:Userinfo.getUserId() limit 1];
  bu = currentUser.Business_Unit__c;
  system.debug(currentUser);
  take5 = [select id FROM Take5__c WHERE Qualified_Business_Unit__c = :bu];
  assets = [select id FROM Note WHERE ParentId =:take5.Id];
  return assets;
 }

}