fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/CE_Reimbursement_Expense__c.object-meta.xml
<CustomObject>
    <label>CE Reimbursement/Expense</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Reimbursement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CE Reimbursement/Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/CE_Contractor_Email__c.field-meta.xml
<CustomField>
    <fullName>CE_Contractor_Email__c</fullName>
    <formula>Clinical_Educator_Name__r.E_mail_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CE/Contractor Email</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Contact_EMail__c.field-meta.xml
<CustomField>
    <fullName>Contact_EMail__c</fullName>
    <label>Contact EMail</label>
    <type>Email</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Education_Record__c.field-meta.xml
<CustomField>
    <fullName>Education_Record__c</fullName>
    <label>Education Record</label>
    <referenceTo>Education_Record__c</referenceTo>
    <relationshipLabel>CE Reimbursement/Expenses</relationshipLabel>
    <relationshipName>Education_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Email_Sent_to_AP__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent_to_AP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Sent to AP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/PresentationPrepTime__c.field-meta.xml
<CustomField>
    <fullName>PresentationPrepTime__c</fullName>
    <label>Presentation Prep Time</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Save</fullName>
                <default>true</default>
                <label>Save</label>
            </value>
            <value>
                <fullName>Submit CRF</fullName>
            </value>
            <value>
                <fullName>Submitted Manually (10/1/14 - 10/31/14)</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved for Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/TotalPresentation__c.field-meta.xml
<CustomField>
    <fullName>TotalPresentation__c</fullName>
    <formula>Reimbursement_Rate__c * (0.5* PresentationPrepTime__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Presentation Prep Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Travel_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Travel_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Travel Eligible</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Workflow_Travel_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Travel_Eligible__c</fullName>
    <formula>Pay_Rate_Card__r.Travel_Eligible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Workflow Travel Eligible</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CS_Education_Record__c/CS_Education_Record__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Education Records</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CS_Education_Record__c/fields/Administrative_Assistant_Email__c.field-meta.xml
<CustomField>
    <fullName>Administrative_Assistant_Email__c</fullName>
    <label>Administrative Assistant Email</label>
    <type>Email</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CS_Education_Record__c/fields/Business_Unit_Abbr__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Abbr__c</fullName>
    <label>Business Unit Abbreviation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CS_Education_Record__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>RecordType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CS_Education_Record__c/fields/SFDC_Admin_Email__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Admin_Email__c</fullName>
    <label>SFDC Admin Email</label>
    <type>Email</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/Education_Record__c.object-meta.xml
<CustomObject>
    <description>OnControl and EZIO Training Records</description>
    <label>Education Record</label>
    <nameField>
        <label>IS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <defaultValue>if(ISPICKVAL($User.Business_Unit__c, &quot;Alternate Care&quot;), &quot;Alternate Care&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Anesthesia&quot;), &quot;Anesthesia&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;EMS&quot;), &quot;EMS&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Interventional&quot;), &quot;Interventional&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Interventional Capital&quot;), &quot;Interventional Capital&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Respiratory&quot;), &quot;Respiratory&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Surgical Disposables&quot;), &quot;Surgical Disposables&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Surgical Instruments&quot;), &quot;Surgical Instruments&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Urology&quot;), &quot;Urology&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Vascular&quot;), &quot;Vascular&quot;,
if(ISPICKVAL($User.Business_Unit__c, &quot;Latin America&quot;), &quot;Latin America&quot;,
NULL
)))))))))))</defaultValue>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>Interventional Urology</fullName>
            </value>
            <value>
                <fullName>LatAm</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Copy_RecordType__c.field-meta.xml
<CustomField>
    <fullName>Copy_RecordType__c</fullName>
    <label>Copy: RecordType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education Program Request</fullName>
            </value>
            <value>
                <fullName>CMA Speaker Request</fullName>
            </value>
            <value>
                <fullName>CMA Procedural Lab</fullName>
            </value>
            <value>
                <fullName>Live Education Program Request</fullName>
            </value>
            <value>
                <fullName>Online Education Program Request</fullName>
            </value>
            <value>
                <fullName>Strategic Vascular Education Programs</fullName>
            </value>
            <value>
                <fullName>Inservice Record</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/CE_Reimbursement_Expense_Helper_Class.cls
public class CE_Reimbursement_Expense_Helper_Class {
    // Education_Helper_Class is the sister class
    public static void updateLookups(List<CE_Reimbursement_Expense__c> newTrigger){
        for(CE_Reimbursement_Expense__c ce : newTrigger){
            if(ce.Travel_Eligible__c != ce.Workflow_Travel_Eligible__c){
                ce.Travel_Eligible__c = ce.Workflow_Travel_Eligible__c;
            }
        }
    }
    
    public static void finalEmailtoAP(List<CE_Reimbursement_Expense__c> newTrigger){
        // This class looks at the Expense records and sends them to AP if they're ready.
        system.debug('Starting Opp Approval Info Trigger - After Update');
        
        List<Id> CRFIds = new List<Id>();
        for (CE_Reimbursement_Expense__c crf: newTrigger) {
            if(
                system.isFuture() == FALSE && 
                crf.Status__c == 'Approved for Payment' && 
                crf.Email_Sent_to_AP__c == FALSE
            ){
               CRFIds.add(CRF.Id); 
            } 
        }
        // Check the list size before calling the future call to reduce empty calls that are filling up the logs now. 12Sep2016 - ESC
        if(CRFIds.size() > 0){
            CE_Reimbursement_Expense_Helper_Class.sendemail(CRFIds);   
        }
    }
    
    // Moved from Education_Record_Update which is a VF controller class
    // 18Oct2017 - ESC
    @future(callout=true)
    Public static void sendemail(list<id> crfids){
        // Test Class: Education_Record_CE_Expenses_Form_Test

        // We now search for the template based on the above SOQL query by technical name. - ESC 16Sep2016
        Id templateId = [SELECT Id from EmailTemplate WHERE DeveloperName = 'CA_Check_Request_Form_Supa' LIMIT 1].Id;
        // Load in the Custom Settings in to list.
        list<CS_Education_Record__c> csList = CS_Education_Record__c.getall().values(); 
        // List to store the CC email addresses
        list<string> emailList = new list<string>();
        list<CE_Reimbursement_Expense__c> crfUpdateList = new list<CE_Reimbursement_Expense__c>();
        
        // Cycle through the records
        for (CE_Reimbursement_Expense__c crf: [SELECT Id, Name, CE_Contractor_Email__c, Education_Record__c, 
                                               Education_Record__r.Contact_Email__c,
                                               Education_Record__r.copy_recordtype__c, 
                                               Education_Record__r.business_unit__c,PresentationPrepTime__c,TotalPresentation__c
                                               FROM CE_Reimbursement_Expense__c 
                                               WHERE Id = :crfids ]) 
        {
            CE_Reimbursement_Expense__c updateCRF = new CE_Reimbursement_Expense__c(
                id = crf.Id,
                Email_Sent_to_AP__c = TRUE
            );
            crfUpdateList.add(updateCRF);
            
            emailList.clear(); // Empty out the list from previous loops/iterations

            system.debug('sendEmail to'+ crf.CE_Contractor_Email__c);
            String contEmail = crf.Education_Record__r.Contact_Email__c;
            
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            
            // Loop through the custom setting for the Administrative Assistants Email Address (18Oct2017 - ESC)
            for(CS_Education_Record__C cser : csList)
            {
                if(
                    cser.RecordType__c == crf.Education_Record__r.copy_Recordtype__c && 
                    cser.Business_Unit_Abbr__c == crf.Education_Record__r.business_unit__c
                )
                {
                    emailList.add(cser.Administrative_Assistant_Email__c);
                    emailList.add(cser.SFDC_Admin_Email__c); // This replaced the static email address.
                    //emailList.add('Kristin.Elliott@teleflex.com');   -- Let's kill the static email address.
                }
            }
            
            /* -- Old method was not properly bulked
            for(CS_Education_Record__C cser : [SELECT Administrative_Assistant_Email__c
                                               FROM CS_Education_Record__c
                                               WHERE RecordType__c =: crf.Education_Record__r.copy_Recordtype__c
                                               AND Business_Unit_Abbr__c =: crf.Education_Record__r.business_unit__C])
            {
                emailList.add(cser.Administrative_Assistant_Email__c);
                emailList.add('Kristin.Elliott@teleflex.com');
            }*/
            
            message.setCCAddresses(emailList);
            message.setReplyTo(contEmail); //added replyTo to fix issue with user's replying back to Salesforce.com Team
            message.setTemplateID(templateId); // Set above before the loop.
            
            // This set's the TO
            message.setTargetObjectId('003E000001ZTlRJ') ; // This is the AP Contract Record O_O
            //message.setTargetObjectId('003E000001WG2OF') ; // This is eric.clay@teleflex.com
            
            //sandbox message.setTargetObjectId('0035600000BrHrk') ;
            message.setWhatId(crf.Id);
            message.setSaveAsActivity(true);
            // Cath error in the attachments to A/p
            try{
                system.debug('*** Body to PDF ***');
            }
            catch(Exception e){
                system.debug('*** Failed to get Body as PDF ***');
            }
            
            List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
            
            for(Attachment a : [SELECT Id, Name, Body, BodyLength, ContentType 
                                FROM Attachment 
                                WHERE ParentId = :crf.Id])
            {
                // Add to attachment file list
                Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                If(a.ContentType<>'application/pdf'){
                    efa.setFileName(a.Name);
                }
                Else{
                    efa.setFileName(a.Name+'.pdf');
                    efa.setContentType('application/pdf');
                }
                efa.setBody(a.Body);
                efa.setcontenttype(a.ContentType);
                fileAttachments.add(efa);
            }
            message.setFileAttachments(fileAttachments);
            //Send Email with attachments
            try{
                system.debug('Sending email to A/P');
                Messaging.sendEmail(new Messaging.SingleEmailMessage[]{ message });
                update crfUpdateList; // Updates "Email Sent to Contractor" to TRUE
            }
            catch(Exception e){
                system.debug('Exception caught... no email was sent.' +e);
            }

        }//end of for loop

    }//end of sendemail method
}