fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Account_Count__c.field-meta.xml
<CustomField>
    <fullName>Account_Count__c</fullName>
    <description>Roll-up of all the related &apos;Contract Customer&apos; records used to determine limits when displaying in Visualforce.</description>
    <inlineHelpText>Roll-up of all the related &apos;Contract Customer&apos; records used to determine limits when displaying in Visualforce.</inlineHelpText>
    <label>Account Count</label>
    <summaryForeignKey>Contract_Customer__c.Agreement__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Material_Count__c.field-meta.xml
<CustomField>
    <fullName>Material_Count__c</fullName>
    <description>Roll-up of all the related &apos;Contract Material&apos; records used to determine limits when displaying in Visualforce.</description>
    <inlineHelpText>Roll-up of all the related &apos;Contract Material&apos; records used to determine limits when displaying in Visualforce.</inlineHelpText>
    <label>Material Count</label>
    <summaryForeignKey>Contract_Material__c.Agreement__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>if(RIGHT(Objective__c,1) = &quot;1&quot;, &quot;Direct/Rebate&quot;, 
if(RIGHT(Objective__c,1) = &quot;2&quot;, &quot;Direct&quot;, 
if(RIGHT(Objective__c,1) = &quot;3&quot;, &quot;Distributor Netbill&quot;, 
if(RIGHT(Objective__c,1) = &quot;4&quot;, &quot;Specialty Market&quot;, 
if(RIGHT(Objective__c,1) = &quot;5&quot;, &quot;Strategic Accounts&quot;, 
if(RIGHT(Objective__c,1) = &quot;6&quot;, &quot;Rebate Only&quot;, 
&quot;Not Defined&quot;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <label>Sub-Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Sub_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group_Name__c</fullName>
    <formula>CASE( Sub_Group__c, 
&quot;1&quot;,&quot;GPO&quot;, 
&quot;2&quot;,&quot;IDN&quot;, 
&quot;3&quot;,&quot;Distribution&quot;, 
&quot;4&quot;,&quot;Individual&quot;, 
&quot;5&quot;,&quot;Government&quot;, 
&quot;6&quot;,&quot;Courtesy&quot;, 
&quot;7&quot;,&quot;International&quot;, 
&quot;8&quot;,&quot;Other&quot;, 
&quot;9&quot;,&quot;Custom&quot;, 
&quot;10&quot;,&quot;VPS&quot;, 
&quot;Not Defined&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub-Group Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/Contract_Renewal__c.object-meta.xml
<CustomObject>
    <label>Contract Renewal</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Contract Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Renewals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Account_Count__c.field-meta.xml
<CustomField>
    <fullName>Account_Count__c</fullName>
    <label>Account Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Contract_Description__c.field-meta.xml
<CustomField>
    <fullName>Contract_Description__c</fullName>
    <label>Contract Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Contract_Header__c.field-meta.xml
<CustomField>
    <fullName>Contract_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Header</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/GPO_Contract_Ref__c.field-meta.xml
<CustomField>
    <fullName>GPO_Contract_Ref__c</fullName>
    <label>GPO Contract Ref</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <formula>CASE(Group__c,  
&quot;00&quot;,&quot;Urology&quot;,
&quot;01&quot;,&quot;Alt Site&quot;,
&quot;02&quot;,&quot;Anesthesia&quot;,
&quot;03&quot;,&quot;OEM&quot;,
&quot;04&quot;,&quot;Respiratory&quot;,
&quot;05&quot;,&quot;Surgical&quot;,
&quot;06&quot;,&quot;Critical Care&quot;,
&quot;07&quot;,&quot;GPO&quot;,
&quot;08&quot;,&quot;IDN&quot;,
&quot;09&quot;,&quot;Distribution&quot;,
&quot;10&quot;,&quot;Dialysis&quot;,
&quot;11&quot;,&quot;Specialty Markets&quot;,
&quot;12&quot;,&quot;Vascular Access&quot;,
&quot;13&quot;,&quot;Interventional&quot;,
&quot;14&quot;,&quot;Cardiac&quot;,
&quot;15&quot;,&quot;Cross Divisional&quot;,
&quot;Not Defined&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Material_Count__c.field-meta.xml
<CustomField>
    <fullName>Material_Count__c</fullName>
    <label>Material Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>if(Objective__c = &quot;01&quot;, &quot;Direct/Rebate (01)&quot;, 
if(Objective__c = &quot;02&quot;, &quot;Direct (02)&quot;, 
if(Objective__c = &quot;03&quot;, &quot;Distributor Netbill (03)&quot;, 
if(Objective__c = &quot;04&quot;, &quot;Specialty Market (04)&quot;, 
if(Objective__c = &quot;05&quot;, &quot;Strategic Accounts (05)&quot;, 
if(Objective__c = &quot;06&quot;, &quot;Rebate Only (06)&quot;, 
&quot;Not Defined&quot;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <label>Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Renewals1</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Do Not Renew</fullName>
            </value>
            <value>
                <fullName>Contract Audit</fullName>
            </value>
            <value>
                <fullName>Sales Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Ready for Renew</fullName>
            </value>
            <value>
                <fullName>Renewal Complete</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
                <isActive>false</isActive>
                <label>Expired</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <label>Sub-Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Sub_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group_Name__c</fullName>
    <formula>CASE( Sub_Group__c,
&quot;1&quot;,&quot;GPO&quot;,
&quot;2&quot;,&quot;IDN&quot;,
&quot;3&quot;,&quot;Distribution&quot;,
&quot;4&quot;,&quot;Individual&quot;,
&quot;5&quot;,&quot;Government&quot;,
&quot;6&quot;,&quot;Courtesy&quot;,
&quot;7&quot;,&quot;International&quot;,
&quot;8&quot;,&quot;Other&quot;,
&quot;9&quot;,&quot;Custom&quot;,
&quot;10&quot;,&quot;VPS&quot;,
&quot;Not Defined&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Group Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Contract_Renewal_Rep.cls
/*********************************************************************
* Description      : This class is used in the Contract Renewal Process
										 to help re-assign contracts to reps (Extension class).
* Test Class       : Contract_Renewal_Test
* VisualForce      : Contract_Renewal_Rep
* Author(s)        : Dun Silver
**********************************************************************/
public class Contract_Renewal_Rep {

	public ApexPages.StandardController stdController;
	public Contract_Renewal__c cr {get;set;}
	public List<User> userList {get;set;}
	public String strName {get;set;}
	public List<Contract_Renewal__c> crList {get;set;}
	public List<String> lstString = new List<String>();

	public Contract_Renewal_Rep(ApexPages.StandardController controller) {
		//stdController = controller;
		this.stdController = stdController;
		cr = new Contract_Renewal__c();
		getCrList();

	}//end of constructor

	//get list of contracts
	public List<Contract_Renewal__c> getCrList(){
		String contractId = ApexPages.currentPage().getParameters().get('contractId');
		System.debug('*** contractId *** ' + contractId);
		//cr = new Contract_Renewal__c();
	   	//List<Contract_Renewal__c> contracts = (Contract_Renewal__c)stdController.getRecord();
	   	//this.stdController = stdController;
	    	//lookupObj = new Contract_Renewal__c();
		if( contractId.contains(',') ){
			System.debug('*** In Contructor If Contains Comma *** ');
				lstString = contractId.split(',');
				//getCrList();
		}
		else{
			System.debug('*** In Contructor Else No Commas *** ');
				lstString.add(contractId);
				System.debug('*** lstString *** ' + lstString);
				//getCrList();
		}

		System.debug('*** In getCrList *** ');
		System.debug('*** lstString *** ' + lstString);
		crList = [SELECT Id,Status__c, Owner.Name, Agreement_Number__c, Contract_Description__c,
								 Owner__c, Owner_Name__c, GPO_Contract_Ref__c, Sales__c, Contract_Header__c,
								 Sales_Org__c, Distribution_Channel__c, Group__c, Group_Name__c, Account_Count__c,
								 Material_Count__c, Objective_Name__c, Sub_Group__c, Sub_Group_Name__c, Valid_From__c,
								 Valid_To__c, Business_Unit__c, Sales_Manager__r.Name, Sales_Rep__r.Name
								 FROM Contract_Renewal__c
								 WHERE Id IN :lstString];

		return crList;
	}
	//get list of users from search
	public void getUserList(){
        //strName = Apexpages.currentpage().getParameters().get('searchText');
        String search = '%'+strName+'%';
        system.debug('*** search *** '+ search);
        userList = [SELECT id, Name, Business_Unit__c, Manager.Name, UserRole.Name, License_Name__c
        					FROM User
        					WHERE Name LIKE :search AND isActive = true AND License_Name__c = 'Salesforce'];

        system.debug('*** userList.size() *** ' + userList.size() );
        system.debug('*** userList *** ' + userList);

        //return userList;
    }
    //end of method to get line items

    public PageReference setNewOwner(){
    	String uId = ApexPages.currentPage().getParameters().get('uId');
    	String contractId = ApexPages.currentPage().getParameters().get('contractId');
			List<Contract_Renewal__c> updOwnerList = new List<Contract_Renewal__c>();

    	system.debug('*** uId *** '+ uId);
    	for(Contract_Renewal__c curr : getCrList()){
				curr.OwnerId = uId;
				updOwnerList.add(curr);
			}

    	//Contract_Renewal__c newOwner = new Contract_Renewal__c(Id=contractId, OwnerId=uId);
    	update updOwnerList;

    	PageReference refreshContract = new Pagereference('/apex/Contract_Renewal_Rep?contractId='+contractId).setRedirect(true);
     return refreshContract;
    }
}//end of class