fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/user_Helper_Class.cls
public class user_Helper_Class {
    
    public static void beforeHelper(List<User> newTrigger,map<id,User> oldtrigger,string trigType){
        
        Map<String, Business_Unit__c> buMap = Business_Unit__c.getAll();
        for(User u : newTrigger){
            if(trigType == 'insert'){
                if(u.Business_Unit_Key__c == NULL && u.Business_Unit__c != NULL){
                    if(buMap.get(u.Business_Unit__c) != NULL){
                        u.Business_Unit_Key__c = buMap.get(u.Business_Unit__c).Key__c;                    
                    }
                }
            }
            else if(trigType == 'update'){
                if((u.Business_Unit_Key__c == NULL && u.Business_Unit__c != NULL) || 
                   (u.Business_Unit__c != NULL && oldtrigger.get(u.Id).Business_Unit__c != u.Business_Unit__c))
                {
                    if(buMap.get(u.Business_Unit__c) != NULL){
                        u.Business_Unit_Key__c = buMap.get(u.Business_Unit__c).Key__c;                    
                    }
                }
                else if(u.Business_Unit__c == NULL){
                    u.Business_Unit_Key__c = '';
                }
            }
        }
    }

}