fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/Territory_User__c.object-meta.xml
<CustomObject>
    <label>Territory User</label>
    <nameField>
        <displayFormat>TU-{0000000}</displayFormat>
        <label>Territory User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Users</relationshipLabel>
    <relationshipName>Territory_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/Zip_Code_Territories__c.object-meta.xml
<CustomObject>
    <label>Zip Code Territories</label>
    <nameField>
        <label>Zip Code Territories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Alternate_Care__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Care__c</fullName>
    <label>Alternate Care</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Anesthesia__c.field-meta.xml
<CustomField>
    <fullName>Anesthesia__c</fullName>
    <label>Anesthesia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/EMS__c.field-meta.xml
<CustomField>
    <fullName>EMS__c</fullName>
    <label>EMS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/IA__c.field-meta.xml
<CustomField>
    <fullName>IA__c</fullName>
    <label>IA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Respiratory__c.field-meta.xml
<CustomField>
    <fullName>Respiratory__c</fullName>
    <label>Respiratory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Surgical_Disposables__c.field-meta.xml
<CustomField>
    <fullName>Surgical_Disposables__c</fullName>
    <label>Surgical Disposables</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Surgical_Instruments__c.field-meta.xml
<CustomField>
    <fullName>Surgical_Instruments__c</fullName>
    <label>Surgical Instruments</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Urology__c.field-meta.xml
<CustomField>
    <fullName>Urology__c</fullName>
    <label>Urology</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Vascular__c.field-meta.xml
<CustomField>
    <fullName>Vascular__c</fullName>
    <label>Vascular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Zip_Code_Territories_Lookup_Test.cls
@isTest
public class Zip_Code_Territories_Lookup_Test {
    static testmethod void myUnitTest() {
      
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User(
            Alias = 'standt', 
            Email='standarduser76@testorg.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', 
            UserName='TeleflexTESTER@teleflex.test.com'
        );
        insert u;
        System.debug('Insert User-->' + u);
        
        Territory_Master__c tm = new Territory_Master__c(
            Name = '800123',
            Territory_Number__c = '800123',
            Business_Unit__c = 'EMS'
        );
        insert tm;
        System.debug('Insert Territory Master-->' + tm);
        
        Territory_User__c tu = new Territory_User__c(
            Territory_Master__c = tm.Id,
            User__c = u.id
        );
        
        insert tu;
        System.debug('Insert Territory User-->' + tu);
                
        Zip_Code_Territories__c zipt = new Zip_Code_Territories__c(
            Name='Test',
            Alternate_Care__c ='800123', 
            Anesthesia__c ='800123', 
            EMS__c='800123', 
            IA__c='800123',
            Respiratory__c='800123',
            Surgical_Instruments__c='800123', 
            Surgical_Disposables__c='800123',
            Urology__c='800123',
            Vascular__c='800123'
        );
        Insert zipt;
    Test.startTest();
        PageReference pageRef = new PageReference('/apex/Zip_Code_Territories_Section');
    	Test.setCurrentPage(pageRef);
        Zip_Code_Territories_Lookup testcontroller = new Zip_Code_Territories_Lookup (new ApexPages.StandardController(zipt));
        testcontroller.getAlt_Care();
        testcontroller.getAnesthesia();
        testcontroller.getEMS();
        testcontroller.getRespiratory();
        testcontroller.getIA();
        testcontroller.getSurg_Inst();
        testcontroller.getSurg_Disp();
        testcontroller.getUrology();
        testcontroller.getVascular(); 
    Test.stopTest();   
	}
}