fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Take5__c/Take5__c.object-meta.xml
<CustomObject>
    <label>Take5</label>
    <nameField>
        <label>Take5 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Take5s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Take5__c/fields/Eligible_Start__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Start__c</fullName>
    <label>Eligible Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Take5__c/fields/Eligible_Stop__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Stop__c</fullName>
    <label>Eligible Stop</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Take5__c/fields/Qualified_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Business_Unit__c</fullName>
    <label>Qualified Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anesthesia/Respiratory</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Cross BU</fullName>
            </value>
            <value>
                <fullName>Interventional Access</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Latin America Distributor</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/take5Test.cls
@isTest
public class take5Test {
    static testMethod void take5Test() {

        Profile p = [select id from profile where name='System Administrator'];
        User tu1 = new User(Username='testing0@teleflex.com.testuser',Email='testuser@teleflex.com',Business_Unit__c = 'Anesthesia/Respiratory', Lastname='User', Firstname='Test', Alias='tuser1',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');

        Date todaysDate = date.today();
        Take5__c t5 = new Take5__c(Qualified_Business_Unit__c='Anesthesia/Respiratory',Eligible_Start__c=todaysDate,Eligible_Stop__c=todaysDate);
        insert t5;

        Note newNote = new Note(Title='test',Body='http://www.google.com',ParentId=t5.Id);
        insert newNote;

        system.runAs(tu1){
            take5AssetController t5ac = new take5AssetController();
            t5ac.getNotes();

        }
    }
}