fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/Invoiced_Sales__c.object-meta.xml
<CustomObject>
    <description>Invoiced Sales is the official name that SAP sales that have are shipped and counted towards compensation.</description>
    <label>Invoiced Sales</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Invoiced Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Primary_Territory_User__c.field-meta.xml
<CustomField>
    <fullName>Primary_Territory_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Territory User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Master2</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ASR</fullName>
            </value>
            <value>
                <fullName>Clinical Manager</fullName>
                <label>Clinical  Education Manager</label>
            </value>
            <value>
                <fullName>Clinical Specialists</fullName>
            </value>
            <value>
                <fullName>Corporate Sales</fullName>
            </value>
            <value>
                <fullName>DNA</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>KAM</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>MDM</fullName>
            </value>
            <value>
                <fullName>Sales Director</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
                <default>true</default>
                <label>Sales Rep</label>
            </value>
            <value>
                <fullName>Sales VP</fullName>
            </value>
            <value>
                <fullName>Service Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used to concatenate the Territory Number with the Primary Territory User Full Name.</inlineHelpText>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/Territory_User__c.object-meta.xml
<CustomObject>
    <label>Territory User</label>
    <nameField>
        <displayFormat>TU-{0000000}</displayFormat>
        <label>Territory User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Rep</fullName>
                <default>true</default>
                <label>Sales Rep</label>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Director</fullName>
            </value>
            <value>
                <fullName>Sales VP</fullName>
            </value>
            <value>
                <fullName>Service Rep</fullName>
            </value>
            <value>
                <fullName>Clinical Specialists</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Users</relationshipLabel>
    <relationshipName>Territory_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/InvoicedSalesAccountShareBatch.cls
global class InvoicedSalesAccountShareBatch implements database.Batchable<sObject>,database.stateful, Schedulable
{
    global integer  totalTuSuccessess =0;
    global integer  totalTuFailures   =0;
    global integer  totalUsSuccessess  =0;
    global integer  totalUsFailures   =0;
    global integer  totalAtmSuccessess =0;
    global integer  totalAtmFailures  =0;
    public string   query ='SELECT id,Account__c,territory__c from Invoiced_Sales__c WHERE CreatedDate=THIS_MONTH';
    
    //start method of the batch
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        
      // String query = 'SELECT id,Account__c,territory__c from Invoiced_Sales__c WHERE CreatedDate=THIS_MONTH';
        return Database.getQueryLocator(query);}
    
    global void execute(Database.BatchableContext BC, List<Invoiced_Sales__c> scope){ 
        
        System.debug('*** Starting shareAccountAndAddToAccountTeam in Invoiced_Sales_Helper_Class ***');
        
        Set<Id> territoryMasterIds = new Set<Id>();
        for(Invoiced_Sales__c sale: scope){
            
            //Insert case
            if(string.isNotEmpty(sale.Territory__c)){
                territoryMasterIds.add(sale.Territory__c);
            }
        }
        
        Map<Id, Territory_Master__c> territoryMap = new Map<Id, Territory_Master__c>([SELECT Id, Sales_Rep__c , Primary_Territory_User__c, Business_Unit__c, 
                                                                                      (SELECT Id, User__c From Territory_Users__r)
                                                                                      FROM Territory_Master__c
                                                                                      WHERE Id IN:territoryMasterIds]);
        
        Map<String, Territory_User__c> territoryUsersToInsert = new Map<String, Territory_User__c>();
        Map<String, AccountShare> shareRecsToInsert = new Map<String, AccountShare>();
        Map<String, AccountTeamMember> accTeamMemRecs = new Map<String, AccountTeamMember>();
        
        for(Invoiced_Sales__c sale: scope){
            if(string.isNotEmpty(sale.Account__c) && string.isNotEmpty(sale.Territory__c) && territoryMap.containsKey(sale.Territory__c)){
                Territory_Master__c tm = territoryMap.get(sale.Territory__c);
                system.debug('tm'+tm);
                if(string.isNotEmpty(tm.Sales_Rep__c) || string.isNotEmpty(tm.Primary_Territory_User__c))
                {
                    Id repId = string.isNotEmpty(tm.Sales_Rep__c) ? tm.Sales_Rep__c : tm.Primary_Territory_User__c;
                    Boolean territoryUserForRepExists = false;
                    for(Territory_User__c territoryUser: tm.Territory_Users__r){
                        if(territoryUser.User__c == repId){
                            territoryUserForRepExists = true;
                        }
                    }
                    String userkey = repId+'|'+tm.Id;
                    if(!territoryUserForRepExists && !territoryUsersToInsert.containsKey(userkey)){
                        Territory_User__c addTU = new Territory_User__c(
                            User__c = repId,
                            Business_Unit__c = tm.Business_Unit__c,
                            Role__c = 'Sales Rep',
                            Territory_Master__c = tm.Id,
                            Primary__c = true
                        );
                        territoryUsersToInsert.put(userkey, addTU);
                    }
                    String tmkey = repId+'|'+sale.Account__c;
                    if(!accTeamMemRecs.containsKey(tmkey)){
                        AccountTeamMember addATM = new AccountTeamMember(
                            AccountId = sale.Account__c,
                            TeamMemberRole = 'Sales Rep',
                            UserId = repId,
                            Access_Granted_Type__c='Automation'
                        );
                        accTeamMemRecs.put(tmkey,addATM);
                    }
                    String askey = repId+'|'+sale.Account__c;
                    if(!shareRecsToInsert.containsKey(askey)){
                        AccountShare addAS = new AccountShare(
                            AccountId = sale.Account__c,
                            OpportunityAccessLevel = 'None',
                            CaseAccessLevel = 'None',
                            AccountAccessLevel = 'Edit',
                            UserOrGroupId = repId
                        );
                        shareRecsToInsert.put(askey,addAS);
                    }
                }
            }
        }
        
        if(territoryUsersToInsert.values() != null && territoryUsersToInsert.values().size()>0){
            system.debug('territoryUsersToInsert:'+territoryUsersToInsert.values());
            database.SaveResult[] myResult=database.insert(territoryUsersToInsert.values(),false);
            for(database.SaveResult s:myResult){
                if(s.isSuccess()){
                    totalTuSuccessess++;
                }
                else{
                    totalTuFailures++;  
                }
            }
        }
        
        if(shareRecsToInsert.values() != null && shareRecsToInsert.values().size()>0){
            system.debug('shareRecsToInsert:'+shareRecsToInsert.values());
            database.SaveResult[] myResult=database.insert(shareRecsToInsert.values(),false);
            for(database.SaveResult s:myResult){
                if(s.isSuccess()){
                    totalUsSuccessess++;
                }
                else{
                    totalUsFailures++;  
                }
            }
        }
        
        if(accTeamMemRecs.values() != null && accTeamMemRecs.values().size()>0){
            system.debug('accTeamMemRecs:'+accTeamMemRecs.values());
            database.SaveResult[] myResult=database.insert(accTeamMemRecs.values(),false);
            for(database.SaveResult s:myResult){
                if(s.isSuccess()){
                    totalAtmSuccessess++;
                }
                else{
                    totalAtmFailures++;  
                }
            }
        }
    }
    global void finish(Database.BatchableContext BC)
    {
        
        AsyncApexJob a = [Select Id,CreatedBy.Email    from AsyncApexJob where Id =:BC.getJobId()];
        system.debug('InvoicedSalesAccountShareBatch Completed! Sending Email to '+a.CreatedBy.Email);
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('InvoicedSalesAccountShareBatch Completed!');
        mail.setPlainTextBody('TerritoryUsers Successess: ' + totalTuSuccessess +   ' Failures: '+ totalTuFailures + ' AccountShare Successess: ' + totalUsSuccessess +   ' Failures: '+ totalUsFailures + ' AccountTeamMember Successess: ' + totalAtmSuccessess +   ' Failures: '+ totalAtmFailures  );
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
    }
    global void execute(SchedulableContext sc)
    {
        InvoicedSalesAccountShareBatch b = new  InvoicedSalesAccountShareBatch ();
        
        database.executebatch(b,200);
    }
}