fullSandbox11072023/force-app/main/default/objects/Product2/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Buom__c.field-meta.xml
<CustomField>
    <fullName>Buom__c</fullName>
    <label>Buom</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>This is the unconverted Cost from SAP</inlineHelpText>
    <label>Cost Raw</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Cost_Price_Unit__c.field-meta.xml
<CustomField>
    <fullName>Cost_Price_Unit__c</fullName>
    <label>Cost Price Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <inlineHelpText>10 - Respiratory and Anesthesia (TFX Only), 
20 - Surgical, 
30 - Surgical, 
40 - Vascular, 
50 - Anesthesia (Arrow Only), 
60 - Cardiac</inlineHelpText>
    <label>Division</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Each_per_Case__c.field-meta.xml
<CustomField>
    <fullName>Each_per_Case__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Each per Case</description>
    <inlineHelpText>Each per Case</inlineHelpText>
    <label>Each per Case</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <externalId>true</externalId>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Material_Status__c.field-meta.xml
<CustomField>
    <fullName>Material_Status__c</fullName>
    <description>Gives the status of the material</description>
    <label>Material Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Material_Status_Numeric__c.field-meta.xml
<CustomField>
    <fullName>Material_Status_Numeric__c</fullName>
    <description>SAP: X-distr.chain status</description>
    <inlineHelpText>Saleable Statuses: 40, 60, Z1, Z8, and Z5 when List &gt; Zero.</inlineHelpText>
    <label>Material Status Numeric</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Qty_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Qty_Sales_Unit__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty/Sales Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Rep_Price__c.field-meta.xml
<CustomField>
    <fullName>Rep_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>ZRST</inlineHelpText>
    <label>Rep Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/RSM_Price__c.field-meta.xml
<CustomField>
    <fullName>RSM_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>ZASD</inlineHelpText>
    <label>RSM Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit__c</fullName>
    <defaultValue>&quot;EA&quot;</defaultValue>
    <label>Sales Unit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <description>Sales Business Unit</description>
    <label>SBU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/SubGroup__c.field-meta.xml
<CustomField>
    <fullName>SubGroup__c</fullName>
    <label>SubGroup</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Sales Unit of Measure 
CS - Case
EA - Each</description>
    <inlineHelpText>Sales Unit of Measure 
CS - Case
EA - Each</inlineHelpText>
    <label>UOM</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/ProductImageUrls__c/ProductImageUrls__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to hold Product Image Urls</description>
    <label>ProductImageUrls</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/ProductImageUrls__c/fields/EndpointSuffix__c.field-meta.xml
<CustomField>
    <fullName>EndpointSuffix__c</fullName>
    <description>EndpointSuffix</description>
    <inlineHelpText>EndpointSuffix</inlineHelpText>
    <label>EndpointSuffix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/ProductImageUrls__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <description>Group</description>
    <inlineHelpText>Group</inlineHelpText>
    <label>Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/ProductImageUrls__c/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <description>SBU</description>
    <inlineHelpText>SBU</inlineHelpText>
    <label>SBU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/UpdateProductImageCont_Test.cls
@IsTest
public class UpdateProductImageCont_Test {
    @testSetup static void setup() {
        
        // Create common test leads
        List<ProductImageUrls__c> testCustomSettings = new List<ProductImageUrls__c>();
        testCustomSettings.add(new ProductImageUrls__c(Name='Default', EndpointSuffix__c='surgical/rusch/pain/products/'));
        insert testCustomSettings;
        
        //create test product
        Product2 prodTest = new Product2(
            Name = '353535',ProductCode= '353535',UOM__c='CS',
            Each_per_Case__c=5,Material_Status__c='MTS',Material_Status_Numeric__c='30',
            Family = 'Hardware',Material__c='353535',Brand_Name__c='Arrow',
            Buom__c='EA',Class__c='Cardiac Care Specialty',Cost__c=11587.40,
            Cost_Price_Unit__c=1000,Division__c='60',Description='TRANSRADIAL ACCESS TRAY',
            Group__c='Regional Anesthesia',SubGroup__c = 'TransRadial Access',
            Qty_Sales_Unit__c=5,Sales_Unit__c='CS',SBU__c='Anesthesia',
            List_Price__c=380.00,Rep_Price__c=350.00,
            Sales_Org__c = 'US10',Distribution_Channel__c = '10',
            Sales_Org_Key__c = 'US103010',RSM_Price__c=330.00
        );
        //prodList.add(prodTest.Name);
        insert prodTest;        
    }
    
    //method to test Anesthesia brand
    public static testMethod void testProductImageUpdate(){
        String body = '{"id":24849,"product_code":"353535","name":"DEBAKEY PERIPHERAL VASCULAR CLAMP",'+
      '"product-description":"ANGLED, 3 3/4\\" (9.4cm) tip length, 2.8mm tip width, Curved shaft, 7 1/8\\" (18cm)",'+
      '"images":[{"format":"details","urls":["https://www.teleflexarcatalog.com/images/products/pilling/details/SR_353535.jpg",'+
      '"https://www.teleflexarcatalog.com/images/products/pilling/details/SR_353535_CU.jpg"]},'+
      '{"format":"hi-res","urls":["https://www.teleflexarcatalog.com/images/products/pilling/hi-res/SR_353535.jpg",'+
      '"https://www.teleflexarcatalog.com/images/products/pilling/hi-res/SR_353535_CU.jpg"]},'+
      '{"format":"listing","urls":["https://www.teleflexarcatalog.com/images/products/pilling/listing/SR_353535.jpg",'+
      '"https://www.teleflexarcatalog.com/images/products/pilling/listing/SR_353535_CU.jpg"]},'+
      '{"format":"thumb","urls":["https://www.teleflexarcatalog.com/images/products/pilling/thumb/SR_353535.jpg",'+
      '"https://www.teleflexarcatalog.com/images/products/pilling/thumb/SR_353535_CU.jpg"]}],'+
      '"url":"https://www.teleflexarcatalog.com/anesthesia-respiratory/pain/products/24849"}';
        // Set single mock implementation that responds dynamically to different requests

        try{
           test.startTest();
            SingleRequestMock fakeResponse = new SingleRequestMock(200,'OK',body,null);
            Test.setMock(httpCalloutMock.class, fakeResponse);
            Product2 p = [SELECT Id
                         FROM Product2
                         Where Name = '353535'];
            UpdateProductImageCont.updateImageUrl(p.Id);
            test.stopTest();
         }
         catch(exception e){}
    }
}