fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/Lab_Participant__c.object-meta.xml
<CustomObject>
    <label>Lab Participant</label>
    <nameField>
        <label>Lab Participant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
            <value>
                <fullName>Cardiac</fullName>
            </value>
            <value>
                <fullName>Interventional Access</fullName>
            </value>
            <value>
                <fullName>LMA</fullName>
            </value>
            <value>
                <fullName>Specialty Markets</fullName>
            </value>
            <value>
                <fullName>Vidacare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Zip_Code_Auto_Route__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Auto_Route__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Zip Code Auto Route</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Zip_Code_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Business_Unit__c</fullName>
    <formula>IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Hos&quot;, &quot;Vascular&quot;, 
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 2) = &quot;ED&quot;, &quot;Vascular&quot;, 
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;EMS&quot;, &quot;EMS&quot;, 
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Int&quot;, &quot;Interventional Access&quot;, 
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Ane&quot;, &quot;Anesthesia&quot;, 
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Sur&quot;, &quot;Surgical Instruments&quot;, 
&quot;&quot; 
))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Zip_Code_Territories__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Territories__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code Territories</label>
    <referenceTo>Zip_Code_Territories__c</referenceTo>
    <relationshipLabel>Lab Participants</relationshipLabel>
    <relationshipName>Lab_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Zip_Code_Territory_User__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Territory_User__c</fullName>
    <formula>if(Zip_Code_Business_Unit__c = &quot;Vascular&quot;, Zip_Code_Territories__r.Vascular__c,
if(Zip_Code_Business_Unit__c = &quot;EMS&quot;, Zip_Code_Territories__r.EMS__c,
if(Zip_Code_Business_Unit__c = &quot;IA&quot;, Zip_Code_Territories__r.IA__c,
if(Zip_Code_Business_Unit__c = &quot;Anesthesia&quot;, Zip_Code_Territories__r.Anesthesia__c,
&quot;&quot;
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code Territory User</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Zip_Code_Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Zip__c</fullName>
    <formula>LEFT(Mailing_Zip_Code__c, 5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code Zip</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Specialty Markets</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Surgical Percuvance</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Zip_Code_Auto_Route__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Auto_Route__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field used to drive whether the Zip Code Territory automation fires again (if false).</description>
    <inlineHelpText>Please uncheck when you want to evaluate and assign this lead using territory rules.</inlineHelpText>
    <label>Do Not Assign Lead using Territory rules</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Zip_Code_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Business_Unit__c</fullName>
    <formula>IF(!ISBLANK(TEXT(Business_Unit__c)), TEXT(Business_Unit__c),
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Hos&quot;, &quot;Vascular&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;EMS&quot;, &quot;EMS&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Int&quot;, &quot;IA&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Ane&quot;, &quot;Anesthesia&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Sur&quot;, &quot;Surgical&quot;,
&quot;&quot;
))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Zip_Code_Territories__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Territories__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zip Code Territories</label>
    <referenceTo>Zip_Code_Territories__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Zip_Code_Territory_User__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Territory_User__c</fullName>
    <description>This will not support all SBU&apos;s so will have to show this with the trigger...</description>
    <formula>if(ISPICKVAL(Business_Unit__c, &quot;Anesthesia&quot;),  Zip_Code_Territories__r.Anesthesia__c,
if(ISPICKVAL(Business_Unit__c, &quot;Surgical&quot;), Zip_Code_Territories__r.Surgical_Instruments__c,
if(ISPICKVAL(Business_Unit__c, &quot;EMS&quot;), Zip_Code_Territories__r.EMS__c,
if(ISPICKVAL(Business_Unit__c, &quot;Respiratory&quot;), Zip_Code_Territories__r.Respiratory__c,
if(ISPICKVAL(Business_Unit__c, &quot;Surgical Disposables&quot;), Zip_Code_Territories__r.Surgical_Disposables__c,
if(ISPICKVAL(Business_Unit__c, &quot;Surgical Instruments&quot;), Zip_Code_Territories__r.Surgical_Instruments__c,
if(ISPICKVAL(Business_Unit__c, &quot;Surgical Percuvance&quot;), Zip_Code_Territories__r.Surgical_Percuvance__c,
if(ISPICKVAL(Business_Unit__c, &quot;Vascular&quot;), Zip_Code_Territories__r.Vascular__c,
if(ISPICKVAL(Business_Unit__c, &quot;Interventional Access&quot;),  Zip_Code_Territories__r.IA__c,
&quot;&quot;
)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code Territory User</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Zip_Code_Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Zip__c</fullName>
    <formula>LEFT(PostalCode, 5)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code Zip</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead_Settings__c/Lead_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Leading Routing - These settings are used to change the record type and for routing leads to the appropriate queue.</description>
    <label>Lead Settings</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Lead_Settings__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/Territory_User__c.object-meta.xml
<CustomObject>
    <label>Territory User</label>
    <nameField>
        <displayFormat>TU-{0000000}</displayFormat>
        <label>Territory User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/Zip_Code_Territories__c.object-meta.xml
<CustomObject>
    <label>Zip Code Territories</label>
    <nameField>
        <label>Zip Code Territories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <externalId>true</externalId>
    <label>Zip Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/territory_zipcode.cls
public class territory_zipcode {
    /*
    public static void zipLookup(String objName, List<sObject> newTrigger){
        System.debug('Starting --------- ZipLookup! -------');
        set<String> zips = new set<String>();
        for(sObject s : newTrigger){
            zips.add(String.valueOf(s.get('Zip_Code_Zip__c')));
            System.debug('Adding this ZIP to the list: ' + String.valueOf(s.get('Zip_Code_Zip__c')));
        }
        
        Map<String, Id> listZip = new Map<String, Id>();
        for(Zip_Code_Territories__c zcMap : [SELECT Zip_Code__c, Id FROM Zip_Code_Territories__c WHERE Zip_Code__c IN :zips]){
            listZip.put(zcMap.Zip_Code__c, zcMap.Id);
            System.debug('Zip Code Map:' + listZip); 
        }
        
        System.debug('listZip Size: ' + listZip.size());         
        list<sObject> updateZip = new list<sObject>();
        
        for(sObject s : newTrigger){
            if(String.valueOf(s.get('Zip_Code_Zip__c')) != NULL && (String.valueOf(s.get('Business_Unit__c')) != NULL || String.valueOf(s.get('Zip_Code_Business_Unit__c')) != NULL) && listZip.size() > 0){
                
                if(Trigger.isAfter){
                    // Gets the Object Type and creates the new record
                    sObject addObj = Schema.getGlobalDescribe().get(objName).newSObject();
                    
                    //addObj.put('Zip_Code_Auto_Route__c', TRUE);
                    addObj.put('id', s.get('id'));
                    addObj.put('Zip_Code_Territories__c', listZip.get(String.valueOf(s.get('Zip_Code_Zip__c'))));
                    
                    //if(String.valueOf(s.get('s.Business_Unit__c')) == NULL && objName == 'Lead'){
                    //    addObj.put('Business_Unit__c', String.valueOf(s.get('s.Zip_Code_Business_Unit__c')));                        
                    //}

                    system.debug('Adding Zip Code Record for Update: ' + addObj);
                    updateZip.add(addObj);

                }
                else{
                    System.debug('Zip Map Debug -------' + listZip.get(String.valueOf(s.get('Zip_Code_Zip__c'))));
                    System.debug('Zip Code -------' + String.valueOf(s.get('Zip_Code_Zip__c')));

                    s.put('Zip_Code_Territories__c', listZip.get(String.valueOf(s.get('Zip_Code_Zip__c'))));
                }
            }
        }
        if(updateZip.size() > 0){
            update updateZip;
            system.debug('System Update with:' + updateZip);
        }
        System.debug('--------- Finished with ZipLookup! -------');
    }

    public static void userAssign2(list<Lead> newTrigger){
        // Method looks at the related Zip Code Territory record and the business unit and
        // Assigns the related 'active' territory user.
        System.debug('--------- Starting UserAssign! -------');
        set<String> usrs = new set<String>();
        
        for(Lead lpu : newTrigger){
            usrs.add(lpu.Zip_Code_Territory_User__c);
        }
        Map<String, ID> listUsrs = new Map<String, ID>();
        
        for(Territory_User__c usrMap : [SELECT Territory_Master__r.name, User__c 
                                        FROM Territory_User__c 
                                        WHERE Territory_Master__r.name IN :usrs AND User__r.IsActive = TRUE])
        {
            listUsrs.put(usrMap.Territory_Master__r.name, usrMap.User__c);
            System.debug('Map List Debug:Name -------' + usrMap.Territory_Master__r.name);
            System.debug('Map List Debug:UserId -------' + usrMap.User__c);
        }
        
        list<sObject> updateObj = new list<sObject>();
        List<Lead_Settings__c> ldoList = new List<Lead_Settings__c>();
        ldoList.addAll(Lead_Settings__c.getAll().values());
        
        Map<String, Lead_Settings__c> lsMap = new Map<String, Lead_Settings__c>();
        Map<String, Id> qMap = new Map<String, Id>();
        Map<String, Id> rMap = new Map<String, Id>();
        for(Lead_Settings__c ls : ldoList){
            lsMap.put(ls.Name, ls);
            qMap.put(ls.Name, ls.Lead_Owner_ID__c);
            rMap.put(ls.Name, ls.Record_Type_ID__c);
        }
        system.debug('Lead Map: ' + qMap);
        
        
        

        list<lead> lUpdate = new list<lead>();
        for(lead l : newTrigger){
            if(l.Zip_Code_Auto_Route__c == FALSE && listUsrs.size() > 0 && listUsrs.get(l.Zip_Code_Territory_User__c) != NULL){

                string sbu = l.Zip_Code_Business_Unit__c;
                string ownerID = l.Zip_Code_Territory_User__c;
                string recordID = rMap.get(sbu);
                system.debug('List User (Check for NULL): ' + ownerID);

                lead ladd = new lead();
                ladd.Id = l.Id;
                ladd.Zip_Code_Auto_Route__c = TRUE;
                
                
                if(recordID != NULL){
                    ladd.RecordTypeId = rMap.get(sbu);
                }
                else{
                    ladd.RecordTypeId = rMap.get('Default');
                }
                if(ownerID != NULL){
                    if(qMap.get(sbu) == NULL){
                        ladd.ownerID = qMap.get(sbu);
                    }
                    else{
                        ladd.ownerID = qMap.get('Default');    
                    }
                }
                
                lUpdate.add(ladd);
            }
        }
        if(lUpdate.size() > 0){
            update lUpdate;
        }
    }

    
    public static void userAssign(String objName, List<sObject> newTrigger){
        if(master_TriggerHelperClass.qd('ZipCode_User_Assign')){
            System.debug('--------- Starting UserAssign! -------');
            set<String> usrs = new set<String>();
            string zipusradd;
            string altusradd;
            for(sObject s : newTrigger){
                zipusradd = String.valueOf(s.get('Zip_Code_Territory_User__c'));
                altusradd = String.valueOf(s.get('Territory_Based_Owner__c'));
                if(zipusradd != NULL){
                    usrs.add(zipusradd);
                }
                else if(zipusradd != NULL){
                    usrs.add(altusradd);
                }
                System.debug('zipusradd and altusradd: ' + zipusradd + ' and ' + altusradd);
                System.debug('User Set: ' + usrs);
            }
            Map<String, ID> listUsrs = new Map<String, ID>();
            
            for(Territory_User__c usrMap : [SELECT Territory_Master__r.name, User__c 
                                            FROM Territory_User__c 
                                            WHERE Territory_Master__r.name IN :usrs 
                                            AND User__r.IsActive = TRUE])
            {
                listUsrs.put(usrMap.Territory_Master__r.name, usrMap.User__c);
                System.debug('Map List Debug:Name -------' + usrMap.Territory_Master__r.name);
                System.debug('Map List Debug:UserId -------' + usrMap.User__c);
            }
            
            
            list<sObject> updateObj = new list<sObject>();
            List<Lead_Settings__c> ldoList = new List<Lead_Settings__c>();
            ldoList.addAll(Lead_Settings__c.getAll().values());
            
            Map<String, Lead_Settings__c> lsMap = new Map<String, Lead_Settings__c>();
            Map<String, Id> qMap = new Map<String, Id>();
            Map<String, Id> rMap = new Map<String, Id>();
            for(Lead_Settings__c ls : ldoList){
                lsMap.put(ls.Name, ls);
                qMap.put(ls.Name, ls.Lead_Owner_ID__c);
                rMap.put(ls.Name, ls.Record_Type_ID__c);
            }
            system.debug('Lead Map: ' + qMap);
            
            for(sObject s : newTrigger){
                if(!(Boolean.valueOf(s.get('Zip_Code_Auto_Route__c'))) && (String.valueOf(s.get('Business_Unit__c')) != NULL || String.valueOf(s.get('Zip_Code_Business_Unit__c')) != NULL)){
                    
                    string sbu = String.valueOf(s.get('Zip_Code_Business_Unit__c'));
                    string ownerID = listUsrs.get(String.valueOf(s.get('Zip_Code_Territory_User__c')));
                    string recordID = rMap.get(sbu);
                    //if(qMap.get(sbu).Record_Type_ID__c <> NULL){
                    if(recordID <> NULL){
                        recordID = '' + rMap.get(sbu);
                    }
                    else{
                        recordID = rMap.get('Default');
                    }
                    system.debug('List User (Check for NULL): ' + ownerID);
                    if(ownerID == NULL){
                        if(qMap.get(sbu) == NULL){
                            ownerID = qMap.get('Default');    
                        }
                        else{
                            ownerID = qMap.get(sbu);    
                        }
                    }
                    if(recordID == NULL){
                        recordID = rMap.get('Default');
                    }
                    if(ownerID != NULL){
                        if(Trigger.isAfter){
                            
                            // Gets the Object Type and creates the new record
                            sObject addObj = Schema.getGlobalDescribe().get(objName).newSObject();
                            
                            addObj.put('Zip_Code_Auto_Route__c', TRUE);
                            addObj.put('id', s.get('id'));
                            
                            
                            
                            if(objName == 'Lab_Participant__c'){
                                addObj.put('Approver__c', ownerID);
                            }
                            else{
                                addObj.put('OwnerId', ownerID);
                                addObj.put('RecordTypeId', recordID);
                            }                        
                            
                            System.debug('Update Owner Record: ' + addObj);
                            updateObj.add(addObj);
                        }
                        else{
                            system.debug('Insert Assign User Section');
                            s.put('Zip_Code_Auto_Route__c', TRUE);
                            if(objName == 'Lab_Participant__c'){
                                s.put('Approver__c', ownerID);	     
                            }
                            else{
                                s.put('OwnerId', ownerID);	     
                                s.put('RecordTypeId', recordID);
                            }
                            System.debug('User ID: ' + ownerID);     
                        }
                    }
                    else{
                        system.debug('Owner ID was NULL! - Probably because there was not a DEFAULT lead queue mapping in the Customer Setting for the BU specified');
                    }
                    
                    
                }
            }
            if(updateObj.size() > 0){
                update updateObj;
            }
            System.debug('Finished --------- userAssign! -------');
        }
        
    }*/
}