fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/Pain_Profile__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about Accounts from the Pain Management Team AEM.</description>
    <label>Pain Profile</label>
    <nameField>
        <displayFormat>Pain-{00000}</displayFormat>
        <label>Pain Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pain Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pain Profiles</relationshipLabel>
    <relationshipName>Pain_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PainProfilesBatch.cls
global class PainProfilesBatch implements database.Batchable<sObject>, Schedulable
{
    //start method of the batch
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //List<Pain_Profile__c> painLst  = new List<pain_profile__c>();
        
        String query = 'SELECT id,Account__c from Pain_Profile__c';
        return Database.getQueryLocator(query);}
    
    global void execute(Database.BatchableContext BC, List<pain_Profile__c> scope){ 
        
        update scope;
        system.debug('Pain Profiles list ' + scope.size()); 
    }
    global void finish(Database.BatchableContext BC)
    {
        system.debug('PainProfilesUpdate completed!');
        
    }
    global void execute(SchedulableContext sc)
    {
        PainProfilesBatch b = new  PainProfilesBatch ();
        
        database.executebatch(b,100);
    }
}