fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/Pain_Profile__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about Accounts from the Pain Management Team AEM.</description>
    <label>Pain Profile</label>
    <nameField>
        <displayFormat>Pain-{00000}</displayFormat>
        <label>Pain Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pain Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pain Profiles</relationshipLabel>
    <relationshipName>Pain_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/painProfilesBatchTest.cls
@istest
public class painProfilesBatchTest {
    @testSetup static void setup() {
        Account acc = new Account();
        acc.Name = 'Testacc';
        insert acc;
      // Create  test Pain Profiles
      List<Pain_Profile__c> painLst  = new List<pain_profile__c>();
        for(Integer i=0;i<2;i++) {
                painLst.add(new pain_Profile__c(Account__c = acc.ID));
            }
        for(Integer i=0;i<2;i++) {
                painLst.add(new pain_Profile__c(Account__c = acc.ID));
            } 
         for(Integer i=0;i<2;i++) {
                painLst.add(new pain_Profile__c(Account__c = acc.ID));
            } 
        
         system.debug('Pain Profiles list' + painLst.size()); 

        insert painLst;
    }
        
@isTest static void testBatch() {
   Test.startTest();
     PainProfilesBatch batch = new  PainProfilesBatch ();
        
        database.executebatch(batch,200);  
    
    String sch='0 0 0 ? * * *';
		String jobId = System.schedule('PainProfilesBatchUpdate Schedule', sch , batch);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        System.assertEquals(0, ct.TimesTriggered);
    
    Test.stopTest();
        List<Pain_Profile__c> painLst1 = [SELECT Id,Account__c from Pain_Profile__c];
        system.assertEquals(6, painLst1.size());
    }
    }