fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Parent_Territory__c.field-meta.xml
<CustomField>
    <fullName>Parent_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/Territory_User__c.object-meta.xml
<CustomObject>
    <label>Territory User</label>
    <nameField>
        <displayFormat>TU-{0000000}</displayFormat>
        <label>Territory User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Users</relationshipLabel>
    <relationshipName>Territory_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/Zip_Code_Territories__c.object-meta.xml
<CustomObject>
    <label>Zip Code Territories</label>
    <nameField>
        <label>Zip Code Territories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Alternate_Care__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Care__c</fullName>
    <label>Alternate Care</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Anesthesia__c.field-meta.xml
<CustomField>
    <fullName>Anesthesia__c</fullName>
    <label>Anesthesia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/EMS__c.field-meta.xml
<CustomField>
    <fullName>EMS__c</fullName>
    <label>EMS</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/IA__c.field-meta.xml
<CustomField>
    <fullName>IA__c</fullName>
    <label>IA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Respiratory__c.field-meta.xml
<CustomField>
    <fullName>Respiratory__c</fullName>
    <label>Respiratory</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Surgical_Disposables__c.field-meta.xml
<CustomField>
    <fullName>Surgical_Disposables__c</fullName>
    <label>Surgical Disposables</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Surgical_Instruments__c.field-meta.xml
<CustomField>
    <fullName>Surgical_Instruments__c</fullName>
    <label>Surgical Instruments</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Urology__c.field-meta.xml
<CustomField>
    <fullName>Urology__c</fullName>
    <label>Urology</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Zip_Code_Territories__c/fields/Vascular__c.field-meta.xml
<CustomField>
    <fullName>Vascular__c</fullName>
    <label>Vascular</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Zip_Code_Territories_Lookup.cls
public class Zip_Code_Territories_Lookup {
    
    private final Zip_Code_Territories__c zipt;

    public Zip_Code_Territories_Lookup(ApexPages.StandardController stdController) {

        this.zipt = (Zip_Code_Territories__c)stdController.getRecord();
   
    }
    public Territory_User__c getAlt_Care() {
        Try{
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.Alternate_Care__c
                    LIMIT 1];
       }
        catch(exception ex) {
            return null;
        }
        
    }
    public Territory_User__c getAnesthesia() {
        Try {
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.Anesthesia__c
                    LIMIT 1];
        }
        catch(exception ex) {
            return NULL;
        }
        
    }
    
     public Territory_User__c getEMS()  {
        Try {
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.EMS__c
                    LIMIT 1];
        }
        catch(exception ex) {
            return NULL;
        }
        
    }
    
     public Territory_User__c getIA()  {
        Try {
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.IA__c
                    LIMIT 1];
        }
        catch(exception ex) {
            return NULL;
        }
        
    }
    public Territory_User__c getRespiratory()  {
        try {
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.Respiratory__c
                    LIMIT 1];
        }
        catch(exception ex){
            return NULL;
        }
        
    }
     public Territory_User__c getSurg_Inst()  {
        try {
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.Surgical_Instruments__c
                    LIMIT 1];
        }
        catch(exception ex) {
            return NULL;
        }
        
    }
    
    public Territory_User__c getSurg_Disp()  {
         Try{
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.Surgical_Disposables__c
                    LIMIT 1];
       }
        catch(exception ex) {
            return null;
        }
        
    }
    
    public Territory_User__c getUrology()  {
        try {
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.Urology__c
                    LIMIT 1];
        }
        catch(exception ex) {
            return NULL;
        }
        
    }
    
    public Territory_User__c getVascular()  {
        try {
            return [SELECT User__r.Name, Territory_Master__r.Id  
                    FROM Territory_User__c 
                    WHERE Territory_Master__r.Name = :this.zipt.Vascular__c
                    LIMIT 1];
        }
        catch(exception ex) {
            return NULL;
        }
        
    }
  
    
        
}