fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Quota__c/Territory_Quota__c.object-meta.xml
<CustomObject>
    <label>Territory Quota</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Quota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Quota</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Quota__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <formula>Territory_Master__r.Sales_Rep_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Quota__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Master</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Quota</relationshipLabel>
    <relationshipName>Territory_Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Quota__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Territory Quota</relationshipLabel>
    <relationshipName>Territory_Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/territory_Quota_Helper_Class.cls
public class territory_Quota_Helper_Class {
    
    public static void tLookup(List<Territory_Quota__c> newTrigger){
        set<String> tnumSet = new set<String>();
        map<String, Id> tmMap = new map<String, Id>();
        map<String, Id> tuMap = new map<String, Id>();
        
        for(Territory_Quota__c tq : newTrigger){
            tnumSet.add(tq.Territory_Number__c);
        }
        
        if(tnumSet.size() > 0){
            for(Territory_Master__c tm : [SELECT Id, Sales_Rep__c, Territory_Number__c, Sales_Rep__r.IsActive 
                                          FROM Territory_Master__c  
                                          WHERE Territory_Number__c =:tnumSet])
            {
                if(tm.Sales_Rep__r.IsActive == TRUE){
                    tuMap.put(tm.Territory_Number__c, tm.Sales_Rep__c);    
                }
                tmMap.put(tm.Territory_Number__c, tm.Id);
            }
        }
        
        for(Territory_Quota__c tq : newTrigger){
            if(tmMap.containsKey(tq.Territory_Number__c)){
                tq.Territory_Master__c = tmMap.get(tq.Territory_Number__c);
            }
            if(tuMap.containsKey(tq.Territory_Number__c)){
                tq.User__c = tuMap.get(tq.Territory_Number__c);
            }
        }
    }
}