fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/Request_Demo_Unit__c.object-meta.xml
<CustomObject>
    <description>Records of Approved Reps</description>
    <label>Request Demo Unit</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Demo Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/fields/Agree__c.field-meta.xml
<CustomField>
    <fullName>Agree__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I have read and agree</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/fields/Trainings__c.field-meta.xml
<CustomField>
    <fullName>Trainings__c</fullName>
    <description>Grans user permission to request a demo unit.</description>
    <inlineHelpText>Completed Product Training - Permission to get a demo unit
Completed Bedside Proctor Training - Can support a case on their own.</inlineHelpText>
    <label>Trainings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VPS Expert Trainer</fullName>
            </value>
            <value>
                <fullName>VPS G4 Product Training</fullName>
            </value>
            <value>
                <fullName>VPS G4 Bedside Proctoring</fullName>
            </value>
            <value>
                <fullName>VPS Rhythm Product Training</fullName>
            </value>
            <value>
                <fullName>VPS Rhythm Bedside Proctoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Vascular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Approved_Reps</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/VPS_Console__c/VPS_Console__c.object-meta.xml
<CustomObject>
    <description>Vascular Positioning Systems</description>
    <label>VPS Console</label>
    <nameField>
        <label>Serial #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VPS Consoles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/VPS_Console__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>VPS Contract Renewels</relationshipLabel>
    <relationshipName>VPS_Consoles</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/VPS_Console__c/fields/Approved_Rep__c.field-meta.xml
<CustomField>
    <fullName>Approved_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reps approved for Demo units.</description>
    <label>Approved Rep</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request_Demo_Unit__c.Status__c</field>
            <operation>contains</operation>
            <value>Approved</value>
        </filterItems>
        <filterItems>
            <field>Request_Demo_Unit__c.Agree__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Request_Demo_Unit__c</referenceTo>
    <relationshipLabel>VPS Consoles</relationshipLabel>
    <relationshipName>VPS_Machines</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/VPS_Console__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <description>Check if a machine is In-Use or being repaired.</description>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>With Rep</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/VPS_Console__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who owns the VPS machine.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>VPS_Machines</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/vpsUpdateOwnerTest.cls
/*********************************************************************
* Description      : Test coverage for vpsUpdateOwner VPS process.
* Coverage         : Triggers(vpsUpdateOwner)
* Author(s)        : Dun Silver
**********************************************************************/
@isTest
public class vpsUpdateOwnerTest {

    static testMethod void TestvpsUpdateOwner(){
       list<User> users = new list<User>();
            User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
            System.runAs (thisUser) {
                Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
                for (Integer i=0;i<10;i++) {
                    //create instance of a user
                    User u = new User();
                    u.Alias = 'tUsr'+i;
                    u.Email = 'testUser'+i+'@teleflex.com';
                    u.EmailEncodingKey = 'UTF-8';
                    u.LastName = 'TestUser' + i;
                    u.LanguageLocaleKey = 'en_US';
                    u.LocaleSidKey = 'en_US';
                    u.ProfileId = p.id;
                    u.UserRoleId = '00EE0000000cNk8';
                    u.TimeZoneSidKey = 'America/Los_Angeles';
                    u.Username = 'myTestUser'+i+'@teleflex.com';
                    //add new users to list
                    users.add(u);
                }
                //insert new users from list
                insert users;
                system.assertEquals(10,users.size());
           }

        //list of demo request
        list<Request_Demo_Unit__c> reqRep = new list<Request_Demo_Unit__c>();

        for(integer j=0;j<10;j++){
            //instance of request
            Request_Demo_Unit__c  r = new Request_Demo_Unit__c();
            r.Trainings__c = 'Completed Product Training';
            //r.Agree__c = true;
            //r.Status__c = 'Approved';
            r.User__c = users[j].id;
            r.OwnerId = users[j].id;
            //add request to list of request
            reqRep.add(r);
        }

        //insert new request
        insert reqRep;
        system.assertEquals(10,reqRep.size());

        for(integer a=0; a < reqRep.size(); a++){
            reqRep[a].status__c = 'Approved';
            reqRep[a].Agree__c = true;
        }
        update reqRep;
Account acct = new Account(name = 'vpsconsoletestaccount');
            insert (acct);
        //list of demo request
        list<VPS_Console__c> vps = new list<VPS_Console__c>();

        for(integer k=0;k<10;k++){
            //instance of request
            VPS_Console__c  v = new VPS_Console__c();
            v.Approved_Rep__c = reqRep[k].id;
            v.Unit_Status__c = 'With Rep';
            v.Name = 'GB4' +k+k+k+k;
            v.OwnerId = users[k].id;
            v.account__c= acct.id;
            //add request to list of request
            vps.add(v);
        }

        //insert new request
        insert vps;
        system.assertEquals(10,vps.size());

    }

}