fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/Request_Demo_Unit__c.object-meta.xml
<CustomObject>
    <description>Records of Approved Reps</description>
    <label>Request Demo Unit</label>
    <nameField>
        <label>Rep Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Demo Units</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/fields/Choose_Unit__c.field-meta.xml
<CustomField>
    <fullName>Choose_Unit__c</fullName>
    <label>Choose Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>G4</fullName>
            </value>
            <value>
                <fullName>Rhythm</fullName>
            </value>
            <value>
                <fullName>G4 &amp; Rhythm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/fields/Trainings__c.field-meta.xml
<CustomField>
    <fullName>Trainings__c</fullName>
    <description>Grans user permission to request a demo unit.</description>
    <inlineHelpText>Completed Product Training - Permission to get a demo unit
Completed Bedside Proctor Training - Can support a case on their own.</inlineHelpText>
    <label>Trainings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VPS Expert Trainer</fullName>
            </value>
            <value>
                <fullName>VPS G4 Product Training</fullName>
            </value>
            <value>
                <fullName>VPS G4 Bedside Proctoring</fullName>
            </value>
            <value>
                <fullName>VPS Rhythm Product Training</fullName>
            </value>
            <value>
                <fullName>VPS Rhythm Bedside Proctoring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Request_Demo_Unit__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Vascular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Approved_Reps</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/requestDemoDupeCheck.cls
global with sharing class requestDemoDupeCheck {
		public requestDemoDupeCheck() {
		}

		Public Boolean dupeCheck(Map<Id,String> repMap){
				Map<Id,String> repUnit = new Map<Id,String>();
				List<String> listOfDupes = new List<String>();
				List<Request_Demo_Unit__c> listReps = [SELECT User__c, Choose_Unit__c
																							FROM Request_Demo_Unit__c];

				for(Request_Demo_Unit__c curr : listReps){
						repUnit.put(curr.User__c,curr.Choose_Unit__c);
				}//end of for(Request_Demo_Unit__c curr : listReps)

				for(String curr : repMap.keySet() ){
						//logic to check for keys in both maths
						System.debug('*** repUnit.containsKey(curr) *** ' + repUnit.containsKey(curr) );
						System.debug('*** repUnit.get(curr) *** ' + repUnit.get(curr) );
						System.debug('*** repMap.get(curr) *** ' + repMap.get(curr) );
						//System.debug('*** listOfDupes *** ' + listOfDupes);
						if(repUnit.containsKey(curr) && (repUnit.get(curr) == repMap.get(curr) ) &&
						 	repMap.get(curr) != NULL ){
								listOfDupes.add(curr);
						}
				}//end of for(String curr : repMap.keySet() )
				System.debug('*** listOfDupes *** ' + listOfDupes);

				//set boolean based on dupeList
				if(listOfDupes.size() > 0){
						return true;
				}
				else{
						return false;
				}

		}//end of boolean dupeCheck

		/*
		Public Boolean dupeCheck1(Map<Id,String> repMap){
				Map<Id,String> repUnit = new Map<Id,String>();
				List<String> listOfDupes = new List<String>();
				List<Request_Demo_Unit__c> listReps = [SELECT User__c, Choose_Unit__c, Trainings__c
																							FROM Request_Demo_Unit__c];

				for(Request_Demo_Unit__c curr : listReps){
						repUnit.put(curr.User__c,curr.Trainings__c);
				}//end of for(Request_Demo_Unit__c curr : listReps)

				System.debug('*** repUnit *** ' + repUnit);

				for(String curr : repMap.keySet() ){
						//logic to check for keys in both maths
						System.debug('*** repUnit.containsKey(curr) *** ' + repUnit.containsKey(curr) );
						System.debug('*** repUnit.get(curr) *** ' + repUnit.get(curr) );
						System.debug('*** repMap.get(curr) *** ' + repMap.get(curr) );
						//System.debug('*** listOfDupes *** ' + listOfDupes);
						if(repUnit.containsKey(curr) && (repUnit.get(curr) == repMap.get(curr) ) &&
						 	repMap.get(curr) != NULL ){
								listOfDupes.add(curr);
						}
				}//end of for(String curr : repMap.keySet() )
				System.debug('*** listOfDupes *** ' + listOfDupes);

				//set boolean based on dupeList
				if(listOfDupes.size() > 0){
						return true;
				}
				else{
						return false;
				}
		}//end of boolean dupeCheck1
		*/
}