fullSandbox11072023/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Risk__c/Risk__c.object-meta.xml
<CustomObject>
    <label>Risk</label>
    <nameField>
        <displayFormat>RISK{00000000}</displayFormat>
        <label>Risk #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Risk__c/fields/Current_Risk_Level__c.field-meta.xml
<CustomField>
    <fullName>Current_Risk_Level__c</fullName>
    <label>Current Risk Level</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Risk__c/fields/Impact_of_Risk__c.field-meta.xml
<CustomField>
    <fullName>Impact_of_Risk__c</fullName>
    <description>5 - Inability to deliver, business case/objective not viable
4 - Substantial delay, key deliverable not met, incur costs
3 - Delay, increased cost in excess of tolerance
2 - Small delay, small increased cost, but absorbable
1 - Insignificant changes, re-planning may be required</description>
    <inlineHelpText>5 - Inability to deliver
4 - Substantial delay, key deliverable not met, incur costs
3 - Delay, increased cost in excess of tolerance
2 - Small delay, small increased cost, but absorbable
1 - Insignificant changes, re-planning may be required</inlineHelpText>
    <label>Impact of Risk</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Risk__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Risk__c/fields/Likelihood_of_Occurrence__c.field-meta.xml
<CustomField>
    <fullName>Likelihood_of_Occurrence__c</fullName>
    <description>5 - Certain, Already Observed
4 - More likely to occur than not
3 - 50/50/ chance of occurring
2 - Less likely to occur
1 - Very unlikely to occur</description>
    <inlineHelpText>5 - Certain, Already Observed
4 - More likely to occur than not
3 - 50/50/ chance of occurring
2 - Less likely to occur
1 - Very unlikely to occur</inlineHelpText>
    <label>Likelihood</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Risk_Lookup__c/Risk_Lookup__c.object-meta.xml
<CustomObject>
    <label>Risk Lookup</label>
    <nameField>
        <label>Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Risk_Lookup__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Risk_Lookup__c/fields/Traffic_Light__c.field-meta.xml
<CustomField>
    <fullName>Traffic_Light__c</fullName>
    <label>Traffic Light</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/riskUpdaterTest.cls
@isTest
public class riskUpdaterTest {
    static testMethod void riskUpdaterTest() {
        Risk_Lookup__c lookup = new Risk_Lookup__c(Name='66',Rating__c='Low',Traffic_Light__c='Low');
        insert lookup;
        Project__c proj = new Project__c(Name='TESTING');
        insert proj;
        Risk__c risk = new Risk__c(Initiative__c = proj.Id,Impact_Of_Risk__c='6',Likelihood_Of_Occurrence__c='6');
        insert risk;
        
        Risk__c newRisk = [SELECT Current_Risk_Level__c FROM Risk__c WHERE Id=:risk.Id];
        System.AssertEquals('Low',newRisk.Current_Risk_Level__c);
    }
}