fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/CE_Reimbursement_Expense__c.object-meta.xml
<CustomObject>
    <label>CE Reimbursement/Expense</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Reimbursement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CE Reimbursement/Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Education_Record__c.field-meta.xml
<CustomField>
    <fullName>Education_Record__c</fullName>
    <label>Education Record</label>
    <referenceTo>Education_Record__c</referenceTo>
    <relationshipLabel>CE Reimbursement/Expenses</relationshipLabel>
    <relationshipName>Education_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CE_Reimbursement_Expense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Save</fullName>
                <default>true</default>
                <label>Save</label>
            </value>
            <value>
                <fullName>Submit CRF</fullName>
            </value>
            <value>
                <fullName>Submitted Manually (10/1/14 - 10/31/14)</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved for Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/Education_Record__c.object-meta.xml
<CustomObject>
    <description>OnControl and EZIO Training Records</description>
    <label>Education Record</label>
    <nameField>
        <label>IS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Clinical_Educator__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Educator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Confirmed Clinical Educator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Confirmed Clinical Educator that is Active or Contact Clinical Affairs to activate the profile.</errorMessage>
        <filterItems>
            <field>Profile__c.Active_Profile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Profile__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TFX - Internal Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Education Records</relationshipLabel>
    <relationshipName>Education_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Copy_RecordType__c.field-meta.xml
<CustomField>
    <fullName>Copy_RecordType__c</fullName>
    <label>Copy: RecordType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Education Program Request</fullName>
            </value>
            <value>
                <fullName>CMA Speaker Request</fullName>
            </value>
            <value>
                <fullName>CMA Procedural Lab</fullName>
            </value>
            <value>
                <fullName>Live Education Program Request</fullName>
            </value>
            <value>
                <fullName>Online Education Program Request</fullName>
            </value>
            <value>
                <fullName>Strategic Vascular Education Programs</fullName>
            </value>
            <value>
                <fullName>Inservice Record</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Ending_Date__c.field-meta.xml
<CustomField>
    <fullName>Ending_Date__c</fullName>
    <label>Confirmed End Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Legacy_Confirmed_Educator_Check__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Confirmed_Educator_Check__c</fullName>
    <formula>NOT(ISNULL(Program_Type__c))  = FALSE</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legacy Confirmed Educator Check</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Request</fullName>
            </value>
            <value>
                <fullName>NEW</fullName>
                <default>true</default>
                <label>NEW</label>
            </value>
            <value>
                <fullName>1st Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>RSM Review</fullName>
            </value>
            <value>
                <fullName>Director Review</fullName>
            </value>
            <value>
                <fullName>Marketing Review</fullName>
            </value>
            <value>
                <fullName>BU Review</fullName>
            </value>
            <value>
                <fullName>CEM Vetting</fullName>
            </value>
            <value>
                <fullName>AEM Input</fullName>
            </value>
            <value>
                <fullName>CEM Review</fullName>
            </value>
            <value>
                <fullName>RCEM Review</fullName>
            </value>
            <value>
                <fullName>CMA Review</fullName>
            </value>
            <value>
                <fullName>CSS Review</fullName>
            </value>
            <value>
                <fullName>RCSM Review</fullName>
            </value>
            <value>
                <fullName>CMA Vetting</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Review Complete/Education in Progress</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Training Completed</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Education Record</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Hourly_Rate__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Rate__c</fullName>
    <label>Hourly Rate</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Onboarding – For new CEs not yet available to conduct training.
Active – CE is available
Hold – CE is currently inactive but in good standing for future business
Inactive – CE is not eligible for future training</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <default>true</default>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Inactive (Permanent)</fullName>
            </value>
            <value>
                <fullName>Active - NDA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Education_Record_Training_Completed.cls
global class Education_Record_Training_Completed implements Schedulable{
    global void execute(SchedulableContext SC) {

        List<Education_Record__c> updateER = new List<Education_Record__c>();
        string query;
        if(test.isRunningTest()){
            query = 'SELECT Id, Stage__c FROM Education_Record__c WHERE Ending_Date__c = THIS_WEEK AND Stage__c = \'Confirmed\' AND Legacy_Confirmed_Educator_Check__c = FALSE';
        }
        else{
            query = 'SELECT Id, Stage__c FROM Education_Record__c WHERE Ending_Date__c = Today AND Stage__c = \'Confirmed\' AND Legacy_Confirmed_Educator_Check__c = FALSE';            
        }

        
        for(Education_Record__c er: database.query(query))
        {
            er.stage__c = 'Training Completed';
            updateER.add(er);
        }
        if(updateER.size() > 0){
            Database.update(updateER,false);
        }
        
        
        /* Old Class - Creation of the CRF/Expense records is now handled with the trigger as is changing the status from New to Save.
         * 14Jan2018 - ESC
List<Education_Record__c> edrecUpdate = new List<Education_Record__c>();
        List<CE_Reimbursement_Expense__c> crfcmaUpdate = new List<CE_Reimbursement_Expense__c>();
        String educErrors = '';
        String crfErrors = '';

        List<Education_Record__c> edrec = [Select Id, Name, Stage__c, Copy_RecordType__c, OwnerId, Clinical_Educator__r.Hourly_Rate__c
                                            From Education_Record__c
                                            Where Ending_Date__c=Today AND Stage__c ='Confirmed' AND Clinical_Educator__r.Hourly_Rate__c != null
                                            AND (Copy_RecordType__c ='Live Education Program Request' OR Copy_RecordType__c ='Inservice Record'
                                            OR Copy_RecordType__c ='Strategic Marketing Education Program Request')];

        for(Education_Record__c er: edrec){
            //if(er.Stage__c == 'Confirmed' && (er.Copy_RecordType__c =='Live Education Program Request' || er.Copy_RecordType__c =='Inservice Record' ||) )
            er.stage__c = 'Training Completed';
            edrecUpdate.add(er);
        }

        Database.update(edrecUpdate,false);
        //update edrecUpdate;
        System.debug(JSON.serializePretty(edrecUpdate));

        List<CE_Reimbursement_Expense__c> crfcma = [Select Id, Name, Education_Record__r.Stage__c, Education_Record__r.Ending_Date__c, Status__c, Education_Record__r.Copy_RecordType__c
                                                    From CE_Reimbursement_Expense__c
                                                    Where Education_Record__r.Ending_Date__c=Today AND Education_Record__r.Stage__c ='Confirmed'
                                                    AND (Education_Record__r.Copy_RecordType__c ='CMA Record'
                                                    OR Education_Record__r.Copy_RecordType__c ='CMA Record MEG'
                                                    OR Education_Record__r.Copy_RecordType__c ='CMA Procedural Lab'
                                                    OR Education_Record__r.Copy_RecordType__c ='CMA Speaking Engagement') AND Status__c = 'Save'];

        for(CE_Reimbursement_Expense__c ercma: crfcma){
            ercma.status__c = 'New';
            crfcmaUpdate.add(ercma);
        }

        Database.update(crfcmaUpdate,false);
        //update crfcmaUpdate;
        System.debug(JSON.serializePretty(crfcmaUpdate));*/

    }//end of schedulable method

}//end of class