fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/Education_Record__c.object-meta.xml
<CustomObject>
    <description>OnControl and EZIO Training Records</description>
    <label>Education Record</label>
    <nameField>
        <label>IS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Account_Facility__c.field-meta.xml
<CustomField>
    <fullName>Account_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account/Facility</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Education Records</relationshipLabel>
    <relationshipName>Education_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/CEM__c.field-meta.xml
<CustomField>
    <fullName>CEM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Education_RecordsCEM</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Clinical_Educator__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Educator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Confirmed Clinical Educator</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a Confirmed Clinical Educator that is Active or Contact Clinical Affairs to activate the profile.</errorMessage>
        <filterItems>
            <field>Profile__c.Active_Profile__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Profile__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TFX - Internal Resource</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Education Records</relationshipLabel>
    <relationshipName>Education_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Hotel_Requested__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Requested__c</fullName>
    <label>Hotel Requested</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/RSM__c.field-meta.xml
<CustomField>
    <fullName>RSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RSM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>RSM, Executive</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Education_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Representative</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Education_Records2</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/CEM__c.field-meta.xml
<CustomField>
    <fullName>CEM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible CEM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Clinical</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Clinical_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/E_mail_Address__c.field-meta.xml
<CustomField>
    <fullName>E_mail_Address__c</fullName>
    <inlineHelpText>What is their e-mail address?</inlineHelpText>
    <label>E-mail Address</label>
    <type>Email</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <inlineHelpText>What is their preferred mailing address?</inlineHelpText>
    <label>Mailing Address</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_Country__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Country__c</fullName>
    <label>Mailing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BW</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CR</fullName>
            </value>
            <value>
                <fullName>CU</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>DZ</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>EE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State/Province</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip__c</fullName>
    <label>Mailing Zip/Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clinical_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Onboarding – For new CEs not yet available to conduct training.
Active – CE is available
Hold – CE is currently inactive but in good standing for future business
Inactive – CE is not eligible for future training</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <default>true</default>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Inactive (Permanent)</fullName>
            </value>
            <value>
                <fullName>Active - NDA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Education_Assign_Approvers_Test.cls
@isTest
public class Education_Assign_Approvers_Test {
    // Education_Global_Test_Class replaces this test class - 08Mar2018 - ESC
/*
    static testmethod void myUnitTest() {
        Test.startTest();
        
        Account accTest = new Account(
            Name='Test Account',
            // Account_Code__c='3333333',
            Description = 'Test_Account');
        
        insert accTest;
        System.debug('Account-->' + accTest);
        
        Contact contTest = new Contact(
            FirstName='Contact',
            LastName='Test',
            Account = accTest,
            email = 'test@test.com'
        );
        
        insert contTest;
        System.debug('Contact-->' + ContTest);
        
        Profile profile1 = [Select Id from Profile where name = 'Clinical Team'];
        
        User ManagerTest = new User(
            FirstName = 'Test',
            LastName = 'Test',
            username = 'ManagerTest4545@test.com',
            Email = 'ManagerTest@test.com',
            Alias = 'ManTest',
            ProfileId = profile1.Id,
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        insert ManagerTest;
        System.debug('ManagerTest-->' + ManagerTest);
        
        User ManagerTest2 = new User(
            FirstName = 'Test2',
            LastName = 'Test2',
            username = 'ManagerTest5656@test.com',
            Email = 'ManagerTest2@test.com',
            Alias = 'ManTest2',
            ProfileId = profile1.Id,
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        insert ManagerTest2;
        System.debug('ManagerTest2-->' + ManagerTest2);
        
        User SalesRepTest = new User(
            FirstName = 'Test SR',
            LastName = 'Test',
            username = 'SalesRepTest4545@test.com',
            Manager = ManagerTest,
            CEM__c =  ManagerTest.Id,
            Email = 'SalesRepTest@test.com',
            Alias = 'SalTest',
            ProfileId = profile1.Id,
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        
        insert SalesRepTest;
        System.debug('SalesRepTest-->' + SalesRepTest);
        
        User SalesRepTest2 = new User(
            FirstName = 'Test2 SR',
            LastName = 'Test2',
            username = 'SalesRepTest5656@test.com',
            Manager = ManagerTest,
            CEM__c =  ManagerTest.Id,
            Email = 'SalesRepTest2@test.com',
            Alias = 'SalTest2',
            ProfileId = profile1.Id,
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            TimeZoneSidKey='America/Chicago'
        );
        
        insert SalesRepTest2;
        System.debug('SalesRepTest2-->' + SalesRepTest2);
        
        Profile__c profTest = new Profile__c(
            
            First_Name__c = 'Prof1',
            Name = 'Last1',
            CEM__c = ManagerTest.Id,
            Status__c = 'Active',
            Phone_Number__c = '9192223333',
            Mailing_Address__c = '123 Test St',
            Mailing_City__c = 'Raleigh',
            Mailing_State__c = 'NC',
            Mailing_Zip__c = '27610',
            Mailing_Country__c = 'US',
            E_mail_Address__c = 'duntee.silver@teleflex.com'
        );
        insert profTest;
        
        Profile__c profTest2 = new Profile__c(
            
            First_Name__c = 'Prof2',
            Status__c = 'Active',
            Name = 'Last2',
            CEM__c = ManagerTest.Id,
            Phone_Number__c = '9192223333',
            Mailing_Address__c = '123 Test St',
            Mailing_City__c = 'Raleigh',
            Mailing_State__c = 'NC',
            Mailing_Zip__c = '27610',
            Mailing_Country__c = 'US',
            E_mail_Address__c = 'eric.clay@teleflex.com'
        );
        insert profTest2;
        
        Education_Record__c EducTest = new Education_Record__c(
            Name = 'Education Test',
            Account_Facility__c =  accTest.Id,
            Sales_Rep__c = SalesRepTest.Id,
            CEM__c = SalesRepTest.Id,
            Hotel_Requested__c = 'No',
            Clinical_Educator__c = profTest.Id
        );
        Insert EducTest;
        System.debug('EducTest-->' + EducTest);
        
        System.assertNotEquals(EducTest.RSM__c,ManagerTest.Id);
        System.assertEquals(EducTest.Clinical_Educator__c,profTest.Id);
        
        EducTest.Sales_Rep__c = SalesRepTest2.Id;
        EducTest.Clinical_Educator__c = profTest2.Id;
        update EducTest;
        
        System.assertEquals(EducTest.Clinical_Educator__c,profTest2.Id);
        
        //  list<Id> EDList = new List<Id>();
        //      EDList.add(EducTest.Id);
        
        Test.stopTest();
        
    }*/
}