fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Choose the primary contact for this opportunity. This person has to be setup as a contact on the account before you can add them here.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities as Primary Contact</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Opportunity/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <inlineHelpText>The name of the product family associated with this opportunity.</inlineHelpText>
    <label>Product Family Old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Acute</fullName>
            </value>
            <value>
                <fullName>Aerosol Therapy</fullName>
            </value>
            <value>
                <fullName>Airway</fullName>
                <color>#A53711</color>
                <label>Airway</label>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Arterial</fullName>
                <color>#E27001</color>
                <label>Arterial</label>
            </value>
            <value>
                <fullName>Auto Ligation</fullName>
            </value>
            <value>
                <fullName>Automatization</fullName>
            </value>
            <value>
                <fullName>Cardiac</fullName>
            </value>
            <value>
                <fullName>Caregiver Safety</fullName>
            </value>
            <value>
                <fullName>Central Venous Access</fullName>
                <color>#0B6FCE</color>
                <label>Central Venous Access</label>
            </value>
            <value>
                <fullName>Chest Drainage</fullName>
            </value>
            <value>
                <fullName>Dialysis Access</fullName>
            </value>
            <value>
                <fullName>Endurance</fullName>
            </value>
            <value>
                <fullName>EZ-IO</fullName>
                <color>#999999</color>
                <label>EZ-IO</label>
            </value>
            <value>
                <fullName>Fascial closure</fullName>
            </value>
            <value>
                <fullName>General Specialties</fullName>
            </value>
            <value>
                <fullName>IAB</fullName>
            </value>
            <value>
                <fullName>Instruments</fullName>
            </value>
            <value>
                <fullName>Interventional Procedures</fullName>
            </value>
            <value>
                <fullName>IR JACC</fullName>
            </value>
            <value>
                <fullName>Ligation</fullName>
            </value>
            <value>
                <fullName>LMA</fullName>
            </value>
            <value>
                <fullName>Minilap</fullName>
            </value>
            <value>
                <fullName>OnControl</fullName>
            </value>
            <value>
                <fullName>Other (Third Party)</fullName>
            </value>
            <value>
                <fullName>Oxygen Therapy</fullName>
            </value>
            <value>
                <fullName>Pain Management</fullName>
                <color>#66E9BD</color>
                <label>Pain Management</label>
            </value>
            <value>
                <fullName>Passive Humidification</fullName>
            </value>
            <value>
                <fullName>Percuvance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Opportunity/fields/Product_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_of_Interest__c</fullName>
    <label>Product of Interest Old</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Product_Family__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1605 Filters</fullName>
            </value>
            <value>
                <fullName>1A</fullName>
            </value>
            <value>
                <fullName>3 Lumen PICC</fullName>
            </value>
            <value>
                <fullName>780 Circuit Kits</fullName>
            </value>
            <value>
                <fullName>AC2 Pumps</fullName>
            </value>
            <value>
                <fullName>AC3 Pumps</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Active Humidification</fullName>
            </value>
            <value>
                <fullName>Acute Double Lumen Catheter</fullName>
            </value>
            <value>
                <fullName>Acute Hemodialysis</fullName>
            </value>
            <value>
                <fullName>Acute Hemodialysis AGB+</fullName>
            </value>
            <value>
                <fullName>Acute Triple Lumen Catheter</fullName>
            </value>
            <value>
                <fullName>Adaptors &amp; Connectors</fullName>
            </value>
            <value>
                <fullName>AE-05</fullName>
            </value>
            <value>
                <fullName>AE-10</fullName>
            </value>
            <value>
                <fullName>AE5</fullName>
            </value>
            <value>
                <fullName>Aerosol Therapy</fullName>
            </value>
            <value>
                <fullName>AirTraq (Avant &amp; SP)</fullName>
            </value>
            <value>
                <fullName>AKP1A</fullName>
            </value>
            <value>
                <fullName>Alligator Grasper</fullName>
            </value>
            <value>
                <fullName>Ambit Pump</fullName>
            </value>
            <value>
                <fullName>Appliers</fullName>
            </value>
            <value>
                <fullName>Arrow Midline with Chlorag+ard</fullName>
            </value>
            <value>
                <fullName>Arrow PICC (A5)</fullName>
            </value>
            <value>
                <fullName>Arrow PICC with Chlorag+ard</fullName>
            </value>
            <value>
                <fullName>Atomization</fullName>
            </value>
            <value>
                <fullName>AutoFuser (CPNB &amp; Incisional Sites)</fullName>
            </value>
            <value>
                <fullName>Babcock Grasper</fullName>
            </value>
            <value>
                <fullName>Berci Passer</fullName>
            </value>
            <value>
                <fullName>Berman Catheters</fullName>
            </value>
            <value>
                <fullName>Cholangiography</fullName>
            </value>
            <value>
                <fullName>DispoLED</fullName>
            </value>
            <value>
                <fullName>EFx</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Spinals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/oppProbabilityTriggerTest.cls
@isTest
private class oppProbabilityTriggerTest {
/*
    static testMethod void testoppProbability(){

        Account a = new Account(Name='Test Account ');
        insert a;

        Contact c = new Contact(
            LastName = 'Test',
            AccountId = a.Id
        );
        insert c;

        Id Anesthesia_ID = [select id from RecordType where Name = 'Anesthesia Opportunity' LIMIT 1].id;

        Opportunity o = new Opportunity(
            Name = 'test',
            AccountId = a.Id,
            RecordTypeId = Anesthesia_ID,
            StageName = 'Qualified Prospect',
            Amount = 1,
            Primary_Contact__c = c.id,
            CloseDate = system.today() + 90,
            Product_Family__c = 'Airway',
            Product_Of_Interest__c = 'DispoLED'
        );
        system.debug('Record ID' + Anesthesia_ID);
        insert o;

        o.Product_Of_Interest__c = 'Spinals';
        update o;

        o.Product_Of_Interest__c = 'DispoLED,Spinals';
        update o;

        Id Surgical_ID = [select id from RecordType where Name = 'Surgical Sales Opportunity' LIMIT 1].id;

        Opportunity o2 = new Opportunity(
            Name = 'test2',
            AccountId = a.Id,
            RecordTypeId = Surgical_ID,
            StageName = 'Qualified Prospect',
            Amount = 1,
            Primary_Contact__c = c.id,
            CloseDate = system.today() + 90,
            Product_Family__c = 'Instruments',
            Product_Of_Interest__c = 'EFx'
        );
        //Opportunity o2 = new Opportunity(Name='Test',AccountId=a.Id,Type='New Business', LeadSource='Self Generated',Description='Test',Amount=10000,CloseDate=system.today(), Product_Family__c='Ligation',Product_Of_Interest__c='Metal',StageName='Close');
        insert o2;

        o2.Product_Family__c = 'Skin Stapling';
        update o2;

        o2.Product_Of_Interest__c = 'Cholangiography';
        o2.Focus__c='';
        update o2;

    }*/
}