fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/Contract_Material__c.object-meta.xml
<CustomObject>
    <label>Contract Material</label>
    <nameField>
        <label>Contract Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/Cross_Reference__c.object-meta.xml
<CustomObject>
    <label>Cross Reference</label>
    <nameField>
        <displayFormat>Xref-{00000000}</displayFormat>
        <label>Cross Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/Price_Quote__c.object-meta.xml
<CustomObject>
    <description>Used for Pricing portal instead of standard quotes object</description>
    <label>Price Quote</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Price Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote_Line_Item__c/Price_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Price Quote Line Item</label>
    <nameField>
        <displayFormat>PQL-{0000000}</displayFormat>
        <label>Price Quote Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote_Line_Item__c/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>Price Quote Line Items</relationshipLabel>
    <relationshipName>Price_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Sort_LineItemsCtrl_Test.cls
/*********************************************************************
* Description      : Test coverage for Pricing Portal PP_Sort_LineItemsCtrl Page.
* Coverage         : Classes(PP_Sort_LineItemsCtrl)
* Author(s)        : Dun Silver, Eric Clay
**********************************************************************/
@isTest
private class PP_Sort_LineItemsCtrl_Test {

    static testMethod void PP_Sort_LineItemsCtrl_UnitTest() {
      	Account accRec = TestDataFactory.createAccount('TestAccount');
      	Contact conRec = TestDataFactory.createContact('TestContact', accRec.Id);
      	Price_Quote__c pcqRec = TestDataFactory.createPriceQuote(accRec.Id,conRec.Id);
      	Product2 proRec = TestDataFactory.createProduct('AA-10511-1');
      	INSERT proRec;
        Contract_Header__c cHead = TestDataFactory.createContractHeader('Test Head');
        INSERT cHead;
        Contract_Material__c conMat = TestDataFactory.createContractMat( proRec, cHead );
        INSERT conMat;
      	System.debug('----------pcqRec.Name------------'+pcqRec.Name);
      	Cross_Reference__c crfRec = TestDataFactory.createCrossRef(proRec.Id);
      	Price_Quote_Line_Item__c pqlItem = TestDataFactory.createPriceQLineItem(pcqRec.Id, proRec.Id, crfRec.Id);

      	Test.setCurrentPageReference(new PageReference('Page.PP_Price_Quote'));
        System.currentPageReference().getParameters().put('pqid', pcqRec.Id);
        PP_Sort_LineItemsCtrl sortLItem = new PP_Sort_LineItemsCtrl();
        PP_Sort_LineItemsCtrl.saveSortedRows(new List<String>{pqlItem.id});
        PP_Sort_LineItemsCtrl.saveSortedRows(new List<String>{'123456'});
    }
}