fullSandbox11072023/force-app/main/default/objects/Dupe_Account__c/Dupe_Account__c.object-meta.xml
<CustomObject>
    <label>Dupe Account</label>
    <nameField>
        <label>Dupe Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dupe Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/ClearDupeBatchTest.cls
@isTest
public class ClearDupeBatchTest {
    static testMethod void testClearDupeBatch(){
        
        Dupe_Account__c dupe = new Dupe_Account__c(Name='9876543');
        insert dupe;
        
        Account a = new Account(Name='Test Account 1');
        insert a;
        
        Account b = new Account(Name='Test Account 2');
        insert b;
        
        
        Territory_Master__c tm = new Territory_Master__c(Name='900130', Territory_Number__c='900130');
        insert tm;
        
       
        BatchClearDupes assign = new BatchClearDupes();
        ID batchprocessid2 = Database.executeBatch(assign);

    }
}