fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <label>Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_2__c</fullName>
    <label>Account Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>2 Digit Customer Group Number.</inlineHelpText>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/ERP_Active__c.field-meta.xml
<CustomField>
    <fullName>ERP_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is updated as part of the Daily Data Load from the ERP system. Any Active Customers will have a Value of True (checked).</description>
    <inlineHelpText>When this box is checked, the account is an active customer in the ERP System.</inlineHelpText>
    <label>Active in SAP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Main_GPO__c.field-meta.xml
<CustomField>
    <fullName>Main_GPO__c</fullName>
    <inlineHelpText>Primary group purchasing affiliation.</inlineHelpText>
    <label>Primary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Premier Purchasing Partners</fullName>
            </value>
            <value>
                <fullName>MedAssets Supply Chain Systems</fullName>
            </value>
            <value>
                <fullName>Vizient Inc.</fullName>
            </value>
            <value>
                <fullName>HealthTrust Purchasing Group</fullName>
            </value>
            <value>
                <fullName>ROI</fullName>
            </value>
            <value>
                <fullName>FirstChoice Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <formula>Sales_Org__c + Distribution_Channel__c</formula>
    <label>Sales Org Key</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Secondary_GPO__c.field-meta.xml
<CustomField>
    <fullName>Secondary_GPO__c</fullName>
    <inlineHelpText>The secondary group purchasing organization.</inlineHelpText>
    <label>Secondary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Dignity</fullName>
            </value>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Vizient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <formula>Account.Account_Group_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer_Group_Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/Price_Quote__c.object-meta.xml
<CustomObject>
    <description>Used for Pricing portal instead of standard quotes object</description>
    <label>Price Quote</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Price Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account_Name__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_SelectAccount.cls
/*********************************************************************
* Description      : Controller Class for Pricing Portal Select Account.
* Test Class       : PP_SelectAccount
* VisualForce      : PP_SelectAccount
* Author(s)        : Dun Silver, Eric Clay
**********************************************************************/
Public with sharing class PP_SelectAccount{

    Public String strCust{get; set;}
    public String prf {
        get {
            if(ApexPages.currentPage().getParameters().get('prf') != NULL){
                return '&prf=' + ApexPages.currentPage().getParameters().get('prf');
            }
            return NULL;
        }
        set;
    }

    public String pq {
        get {
            if(ApexPages.currentPage().getParameters().get('pqId') != NULL){
                return '&pqId=' + ApexPages.currentPage().getParameters().get('pqId');
            }
            return NULL;
        }
        set;
    }

    //method to get URL paraments and redirect
    public pagereference getURL(){

        String quoteId = ApexPages.currentPage().getParameters().get('pqID');
        string search = strCust;
        if(search != NULL){
            search = search.trim();

            if(prf != NULL) search += prf;

            if(pq != NULL) search += pq;


            PageReference getCustomer = New Pagereference('/apex/PP_SelectAccount?gs=off&cid=' + search);
            getCustomer.setRedirect(true);
            System.debug('search in Cust Details GET URL ===================================== ' + search);
            return getCustomer;

        }
        else{
            return NULL;
        }


    }

    public string currSalesOrgKey{get;set;}
    public list<Account> getSearch(){
        //Get parameter from URL and assign to string variable
        if(ApexPages.currentPage().getParameters().get('cid') != NULL){
            string cid = ApexPages.currentPage().getParameters().get('cid');
            cid = cid.trim();
            system.debug('cid: ' + cid);


            if(cid.length() < 2){
                apexPages.addmessage(new apexpages.message(apexpages.severity.Error, System.label.EMEA_Search_Terms_must_be_longer_than_one_character));
                return NULL;
            }
            else{
                currSalesOrgKey = PP_Menu.cUserTemp.Active_Sales_Org_Key__c;
                System.debug('****PP_Menu.cUserTemp.Active_Sales_Org_Key__c**** ' + currSalesOrgKey);
                transient String searchQuery = 'FIND \'' + cid + '\' IN ALL FIELDS RETURNING Account(SAP_Sold_To__c,Name,Account_Name_2__c,ShippingStreet,ShippingCity,' +
                    'ShippingState,ShippingPostalCode, Account_Group__c, Customer_Group__c, Customer_Group_Name__c, ERP_Active__c, Main_GPO__c, Secondary_GPO__c ' +
                    'WHERE Sales_Org_Key__c = \'' + currSalesOrgKey + '\' AND (Account_Group__c = \'Z001\' OR Account_Group__c = \'Z002\' OR Account_Group__c = \'ZREB\'))';

                //add searchQuery to a lists
                List<List <sObject>> searchList = search.query(searchQuery);
                list<Account> accountInfo = ((List<Account>)searchList[0]);
                System.debug('accountInfo ===================================== ' + accountInfo);

                //error check for empty list returns
                if(accountInfo.size() == 0){
                    apexPages.addmessage(new apexpages.message(apexpages.severity.Error, System.label.EMEA_Sorry_no_results_returned_with_matching_string));
                    return NULL;
                }
                else{
                    return accountInfo;
                }
            }

        }
        else{
            return NULL;
        }
    }

    //Get Recent Accounts for current user
    public list<Account> getAccs(){
        return [SELECT Id, Name, SAP_Sold_To__c, ERP_Active__c, Account_Name_2__c,
                ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, Main_GPO__c, Secondary_GPO__c
                FROM Account
                WHERE LastViewedDate != NULL
                ORDER BY LastViewedDate DESC limit 10];
    }

    //Get Recent Quotes for current user
    public list<Price_Quote__c> getPqs(){
        return [SELECT Id, Name, Contact_Name__r.Name, Account_Name__r.Name
                FROM Price_Quote__c
                WHERE LastViewedDate != NULL
                ORDER BY LastViewedDate DESC limit 10];
    }

}