fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <label>Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <formula>Sales_Org__c + Distribution_Channel__c</formula>
    <label>Sales Org Key</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org_Key__c</fullName>
    <label>Active Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/Cross_Reference__c.object-meta.xml
<CustomObject>
    <label>Cross Reference</label>
    <nameField>
        <displayFormat>Xref-{00000000}</displayFormat>
        <label>Cross Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <label>Competitor</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product_Code__c</fullName>
    <externalId>true</externalId>
    <label>Competitor Product Code</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product_Description__c</fullName>
    <label>Competitor Product Description</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Percent_Match__c.field-meta.xml
<CustomField>
    <fullName>Percent_Match__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Percent Match</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFX Cross 1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Competitive Cross References</relationshipLabel>
    <relationshipName>Cross_References</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/TFX_Product__c.field-meta.xml
<CustomField>
    <fullName>TFX_Product__c</fullName>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TFX Product</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/PRF__c.object-meta.xml
<CustomObject>
    <label>PRF</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/PRF_Name__c.field-meta.xml
<CustomField>
    <fullName>PRF_Name__c</fullName>
    <formula>Name &amp; &quot; - &quot; &amp; Account__r.Name &amp; &quot; - &quot; &amp; Contact__r.Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PRF Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>PRF</relationshipLabel>
    <relationshipName>PRF</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/Price_Quote__c.object-meta.xml
<CustomObject>
    <description>Used for Pricing portal instead of standard quotes object</description>
    <label>Price Quote</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Price Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/PRF__c.field-meta.xml
<CustomField>
    <fullName>PRF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRF</label>
    <referenceTo>PRF__c</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Price_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote_Name__c</fullName>
    <formula>Name &amp; &quot; - &quot; &amp;  SUBSTITUTE(Account_Name__r.Name, &quot;,&quot;, &quot;&quot;)  &amp; &quot; - &quot; &amp; SUBSTITUTE(Contact_Name__r.Full_Name__c, &quot;,&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Quote Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#78C953</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ready for Approval</fullName>
                <color>#E27001</color>
                <label>Ready for Approval</label>
            </value>
            <value>
                <fullName>PRF In Process</fullName>
                <color>#A845DC</color>
                <label>PRF In Process</label>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
                <color>#F3D904</color>
                <label>Waiting on Approval</label>
            </value>
            <value>
                <fullName>Waiting for Contracts Approval</fullName>
                <color>#A53711</color>
                <label>Waiting for Contracts Approval</label>
            </value>
            <value>
                <fullName>Waiting For RSM Approval</fullName>
                <color>#66E9BD</color>
                <label>Waiting For RSM Approval</label>
            </value>
            <value>
                <fullName>Waiting on Director Level Approval</fullName>
                <color>#0B24BE</color>
                <label>Waiting on Director Level Approval</label>
            </value>
            <value>
                <fullName>Waiting on VP Level Approval</fullName>
                <color>#419249</color>
                <label>Waiting on VP Level Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#B6E32E</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#33CC00</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Alt_Site_List__c.field-meta.xml
<CustomField>
    <fullName>Alt_Site_List__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Alt Site List</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Distributor_List__c.field-meta.xml
<CustomField>
    <fullName>Distributor_List__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Distributor List</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Rep_Price__c.field-meta.xml
<CustomField>
    <fullName>Rep_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>ZRST</inlineHelpText>
    <label>Rep Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/RSM_Price__c.field-meta.xml
<CustomField>
    <fullName>RSM_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>ZASD</inlineHelpText>
    <label>RSM Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_CompProductSearch.cls
/*********************************************************************
* Description      : Class to handle Competitor Product Search in Pricing Portal.
* Test Classes     : PP_CompProductSearch_Test
* VisualForce      : PP_CompProductSearch
* Author(s)        : Dun Silver
**********************************************************************/
public class PP_CompProductSearch{
    Public Integer size{get;set;}
    Public Integer noOfRecords{get; set;}
    public String compEntry {get;set;}
    Public String strQuoteId;
    String compEntry2;
    String rowIndex;

    Public String recID {get; set;}
    Public String recName {get; set;}
    Public String recType {get; set;}
    Public String recSales_Org_Key {get; set;}
    public List<Cross_Reference__c> prodList {get;set;}
    public String userLocale {get;set;}
    public Map<Id,String> formatListPrices {get;set;}
    public Map<Id,String> formatDistributorPrices {get;set;}
    public Map<Id,String> formatAltSitePrices {get;set;}
    public Map<Id,String> formatRsmPrices {get;set;}
    public Map<Id,String> formatRepPrices {get;set;}

    //get active quote of current user
    public String activeQuoteIdStr {get{
        List<User> userList = [Select id, Active_Quote_Id__c from User Where Id=: UserInfo.getUserId()];
        if(userList.size() > 0) {
            activeQuoteIdStr = userList[0].Active_Quote_Id__c;
        }
        return activeQuoteIdStr;
    }set;}

    public Price_Quote__c tempQuote {get{
      try{
        tempQuote = [Select Id, Name, Status__c,Sales_Org_Key__c,Account_Name__r.SAP_Sold_To__c,
                  Account_Name__r.Account_Group__c,CurrencyIsoCode from Price_Quote__c WHERE LastViewedDate != NULL
                  ORDER BY LastViewedDate DESC limit 1];
        return tempQuote;
      }
      catch(Exception e){
        Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,''+'User has no active quote: ' + e));
        return null;
      }

    }set;}

    public List<SelectOption> paginationSizeOptions{get;set;}

        /* Competitor search
        If(ApexPages.currentPage().getParameters().get('compsrch') != null || ApexPages.currentPage().getParameters().get('compsrch') != ''){

            PageReference compProductSearch = New Pagereference('/apex/PP_CompProductSearch?pqid='+strQuoteId+'&compsrch='+ strCrossReference+'&rowIndex='+rowIndex);
            System.debug('strCrossReference Create Quote1 ===================================== ' + strCrossReference);
            compProductSearch.setRedirect(true);
        }
        end Competitor search */

    public PageReference getURL() {
        strQuoteId = ApexPages.currentPage().getParameters().get('pqId');

        PageReference compProductSearch = New Pagereference('/apex/PP_CompProductSearch?pqid='+strQuoteId+'&compsrch='
                                                            + compEntry+'&gs=off');
        compProductSearch.setRedirect(true);
        System.debug('compEntry Create Quote1 ===================================== ' + compEntry);
        return compProductSearch;
    }
    
    public void clearSearch() {
        compEntry = '';
    }


    public PP_CompProductSearch(){
      userLocale = UserInfo.getLocale();
      formatListPrices = new Map<Id,String>();
      formatDistributorPrices = new Map<Id,String>();
      formatAltSitePrices = new Map<Id,String>();
      formatRsmPrices = new Map<Id,String>();
      formatRepPrices = new Map<Id,String>();

      if(ApexPages.currentPage().getParameters().get('pqId') != NULL){
          for(Price_Quote__c pq : [Select Sales_Org_Key__c, Price_Quote_Name__c
                                   FROM Price_Quote__c
                                   WHERE Id =: ApexPages.currentPage().getParameters().get('pqId')
                                   LIMIT 1])
          {
              recName = pq.Price_Quote_Name__c;
              recType = 'Quote';
              recSales_Org_Key = pq.Sales_Org_Key__c;
              recID = ApexPages.currentPage().getParameters().get('pqId');
          }

      }
      else if(ApexPages.currentPage().getParameters().get('prfId') != NULL){
          for(PRF__c prf : [Select Sales_Org_Key__c, PRF_Name__c
                            FROM PRF__c
                            WHERE Id =: ApexPages.currentPage().getParameters().get('prfId')
                            LIMIT 1])
          {
              recName = prf.PRF_Name__c;
              recType = 'PRF';
              recSales_Org_Key = prf.Sales_Org_Key__c;
              recID = ApexPages.currentPage().getParameters().get('prfId');
          }
      }
      else{
          String salesOrgKey = [SELECT Active_Sales_Org_Key__c
                                FROM Contract_User__c
                                WHERE User__c = :UserInfo.getUserId()
                                LIMIT 1].Active_Sales_Org_Key__c;
          
          recSales_Org_Key = salesOrgKey;
      }  

      rowIndex = ApexPages.currentPage().getParameters().get('rowIndex');

        compEntry = Apexpages.currentPage().getParameters().get('compsrch');
        System.debug('*** compEntry *** ' + compEntry);
        compEntry2 = '%' +compEntry+ '%';
        System.debug('*** compEntry2 *** ' + compEntry2);
        size=10;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));
    }//end of constructor

    public ApexPages.StandardSetController setCon {
        get {
            System.debug('*** setCon ***'+compEntry);
            /*Added by Siva on 15 Nov. 2018 to return null when serach string is not entered*/
            if(compEntry == '' || compEntry == null){
                System.debug('*** setCon *** Nothing has been searched!');
                return null;
            }
            else{
                if(setCon == null) {
                  System.debug('*** In setCon if ***');
                    setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                          [SELECT Competitor_Product_Code__c,Competitor_Product_Description__c,TFX_Product__c, Product__c,Competitor_Name__c,
                          Percent_Match__c,Name,Product__r.List_Price__c,Product__r.Rep_Price__c,Product__r.RSM_price__c,Product__r.Sales_Org__c,
                          Product__r.Distribution_Channel__c, Product__r.Distributor_List__c, Product__r.Alt_Site_List__c
                          FROM Cross_Reference__c
                          WHERE Competitor_Product_Code__c LIKE :compEntry2
                          ORDER BY Competitor_Product_Code__c]));
                    setCon.setPageSize(size);
                    noOfRecords = setCon.getResultSize();
                }
            }
            System.debug('*** setCon *** ' + setCon);
            return setCon;
        }
        set;
    }

    //Changes the size of pagination
    public PageReference refreshPageSize() {
         setCon.setPageSize(size);
         return null;
    }

    // Initialize setCon and return a list of record

    public List<Cross_Reference__c> getCompProduct() {
      prodList = (List<Cross_Reference__c>) setCon.getRecords();
      formatListPrices = getFormatListPrices(prodList);
      formatDistributorPrices = getFormatDistributorPrices(prodList);
      formatAltSitePrices = getFormatAltSitePrices(prodList);
      formatRsmPrices = getFormatRsmPrices(prodList);
      formatRepPrices = getFormatRepPrices(prodList);
      return (List<Cross_Reference__c>) setCon.getRecords();
    }

    //method to create breadcrumb back to active quote
    public String getActiveQuoteIdStr() {
        String activeQuoteIdStr = '';

        //get active quoteId
        List<User> userList = [Select id, Active_Quote_Id__c from User Where Id=: UserInfo.getUserId()];
        if(userList.size() > 0) {
            activeQuoteIdStr = userList[0].Active_Quote_Id__c;
        }
        return activeQuoteIdStr;
    }

    //method to create breadcrumb back to active quote
    public String getActiveQuoteName() {
        String activeQuoteName = '';
        String activeQuoteIdStr = '';

        //get active quoteId
        List<User> userList = [Select id, Active_Quote_Id__c from User Where Id=: UserInfo.getUserId()];
        if(userList.size() > 0) {
            activeQuoteIdStr = userList[0].Active_Quote_Id__c;
        }

        //get quote name
        List<Price_Quote__c> qList = [Select Id, Name from Price_Quote__c Where Id=:activeQuoteIdStr];
        if(qList.size() > 0) {
            activeQuoteName = qList[0].Name;
        }
        return activeQuoteName;
    }

    //method to get SAP Price
    public PageReference sapPrice(){
      strQuoteId = ApexPages.currentPage().getParameters().get('pqId');
      PP_SAP_Price sapPrice = new PP_SAP_Price();
      List<String> matNames = new List<String>();
      String materialStr = ApexPages.currentPage().getParameters().get('prdsrchVal');
      String crossStr = ApexPages.currentPage().getParameters().get('compsrchVal');
      matNames.add(materialStr);
      sapPrice.getSAPprice(matNames,crossStr,NULL,strQuoteId);
      return null;
    }
    //end of SAP Price Method

    public Map<Id,String> getFormatListPrices(List<Cross_Reference__c> prodList ){
      System.debug('*** IN getFormatListPrices *** ');
        Decimal formDec;
        String newDec;
        for(Cross_Reference__c curr : prodList ){
          System.debug('*** curr.Id *** ' + curr.Id);
            if(userLocale != 'en_US'){
                System.debug('*** userLocale *** ' + userLocale);
                if(curr.Product__r.List_Price__c == NULL){
                  curr.Product__r.List_Price__c = 0;
                }
                formDec = curr.Product__r.List_Price__c;
                newDec = formDec.format();
                formatListPrices.put(curr.Id,newDec);
            }
            else{
              if(curr.Product__r.List_Price__c == NULL){
                curr.Product__r.List_Price__c = 0;
              }
              newDec = String.valueOf(curr.Product__r.List_Price__c);
              formatListPrices.put(curr.Id,newDec);
            }
        }
        System.debug('*** formatListPrices *** ' + formatListPrices);
        return formatListPrices;
    }//end of getFormatListPrices

    public Map<Id,String> getFormatDistributorPrices(List<Cross_Reference__c> prodList ){
      System.debug('*** IN getFormatDistributorPrices *** ');
        Decimal formDec;
        String newDec;
        for(Cross_Reference__c curr : prodList ){
          System.debug('*** curr.Id *** ' + curr.Id);
            if(userLocale != 'en_US'){
                System.debug('*** userLocale *** ' + userLocale);
                if(curr.Product__r.Distributor_List__c == NULL){
                  curr.Product__r.Distributor_List__c = 0;
                }
                formDec = curr.Product__r.Distributor_List__c;
                newDec = formDec.format();
                formatListPrices.put(curr.Id,newDec);
            }
            else{
              if(curr.Product__r.Distributor_List__c == NULL){
                curr.Product__r.Distributor_List__c = 0;
              }
              newDec = String.valueOf(curr.Product__r.Distributor_List__c);
              formatDistributorPrices.put(curr.Id,newDec);
            }
        }
        System.debug('*** formatDistributorPrices *** ' + formatDistributorPrices);
        return formatListPrices;
    }//end of getFormatDistributorPrices

    public Map<Id,String> getFormatAltSitePrices(List<Cross_Reference__c> prodList ){
      System.debug('*** IN getFormatAltSitePrices *** ');
        Decimal formDec;
        String newDec;
        for(Cross_Reference__c curr : prodList ){
          System.debug('*** curr.Id *** ' + curr.Id);
            if(userLocale != 'en_US'){
                System.debug('*** userLocale *** ' + userLocale);
                if(curr.Product__r.Alt_Site_List__c == NULL){
                  curr.Product__r.Alt_Site_List__c = 0;
                }
                formDec = curr.Product__r.Alt_Site_List__c;
                newDec = formDec.format();
                formatAltSitePrices.put(curr.Id,newDec);
            }
            else{
              if(curr.Product__r.Alt_Site_List__c == NULL){
                curr.Product__r.Alt_Site_List__c = 0;
              }
              newDec = String.valueOf(curr.Product__r.Alt_Site_List__c);
              formatAltSitePrices.put(curr.Id,newDec);
            }
        }
        System.debug('*** formatAltSitePrices *** ' + formatAltSitePrices);
        return formatAltSitePrices;
    }//end of getFormatAltSitePrices

    //format currency for different locales
    public Map<Id,String> getFormatRsmPrices(List<Cross_Reference__c> prodList ){
      System.debug('*** IN getFormatRsmPrices *** ');
        Decimal formDec;
        String newDec;
        for(Cross_Reference__c curr : prodList){
          System.debug('*** curr.Id *** ' + curr.Id);
            if(userLocale != 'en_US'){
                System.debug('*** userLocale *** ' + userLocale);
                if(curr.Product__r.Rsm_Price__c == NULL){
                  curr.Product__r.Rsm_Price__c = 0;
                }
                formDec = curr.Product__r.Rsm_Price__c;
                newDec = formDec.format();
                formatRsmPrices.put(curr.Id,newDec);
            }
            else{
              if(curr.Product__r.Rsm_Price__c == NULL){
                curr.Product__r.Rsm_Price__c = 0;
              }
              newDec = String.valueOf(curr.Product__r.Rsm_Price__c);
              formatRsmPrices.put(curr.Id,newDec);
            }
        }
        System.debug('*** formatRsmPrices *** ' + formatRsmPrices);
        return formatRsmPrices;
    }//end of getFormatRsmPrices

    //format currency for different locales
    public Map<Id,String> getFormatRepPrices(List<Cross_Reference__c> prodList ){
      System.debug('*** IN getFormatRepPrices *** ');
        Decimal formDec;
        String newDec;
        for(Cross_Reference__c curr : prodList){
          System.debug('*** curr.Id *** ' + curr.Id);
            if(userLocale != 'en_US'){
                System.debug('*** userLocale *** ' + userLocale);
                if(curr.Product__r.Rep_Price__c == NULL){
                  curr.Product__r.Rep_Price__c = 0;
                }
                formDec = curr.Product__r.Rep_Price__c;
                newDec = formDec.format();
                formatRepPrices.put(curr.Id,newDec);
            }
            else{
              if(curr.Product__r.Rep_Price__c == NULL){
                curr.Product__r.Rep_Price__c = 0;
              }
              newDec = String.valueOf(curr.Product__r.Rep_Price__c);
              formatRepPrices.put(curr.Id,newDec);
            }
        }
        System.debug('*** formatRepPrices *** ' + formatRepPrices);
        return formatRepPrices;
    }//end of getFormatRepPrices
}