fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <label>Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>2 Digit Customer Group Number.</inlineHelpText>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/ERP_Active__c.field-meta.xml
<CustomField>
    <fullName>ERP_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is updated as part of the Daily Data Load from the ERP system. Any Active Customers will have a Value of True (checked).</description>
    <inlineHelpText>When this box is checked, the account is an active customer in the ERP System.</inlineHelpText>
    <label>Active in SAP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/zBlock__c.field-meta.xml
<CustomField>
    <fullName>zBlock__c</fullName>
    <label>zBlock</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/Contract_Partnership__c.object-meta.xml
<CustomObject>
    <label>Contract Partnership</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contract Partnership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Relationship that is valid but for whatever reason we need to have filtered out.</inlineHelpText>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Sale_to__c.field-meta.xml
<CustomField>
    <fullName>Sale_to__c</fullName>
    <label>Sold-to</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Ship_to__c.field-meta.xml
<CustomField>
    <fullName>Ship_to__c</fullName>
    <label>Ship-to</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Contract_Partnership_Helper_Class_Test.cls
/*********************************************************************
* Description     : Test class for Contract_Partnership_Helper_Class
* Covered Classes : Contract_Partnership_Helper_Class
* Author(s)       : Duntee Silver
**********************************************************************/
@isTest
public class Contract_Partnership_Helper_Class_Test {

    /*Code coverage for Contract_Partnership_Helper_Class*/
    @isTest static void validateAccountsTest() {
        List<Contract_Partnership__c> cpList = new List<Contract_Partnership__c>();
        Account accTest109 = new Account(
            Name = 'TestAccount109',
            SAP_Sold_To__c = '555555',
            Account_Group__c = 'Z001',
            Customer_Group__c = '16',
            zBlock__c = '00',
            ERP_Active__c = TRUE,
            Sales_Org__c = 'US60'
        );
        insert accTest109;
        
        Account accTest110 = new Account(
            Name = 'TestAccount110',
            SAP_Sold_To__c = '444444',
            Account_Group__c = 'Z002',
            Customer_Group__c = '01',
            zBlock__c = '00',
            ERP_Active__c = TRUE,
            Sales_Org__c = 'US60'
        );
        insert accTest110;
        
        Contract_Partnership__c cp1 = new Contract_Partnership__c(
        	Sale_To__c = '444444',
            Ship_To__c = '555555',
            Disabled__c = FALSE
        );
		cpList.add(cp1);
		System.assertEquals(true, cpList.size() > 0);      
        Contract_Partnership_Helper_Class.validateAccount(cpList);
        
    }//end of validateAccountsTest
    
}//end Contract_Partnership_Helper_Class_Test