fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <label>Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Cath_Lab__c.field-meta.xml
<CustomField>
    <fullName>Cath_Lab__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if this account has a Cath Lab.</description>
    <inlineHelpText>Check this box if this account has a Cath Lab.</inlineHelpText>
    <label>Cath Lab</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>2 Digit Customer Group Number.</inlineHelpText>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Emergency__c.field-meta.xml
<CustomField>
    <fullName>Emergency__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if the hospital has an emergency department.</description>
    <inlineHelpText>Check this box if the hospital has an emergency department.</inlineHelpText>
    <label>Emergency</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/ERP_Active__c.field-meta.xml
<CustomField>
    <fullName>ERP_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is updated as part of the Daily Data Load from the ERP system. Any Active Customers will have a Value of True (checked).</description>
    <inlineHelpText>When this box is checked, the account is an active customer in the ERP System.</inlineHelpText>
    <label>Active in SAP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Main_GPO__c.field-meta.xml
<CustomField>
    <fullName>Main_GPO__c</fullName>
    <inlineHelpText>Primary group purchasing affiliation.</inlineHelpText>
    <label>Primary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Premier Purchasing Partners</fullName>
            </value>
            <value>
                <fullName>MedAssets Supply Chain Systems</fullName>
            </value>
            <value>
                <fullName>Vizient Inc.</fullName>
            </value>
            <value>
                <fullName>HealthTrust Purchasing Group</fullName>
            </value>
            <value>
                <fullName>ROI</fullName>
            </value>
            <value>
                <fullName>FirstChoice Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Radiology__c.field-meta.xml
<CustomField>
    <fullName>Radiology__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box is account has a radiology department.</description>
    <inlineHelpText>Check this box is account has a radiology department.</inlineHelpText>
    <label>Radiology</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Secondary_GPO__c.field-meta.xml
<CustomField>
    <fullName>Secondary_GPO__c</fullName>
    <inlineHelpText>The secondary group purchasing organization.</inlineHelpText>
    <label>Secondary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Dignity</fullName>
            </value>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Vizient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/zBlock__c.field-meta.xml
<CustomField>
    <fullName>zBlock__c</fullName>
    <label>zBlock</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/classes/accountGraphTests.cls
@isTest
public class accountGraphTests {
    static testMethod void accountGraphTests() {
    
        //Account a= new Account(;
        //a.Name= 
        Account ta1 = new Account(
            Name = 'testAccount1',
            SAP_Sold_To__c = '102059',
            Account_Group__c = 'Z002',
            Customer_Group__c = '16'/*,
            zBlock__c = '00',
            ERP_Active__c = TRUE,
            BillingState= 'Test',
            ShippingState='ShippingTest',
            Type='Bill To',
            Main_GPO__c ='ROI',
            Secondary_GPO__c ='Amerinet',
            Radiology__c = true,
            Emergency__c =true,
            Cath_Lab__c =true*/
        );
        insert ta1;

        //Profile p = [SELECT Id FROM Profile WHERE Name='Anesthesia Medical Sales Rep'];
        Profile p = [select id from profile where name='System Administrator'];
        User tu1 = new User(Username='testing1@teleflex.com.testuser',Email='testuser@teleflex.com',Business_Unit__c = 'Latin America', Lastname='User', Firstname='Test', Alias='tuser1',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');
        User tu2 = new User(Username='testing2@teleflex.com.testuser',Email='testuser@teleflex.com',Business_Unit__c = 'Surgical', Lastname='User', Firstname='Test', Alias='tuser2',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');
        User tu3 = new User(Username='testing3@teleflex.com.testuser',Email='testuser@teleflex.com',Business_Unit__c = 'Vascular', Lastname='User', Firstname='Test', Alias='tuser3',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');
        User tu4 = new User(Username='testing4@teleflex.com.testuser',Email='testuser@teleflex.com',Business_Unit__c = 'Interventional', Lastname='User', Firstname='Test', Alias='tuser4',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');
        User tu5 = new User(Username='testing5@teleflex.com.testuser',Email='testuser@teleflex.com',Business_Unit__c = 'Specialty', Lastname='User', Firstname='Test', Alias='tuser5',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');
        User tu6 = new User(Username='testing6@teleflex.com.testuser',Email='testuser@teleflex.com',Business_Unit__c = 'Anesthesia/Respiratory', Lastname='User', Firstname='Test', Alias='tuser6',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');

        insert tu1;
        insert tu2;
        insert tu3;
        insert tu4;
        insert tu5;
        insert tu6;

        system.runAs(tu1){
            accountGraph testing = new accountGraph(new ApexPages.StandardController(ta1));
            testing.getPieData();
        }
        system.runAs(tu2){
            accountGraph testing = new accountGraph(new ApexPages.StandardController(ta1));
            testing.getPieData();
        }
        system.runAs(tu3){
            accountGraph testing = new accountGraph(new ApexPages.StandardController(ta1));
            testing.getPieData();
        }
        system.runAs(tu4){
            accountGraph testing = new accountGraph(new ApexPages.StandardController(ta1));
            testing.getPieData();
        }
        system.runAs(tu5){
            accountGraph testing = new accountGraph(new ApexPages.StandardController(ta1));
            testing.getPieData();
        }
        system.runAs(tu6){
            accountGraph testing = new accountGraph(new ApexPages.StandardController(ta1));
            testing.getPieData();
        }

    }
}