fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <label>Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>For Latin America Product Family choices. Only Latin America should see this.</description>
    <inlineHelpText>Choose a Business Unit to see the Product Families for that Business Unit.</inlineHelpText>
    <label>Business Unit Old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>LMA</fullName>
            </value>
            <value>
                <fullName>Vidacare</fullName>
            </value>
            <value>
                <fullName>AEMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Opportunity/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/PRF__c.object-meta.xml
<CustomObject>
    <label>PRF</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Owner_Cell__c.field-meta.xml
<CustomField>
    <fullName>Owner_Cell__c</fullName>
    <formula>Owner:User.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Cell</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Owner_Email__c</fullName>
    <formula>Owner:User.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Email</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>PRF</relationshipLabel>
    <relationshipName>PRF</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/Price_Quote__c.object-meta.xml
<CustomObject>
    <description>Used for Pricing portal instead of standard quotes object</description>
    <label>Price Quote</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Price Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Account_Name__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Commit_Date__c.field-meta.xml
<CustomField>
    <fullName>Commit_Date__c</fullName>
    <label>Commit Date</label>
    <type>DateTime</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account_Name__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Customer_comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_comments__c</fullName>
    <label>Customer comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <defaultValue>TODAY() + 90</defaultValue>
    <description>Expiration date of the quote</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Grand_Total__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total__c</fullName>
    <label>Grand Total</label>
    <summarizedField>Price_Quote_Line_Item__c.Extended_Price__c</summarizedField>
    <summaryForeignKey>Price_Quote_Line_Item__c.Price_Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Internal_Comments_Only__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments_Only__c</fullName>
    <label>Internal Comments Only</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/No_Opp__c.field-meta.xml
<CustomField>
    <fullName>No_Opp__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Do not create an Opportunity</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Owner_Cell__c.field-meta.xml
<CustomField>
    <fullName>Owner_Cell__c</fullName>
    <formula>Owner:User.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Help!</inlineHelpText>
    <label>Owner Cell</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Owner_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Full_Name__c</fullName>
    <formula>Owner:User.FirstName &amp; &quot; &quot; &amp;  Owner:User.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Full Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Owner_ID__c.field-meta.xml
<CustomField>
    <fullName>Owner_ID__c</fullName>
    <formula>Owner:User.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner ID</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Owner_Phone__c.field-meta.xml
<CustomField>
    <fullName>Owner_Phone__c</fullName>
    <formula>Owner:User.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Phone</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Quote_Description__c.field-meta.xml
<CustomField>
    <fullName>Quote_Description__c</fullName>
    <label>Quote Description</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#78C953</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ready for Approval</fullName>
                <color>#E27001</color>
                <label>Ready for Approval</label>
            </value>
            <value>
                <fullName>PRF In Process</fullName>
                <color>#A845DC</color>
                <label>PRF In Process</label>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
                <color>#F3D904</color>
                <label>Waiting on Approval</label>
            </value>
            <value>
                <fullName>Waiting for Contracts Approval</fullName>
                <color>#A53711</color>
                <label>Waiting for Contracts Approval</label>
            </value>
            <value>
                <fullName>Waiting For RSM Approval</fullName>
                <color>#66E9BD</color>
                <label>Waiting For RSM Approval</label>
            </value>
            <value>
                <fullName>Waiting on Director Level Approval</fullName>
                <color>#0B24BE</color>
                <label>Waiting on Director Level Approval</label>
            </value>
            <value>
                <fullName>Waiting on VP Level Approval</fullName>
                <color>#419249</color>
                <label>Waiting on VP Level Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#B6E32E</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#33CC00</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote_Line_Item__c/Price_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Price Quote Line Item</label>
    <nameField>
        <displayFormat>PQL-{0000000}</displayFormat>
        <label>Price Quote Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote_Line_Item__c/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>Price Quote Line Items</relationshipLabel>
    <relationshipName>Price_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote_Line_Item__c/fields/SAP_Sold_to__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_to__c</fullName>
    <label>SAP Sold-to</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_ImportCsv.cls
//PP_Global_Test_Class (importCsvTest method)
public with sharing class PP_ImportCsv {

	public Price_Quote__c pq {get;set;}
	private ApexPages.StandardController ctrl;

	//import CSV Stuff
	public Blob csvFileBody{get;set;}
	public string csvAsString{get;set;}
	public List<String> csvFileLines{get;set;}
	//end of import CSV Stuff

	public PP_ImportCsv() {
		String strQuoteId = ApexPages.currentPage().getParameters().get('pqid');

		pq = (strQuoteId == null) ? new Price_Quote__c() :
		 [Select Id, Name, Status__c, Commit_Date__c, CreatedDate, LastModifiedDate, Grand_Total__c, Customer_comments__c, Internal_Comments_Only__c,
              Account_Name__r.Name,Account_Name__c, Account_Name__r.Id, Account_Name__r.BillingStreet, Account_Name__r.BillingCity, Account_Name__r.BillingState,
              Account_Name__r.BillingPostalCode, Account_Name__r.BillingCountry, Account_Name__r.SAP_Sold_To__c,Account_Name__r.Account_Group__c, Quote_Description__c, No_Opp__c,
              Expiration_Date__c, Owner_ID__c, Owner_Full_Name__c, Owner_Cell__c, Owner_Phone__c, Owner_Email__c, Contact_Name__r.name, Opportunity__r.Name,
              Business_Unit__c, Contact_Name__r.id, Contact_Name__r.phone, Contact_Name__r.email, LastModifiedById, CreatedById, PRF__c,
              CurrencyIsoCode,Sales_Org_Key__c, Line_Count__c,Owner_Business_Unit__c, InApproval__c,One_Time_Purchase__c, Account_Name__r.Price_List_Type__c
              FROM Price_Quote__c
              WHERE id = :strQuoteId LIMIT 1];

      ctrl = new ApexPages.StandardController(pq);
			system.debug('pq = ' + pq);
	}

	//method to import a CSV
	public PageReference importCSVFile(){
		try{
				csvAsString = csvFileBody.toString();
				System.debug('csvAsString *** ' + csvAsString);
				csvFileLines = csvAsString.split('\n');
				List<String> prodNames = new List<String>();
				Map<String,Decimal> liMap = new Map<String,Decimal>();
				Map<String,Integer> liMapQuan = new Map<String,Integer>();
				List<Price_Quote_Line_Item__c> lines = new List<Price_Quote_Line_Item__c>();
				Decimal dprice;
				Integer quan;
				System.debug('*** csvFileLines.size() *** ' + csvFileLines.size());
				for(Integer i=1;i<csvFileLines.size();i++){
						//Price_Quote_Line_Item__c liObj = new Price_Quote_Line_Item__c() ;
						List<String> csvRecordData = csvFileLines[i].split(',');
						System.debug('*** csvRecordData *** ' + csvRecordData);
                    	System.debug('*** csvRecordData.size() *** ' + csvRecordData.size() );
						System.debug('*** i *** ' + i);
		
						for(Integer k=1;k<csvRecordData.size();k++){
							System.debug('*** csvRecordData.size() *** ' + csvRecordData.size());
                            if(k==1){
                                System.debug('*** k *** ' + k);
                                if(csvRecordData[k] != NULL && csvRecordData[k] != ''){
                                    System.debug('*** IN csvRecordDate[1] IF ***');
									dprice = decimal.valueOf(csvRecordData[1].trim());
									liMap.put(csvRecordData[0],dprice);
									System.debug('*** liMap csvRecordData[1] IF *** ' + liMap);
                                }//end of inner if
                                else{
									System.debug('*** IN csvRecordDate[1] ELSE ***');
									dprice = 0.01;
									liMap.put(csvRecordData[0],dprice);
									System.debug('*** liMap csvRecordData[1] ELSE *** ' + liMap);
								}//end else
                            }//end of outter if

                            if(k==2){
                                System.debug('*** k *** ' + k);
                                System.debug('*** csvRecordData[k] in k==2 *** ' + csvRecordData[k]);
                                if(csvRecordData[k] != NULL && csvRecordData[k] != ''){
                                    System.debug('*** IN csvRecordDate[2] IF ***');
                                    System.debug('*** csvRecordData[2] IN IF *** ' + csvRecordData[2]);
                                    quan = integer.valueOf(csvRecordData[2].trim());
                                    liMapQuan.put(csvRecordData[0],quan);
                                    System.debug('*** liMapQuan csvRecordData[2] IF *** ' + liMapQuan);
                                }//end inner if
                                else{
                                    System.debug('*** IN csvRecordDate[2] ELSE ***');
                                    quan = 1;
                                    liMapQuan.put(csvRecordData[0],quan);
                                    System.debug('*** liMapQuan csvRecordData[2] ELSE *** ' + liMapQuan);
                                }//end else 
                            }//end outter if
                            
						}//end inner for(Integer k=1;k<csvRecordData.size();k++)

						system.debug('liMap ' + liMap);
                    	system.debug('liMapQuan ' + liMapQuan);
						system.debug('csvFileLines['+i+'] ' + csvFileLines[i]);
						prodNames.add(csvRecordData[0]);
				}//end outter for(Integer i=1;i<csvFileLines.size();i++)

				List<Product2> prods = [SELECT Id, Name, List_Price__c, Rep_Price__c, RSM_Price__c, CurrencyIsoCode,
										Director_Price__c, Floor_Price__c, Cost__c, Cost_Formula__c, Description
										FROM Product2
										WHERE Name IN: prodNames AND Sales_Org_Key__c =: pq.Sales_Org_Key__c];

				system.debug('prods *** ' + prods);
				for(Product2 curr : prods){

					//system.debug('price ***' + price);
					//system.debug('dprice ***' + dprice);
					Price_Quote_Line_Item__c obj = new Price_Quote_Line_Item__c();
					obj.Refresh__c = true;
					obj.Price_Quote__c = pq.Id;
					obj.Material_Name__c = curr.Id;
					obj.Product_Description__c = curr.Description;
					obj.List_Price__c = curr.List_Price__c;
					obj.Rep_Price__c = curr.Rep_Price__c;
					obj.RSM_Price__c = curr.RSM_Price__c;
					obj.Director_Price__c = curr.Director_Price__c;
					obj.Floor_Price__c = curr.Floor_Price__c;
					obj.Cost__c = curr.Cost_Formula__c;
					//system.debug('curr.name ***' + curr.Name);
					//system.debug('decimal Price ***' + liMap.get(curr.Name));
					obj.Sales_Price__c = liMap.get(curr.name);
					obj.Quantity__c = liMapQuan.get(curr.name);
					obj.CurrencyIsoCode = curr.CurrencyIsoCode;
					//obj.Row_Order__c = lineCount + 1;
					lines.add(obj);
				}

				try{
					insert lines; // insert line items with just standard pricing
				}
				catch(Exception e){
					ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while trying to insert materials.  Please make sure input csv file is correct.. (Error: '+e.getMessage()+')');
				}

		 }//end of outter try
		 catch (Exception e)
		 {
				 ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while importing data Please make sure input csv file is correct.. (Error: '+e.getMessage()+')');
				 ApexPages.addMessage(errorMessage);
		 }

		 String quoteid = pq.Id;
		 List<Price_Quote_Line_Item__c> check = [SELECT Eligible_Price__c,Id,Material_Name__c,Refresh__c,Sales_Price__c FROM Price_Quote_Line_Item__c WHERE refresh__c = true AND Price_Quote__c =:quoteid];
		 if(check.size() > 0){
			 String query = 'SELECT Eligible_Price__c,Id,Material_Name__c,Refresh__c,Sales_Price__c FROM Price_Quote_Line_Item__c WHERE refresh__c = true AND Price_Quote__c = \''+quoteid+'\'';
			 PP_ImportCsvBatch batch = new PP_ImportCsvBatch(query);
			 Database.executeBatch(batch,50);
			 ID batchprocessid = Database.executeBatch(batch,50);

			 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Your request is being processed.  You will receive an email when your batch job is complete.'));
			 return null;
		 }
		 else{
			 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.label.EMEA_No_line_items_found_for_this_Price_Quote));
			 return null;
		 }

	 }//end of importCsv method

}