fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <label>Account Group</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Account_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_2__c</fullName>
    <label>Account Name 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Agreement_Count__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Count__c</fullName>
    <label>Agreement Count</label>
    <summaryForeignKey>Contract_Customer__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group_Formula__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Formula__c</fullName>
    <formula>IF(
AND(
NOT(ISBLANK(Customer_Group_Name__c)),
NOT(ISBLANK(Customer_Group__c))
), Customer_Group_Name__c &amp; &quot; (&quot; &amp; Customer_Group__c &amp; &quot;)&quot;,
&quot;&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Group</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/ERP_Active__c.field-meta.xml
<CustomField>
    <fullName>ERP_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is updated as part of the Daily Data Load from the ERP system. Any Active Customers will have a Value of True (checked).</description>
    <inlineHelpText>When this box is checked, the account is an active customer in the ERP System.</inlineHelpText>
    <label>Active in SAP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Free_Freight_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Free_Freight_Threshold__c</fullName>
    <label>Free Freight Threshold</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Last_SAP_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_SAP_Update__c</fullName>
    <label>Last SAP Update</label>
    <type>DateTime</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/List_Price_Type__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Type__c</fullName>
    <formula>CASE(Price_List_Type__c, 
&quot;ZA&quot;, &quot;Alt Site (ZA)&quot;, 
&quot;ZD&quot;, &quot;Distributor (ZD)&quot;,
&quot;Hospital (ZH)&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>List Price Type</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Main_GPO__c.field-meta.xml
<CustomField>
    <fullName>Main_GPO__c</fullName>
    <inlineHelpText>Primary group purchasing affiliation.</inlineHelpText>
    <label>Primary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Premier Purchasing Partners</fullName>
            </value>
            <value>
                <fullName>MedAssets Supply Chain Systems</fullName>
            </value>
            <value>
                <fullName>Vizient Inc.</fullName>
            </value>
            <value>
                <fullName>HealthTrust Purchasing Group</fullName>
            </value>
            <value>
                <fullName>ROI</fullName>
            </value>
            <value>
                <fullName>FirstChoice Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Secondary_GPO__c.field-meta.xml
<CustomField>
    <fullName>Secondary_GPO__c</fullName>
    <inlineHelpText>The secondary group purchasing organization.</inlineHelpText>
    <label>Secondary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Dignity</fullName>
            </value>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Vizient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <description>Payment Terms</description>
    <inlineHelpText>Payment Terms</inlineHelpText>
    <label>Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>Territory_Key__c</fullName>
    <description>Territory_Key__c is built every day as part of the daily Invoiced Sales ETL. 
Apex: account_Active_Sales
Scheduled Apex: Invoiced_Sales_Maintenance_Scheduler</description>
    <inlineHelpText>List of Territory Numbers that have Sales related to this Account.</inlineHelpText>
    <label>Territory Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>&quot;Yes&quot;</defaultValue>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/Contract_Customer__c.object-meta.xml
<CustomObject>
    <label>Contract Customer</label>
    <nameField>
        <label>Contract Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <inlineHelpText>GPO Owner Name</inlineHelpText>
    <label>Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/Contract_Partnership__c.object-meta.xml
<CustomObject>
    <label>Contract Partnership</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contract Partnership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Relationship that is valid but for whatever reason we need to have filtered out.</inlineHelpText>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Sale_to__c.field-meta.xml
<CustomField>
    <fullName>Sale_to__c</fullName>
    <label>Sold-to</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Ship_to__c.field-meta.xml
<CustomField>
    <fullName>Ship_to__c</fullName>
    <label>Ship-to</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/Price_Quote__c.object-meta.xml
<CustomObject>
    <description>Used for Pricing portal instead of standard quotes object</description>
    <label>Price Quote</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Price Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/List_Price_Type__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Type__c</fullName>
    <formula>Account_Name__r.List_Price_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>List Price Type</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Alignment__c/Territory_Alignment__c.object-meta.xml
<CustomObject>
    <label>Territory Alignment Rules</label>
    <nameField>
        <label>ZPSA Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Alignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Alignment__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Master</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Alignment Rules</relationshipLabel>
    <relationshipName>Territory_Alignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <label>Territory Account Assignments</label>
    <nameField>
        <label>Territory Assignments</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Account Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Territory_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Territory_Alignment__c</fullName>
    <label>Territory Alignment Rules</label>
    <referenceTo>Territory_Alignment__c</referenceTo>
    <relationshipLabel>Territory Account Assignments</relationshipLabel>
    <relationshipName>Territory_Assignment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Customer_Details.cls
/*********************************************************************
* Description      : Controller Class for Customer Details.
* Test Class       : PP_Customer_Details_Test
* VisualForce      : PP_Customer_Details
* Author(s)        : Dun Silver
**********************************************************************/
Public with sharing class PP_Customer_Details{

    public Account acct {get; set;}

    public String strCust{get; set;}

    public boolean refreshpage {get; set;}
    public boolean showSoldTo {get; set;}

    public map<String, Account> CCList{get; set;}

    public set<String> cnlist{get; set;}
    public set<String> acheck{get; set;}

    public list<Account> cplist{get; set;}
    
    // New Account Team - 26Jun2018
    public list<Territory_Master__c> ATMlist {get; set;}
    public list<String> tsort {get; set;}
    public map<String, String> tSales {get; set;}
    public map<String, Territory_Master__c> atmMap {get; set;}
    public map<String, String> repMap {get; set;}
    public map<String, String> repId {get; set;}
    
    public boolean atmCheck {get; set;}
    // End New

    //get language of end user
    public String userLang{get{
        return UserInfo.getLanguage();
    }set;}

    Public String cid{get{
        return ApexPages.currentPage().getParameters().get('cid');
    } set;}

    public PP_Customer_Details(){
        system.debug('-- Starting Inner Class --');
        //String AcctNum;
        acct = new Account();
        cnlist = new set<String>();

        acheck = new set<string>();
        CCList = new map<String, Account>();
        cplist = new list<Account>();
        refreshpage = FALSE;
        showSoldTo = FALSE;

        if(ApexPages.currentPage().getParameters().get('cid') != NULL){
            acct = [SELECT Id, Name, ShippingStreet, ShippingCity, ShippingState, Terms__c,
                    ShippingPostalCode, ShippingCountry, SAP_Sold_To__c, Free_Freight_Threshold__c,
                    ERP_Active__c, Type, Customer_Group_Formula__c, Main_GPO__c, Secondary_GPO__c,
                    Last_SAP_Update__c, Agreement_Count__c, List_Price_Type__c,
                    Territory_Key__c, Account_Name_2__c
                    FROM Account
                    WHERE SAP_Sold_To__c = :ApexPages.currentPage().getParameters().get('cid')
                    LIMIT 1];

        }
        else if(ApexPages.currentPage().getParameters().get('id') != NULL){
            acct = [SELECT Id, Name, ShippingStreet, ShippingCity, ShippingState, Terms__c,
                    ShippingPostalCode, ShippingCountry, SAP_Sold_To__c, Free_Freight_Threshold__c,
                    ERP_Active__c, Type, Customer_Group_Formula__c, Main_GPO__c, Secondary_GPO__c,
                    Last_SAP_Update__c, Agreement_Count__c, List_Price_Type__c, RecordType.Name,
                    Territory_Key__c, Account_Name_2__c
                    FROM Account
                    WHERE Id = :ApexPages.currentPage().getParameters().get('id')
                    LIMIT 1];
        }
        system.debug('acct: ' + acct);

        if(acct != NULL){
            list<String> soldtoList = new list<String>();

            if(acct.SAP_Sold_To__c != NULL){
                //loop to grab Sold To Partner codes and store in list
                if(acct.Agreement_Count__c > 0){
                    cnlist.add(acct.SAP_Sold_To__c);
                }
                else{
                    system.debug('Skipping Primary Account - Missing Contracts: ' + acct.SAP_Sold_To__c);
                }

                for(Contract_Partnership__c cp : [SELECT Sale_to__c, Ship_to__c
                                                  FROM Contract_Partnership__c
                                                  WHERE Ship_to__c = :acct.SAP_Sold_To__c 
                                                  AND Disabled__c = FALSE])
                {
                    cnlist.add(cp.Sale_to__c);
                    soldtoList.add(cp.Sale_to__c);
                }
                System.debug('cnlist ===================================== ' + cnlist);

                // Build List of Accounts to Check if User has access to Sold-To Accounts
                for(Account a : [SELECT SAP_Sold_To__c FROM Account WHERE SAP_Sold_To__c IN :cnlist ORDER BY SAP_Sold_To__c]){
                    acheck.add(a.SAP_Sold_To__c);
                }
                System.debug('acheck ===================================== ' + acheck);
                // If the size is the same - ALL Good!
                if(cnlist.size() == acheck.size()){
                    System.debug('acheck: ' + acheck.size());
                    refreshpage = FALSE;
                }
                else if(acheck.isEmpty()){ // Support for Prospect Accounts - ALL Good!
                  System.debug('*** acheck.isEmpty() ***');
                    refreshpage = TRUE;
                }
                else{ // ELSE when the page loads the page action/method checkSecurity will fire.
                // This will add the user to the Sold-To account share
                  System.debug('*** ELSE AFTER acheck.isEmpty() ***');
                  refreshpage = TRUE;
                }

                //PP_Customer_Detail_Helper newChk = new PP_Customer_Detail_Helper();
                //newChk.checkSecurity(cnlist,acheck);
                System.debug('*** refreshpage after else *** ' + refreshpage);
                if(refreshpage == FALSE && soldtoList.size() > 0){
                    for(Account a : [SELECT Name, SAP_Sold_To__c FROM Account where SAP_Sold_To__c = :soldtoList])
                    {
                        cplist.add(a);
                        showSoldTo = TRUE;
                    }
                }


            } // END SAP != NULL IF

            // Build List of Contracts
            //if(acct != NULL){
            system.debug('-- Building List of Contracts -- ');
            for(Account a : [SELECT Name, SAP_Sold_To__c,ShippingCity,ShippingStreet,ShippingState,ShippingPostalCode,
                             (SELECT Name, Agreement__r.Owner__c, Agreement__r.Name, Agreement__r.GPO_Contract_Ref__c,
                              Agreement__r.Owner_Name__c, Agreement__r.Description__c,Account__r.SAP_Sold_To__c,
                              Agreement__r.Objective__c, Agreement__r.Objective_Name__c,
                              Valid_From__c, Valid_To__c, Condition__c, Agreement__r.Divisions__c
                              FROM Contract_Customers__r
                              WHERE Active_Future__c = TRUE
                              ORDER BY Agreement__r.Description__c ASC)
                             FROM Account
                             WHERE SAP_Sold_To__c IN :cnlist
                             //AND Agreement_Count__c > 0
                             Order BY Account_Group__c DESC])
            {
                CCList.put(a.SAP_Sold_To__c, a);
            }
                system.debug(' -- List of Contracts: ' + CCList.size());
            //}
            
            // Build out the Account Team - 26Jun2018 - ESC
            // Pulled from the VF Account Page
            ATMlist = new list<Territory_Master__c>();
            tsort = new list<String>();
            atmMap = new map<String, Territory_Master__c>();
            repMap = new map<String, String>();
            repId = new map<String, String>();
            tSales = new map<String, String>();
            atmCheck = false;

            // This builds out a map of Territories that have Sales
          List<String> sortedvalue = new List<String>(); 
            if(acct.Territory_Key__c != NULL){
                string poiList = acct.Territory_Key__c;
                sortedvalue = poiList.split(';');
                sortedvalue.sort();
                for(string s : sortedvalue){
                    tSales.put(s, '$');
                } 
            }
            
            // New ATMlist
            set<String> tset = new set<String>();
            for(Territory_Assignment__c ta : [SELECT Territory_Number__c 
                                              FROM Territory_Assignment__c
                                              WHERE Account__c =:acct.Id 
                                              AND Territory_Alignment__r.Active__c = TRUE 
                                              ORDER BY Business_Unit__c])
            {
                tset.add(ta.Territory_Number__c);
            }
            //adding the territories that have sales
            tset.addAll(sortedvalue);
            //Check standard account team memebers and add thier territories to tset
		Set<Id> accountTeamUsersSet = new Set<Id>();
        for(AccountTeamMember atm: [SELECT UserId 
                                          FROM AccountTeamMember
                                          WHERE AccountId =: acct.Id])
        {
            accountTeamUsersSet.add(atm.UserId);
        }
        if(!accountTeamUsersSet.isEmpty()){
            for(Territory_Master__c tmByUser :[SELECT Id, Territory_Number__c
                                     FROM Territory_Master__c 
                                     WHERE Primary_Territory_User__c IN:accountTeamUsersSet OR Sales_Rep__c IN:accountTeamUsersSet])
            {
                 tset.add(tmByUser.Territory_Number__c);
            }
        }

            
            for(Territory_Master__c tm :[SELECT Id, Name, Role__c, Business_Unit__c, Primary_Territory_User__r.Name, Sales_Rep__r.Name,
                                         Territory_Number__c
                                         FROM Territory_Master__c 
                                         WHERE Territory_Number__c =:tset
                                         ORDER BY Business_Unit__c, Role__c DESC])
            {
                atmCheck = true;
                tsort.add(tm.Territory_Number__c);
                atmMap.put(tm.Territory_Number__c, tm);
                if(tm.Sales_Rep__r.Name != NULL){
                    repMap.put(tm.Territory_Number__c, tm.Sales_Rep__r.Name);
                    repId.put(tm.Territory_Number__c, tm.Sales_Rep__r.Id);
                }
                else if(tm.Primary_Territory_User__r.Name != NULL){
                    repMap.put(tm.Territory_Number__c, tm.Primary_Territory_User__r.Name);
                    repId.put(tm.Territory_Number__c, tm.Primary_Territory_User__r.Id);
                }
                else{
                    repMap.put(tm.Territory_Number__c, 'Open');
                    repId.put(tm.Territory_Number__c, 'Blank');
                }
                if(!tSales.containsKey(tm.Territory_Number__c)){
                    tSales.put(tm.Territory_Number__c, '-');
                }
            }
            // End new ATM
            
            
        } // END acct != NULL IF
    }



    /*Public set<String> cnlist {get{

        String AcctNum = ApexPages.currentPage().getParameters().get('cid');
        AcctNum = AcctNum.trim();

        cnlist = new set<String>();

        //loop to grab Sold To Partner codes and store in list
        cnlist.add(AcctNum);
        for(Contract_Partnership__c cp : [SELECT Sale_to__c, Ship_to__c
                                          FROM Contract_Partnership__c
                                          WHERE Ship_to__c = :AcctNum])
        {
            cnlist.add(cp.Sale_to__c);
        }
        System.debug('cnlist ===================================== ' + cnlist);
        set<string> acheck = new set<string>();
        for(Account a : [SELECT SAP_Sold_To__c FROM Account WHERE SAP_Sold_To__c IN :cnlist]){
            acheck.add(a.SAP_Sold_To__c);
        }
        PP_Customer_Detail_Helper checkSecurity = new PP_Customer_Detail_Helper();
        checkSecurity.checkSecurity(cnlist,acheck);

        return cnlist;

    } set;} */

    Public void checkSecurity(){
        /*
        String AcctNum = ApexPages.currentPage().getParameters().get('cid');
        AcctNum = AcctNum.trim();

        set<string> cnlist2 = new set<String>();

        //loop to grab Sold To Partner codes and store in list
        cnlist2.add(AcctNum);
        for(Contract_Partnership__c cp : [SELECT Sale_to__c, Ship_to__c
                                          FROM Contract_Partnership__c
                                          WHERE Ship_to__c = :AcctNum])
        {
            cnlist2.add(cp.Sale_to__c);
        }
        */
        System.debug('*** refreshpage checkSecurity *** ' + refreshpage);
        if(refreshpage){
            System.debug('*** IN PP_Customer_Details checkSecurity IF(refreshpage) ***');
            set<string> acheck = new set<string>();
            for(Account a : [SELECT SAP_Sold_To__c FROM Account WHERE SAP_Sold_To__c IN :cnlist]){
                acheck.add(a.SAP_Sold_To__c);
            }
            System.debug('*** cnlist *** ' + cnlist);
            System.debug('*** acheck *** ' + acheck);
            PP_Customer_Detail_Helper checkSecurity = new PP_Customer_Detail_Helper();
            checkSecurity.checkSecurity(cnlist,acheck);
        }
    }
    // Catch 'Lookup Customer' and redirect back
    public pagereference getURL(){
        System.debug('strCust ============================== ' + strCust);
        string search = strCust;
        if(search != NULL){
            search = search.trim();
            list<Account> AcctCheck = [SELECT Id FROM Account WHERE SAP_Sold_To__c  = :search LIMIT 1];

            if(AcctCheck.size() > 0){
                system.debug('search: ' + search);
                PageReference getCustomer = New Pagereference('/apex/PP_Customer_Details?cid='+search);
                getCustomer.setRedirect(true);
                return getCustomer;
            }
            else{
                apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Not a valid Contract Customer Number...'));
                return NULL;
            }

        }
        else{
            apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Please enter a Customer Number...'));
            return NULL;
        }
    }

    /* public map<String, Account> getCCList(){

        try{

            system.debug('-- Starting getCCList --');
            map<String, Account> aMap = new map<String, Account>();
            for(Account a : [SELECT Name, SAP_Sold_To__c,ShippingCity,ShippingStreet,ShippingState,ShippingPostalCode,
                             (SELECT Name, Agreement__r.Owner__c, Agreement__r.Name, Agreement__r.GPO_Contract_Ref__c,
                              Agreement__r.Owner_Name__c, Agreement__r.Description__c,Account__r.SAP_Sold_To__c,
                              Agreement__r.Objective__c, Agreement__r.Objective_Name__c,
                              Valid_From__c, Valid_To__c, Condition__c, Agreement__r.Divisions__c
                              FROM Contract_Customers__r
                              WHERE Active_Future__c = TRUE
                              ORDER BY Agreement__r.Description__c ASC)
                             FROM Account
                             WHERE SAP_Sold_To__c IN :cnlist
                             //AND Agreement_Count__c > 0
                             Order BY Account_Group__c DESC])
            {
                aMap.put(a.SAP_Sold_To__c, a);
            }
            return aMap;
        }
        catch (Exception e){
            return NULL;
        }


    }
*/
    /*
    //method to get recent accounts and quotes
    public void createRecentLists() {
        recentAccList = new List<Account>();
        recentQuoteList = new List<Price_Quote__c>();

        recentAccList = [SELECT Id, Name,LastViewedDate,SAP_Sold_To__c FROM Account WHERE LastViewedDate !=null ORDER BY LastViewedDate DESC limit 10];
        recentQuoteList = [SELECT Id, Account_Name__R.Name, Name,LastViewedDate,Contact_Name__r.Name FROM Price_Quote__c WHERE LastViewedDate !=null ORDER BY LastViewedDate DESC limit 10];
    }
    */
    public Id getcustomerreport(){
        try {
            return [SELECT Id FROM Report WHERE Name = 'Contract Customer Detail' LIMIT 1].id;
        }
        catch (Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }
    /*
    public list<Account> getcplist(){
        if(ApexPages.currentPage().getParameters().get('cid') != NULL){
            list<Account> soldtoAcc = new list<Account>();
            list<String> sapList = new list<String>();
            try{
                if(ApexPages.currentPage().getParameters().get('cid') != NULL){
                    for(Contract_Partnership__c cp : [SELECT Sale_to__c
                                                      FROM Contract_Partnership__c
                                                      WHERE Ship_to__c = :ApexPages.currentPage().getParameters().get('cid')])
                    {
                        sapList.add(cp.Sale_to__c);
                    }
                    if(sapList.size() > 0){
                        soldtoAcc = [SELECT Name, SAP_Sold_To__c FROM Account where SAP_Sold_To__c = :sapList];
                        return soldtoAcc;
                    }
                }
                return NULL;
            }
            catch (Exception e){
                system.debug('Exception: ' + e);
                return NULL;
            }
        }
        else{
            return NULL;
        }
    }*/

    //method to get searched customer info
    /*
    public Account getcc(){
        if(ApexPages.currentPage().getParameters().get('cid') != NULL){
            try{
                return [SELECT Id, Name, ShippingStreet, ShippingCity, ShippingState,
                        ShippingPostalCode, ShippingCountry, SAP_Sold_To__c,
                        ERP_Active__c, Type, Customer_Group_Formula__c, Main_GPO__c, Secondary_GPO__c,
                        Last_SAP_Update__c
                        FROM Account
                        WHERE SAP_Sold_To__c = :ApexPages.currentPage().getParameters().get('cid')];
            }
            catch(Exception e){
                system.debug('Exception: ' + e);
                return NULL;
            }
        }
        else if(ApexPages.currentPage().getParameters().get('id') != NULL){
            try{
                return [SELECT Id, Name, ShippingStreet, ShippingCity, ShippingState,
                        ShippingPostalCode, ShippingCountry, SAP_Sold_To__c,
                        ERP_Active__c, Type, Customer_Group_Formula__c, Main_GPO__c, Secondary_GPO__c,
                        Last_SAP_Update__c
                        FROM Account
                        WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
            }
            catch(Exception e){
                system.debug('Exception: ' + e);
                return NULL;
            }
        }
        else{
            return NULL;
        }

    }
*/
}