fullSandbox11072023/force-app/main/default/objects/Account/fields/Active_Sales__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales__c</fullName>
    <description>Sales_by_BU_Key__c is built every day as part of the daily Invoiced Sales ETL. 
Apex: account_Active_Sales
Scheduled Apex: Invoiced_Sales_Maintenance_Scheduler changed to account_Active_Sales_check</description>
    <formula>Sales_by_BU_Key__c != NULL</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Account has Sales from this Year or Last</inlineHelpText>
    <label>Active Sales</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10CR - HO Corporate Retail</fullName>
            </value>
            <value>
                <fullName>10HO - HO Hardware</fullName>
            </value>
            <value>
                <fullName>10IR - HO Independent Retail</fullName>
            </value>
            <value>
                <fullName>10SI - HO Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>12CR - NSW Corporate Retail</fullName>
            </value>
            <value>
                <fullName>12IR - NSW Independent Retail</fullName>
            </value>
            <value>
                <fullName>12SI - NSW Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>13CR - VIC Corporate Retail</fullName>
            </value>
            <value>
                <fullName>13IR - VIC Independent Retail</fullName>
            </value>
            <value>
                <fullName>13SI - VIC Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>14CR - QLD Corporate Retail</fullName>
            </value>
            <value>
                <fullName>14IR - QLD Independent Retail</fullName>
            </value>
            <value>
                <fullName>14SI - QLD Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>15CR - SA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>15IR - SA Independent Retail</fullName>
            </value>
            <value>
                <fullName>15SI - SA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>16CR - WA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>16IR - WA Independent Retail</fullName>
            </value>
            <value>
                <fullName>16SI - WA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>18CR - Int/Emer Corporate Retail</fullName>
            </value>
            <value>
                <fullName>18IR - Int/Emer Independent Retail</fullName>
            </value>
            <value>
                <fullName>18SI - Int/Emer Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>31IN - Fishers Industrial</fullName>
            </value>
            <value>
                <fullName>31RS - Fishers Reseller</fullName>
            </value>
            <value>
                <fullName>4201 - ACT</fullName>
            </value>
            <value>
                <fullName>4202 - South Eastern Sydney</fullName>
            </value>
            <value>
                <fullName>4203 - Southern NSW</fullName>
            </value>
            <value>
                <fullName>4204 - South Western Sydney</fullName>
            </value>
            <value>
                <fullName>4205 - Western NSW</fullName>
            </value>
            <value>
                <fullName>4206 - Western Syd LHN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/Invoiced_Sales__c.object-meta.xml
<CustomObject>
    <description>Invoiced Sales is the official name that SAP sales that have are shipped and counted towards compensation.</description>
    <label>Invoiced Sales</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Invoiced Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Commissionable Date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/YOY_Flag__c.field-meta.xml
<CustomField>
    <fullName>YOY_Flag__c</fullName>
    <formula>MONTH(Date__c) &lt;= MONTH(Business_Days__r.Date_Key__c)
/*
AND(
OR(
MONTH(Date__c) &lt;= MONTH(Business_Days__r.Date__c),
MONTH(Date__c) = 1
),
OR(
YEAR(Date__c) = YEAR(TODAY())-1,
YEAR(Date__c) = YEAR(TODAY())
)
)*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Filters from current month back to January</inlineHelpText>
    <label>YOY Flag</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/Sales_Accounts__c.object-meta.xml
<CustomObject>
    <label>Sales Account</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Sales Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Accounts</relationshipLabel>
    <relationshipName>Sales_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <externalId>true</externalId>
    <label>Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/Sales_PYTD__c.field-meta.xml
<CustomField>
    <fullName>Sales_PYTD__c</fullName>
    <label>Sales PYTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <formula>Account__r.SAP_Sold_To__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Code</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Sales Accounts</relationshipLabel>
    <relationshipName>Sales_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Build_Sales_Last_Ordered_Batch.cls
global class Build_Sales_Last_Ordered_Batch Implements Database.Batchable<sObject> {
    // Step 1. Invoiced_Sales_Maintenance_Batch - Purges old out of date 'Invoice Sales' files
    // Step 2. Invoiced_Sales_Detail_Maintenance_Batch - Purges Invoiced Sales Detail Records not updated today
    // Step 3. Open_Orders_Maintenance_Batch - Purges Open Orders records not updated today
    // Step 4. account_Active_Sales - Associates the BU and Territory number to the account that drives 'Territory Key', 'Active Sales', and 'Active Sales My BU'
    // Step 5. Build_Sales_Accounts_Batch - Builds the 'Sales Account' records relating the Account and Territory.
    // Step 6. Build_Sales_Last_Ordered_Batch - Build's the 'Last Ordered' on Sales Accounts

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query;
        
        query = 'SELECT Id, Name, SAP_Code__c FROM Account WHERE Active_Sales__c = TRUE ';
        
        system.debug('Starting Batch: ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        // Last Ordered Date
        // Create List
        // Check Open Orders
        // Check Order Details
        // Check Invoiced Orders
        // Write: # of open orders / open orders by Territory
        
        list<Account> aList = (list<Account>)scope;
        set<Id> aSet = new set<Id>();
        set<String> asKey = new set<String>();
        
        map<String, Id> asMap = new map<String, Id>();
        map<String, Decimal> lastyearSales = new map<String, Decimal>();
        map<String, Decimal> thisyearSales = new map<String, Decimal>();
        list<Sales_Accounts__c> saList = new list<Sales_Accounts__c>();
        
        decimal sales; // Sales
        string yearCurrent; 
        string account;
        string territory;
        
        string thisYear = String.valueOf(System.Today().year());
        string lastYear = String.valueOf(System.Today().year()-1);
        
        for(Account a : aList){
            aSet.add(a.Id);
        }
        
        for(Sales_Accounts__c sa : [SELECT Id, Key__c 
                                    FROM Sales_Accounts__c 
                                    WHERE Account__c =:aSet])
        {
            asMap.put(sa.Key__c, sa.Id);
        }
        
        for(AggregateResult ar : [SELECT Territory__c territory, Account__c account, CALENDAR_YEAR(Date__c) Year, SUM(Sales__c) Sales 
                                  FROM Invoiced_Sales__c 
                                  WHERE Account__c = :aSet 
                                  AND YOY_Flag__c = TRUE 
                                  GROUP BY Territory__c, Account__c, CALENDAR_YEAR(Date__c)])
        {
            sales = (decimal) ar.get('Sales');
            account = (string) ar.get('account');
            territory = (string) ar.get('territory');
            yearCurrent = String.valueOf(ar.get('Year'));
            
            if(yearCurrent == thisYear){
                thisyearSales.put(account + '-' + territory, sales);
            }
            else if(yearCurrent == lastYear){
                lastyearSales.put(account + '-' + territory, sales);
            }
            asKey.add(account + '-' + territory);
        }
        list<String> asSplit = new list<String>();
        integer sloop;
        
        for(string asales : asKey){
            sloop = 1;
            asSplit = asales.split('-', -2);

            for(string split : asSplit){
                if(sloop == 1){
                    account = split;
                    ++sloop;
                }
                else if(sloop == 2){
                    territory = split;
                    ++sloop;
                }
            }
            
            if(thisyearSales.get(asales) != NULL || lastyearSales.get(asales) != NULL){
                Sales_Accounts__c newSA = new Sales_Accounts__c(
                    Account__c = account,
                    Territory__c = territory,
                    Key__c = asales,
                    Sales_YTD__c = 0,
                    Sales_PYTD__c = 0
                );
                if(thisyearSales.get(asales) != NULL){
                    newSA.Sales_YTD__c = thisyearSales.get(asales);
                }
                if(lastyearSales.get(asales) != NULL){
                    newSA.Sales_PYTD__c = lastyearSales.get(asales);
                }
                if(asMap.get(asales) != NULL){
                    newSA.Id = asMap.get(asales);
                }                
                saList.add(newSA);
            }
        }

        if(saList.size() > 0){
            upsert saList;
        }
        
        
    }
    
    
    global void finish(Database.BatchableContext BC){
        //UserInfo.getUserEmail();
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob WHERE Id =
                          :BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {a.CreatedBy.Email};
            mail.setToAddresses(toAddresses);
        mail.setSubject('Build Contracts Headers Finished: ' + a.Status);
        mail.setPlainTextBody
            ('The batch Apex job processed ' + a.JobItemsProcessed +
             ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
}