fullSandbox11072023/force-app/main/default/objects/Account/fields/Agreement_Count__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Count__c</fullName>
    <label>Agreement Count</label>
    <summaryForeignKey>Contract_Customer__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>2 Digit Customer Group Number.</inlineHelpText>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/Contract_Customer__c.object-meta.xml
<CustomObject>
    <label>Contract Customer</label>
    <nameField>
        <label>Contract Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <inlineHelpText>GPO Owner Name</inlineHelpText>
    <label>Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Membership_Export_Test.cls
public class PP_Membership_Export_Test {

    public String filename { 
        get { 
            String temp_name = [Select Owner_Name__c FROM Contract_Header__c WHERE Owner__c = :ApexPages.currentPage().getParameters().get('oid') LIMIT 1].Owner_Name__c;
			temp_name = temp_name.replace(',','');
            temp_name += ' Membership ';
            temp_name += datetime.now().format('mm-dd-yyyy');
            System.debug('Temp_Name ===================================== ' + temp_name);            
            return temp_name; 
        } 
        set; }
    public transient list<Account> accList {get; set;}
    public transient list<Contract_Customer__c> accList_temp {get; set;}
    public transient set<String> accSet {get; set;}

    public list<Account> getAccounts(){
        list<Contract_Customer__c> accList_temp;
        accList_temp = [SELECT SAP_Code__c FROM Contract_Customer__c WHERE Agreement__r.Owner__c = :ApexPages.currentPage().getParameters().get('oid')];
        set<String> accSet;
        for(Contract_Customer__c c : accList_temp){
            accSet.add(c.Sap_Code__c);
        }
        list<Account> accList;
        
        //accSet =  [SELECT id, SAP_Code__c, Account_Name__c FROM Contract_Customer__c WHERE Agreement__r.Owner__c = :ApexPages.currentPage().getParameters().get('oid') ORDER BY Account_Name__c];
        //accList = [SELECT id, SAP_Sold_To__c, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Customer_Group__c, Customer_Group_Name__c FROM Account where Agreement_Count__c > 0 AND id IN (SELECT Account__c FROM Contract_Customer__c WHERE Agreement__r.Owner__c = :ApexPages.currentPage().getParameters().get('oid')) ORDER BY Name];
        
        accList = [SELECT SAP_Sold_To__c, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, Customer_Group__c, Customer_Group_Name__c FROM Account where SAP_Sold_To__c IN :accSet ORDER BY Name];
        return accList;
    }
    
    

}