fullSandbox11072023/force-app/main/default/objects/Account/fields/Billing_Address_Full__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address_Full__c</fullName>
    <formula>If(BillingCity != &apos;&apos;, BillingStreet + BR() +
BillingCity+ &quot;, &quot;+ BillingState + &quot; &quot; + BillingPostalCode + &quot; &quot; + BillingCountry, &apos;&apos;)</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Account__c/Territory_Account__c.object-meta.xml
<CustomObject>
    <label>Territory Account</label>
    <nameField>
        <displayFormat>Terr-{0000000}</displayFormat>
        <label>Territory Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Account__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory Number</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Accounts</relationshipLabel>
    <relationshipName>Territory_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Parent_Territory__c.field-meta.xml
<CustomField>
    <fullName>Parent_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Master</relationshipLabel>
    <relationshipName>Territory_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Region_Name__c.field-meta.xml
<CustomField>
    <fullName>Region_Name__c</fullName>
    <label>Region Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Region_Number__c.field-meta.xml
<CustomField>
    <fullName>Region_Number__c</fullName>
    <label>Region Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <label>Territory Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/Territory_User__c.object-meta.xml
<CustomObject>
    <label>Territory User</label>
    <nameField>
        <displayFormat>TU-{0000000}</displayFormat>
        <label>Territory User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Users</relationshipLabel>
    <relationshipName>Territory_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/territory_User_ShowAccounts.cls
public class territory_User_ShowAccounts {
    public String uid {get; set;}
    public String userName { 
        get { 
            String user_name = '';
            if(ApexPages.currentPage().getParameters().get('id') != NULL){
                user_name = [Select name FROM user WHERE id = :ApexPages.currentPage().getParameters().get('id') LIMIT 1].Name; 
            }
            return user_name; 
        } 
        set; }
    
    public String getuserName2(){ 
        
        String user_name = '';
        if(ApexPages.currentPage().getParameters().get('id') != NULL){
            user_name = [Select name FROM user WHERE id = :ApexPages.currentPage().getParameters().get('id') LIMIT 1].Name; 
        }
        
        return user_name;
    }
        
    
    public list<Territory_Account__c> getAccounts(){
        uid = ApexPages.currentPage().getParameters().get('id');
        list<String> terlist = new list<String>();
        
        for(Territory_User__c t : [SELECT Territory_Master__r.Territory_Number__c FROM Territory_User__c WHERE User__c = :uid]){
            terlist.add(t.Territory_Master__r.Territory_Number__c);
        }
        
        list<Territory_Account__c> taList = new list<Territory_Account__c>([SELECT Name, Account__r.Billing_Address_Full__c, Account__r.SAP_Sold_To__c, Account__r.name, Territory_Master__r.Region_Name__c, Territory_Master__r.Region_Number__c, Territory_Master__r.Territory_Name__c, Territory_Master__c, Territory_Master__r.Business_Unit__c, Territory_Master__r.Name FROM Territory_Account__c WHERE Territory_Master__r.name IN :terlist ORDER by Account__r.name]);
        
        return talist;
    }
    
}