fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Business_Unit1__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit1__c</fullName>
    <description>Choose the Business Unit that this contact belongs to</description>
    <inlineHelpText>Choose the Business Unit that this contact belongs to</inlineHelpText>
    <label>Business Unit</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Clinical Affairs</fullName>
            </value>
            <value>
                <fullName>Commercial Operations</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>LMA</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Position_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Job_Title__c</fullName>
    <label>Position/Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abdominal Transplant Surgeon</fullName>
            </value>
            <value>
                <fullName>Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>ALS Provider</fullName>
            </value>
            <value>
                <fullName>Anesthesia Director</fullName>
            </value>
            <value>
                <fullName>Anesthesia Tech</fullName>
            </value>
            <value>
                <fullName>Anesthesiologist</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Asst Chief</fullName>
            </value>
            <value>
                <fullName>Bariatric Surgeon</fullName>
            </value>
            <value>
                <fullName>Bio Med</fullName>
            </value>
            <value>
                <fullName>BLS Provider</fullName>
            </value>
            <value>
                <fullName>Buyer/Purchasing Staff</fullName>
            </value>
            <value>
                <fullName>Captain</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Director</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Manager</fullName>
            </value>
            <value>
                <fullName>Category Manager</fullName>
            </value>
            <value>
                <fullName>CCL Manager</fullName>
            </value>
            <value>
                <fullName>CCL Scheduler</fullName>
            </value>
            <value>
                <fullName>Central Supply</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Chief Nursing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of CV</fullName>
            </value>
            <value>
                <fullName>Chief of General Surgery</fullName>
            </value>
            <value>
                <fullName>Chief of GYN</fullName>
            </value>
            <value>
                <fullName>CLABSI Team</fullName>
            </value>
            <value>
                <fullName>Clinical Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/classes/otherContacts.cls
public with sharing class otherContacts {
        
        private Account acct;

    public otherContacts(ApexPages.StandardController stdController) {
        this.acct = (Account)stdController.getRecord();
    }
    
    user u = [SELECT Business_Unit__c FROM User WHERE Id=:userinfo.getuserid()];
    string bu = u.business_unit__c;
    
    List<Contact> otherCtcs;

    public List<Contact> getotherCtcs() {
        otherCtcs = [SELECT Id, AccountId, Salutation, Name, Business_Unit1__c, Title, Position_Job_Title__c, email, phone FROM Contact WHERE AccountId=:acct.id AND Contact.Business_Unit1__c EXCLUDES (:bu) ORDER BY Name ASC NULLS LAST];
        return otherCtcs;
    
    }

}