fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Specialty Markets</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Surgical Percuvance</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/Top_10_Selling_Products__c.object-meta.xml
<CustomObject>
    <description>This object displays the top 10 Selling Products for the Account. The data is received from QAD and is displayed as a read only.</description>
    <label>Top 10 Selling Products</label>
    <nameField>
        <displayFormat>Top Ten -{0000000000}</displayFormat>
        <label>Top 10 Selling Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Top 10 Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Top 10 Selling Products</relationshipLabel>
    <relationshipName>Top_10_Selling_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/fields/Growth_pct__c.field-meta.xml
<CustomField>
    <fullName>Growth_pct__c</fullName>
    <formula>if(Sales_Prior_Year__c = 0, 1, Growth__c / Sales_Prior_Year__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Growth %</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/fields/Item_number__c.field-meta.xml
<CustomField>
    <fullName>Item_number__c</fullName>
    <description>Item Number</description>
    <label>Item #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <description>Product  Description</description>
    <label>Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/fields/Sales_Prior_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Prior_Year__c</fullName>
    <description>Sales Prior Fiscal Year</description>
    <label>Sales Prior Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Top_10_Selling_Products__c/fields/Sales_YTD__c.field-meta.xml
<CustomField>
    <fullName>Sales_YTD__c</fullName>
    <description>Sales Year To Date (YTD)</description>
    <label>Sales YTD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/topTenBU.cls
public with sharing class topTenBU {

    private Account acct;
    
    
    
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard
    // controller.
    public topTenBU(ApexPages.StandardController stdController) {
        this.acct = (Account)stdController.getRecord();
    }
    
    user u = [SELECT Business_Unit__c FROM User WHERE Id=:userinfo.getuserid()];
    string bu = u.business_unit__c;
    string newBu;
    List<Top_10_Selling_Products__c> myT10BU;

    public List<Top_10_Selling_Products__c> getmyT10BU() {
        if(bu == 'Cross BU'){
                return null;
            //myT10BU = [SELECT Item_Number__c, Product_Description__c, Business_Unit__c, Sales_YTD__c, Sales_Prior_Year__c FROM Top_10_Selling_Products__c WHERE Account__c=:acct.id ORDER BY Sales_YTD__c DESC NULLS LAST];
        }else{
            if(bu.contains('Surgical')){
                newBu = bu.substringBefore(' ');
                myT10BU = [SELECT Item_Number__c, Product_Description__c, Business_Unit__c, Sales_YTD__c, Sales_Prior_Year__c, Growth_pct__c FROM Top_10_Selling_Products__c WHERE Account__c=:acct.id AND Business_Unit__c=:newBu ORDER BY Sales_YTD__c DESC NULLS LAST];
            }
            else if(bu.contains('Alternate')){
                newBu = 'Specialty';
                myT10BU = [SELECT Item_Number__c, Product_Description__c, Business_Unit__c, Sales_YTD__c, Sales_Prior_Year__c, Growth_pct__c FROM Top_10_Selling_Products__c WHERE Account__c=:acct.id AND Business_Unit__c=:newBu ORDER BY Sales_YTD__c DESC NULLS LAST];
            }
            else{
                myT10BU = [SELECT Item_Number__c, Product_Description__c, Business_Unit__c, Sales_YTD__c, Sales_Prior_Year__c, Growth_pct__c FROM Top_10_Selling_Products__c WHERE Account__c=:acct.id AND Business_Unit__c=:bu ORDER BY Sales_YTD__c DESC NULLS LAST];
            }
            
        }
               
        return myT10BU;
    
    }
    
    public String getmyBU() {
        return bu;
    }

    public static testMethod void topTenBUTest() {

        // create a new lead...
        Account acct = new Account(Name='Test Account ');
        // ...set additional fields...
        insert acct;
    
        //Create a reference to the VF page
        PageReference pageRef = Page.accountsRedirect;
        Test.setCurrentPageReference(pageRef);
        // if you wanted to test an existing lead, use the line below (assuming your extension expects the ID param to be set)
        ApexPages.currentPage().getParameters().put('id', acct.Id);
    
        // create an instance of your extension
        // this assumes a new Lead...
        //accountRedirect extension = new accountRedirect(new ApexPages.StandardController(new Lead()));
        // if you wanted to test an existing lead, use the line below...
        accountRedirect extension = new accountRedirect(new ApexPages.StandardController(acct));
        topTenBU extension1 = new topTenBU(new ApexPages.StandardController(acct));
        extension1.getmyT10BU();
        extension.redirect();
    
        // ... start calling methods to exercise your code ...
        
        // tear down objects created in the test
        delete acct;
    }

}