fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10CR - HO Corporate Retail</fullName>
            </value>
            <value>
                <fullName>10HO - HO Hardware</fullName>
            </value>
            <value>
                <fullName>10IR - HO Independent Retail</fullName>
            </value>
            <value>
                <fullName>10SI - HO Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>12CR - NSW Corporate Retail</fullName>
            </value>
            <value>
                <fullName>12IR - NSW Independent Retail</fullName>
            </value>
            <value>
                <fullName>12SI - NSW Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>13CR - VIC Corporate Retail</fullName>
            </value>
            <value>
                <fullName>13IR - VIC Independent Retail</fullName>
            </value>
            <value>
                <fullName>13SI - VIC Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>14CR - QLD Corporate Retail</fullName>
            </value>
            <value>
                <fullName>14IR - QLD Independent Retail</fullName>
            </value>
            <value>
                <fullName>14SI - QLD Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>15CR - SA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>15IR - SA Independent Retail</fullName>
            </value>
            <value>
                <fullName>15SI - SA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>16CR - WA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>16IR - WA Independent Retail</fullName>
            </value>
            <value>
                <fullName>16SI - WA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>18CR - Int/Emer Corporate Retail</fullName>
            </value>
            <value>
                <fullName>18IR - Int/Emer Independent Retail</fullName>
            </value>
            <value>
                <fullName>18SI - Int/Emer Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>31IN - Fishers Industrial</fullName>
            </value>
            <value>
                <fullName>31RS - Fishers Reseller</fullName>
            </value>
            <value>
                <fullName>4201 - ACT</fullName>
            </value>
            <value>
                <fullName>4202 - South Eastern Sydney</fullName>
            </value>
            <value>
                <fullName>4203 - Southern NSW</fullName>
            </value>
            <value>
                <fullName>4204 - South Western Sydney</fullName>
            </value>
            <value>
                <fullName>4205 - Western NSW</fullName>
            </value>
            <value>
                <fullName>4206 - Western Syd LHN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/Invoiced_Sales_Detail__c.object-meta.xml
<CustomObject>
    <label>Invoiced Sales Detail</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Invoiced Sales Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales Details</relationshipLabel>
    <relationshipName>Invoiced_Sales_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Commissionable_Date__c.field-meta.xml
<CustomField>
    <fullName>Commissionable_Date__c</fullName>
    <label>Commissionable Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Fiscal_Period__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Period__c</fullName>
    <label>Fiscal Period</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Line_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Number__c</fullName>
    <label>Line Item Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoiced Sales Details</relationshipLabel>
    <relationshipName>Invoiced_Sales_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Invoiced Sales Details</relationshipLabel>
    <relationshipName>Invoiced_Sales_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/Open_Orders__c.object-meta.xml
<CustomObject>
    <label>Open Orders</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Open Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Open Orders</relationshipLabel>
    <relationshipName>Open_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Line_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Number__c</fullName>
    <label>Line Item Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <inlineHelpText>This is Net Value!</inlineHelpText>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Open Orders</relationshipLabel>
    <relationshipName>Open_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Open Orders</relationshipLabel>
    <relationshipName>Open_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <inlineHelpText>Last 12 Months of Sales</inlineHelpText>
    <label>Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used to concatenate the Territory Number with the Primary Territory User Full Name.</inlineHelpText>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Recent_Sales_Orders.cls
public class Recent_Sales_Orders {
    
    public list<Invoiced_Sales_Detail__c> roList {get; set;}
    public set<String> tSet {get; set;}
    public Account acct {get; set;}
    public Territory_Master__c tmaster {get; set;}
    public map<Id, Decimal> ooMap {get; set;}
    
    public Id tid {get; set;}
    public Id aid {get; set;}
    public string tnumber {get; set;}
    public String pname {get; set;}
    public boolean openOrders {get; set;}

    public Recent_Sales_Orders(){
        roList = new list<Invoiced_Sales_Detail__c>();
        tmaster = new Territory_Master__c();
        
        tid = ApexPages.currentPage().getParameters().get('id');
        tnumber = [SELECT Territory_Number__c FROM Territory_Master__c where Id =:tid].Territory_Number__c;
        tmaster = [SELECT Business_Unit__c FROM Territory_Master__c where Id =:tid];
        tSet = new set<String>();
        acct = new Account();
        ooMap = new map<Id, Decimal>();

        boolean comp = FALSE;
        string query;
        
        if(tid != NULL){

            if(ApexPages.currentPage().getParameters().get('aid') != NULL){
                aid = ApexPages.currentPage().getParameters().get('aid');

                acct = [SELECT Name, SAP_Code__c FROM Account WHERE Id =:aid];
                
                decimal count;
                string account;
                
                for(AggregateResult ar : [SELECT sum(Order_Total__c) cnt, Account__c acct 
                                          FROM Open_Orders__c 
                                          WHERE Account__c =:aid
                                          GROUP BY Account__c])
                {
                    count = (decimal) ar.get('cnt');
                    account = (string) ar.get('acct');
                    ooMap.put(account, count);
                    openOrders = TRUE;
                }
                
                query = 'SELECT Id, Account__r.SAP_Code__c, Account__r.Name, Account__c, Business_Unit__c, Date__c, Fiscal_Period_Date__c, ';
                query += 'Line_Item_Number__c, Commissionable_Date__c, Fiscal_Period__c, Order_Date__c, ';
                query += 'Order_Number__c, PO_Number__c, Product__c, Product__r.Name, Product__r.Description, Quantity__c, Sales__c, SAP_Code__c, ';
                query += 'Territory__c, Territory_Number__c ';
                query += 'FROM Invoiced_Sales_Detail__c ';
                query += 'WHERE Territory__c =:tid ';
                query += 'AND Account__c =:aid ';
                if(comp){
                    query += 'AND Compensatory__c = TRUE ';
                     
                }
                else{
                    query += 'AND Compensatory__c = FALSE ';
                }
                query += 'ORDER BY Commissionable_Date__c desc';
                system.debug('query: ' + query);
                roList = database.query(query);
                
                for(Invoiced_Sales_Detail__c  ro : roList)
                {
                    tSet.add(ro.Territory_Number__c);
                }  
            }
            else{
                for(Invoiced_Sales_Detail__c  ro : [SELECT Id, Account__r.SAP_Code__c, Account__r.Name, Account__c, Business_Unit__c, Date__c, Fiscal_Period_Date__c, 
                                                    Line_Item_Number__c, Commissionable_Date__c, Fiscal_Period__c, Order_Date__c, 
                                                    Order_Number__c, PO_Number__c, Product__c, Product__r.Name, Product__r.Description, Quantity__c, Sales__c, SAP_Code__c, 
                                                    Territory__c, Territory_Number__c 
                                                    FROM Invoiced_Sales_Detail__c 
                                                    WHERE Territory__c =:tid
                                                    ORDER BY Commissionable_Date__c desc
                                                    LIMIT 10000])
                {
                    roList.add(ro);
                    tSet.add(ro.Territory_Number__c);
                }  
            }
        }
        if(tnumber != NULL){
            pname = 'Recent-Orders-' + tnumber;
        }
        else{
            pname = 'Recent-Orders';
        }
    }
}