fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Currency__c.field-meta.xml
<CustomField>
    <fullName>Active_Currency__c</fullName>
    <label>Active Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <inlineHelpText>This only drives material visibility</inlineHelpText>
    <label>Active Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT - Austria</fullName>
            </value>
            <value>
                <fullName>AU - Australia</fullName>
            </value>
            <value>
                <fullName>BE - Belgium</fullName>
            </value>
            <value>
                <fullName>BR - Brazil</fullName>
            </value>
            <value>
                <fullName>CA - Canada</fullName>
            </value>
            <value>
                <fullName>CL - Chile</fullName>
            </value>
            <value>
                <fullName>CO - Colombia</fullName>
            </value>
            <value>
                <fullName>CZ - Czech</fullName>
            </value>
            <value>
                <fullName>DE - Germany</fullName>
            </value>
            <value>
                <fullName>ES - Spain</fullName>
            </value>
            <value>
                <fullName>IE - Ireland</fullName>
            </value>
            <value>
                <fullName>LA - Latin America</fullName>
            </value>
            <value>
                <fullName>MX - Mexico</fullName>
            </value>
            <value>
                <fullName>NL - Netherlands</fullName>
            </value>
            <value>
                <fullName>NZ - New Zealand</fullName>
            </value>
            <value>
                <fullName>PL - Poland</fullName>
            </value>
            <value>
                <fullName>PT - Portugal</fullName>
            </value>
            <value>
                <fullName>SK - Slovakia</fullName>
            </value>
            <value>
                <fullName>UK - United Kingdom</fullName>
            </value>
            <value>
                <fullName>US - Teleflex</fullName>
                <default>true</default>
                <label>US - Teleflex</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org_Key__c</fullName>
    <label>Active Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(User__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Pricing_Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Portal_Access__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Pricing Portal Access</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/US_Material__c.field-meta.xml
<CustomField>
    <fullName>US_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>US Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_creatQuoteContact_Test.cls
@isTest
private class PP_creatQuoteContact_Test {
    
    static testMethod void PP_creatQuoteContact_UnitTest() {

        String roleId = [SELECT Id, Name FROM UserRole WHERE Name LIKE '%EMEA%' LIMIT 1].Id;
        Profile p = [select id from profile where name='System Administrator'];
        
        User u = new User(
            alias = 'uflex76',
            email='unit.test@unit.teleflex.com',
            emailencodingkey='UTF-8',
            firstname='Adam',
            lastname='Franks',
            languagelocalekey='en_US',
            localesidkey='en_GB',
            profileid = p.Id,
            Business_Unit__c='EMEA',
            timezonesidkey='Europe/London',
            username='unit.test@unit.teleflex.com',
            UserRoleId = roleId
        );
        insert u;
     
        System.runAs(u){

            Contract_User__c cu = new Contract_User__c(
                Name = 'Adam Franks',
                User__c = u.id,
                Active_Region__c = 'US - Teleflex/Arrow',
                US_Material__c = TRUE,
                Pricing_Portal_Access__c = TRUE,
                Active_Sales_Org_Key__c = 'AU1010',
                Active_Currency__c = 'USD'
            );
            insert cu;

            Account accObj = TestDataFactory.createAccount('Test Account');
            Contact conObj = TestDataFactory.createContact('Test Contact', accObj.id);

            Test.startTest();
            PP_creatQuoteContact.creatQuoteContact(conObj.Id);
            PP_creatQuoteContact.creatQuoteContactLightning(conObj.Id);
            Test.stopTest();
            
        }
    }
}