fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/Invoiced_Sales__c.object-meta.xml
<CustomObject>
    <description>Invoiced Sales is the official name that SAP sales that have are shipped and counted towards compensation.</description>
    <label>Invoiced Sales</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Invoiced Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Commissionable Date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/Pain_Profile__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about Accounts from the Pain Management Team AEM.</description>
    <label>Pain Profile</label>
    <nameField>
        <displayFormat>Pain-{00000}</displayFormat>
        <label>Pain Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pain Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pain Profiles</relationshipLabel>
    <relationshipName>Pain_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Last_Year_Sales_LMA__c.field-meta.xml
<CustomField>
    <fullName>Last_Year_Sales_LMA__c</fullName>
    <description>Previous Year Sales from January 1st to toadys date.</description>
    <inlineHelpText>Previous Year Sales from January 1st to toadys date.</inlineHelpText>
    <label>Last Year Sales LMA Pumps</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Last_Year_Sales_Regional_Anes__c.field-meta.xml
<CustomField>
    <fullName>Last_Year_Sales_Regional_Anes__c</fullName>
    <description>Previous Year Sales from January 1st to toadys date.</description>
    <inlineHelpText>Previous Year Sales from January 1st to toadys date.</inlineHelpText>
    <label>Last Year Sales Regional Anes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Rolling_12_Month_Sales_LMA__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Month_Sales_LMA__c</fullName>
    <inlineHelpText>Current 12 months rolling sales from todays date.</inlineHelpText>
    <label>Rolling 12 Month Sales ($) LMA Pumps</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Rolling_12_Month_Sales_Regional_Anes__c.field-meta.xml
<CustomField>
    <fullName>Rolling_12_Month_Sales_Regional_Anes__c</fullName>
    <description>Current 12 months rolling sales from todays date.</description>
    <inlineHelpText>Current 12 months rolling sales from todays date.</inlineHelpText>
    <label>Rolling 12 Month Sales ($) Regional Anes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/YTD_Sales_LMA__c.field-meta.xml
<CustomField>
    <fullName>YTD_Sales_LMA__c</fullName>
    <inlineHelpText>Current sales from January 1st to todays date</inlineHelpText>
    <label>YTD Sales LMA Pumps</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/YTD_Sales_Regional_Anes__c.field-meta.xml
<CustomField>
    <fullName>YTD_Sales_Regional_Anes__c</fullName>
    <description>Current sales from January 1st to todays date</description>
    <inlineHelpText>Current sales from January 1st to todays date</inlineHelpText>
    <label>YTD Sales Regional Anes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PainProfileSalesHandler.cls
/*********************************************************************
* Description      : Controller Class for Pain Invoiced Sales Rolling 12 months,Prior YTD,YTD calculations and populated Pain object fields.
* Test Class       : 
* VisualForce      : N/A
* Author(s)        : Siva Machinieni - siva.machineni@teleflex.com
//Siva for Painprofile sales

**********************************************************************/
public class PainProfileSalesHandler { 
  
    /*
* this method is invoked from Master_Pain_Trigger to calculate rolling 12 months,YTD,Last Year sales for different Group__c types. 
*/
    public static void rollingInvSalesFrmPainTgr(List<Pain_Profile__c> painObjLst) {
        
        //initializations...
        List<ID> accIds = new List<ID>();
        Map<id,Pain_Profile__c> PainMap = new Map<id,Pain_Profile__c>();
        
        //this loop executes the input values from trigger - Trigger.New
        for(Pain_Profile__c painObj: painObjLst){
            //init all calculating fields to zero and then add to list.
            //this initialization helps when we PAIN account changes from one to other in that case it won't retain previous account values.
            if(painObj.Account__c != null) {
                painObj.Rolling_12_Month_Sales_LMA__c = 0;
                painObj.Rolling_12_Month_Sales_Regional_Anes__c	 = 0;
                painobj.Last_Year_Sales_LMA__c=0;
                painobj.Last_Year_Sales_Regional_Anes__c=0;
                painobj.YTD_Sales_LMA__c=0;
                painobj.YTD_Sales_Regional_Anes__c=0;
                accIds.add(painObj.Account__c);
                painMap.put(painObj.Account__c, painObj);
            }
        }
        
        for(AggregateResult arLMApain : [select Account__c, SUM(Sales__c) SumOfSales from Invoiced_Sales__c	
                                         WHERE (Date__c = Last_N_Months : 11 or Date__c = THIS_MONTH)
                                         AND Business_Unit__c = 'Anesthesia'
                                         AND Group__c = 'LMA Pain Management'
                                         AND Compensation_Profile__c!='Anesthesia Canada'
                                         AND Account__c in : accIds group by Account__c])
        {
            
            if(painMap.containsKey((String)arLMApain.get('Account__c'))) {
                Pain_Profile__c modpainObj = painMap.get((String)arLMApain.get('Account__c'));
                modpainObj.Rolling_12_Month_Sales_LMA__c = (decimal)arLMApain.get('SumOfSales');  
            }
        }
        
        for(AggregateResult arLMApain : [select Account__c, SUM(Sales__c) SumOfSales from Invoiced_Sales__c	
                                         WHERE (Date__c = THIS_YEAR)
                                         AND Business_Unit__c = 'Anesthesia'
                                         AND Group__c = 'LMA Pain Management'
                                         AND Compensation_Profile__c!='Anesthesia Canada'
                                         AND Account__c in : accIds group by Account__c])
        {
            
            if(painMap.containsKey((String)arLMApain.get('Account__c'))) {
                Pain_Profile__c modpainObj = painMap.get((String)arLMApain.get('Account__c'));
                modpainObj.YTD_Sales_LMA__c = (decimal)arLMApain.get('SumOfSales');  
            }
        }
        
        for(AggregateResult arLMApain : [select Account__c, SUM(Sales__c) SumOfSales from Invoiced_Sales__c	
                                         WHERE (Date__c = Last_YEAR)
                                         AND Business_Unit__c = 'Anesthesia'
                                         AND Group__c = 'LMA Pain Management'
                                         AND Compensation_Profile__c!='Anesthesia Canada'
                                         AND Account__c in : accIds group by Account__c])
        {
            
            if(painMap.containsKey((String)arLMApain.get('Account__c'))) {
                Pain_Profile__c modpainObj = painMap.get((String)arLMApain.get('Account__c'));
                modpainObj.Last_Year_Sales_LMA__c = (decimal)arLMApain.get('SumOfSales');  
            }
        }
        
        for(AggregateResult arRegAnes : [select Account__c, SUM(Sales__c) SumOfSales from Invoiced_Sales__c	
                                         WHERE (Date__c = Last_N_Months : 11 or Date__c = THIS_MONTH)
                                         AND Business_Unit__c = 'Anesthesia'
                                         AND Group__c = 'Regional Anesthesia'
                                         AND Compensation_Profile__c!='Anesthesia Canada'
                                         AND Account__c in : accIds group by Account__c])
        {
            
            if(painMap.containsKey((String)arRegAnes.get('Account__c'))) {
                Pain_Profile__c modpainObj = painMap.get((String)arRegAnes.get('Account__c'));
                modpainObj.Rolling_12_Month_Sales_Regional_Anes__c = (decimal)arRegAnes.get('SumOfSales');  
            }
        }
        
        for(AggregateResult arRegAnes : [select Account__c, SUM(Sales__c) SumOfSales from Invoiced_Sales__c	
                                         WHERE (Date__c = THIS_YEAR)
                                         AND Business_Unit__c = 'Anesthesia'
                                         AND Group__c = 'Regional Anesthesia'
                                         AND Compensation_Profile__c!='Anesthesia Canada'
                                         AND Account__c in : accIds group by Account__c])
        {
            
            if(painMap.containsKey((String)arRegAnes.get('Account__c'))) {
                Pain_Profile__c modpainObj = painMap.get((String)arRegAnes.get('Account__c'));
                modpainObj.YTD_Sales_Regional_Anes__c = (decimal)arRegAnes.get('SumOfSales');  
            }
        }
        
        for(AggregateResult arRegAnes : [select Account__c, SUM(Sales__c) SumOfSales from Invoiced_Sales__c	
                                         WHERE (Date__c = LAST_YEAR)
                                         AND Business_Unit__c = 'Anesthesia'
                                         AND Group__c = 'Regional Anesthesia'
                                         AND Compensation_Profile__c!='Anesthesia Canada' 
                                         AND Account__c in : accIds group by Account__c])
        {
            
            if(painMap.containsKey((String)arRegAnes.get('Account__c'))) {
                Pain_Profile__c modpainObj = painMap.get((String)arRegAnes.get('Account__c'));
                modpainObj.Last_Year_Sales_Regional_Anes__c = (decimal)arRegAnes.get('SumOfSales');  
            }
        }
        
        
        
        
    }
}