fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Existing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Diagnostics</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Specialty Markets</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Surgical Percuvance</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <label>SAP Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead/fields/Zip_Code_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code_Business_Unit__c</fullName>
    <formula>IF(!ISBLANK(TEXT(Business_Unit__c)), TEXT(Business_Unit__c),
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Hos&quot;, &quot;Vascular&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;EMS&quot;, &quot;EMS&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Int&quot;, &quot;IA&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Ane&quot;, &quot;Anesthesia&quot;,
IF(LEFT(Zip_Code_Formstack_Affiliation__c, 3) = &quot;Sur&quot;, &quot;Surgical&quot;,
&quot;&quot;
))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip Code Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/lead_SAP_Helper.cls
public class lead_SAP_Helper {
    public static void insertSAP(list<Lead> newtrigger,map<id,lead> oldtrigger,string trigType){
        if(master_TriggerHelperClass.qd('insertSAP')){
            
            // This class takes the SAP Customer number and looks up the related account and updates
            // the Name and Address fields. Works on insert and update and does not error if the SAP
            // code is not valid. - ESC
            set<string> setsap = new set<string>();
            string sapCompare;
            for(lead l : newtrigger){
                if(trigType == 'update'){
                    sapCompare = oldtrigger.get(l.Id).SAP_Code__c;                     
                }

                if(l.SAP_Code__c != sapCompare && l.SAP_Code__c != NULL){
                    setsap.add(l.SAP_Code__c);
                }
                
                // Update the BU if Empty and Formstack BU is valid
                if(l.Zip_Code_Business_Unit__c != NULL && l.Business_Unit__c == NULL){
                    l.Business_Unit__c = l.Zip_Code_Business_Unit__c;
                }
            }
            
            if(setsap.size() > 0){
                map<String, Account> sapmap = new map<String, Account>();
                for(Account a : [SELECT Id, Name, SAP_Sold_To__c, BillingStreet, 
                                 BillingCity, BillingState, BillingPostalCode 
                                 FROM Account 
                                 WHERE SAP_Sold_To__c = :setsap])
                {
                    sapmap.put(a.SAP_Sold_To__c, a);
                }
                
                for(lead l : newtrigger){
                    if(l.SAP_Code__c != NULL && sapmap.get(l.SAP_Code__c) != NULL){
                        l.Company = sapmap.get(l.SAP_Code__c).Name;
                        l.Street = sapmap.get(l.SAP_Code__c).BillingStreet;
                        l.City = sapmap.get(l.SAP_Code__c).BillingCity;
                        l.State = sapmap.get(l.SAP_Code__c).BillingState;
                        l.PostalCode = sapmap.get(l.SAP_Code__c).BillingPostalCode;
                        l.Account__c = sapmap.get(l.SAP_Code__c).Id;
                    } 
                } 
            } // End If
            
        } // End qd
        
    }
}