fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>2 Digit Customer Group Number.</inlineHelpText>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>Territory_Key__c</fullName>
    <description>Territory_Key__c is built every day as part of the daily Invoiced Sales ETL. 
Apex: account_Active_Sales
Scheduled Apex: Invoiced_Sales_Maintenance_Scheduler</description>
    <inlineHelpText>List of Territory Numbers that have Sales related to this Account.</inlineHelpText>
    <label>Territory Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Zip3__c.field-meta.xml
<CustomField>
    <fullName>Zip3__c</fullName>
    <formula>LEFT(BillingPostalCode,3)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Zip3</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Alignment__c/Territory_Alignment__c.object-meta.xml
<CustomObject>
    <label>Territory Alignment Rules</label>
    <nameField>
        <label>ZPSA Rule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Alignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Alignment__c/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Alignment__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Master</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Alignment Rules</relationshipLabel>
    <relationshipName>Territory_Alignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Alignment__c/fields/Zip3__c.field-meta.xml
<CustomField>
    <fullName>Zip3__c</fullName>
    <label>Zip3</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <label>Territory Account Assignments</label>
    <nameField>
        <label>Territory Assignments</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Account Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Territory__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Territory_Alignment__c</fullName>
    <label>Territory Alignment Rules</label>
    <referenceTo>Territory_Alignment__c</referenceTo>
    <relationshipLabel>Territory Account Assignments</relationshipLabel>
    <relationshipName>Territory_Assignment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ASR</fullName>
            </value>
            <value>
                <fullName>Clinical Manager</fullName>
                <label>Clinical  Education Manager</label>
            </value>
            <value>
                <fullName>Clinical Specialists</fullName>
            </value>
            <value>
                <fullName>Corporate Sales</fullName>
            </value>
            <value>
                <fullName>DNA</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>KAM</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>MDM</fullName>
            </value>
            <value>
                <fullName>Sales Director</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
                <default>true</default>
                <label>Sales Rep</label>
            </value>
            <value>
                <fullName>Sales VP</fullName>
            </value>
            <value>
                <fullName>Service Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Sales_Rep_Email__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Email__c</fullName>
    <inlineHelpText>This is what looks up and populates the Sales Rep lookup field.</inlineHelpText>
    <label>Sales Rep Email</label>
    <type>Email</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/Territory_User__c.object-meta.xml
<CustomObject>
    <label>Territory User</label>
    <nameField>
        <displayFormat>TU-{0000000}</displayFormat>
        <label>Territory User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Rep</fullName>
                <default>true</default>
                <label>Sales Rep</label>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Sales Director</fullName>
            </value>
            <value>
                <fullName>Sales VP</fullName>
            </value>
            <value>
                <fullName>Service Rep</fullName>
            </value>
            <value>
                <fullName>Clinical Specialists</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Users</relationshipLabel>
    <relationshipName>Territory_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/CXSalesRepAccountsQueue_Test.cls
@isTest
public class CXSalesRepAccountsQueue_Test {
    static testmethod void test1() {
        

         set<Id> accIds = new set<Id>();
         List<Id> SalesRepIDs = new List<Id>();
         map<Id,Set<Id>> SRvsAccsMap = new map<Id,Set<Id>>();
         map<Id,Set<Id>> SRvsAccsMapFinal = new map<Id,Set<Id>>();
         Boolean hasMoreRecs;
         Boolean StartNewTransaction;
         Id hasMoreRecsLmtID;
         Integer recsCnt = 0;
        
        List<Id> salRepLst = new List<Id>();      
        Profile p = [select id from profile where name='System Administrator'];
        User u = new User(
            alias = 'uflex76',
            email='unit.test@unit.teleflex.com',
            emailencodingkey='UTF-8',
            firstname='Adam',
            lastname='Franks',
            languagelocalekey='en_US',
            localesidkey='en_GB',
            profileid = p.Id,
            timezonesidkey='Europe/London',
            username='unit.test@unit.teleflex.com',
            Business_Unit__c='BU'
        );
        insert u;
        
        Profile p1 = [select id from profile where name='System Administrator'];
        User u1 = new User(
            alias = 'uflex76',
            email='unit.test@unit.teleflex.com',
            emailencodingkey='UTF-8',
            firstname='Adam',
            lastname='Franks',
            languagelocalekey='en_US',
            localesidkey='en_GB',
            profileid = p1.Id,
            timezonesidkey='Europe/London',
            username='test@unit.teleflex.com',
            Business_Unit__c='BU'
        );
        insert u1;
        
        Account acc = new Account();
        acc.Name = 'CXTestAcc';
        acc.SAP_Sold_To__c = '123456';
        acc.SAP_Code__c='123456';
        acc.Territory_Key__c='123456;234567';
        insert acc;
        
        Account acc1 = new Account();
        acc1.Name = 'CXTestAcc1';
        acc1.SAP_Sold_To__c = '234567';
        acc1.SAP_Code__c='234567';
        acc1.Territory_Key__c='123456;234567';
        insert acc1;
        
        
        
        Territory_Master__c tm = new Territory_Master__c(
            Name = '700123',
            Territory_Number__c = '123456',
            Business_Unit__c = 'Surgical Disposables',
            Sales_Rep_Email__c = 'unit.test@unit.teleflex.com'
        );
        insert tm;
        
        Territory_Master__c tm1 = new Territory_Master__c(
            Name = '700123',
            Territory_Number__c = '234567',
            Business_Unit__c = 'Surgical Disposables',
            Sales_Rep_Email__c = 'unit.test@unit.teleflex.com'
        );
        insert tm1;
        
        Territory_User__c tu = new Territory_User__c(
            User__c = u.Id,
            Business_Unit__c = 'Surgical Disposables',
            Role__c = 'Sales Rep',
            Territory_Master__c = tm.Id,
            Territory_Number__c = '123456'
        );
        insert tu;
        
        Territory_User__c tu1 = new Territory_User__c(
            User__c = u1.Id,
            Business_Unit__c = 'Surgical Disposables',
            Role__c = 'Sales Rep',
            Territory_Master__c = tm1.Id,
            Territory_Number__c = '234567'
        );
        insert tu1;
        
        Territory_Alignment__c tarbc = new Territory_Alignment__c(
            Key__c = '276-02-700123',
            Zip3__c = '276',
            Customer_Group__c = '02',
            Customer_Group_Name__c = 'Dist/Dlr Emg Med Svc',
            Territory__c = '700123',
            Territory_Name__c = '700123',
            Territory2__c = '700123',
            Territory_2_Name__c = '700123',
            Territory3__c = '',
            Territory_3_Name__c = '',
            Territory4__c = '',
            Territory_4_Name__c = '',
            Business_Unit__c = 'Surgical Disposables',
            ZPSA_Table__c = 'A672'
        );
        insert tarbc;
        
        Territory_Alignment__c tarbc1 = new Territory_Alignment__c(
            Key__c = '276-02-70000',
            Zip3__c = '222',
            Customer_Group__c = '22',
            Customer_Group_Name__c = 'Dist/Dlr Emg Med Svc1',
            Territory__c = '70000',
            Territory_Name__c = '70000',
            Territory2__c = '70000',
            Territory_2_Name__c = '70000',
            Territory3__c = '',
            Territory_3_Name__c = '',
            Territory4__c = '',
            Territory_4_Name__c = '',
            Business_Unit__c = 'Surgical Disposables',
            ZPSA_Table__c = 'A671'
        );
        insert tarbc1;
        
        Territory_Assignment__c terrAssignment = new Territory_Assignment__c (
            Name = 'NC-700123',
            Account__c = acc.id,
            Territory_Alignment__c = tarbc.id,
            Territory__c = tm.Id,
            Territory_Number__c = '123456'
        );
        
        insert terrAssignment; 
        
        Territory_Assignment__c terrAssignment1 = new Territory_Assignment__c (
            Name = 'NC-700123',
            Account__c = acc1.id,
            Territory_Alignment__c = tarbc1.id,
            Territory__c = tm1.Id,
            Territory_Number__c = '234567'
        );
        
        insert terrAssignment1;
        
        
        
        salRepLst.add(u.Id);
        //salRepLst.add(u.Id);
        //salRepLst.add(u1.Id);
        accIds.add(acc.Id);
        accIds.add(acc1.Id);
        SalesRepIDs.add(u1.Id);
        SRvsAccsMap.put(u1.Id, accIds);
        SRvsAccsMapFinal.put(u1.Id, accIds);
        hasMoreRecs = true;
        StartNewTransaction = true;
        hasMoreRecsLmtID = terrAssignment1.Id;
        recsCnt = 60000;
        // startTest/stopTest block to force async processes 
        //   to run in the test.
        Test.startTest();
        
        System.enqueueJob(new CXSalesRepAccountsQueue(salRepLst));
        System.enqueueJob(new CXSalesRepAccountsQueue(accIds, SalesRepIDs, SRvsAccsMap, SRvsAccsMapFinal, hasMoreRecs, StartNewTransaction, hasMoreRecsLmtID, recsCnt));
        System.enqueueJob(new CXSalesRepAccountsQueue(accIds, salRepLst, SRvsAccsMap, SRvsAccsMapFinal, false, StartNewTransaction, hasMoreRecsLmtID, 50000));
        
        Test.stopTest();
    }
}