fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <formula>Sales_Org__c + Distribution_Channel__c</formula>
    <label>Sales Org Key</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Currency__c.field-meta.xml
<CustomField>
    <fullName>Active_Currency__c</fullName>
    <label>Active Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Quote__c</fullName>
    <label>Active Quote</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <inlineHelpText>This only drives material visibility</inlineHelpText>
    <label>Active Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT - Austria</fullName>
            </value>
            <value>
                <fullName>AU - Australia</fullName>
            </value>
            <value>
                <fullName>BE - Belgium</fullName>
            </value>
            <value>
                <fullName>BR - Brazil</fullName>
            </value>
            <value>
                <fullName>CA - Canada</fullName>
            </value>
            <value>
                <fullName>CL - Chile</fullName>
            </value>
            <value>
                <fullName>CO - Colombia</fullName>
            </value>
            <value>
                <fullName>CZ - Czech</fullName>
            </value>
            <value>
                <fullName>DE - Germany</fullName>
            </value>
            <value>
                <fullName>ES - Spain</fullName>
            </value>
            <value>
                <fullName>IE - Ireland</fullName>
            </value>
            <value>
                <fullName>LA - Latin America</fullName>
            </value>
            <value>
                <fullName>MX - Mexico</fullName>
            </value>
            <value>
                <fullName>NL - Netherlands</fullName>
            </value>
            <value>
                <fullName>NZ - New Zealand</fullName>
            </value>
            <value>
                <fullName>PL - Poland</fullName>
            </value>
            <value>
                <fullName>PT - Portugal</fullName>
            </value>
            <value>
                <fullName>SK - Slovakia</fullName>
            </value>
            <value>
                <fullName>UK - United Kingdom</fullName>
            </value>
            <value>
                <fullName>US - Teleflex</fullName>
                <default>true</default>
                <label>US - Teleflex</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org__c</fullName>
    <label>Active Sales Org</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org_Key__c</fullName>
    <label>Active Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/AT_Material__c.field-meta.xml
<CustomField>
    <fullName>AT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Austria sales org access.</description>
    <inlineHelpText>Austria sales org access.</inlineHelpText>
    <label>AT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/AU_Material__c.field-meta.xml
<CustomField>
    <fullName>AU_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AU Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/BE_Material__c.field-meta.xml
<CustomField>
    <fullName>BE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Belgium sales org access.</description>
    <inlineHelpText>Belgium sales org access.</inlineHelpText>
    <label>BE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/BR_Material__c.field-meta.xml
<CustomField>
    <fullName>BR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Brazil</description>
    <inlineHelpText>Brazil</inlineHelpText>
    <label>BR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(User__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Material__c.field-meta.xml
<CustomField>
    <fullName>CA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CH_Material__c.field-meta.xml
<CustomField>
    <fullName>CH_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Switzerland sales org access.</description>
    <inlineHelpText>Switzerland sales org access.</inlineHelpText>
    <label>CH Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Material__c.field-meta.xml
<CustomField>
    <fullName>CL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CO_Material__c.field-meta.xml
<CustomField>
    <fullName>CO_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CO Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Create_Quotes__c.field-meta.xml
<CustomField>
    <fullName>Create_Quotes__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create Quotes</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Currency_Preference__c.field-meta.xml
<CustomField>
    <fullName>Currency_Preference__c</fullName>
    <label>Currency Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CZ_Material__c.field-meta.xml
<CustomField>
    <fullName>CZ_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Czech sales org access.</description>
    <inlineHelpText>Czech sales org access.</inlineHelpText>
    <label>CZ Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/DE_Material__c.field-meta.xml
<CustomField>
    <fullName>DE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Grants access to DE10 Sales Org.</description>
    <inlineHelpText>Grants access to DE10 Sales Org.</inlineHelpText>
    <label>DE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/ES_Material__c.field-meta.xml
<CustomField>
    <fullName>ES_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Spain sales org access.</description>
    <inlineHelpText>Spain sales org access.</inlineHelpText>
    <label>ES Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/FR_Material__c.field-meta.xml
<CustomField>
    <fullName>FR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>France sales org access.</description>
    <inlineHelpText>France sales org access.</inlineHelpText>
    <label>FR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/GR_Material__c.field-meta.xml
<CustomField>
    <fullName>GR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Greece sales org access.</description>
    <inlineHelpText>Greece sales org access.</inlineHelpText>
    <label>GR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/IE_Material__c.field-meta.xml
<CustomField>
    <fullName>IE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ireland sales org access.</description>
    <inlineHelpText>Ireland sales org access.</inlineHelpText>
    <label>IE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/IT_Material__c.field-meta.xml
<CustomField>
    <fullName>IT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Italy sales org access.</description>
    <inlineHelpText>Italy sales org access.</inlineHelpText>
    <label>IT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Material__c.field-meta.xml
<CustomField>
    <fullName>LA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Material__c.field-meta.xml
<CustomField>
    <fullName>MX_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Orgs__c/Sales_Orgs__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in code to dynamically control number of sales orgs and pricing flow.</description>
    <label>Sales Orgs</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Sales_Orgs__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <description>Active Region dropdown list values.</description>
    <inlineHelpText>Active Region dropdown list values.</inlineHelpText>
    <label>Active Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Orgs__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_GPO_Matrix.cls
/*********************************************************************
* Description      : Controller Class for Pricing Portal GPO Matrix.
* Test Class       : PP_GPO_Matrix_Test
* VisualForce      : PP_GPO_Matrix
* Author(s)        : Dun Silver, Eric Clay
**********************************************************************/
public with sharing class PP_GPO_Matrix {

    //cUser holds user's pricing portal access data
    public string salesOrgPrefix;
    Public Boolean emeaUserFlag {get; set;}
    
    public static Contract_User__c cUserTemp;
    static{
        cUserTemp = [SELECT Id,Name,Active_Currency__c,Active_Price_Quote__c,Active_Quote__c,Active_Region__c,Active_Sales_Org_Key__c,
                     Active_Sales_Org__c, AT_Material__c,AU_Material__c,BE_Material__c,BR_Material__c,Business_Unit__c,CA_Material__c,
                     CH_Material__c,CL_Material__c,CO_Material__c,Create_Quotes__c,CurrencyIsoCode,Currency_Preference__c,
                     CZ_Material__c,DE_Material__c,ES_Material__c,FR_Material__c,GR_Material__c, User__r.UserRole.Name,
                     IE_Material__c,IT_Material__c,LA_Material__c,MX_Material__c,NL_Material__c,NZ_Material__c,OwnerId,PL_Material__c,
                     Pricing_Portal_Access__c,Pricing_Tier_Access__c,PT_Material__c,SA_Material__c,SK_Material__c,
                     Stationary_Preference__c,UK_Material__c,Update_Type__c,Users_Email__c,User_Active__c,User_Administration__c,
                     User_ID__c,User__c,US_Material__c,View_Margin__c
                     FROM Contract_User__c
                     WHERE User__c = :UserInfo.getUserId()
                     LIMIT 1];
    }
    
    public Contract_User__c cUser{
        get{
            try{
                return cUserTemp;
            }catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
                return null;
            }
        }
        set;
    }

    //fethces GPO Accounts for EMEA Region
    Public Integer size{get;set;}
    Public Integer noOfRecords{get; set;}
    //Public String rowIndex;
    public List<SelectOption> paginationSizeOptions{get;set;}

    //start of constructor
    public PP_GPO_Matrix(){
        //rowIndex = ApexPages.currentPage().getParameters().get('rowIndex');
        size=10;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));

        salesOrgPrefix = cUser.Active_Sales_Org_Key__c.left(2);
        Sales_Orgs__c  srkey = Sales_Orgs__c.getInstance(cUser.Active_Sales_Org_Key__c);
        emeaUserFlag = false;
        if(srkey?.Region__c !='' && srkey?.Region__c =='EMEA'){
            emeaUserFlag = true;

        }else{
            emeaUserFlag = false;
        }
        
        
    }//end constructor

    //get paginated record list
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {                
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [SELECT Id, Name, Sap_Sold_To__c, Account_Name_2__c
                    FROM Account 
                    WHERE ERP_Active__c = TRUE 
                    AND Sales_Org_Key__c = :cUser.Active_Sales_Org_Key__c
                    AND Sap_Sold_To__c LIKE :(salesOrgPrefix + '%')
                    ORDER BY Name]));
                setCon.setPageSize(size);  
                noOfRecords = setCon.getResultSize();
            }            
            return setCon;
        }
        set;
    }

    //Changes the size of pagination
    public PageReference refreshPageSize() {
        try{
            setCon.setPageSize(size);
            return null;
        }
        catch(Exception e){
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,''+'Error detected: ' + e));
            return null;
        }
    }

    //get paginated records
    public List<Account> getEmeaGpos(){
        return (List<Account>)setCon.getRecords();
    }//end getEmeaGpos

    public boolean oid(){
        boolean oid;
        if(ApexPages.currentPage().getParameters().get('oid') != NULL){
            oid = true;
        }
        else{
            oid = false;
        }
        return oid;
    }
    public String ownerName {
        get {
            String owner_name = '';
            try{
                if(ApexPages.currentPage().getParameters().get('oid') != NULL){
                    owner_name = [Select Owner_Name__c FROM Contract_Header__c WHERE Owner__c = :ApexPages.currentPage().getParameters().get('oid') AND GPO_Contract_Ref__c <> NULL AND Active__c = TRUE LIMIT 1].Owner_Name__c;
                }
                return owner_name;
            }
            catch(Exception e){
                system.debug('Exception: ' + e);
                return NULL;
            }

        }
        set; }

    public String ownerID {
        get {
            string owner_id;
            if(ApexPages.currentPage().getParameters().get('oid') != NULL){
                owner_id = ApexPages.currentPage().getParameters().get('oid');
            }
            return owner_id;
        }
        set; }


    public integer td1 {get; set;}
    public string td2 {get; set;}
    public string td3 {get; set;}
    public string cd {get; set;}
    public map<String, String> htmlMap {get; set;}
    public map<String, String> Tiers;


    public list<Contract_Header__c> getCheckCH(){
        try{
            return [Select Id, Name, Owner_Name__c, Owner__c
                    FROM Contract_Header__c
                    WHERE Owner__c = :ApexPages.currentPage().getParameters().get('oid')
                    AND GPO_Contract_Ref__c <> NULL
                    AND Active__c <> FALSE
                    LIMIT 1];
        }
        catch(Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }


    public List<GPO_PickList__c> getItems() {
        try{
            return [SELECT Key__c, Name, Active__c FROM GPO_PickList__c WHERE Active__c = TRUE AND Sales_Org_Key__c = :salesOrgPrefix ORDER BY Name];

        }
        catch (Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }

    public map<String, String> getTiers(){
        td1 = null;
        td2 = null;

        // Group the Contract Tiers by the GPO reference
        map<String, String> htmlMap = new map<String, String>();
        for(Contract_Header__c c : [Select GPO_Contract_Ref__c, Owner__c, Description__c, Contract_Detail__c, Valid_From__c, Valid_To__c
                                    FROM Contract_Header__c
                                    WHERE Owner__c = :ApexPages.currentPage().getParameters().get('oid')
                                    AND GPO_Contract_Ref__c != NULL
                                    AND Active__c = TRUE
                                    ORDER BY GPO_Contract_Ref__c, Description__c ASC])
        {
            //system.debug('GPO Reference: ' + c.GPO_Contract_Ref__c + ' Description: ' + c.Description__c);
            if(c.Contract_Detail__c == NULL){
                cd = '';
            }
            else {
                cd = c.Contract_Detail__c;
            }

            if(!htmlMap.containsKey(c.GPO_Contract_Ref__c)){
                td1 = 1;
                td2 = '<td class="col-md-3">' + c.Description__c + '</td><td class="col-md-3">' + cd + '</td><td class="col-md-1">' + c.Valid_From__c.format() + '</td><td class="col-md-1">' + c.Valid_To__c.format() + '</td></tr>';
            }
            else {
                ++td1;
                td2 = td2 + '<tr><td>' + c.Description__c + '</td><td>' + cd + '</td><td>' + c.Valid_From__c.format() + '</td><td>' + c.Valid_To__c.format() + '</td></tr>';
            }
            td3 = '<tr><td rowspan=' + td1 + ' class="col-md-1"><h4><a href="/apex/PP_Contract_Detail?oid=' + c.Owner__c+'&gporef=' + c.GPO_Contract_Ref__c + '">' + c.GPO_Contract_Ref__c + '</a></h4></td>' + td2;
            htmlMap.put(c.GPO_Contract_Ref__c, td3);
        }
        try{
            return htmlMap;
        }

        catch(Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }//end getTiers

    //method to redirect page back to current page
    public PageReference backToGpoMatrix(){
        return null;
        //return new Pagereference('/apex/PP_GPO_Matrix?oid=' + ApexPages.currentPage().getParameters().get('oid') ).setRedirect(True);
    }

    //Everything below is for EMEA Pricing Portal Users (GPOs/IDNs)
    public list<Contract_Header__c> getCheckChEmea(){
        try{
            return [Select Id, Name, Owner_Name__c, Owner__c
                    FROM Contract_Header__c
                    WHERE Owner__c = :ApexPages.currentPage().getParameters().get('oid')
                    AND Active__c <> FALSE
                    LIMIT 1];
        }
        catch(Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }
    
    //get tiers EMEA
    public map<String, String> getTiersEmea(){
        td1 = null;
        td2 = null;

        // Group the Contract Tiers by the GPO reference
        map<String, String> htmlMap = new map<String, String>();
        for(Contract_Header__c c : [Select Name, GPO_Contract_Ref__c, Owner__c, Description__c, Contract_Detail__c, Valid_From__c, Valid_To__c
                                    FROM Contract_Header__c
                                    WHERE Owner__c = :ApexPages.currentPage().getParameters().get('oid')
                                    AND Active__c = TRUE
                                    ORDER BY GPO_Contract_Ref__c, Description__c ASC])
        {
            //system.debug('GPO Reference: ' + c.GPO_Contract_Ref__c + ' Description: ' + c.Description__c);
            if(c.Contract_Detail__c == NULL){
                cd = '';
            }
            else {
                cd = c.Contract_Detail__c;
            }

            if(!htmlMap.containsKey(c.Owner__c)){
                td1 = 1;
                td2 = '<td class="col-md-3"><a href="/apex/PP_Agreement_Detail?aid=' + c.Name + '">' + c.Name + ' - ' + c.Description__c + '</a></td><td class="col-md-3">' + cd + '</td><td class="col-md-1">' + c.Valid_From__c.format() + '</td><td class="col-md-1">' + c.Valid_To__c.format() + '</td></tr>';
            }
            else {
                ++td1;
                td2 = td2 + '<tr><td><a href="/apex/PP_Agreement_Detail?aid=' + c.Name + '">' + c.Name + ' - ' + c.Description__c + '</a></td><td>' + cd + '</td><td>' + c.Valid_From__c.format() + '</td><td>' + c.Valid_To__c.format() + '</td></tr>';
            }
            td3 = '<tr><td rowspan=' + td1 + ' class="col-md-1"><h4><a href="/apex/PP_Contract_Detail?oid=' + c.Owner__c+'&gporef=' + '' + '">' + c.Owner__c + '</a></h4></td>' + td2;
            htmlMap.put(c.Owner__c, td3);
        }
        try{
            return htmlMap;
        }

        catch(Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }//end getTiersEmea

}//end of PP_GPO_Matrix Class