fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Account__c/CX_Sales_Rep_Account__c.object-meta.xml
<CustomObject>
    <label>CX Sales Rep Account</label>
    <nameField>
        <displayFormat>SA-{00000}</displayFormat>
        <label>CX Sales Rep Account Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CX Sales Rep Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Account__c/fields/CX_Sales_Rep_Feedback__c.field-meta.xml
<CustomField>
    <fullName>CX_Sales_Rep_Feedback__c</fullName>
    <label>CX Sales Rep Feedback</label>
    <referenceTo>CX_Sales_Rep_Feedback__c</referenceTo>
    <relationshipLabel>CX Sales Rep Accounts</relationshipLabel>
    <relationshipName>CX_Sales_Rep_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Account__c/fields/If_no_then_do_you_know_who__c.field-meta.xml
<CustomField>
    <fullName>If_no_then_do_you_know_who__c</fullName>
    <label>If no, then do you know who?</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Account__c/fields/No__c.field-meta.xml
<CustomField>
    <fullName>No__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Account__c/fields/Sales_Rep_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CX Sales Rep Accounts</relationshipLabel>
    <relationshipName>CX_Sales_Rep_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Account__c/fields/Yes__c.field-meta.xml
<CustomField>
    <fullName>Yes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Yes</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Feedback__c/CX_Sales_Rep_Feedback__c.object-meta.xml
<CustomObject>
    <label>CX Sales Rep Feedback</label>
    <nameField>
        <displayFormat>SF-{00000}</displayFormat>
        <label>CX Sales Rep Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CX Sales Rep Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Feedback__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT( Sales_Rep__r.Business_Unit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Feedback__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CX_Sales_Rep_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/CX_Sales_Rep_Feedback__c/fields/Survey_Key__c.field-meta.xml
<CustomField>
    <fullName>Survey_Key__c</fullName>
    <label>Survey Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/SalesRepAccDetails.cls
/*********************************************************************
* Description      : Controller class to save sales rep customer details form lightning tab /lightning/n/Sales_Rep_Customer_Details.
* Test Class       : CustExpAccRepresentationTool_Test
* VisualForce      : N/A
* Author(s)        : Surya Arvan - surya.arvan@teleflex.com

//initial version work item: W-023175 sprint: 2020.05
**********************************************************************/
public class SalesRepAccDetails {

    @AuraEnabled
    public static List<CX_Sales_Rep_Account__c> saveSalesRepFeedbackDetails(String updSalRepAccLst){
        
        List<CX_Sales_Rep_Account__c> cxSalRepAccLst = new List<CX_Sales_Rep_Account__c>();
        if(!String.isBlank(updSalRepAccLst)){
            List<SalesRepAccWarpper> salesRepAccWarpperObjLst = (List<SalesRepAccWarpper>)JSON.deserialize(updSalRepAccLst, List<SalesRepAccWarpper>.class);
            for(SalesRepAccWarpper salesRepAccWarpperObj : salesRepAccWarpperObjLst){
                CX_Sales_Rep_Account__c cxSalesRepAccountObj = new CX_Sales_Rep_Account__c();
                cxSalesRepAccountObj.Id = salesRepAccWarpperObj.cxsrAccId;
                if(!String.isBlank(String.valueOf(salesRepAccWarpperObj.yesChk)))cxSalesRepAccountObj.Yes__c = salesRepAccWarpperObj.yesChk;
                if(!String.isBlank(String.valueOf(salesRepAccWarpperObj.noChk)))cxSalesRepAccountObj.No__c = salesRepAccWarpperObj.noChk;
                cxSalesRepAccountObj.If_no_then_do_you_know_who__c = salesRepAccWarpperObj.if_no_then_do_you_know_who;
                cxSalRepAccLst.add(cxSalesRepAccountObj);
            } 
            
            update cxSalRepAccLst;
        }
        return cxSalRepAccLst;
    }
    
    @AuraEnabled
    public static List<SalesRepAccWarpper> getSalesRepAccDetailsWithSales(String surveykey){
        
        List<SalesRepAccWarpper> retList = new List<SalesRepAccWarpper>();
        //Kelly Thomas'005E0000000PhToIAK';//Ethan Curry'0052S000009Tuq4QAC'; //John DeVito --'00544000008eXZTAA2';//Jason Supper --'005E0000007XGNfIAO';   //Kristie --'005440000099AIMAA2';
        Id currUsr = UserInfo.getUserId();
        
        List<CX_Sales_Rep_Feedback__c> salesRepFdbckObjLst = [select Id, Sales_Rep__r.Name from CX_Sales_Rep_Feedback__c where Sales_Rep__r.Id =: currUsr and Survey_Key__c =: surveykey];
        
        
        if(salesRepFdbckObjLst.size() > 0){
            for(CX_Sales_Rep_Account__c salRepAccObj : [select ID
                                                        , Sales_Rep_Customer__r.Name
                                                        , Sales_Rep_Customer__r.SAP_Sold_To__c
                                                        , CX_Sales_Rep_Feedback__c
                                                        , CX_Sales_Rep_Feedback__r.Business_Unit__c
                                                        , CX_Sales_Rep_Feedback__r.Sales_Rep__r.Name 
                                                        , Yes__c
                                                        , No__c
                                                        , If_no_then_do_you_know_who__c
                                                        from CX_Sales_Rep_Account__c where CX_Sales_Rep_Feedback__c =: salesRepFdbckObjLst.get(0).Id]){
                                                            
                                                            SalesRepAccWarpper salesRepAccWarpperObj = new SalesRepAccWarpper(
                                                                salRepAccObj.ID
                                                                , salRepAccObj.CX_Sales_Rep_Feedback__c
                                                                , salRepAccObj.CX_Sales_Rep_Feedback__r.Business_Unit__c
                                                                , salRepAccObj.Sales_Rep_Customer__r.SAP_Sold_To__c
                                                                , salRepAccObj.Sales_Rep_Customer__r.Name
                                                                , salRepAccObj.CX_Sales_Rep_Feedback__r.Sales_Rep__r.Name
                                                                , salRepAccObj.Yes__c
                                                                , salRepAccObj.No__c
                                                                , salRepAccObj.If_no_then_do_you_know_who__c
                                                            );  
                                                            retList.add(salesRepAccWarpperObj); 
                                                        }
        }
        return retList; 
    }
    
    public class SalesRepAccWarpper {
        
        @AuraEnabled public String cxsrAccId {get;set;}
        @AuraEnabled public String cxsrFdbkId {get;set;}
        @AuraEnabled public String businessUnit {get;set;}
        @AuraEnabled public String custCode {get;set;}
        @AuraEnabled public String accName {get;set;}
        @AuraEnabled public String salesRepName {get;set;}
        @AuraEnabled public Boolean yesChk {get;set;}
        @AuraEnabled public Boolean noChk {get;set;}
        @AuraEnabled public String if_no_then_do_you_know_who {get;set;}
        
        public SalesRepAccWarpper(String cxsrAccId, 
                                  String cxsrFdbkId, 
                                  String businessUnit, 
                                  String custCode, 
                                  String accName,
                                  String salesRepName, 
                                  Boolean yesChk, 
                                  Boolean noChk, 
                                  String if_no_then_do_you_know_who)
        {
            this.cxsrAccId = cxsrAccId;
            this.cxsrFdbkId = cxsrFdbkId;
            this.businessUnit = businessUnit;
            this.custCode = custCode;
            this.accName = accName;
            this.salesRepName = salesRepName;
            this.yesChk = yesChk;
            this.noChk = noChk;
            this.if_no_then_do_you_know_who = if_no_then_do_you_know_who;
        }
        
    }
    
}