fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/BaseQuotaException__c/BaseQuotaException__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for EOY BaseQuota Inclusion.</description>
    <label>BaseQuotaException</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/BaseQuotaException__c/fields/IsException__c.field-meta.xml
<CustomField>
    <fullName>IsException__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used for EOY BaseQuota Inclusion.</description>
    <inlineHelpText>Used for EOY BaseQuota Inclusion.</inlineHelpText>
    <label>IsException</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/CVC_SKUs__c/CVC_SKUs__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of CVC SKUs</description>
    <label>CVC SKUs</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/Invoiced_Sales__c.object-meta.xml
<CustomObject>
    <description>Invoiced Sales is the official name that SAP sales that have are shipped and counted towards compensation.</description>
    <label>Invoiced Sales</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Invoiced Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Commissionable Date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Material_Name__c.field-meta.xml
<CustomField>
    <fullName>Material_Name__c</fullName>
    <label>Material Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Needle_SKUs__c/Needle_SKUs__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Needle SKUs</description>
    <label>Needle SKUs</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/Target_Profile__c.object-meta.xml
<CustomObject>
    <label>Target Profile</label>
    <nameField>
        <displayFormat>TP-{00000}</displayFormat>
        <label>Target Profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Target Profile Pre-Hospital</relationshipLabel>
    <relationshipName>Target_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/X12_Month_CVC_Rolling_Sales__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_CVC_Rolling_Sales__c</fullName>
    <inlineHelpText>Select CVC SKUs</inlineHelpText>
    <label>12M CVC Rolling Sales ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/X12_Month_CVC_Rolling_Sales_eaches__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_CVC_Rolling_Sales_eaches__c</fullName>
    <inlineHelpText>Select CVC SKUs</inlineHelpText>
    <label>12M CVC Rolling Sales (eaches)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/X12_Month_Rolling_Sales__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Sales__c</fullName>
    <description>12 Month&apos;s Rolling Slaes Data</description>
    <inlineHelpText>Needles Only</inlineHelpText>
    <label>12M Needle Rolling Sales ($)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/X12_Month_Rolling_Sales_eaches__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Sales_eaches__c</fullName>
    <description>12 Month&apos;s Rolling Sales in eaches</description>
    <inlineHelpText>Needles Only</inlineHelpText>
    <label>12M Needle Rolling Sales (eaches)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/recordTypes/Hospital.recordType-meta.xml
<RecordType>
    <fullName>Hospital</fullName>
    <active>true</active>
    <label>Hospital</label>
</RecordType>

fullSandbox11072023/force-app/main/default/classes/TargetProfileRollingSalesBatch_Test.cls
@isTest
public class TargetProfileRollingSalesBatch_Test {
    public static Id HospitalRecTypeId = Schema.getGlobalDescribe().get('Target_Profile__c').getDescribe().getRecordTypeInfosByName().get('Hospital').getRecordTypeId();
    public static Id PreHospitalRecTypeId = Schema.getGlobalDescribe().get('Target_Profile__c').getDescribe().getRecordTypeInfosByName().get('Pre-Hospital').getRecordTypeId();
    
    @testSetup
    static void createData() {
        Account acc = new Account();
        acc.Name = 'Testacc';
        insert acc;
        
        insert new Needle_SKUs__c(Name='9079P-VC-005');
        insert new CVC_SKUs__c(Name='AK-47702-CDC');
        
        BaseQuotaException__c bqe = new BaseQuotaException__c(
            Name = 'territory_user_maintenance',
            IsException__c = TRUE
        );
        insert bqe;
        
        List<Invoiced_Sales__c> sales = new List<Invoiced_Sales__c>();
        Invoiced_Sales__c is1 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Surgical Disposables',
            Date__c = Date.Today() - 300,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 100000,
            Quantity__c = 10
        );
        sales.add(is1);
        Invoiced_Sales__c is2 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Surgical Disposables',
            Date__c = Date.Today() - 300,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 200000,
            Quantity__c = 20
        );
        sales.add(is2);
        Invoiced_Sales__c is3 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Surgical Disposables',
            Date__c = Date.Today() - 300,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = 'AK-47702-CDC',
            Sales__c = 400000,
            Quantity__c = 40
        );
        sales.add(is3);
        insert sales;
        
        List<Target_Profile__c> tps = new List<Target_Profile__c>();
        Target_Profile__c tp = new Target_Profile__c();
        tp.RecordTypeId = PreHospitalRecTypeId;
        tp.Account__c = acc.Id;
        tps.add(tp);
        
        Target_Profile__c tpH = new Target_Profile__c();
        tpH.RecordTypeId = HospitalRecTypeId;
        tpH.Account__c = acc.Id;
        tps.add(tpH);
        
        insert tps;
    }//end of createData
    
    //start testing updateRollingSales
    @isTest
    static void test_updateRollingSales() {
        Test.startTest();
        TargetProfileRollingSalesBatch b = new TargetProfileRollingSalesBatch ();
        database.executebatch(b,115);
        
        String sch='0 0 0 ? * * *';
        String jobId = System.schedule('TargetProfileRollingSalesBatch Schedule', sch , b);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        Test.stopTest();
        System.assertEquals(0, ct.TimesTriggered);
        
        
        List<Target_Profile__c> tp = [SELECT Id, Account__c, RecordTypeId, X12_Month_Rolling_Sales__c, X12_Month_Rolling_Sales_eaches__c,
                                      X12_Month_CVC_Rolling_Sales__c, X12_Month_CVC_Rolling_Sales_eaches__c
                                      FROM Target_Profile__c];
        
        for(Target_Profile__c t:tp){
            if(t.RecordTypeId == HospitalRecTypeId){
                system.assertEquals(300000, t.X12_Month_Rolling_Sales__c);
                system.assertEquals(30, t.X12_Month_Rolling_Sales_eaches__c);
                //system.assertEquals(400000, t.X12_Month_CVC_Rolling_Sales__c);
                //system.assertEquals(40, t.X12_Month_CVC_Rolling_Sales_eaches__c);
            }
            else{
                system.assertEquals(300000, t.X12_Month_Rolling_Sales__c);
                system.assertEquals(30, t.X12_Month_Rolling_Sales_eaches__c);
            }
        }
        
    }
}