fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/BaseQuotaException__c/BaseQuotaException__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for EOY BaseQuota Inclusion.</description>
    <label>BaseQuotaException</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/BaseQuotaException__c/fields/IsException__c.field-meta.xml
<CustomField>
    <fullName>IsException__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used for EOY BaseQuota Inclusion.</description>
    <inlineHelpText>Used for EOY BaseQuota Inclusion.</inlineHelpText>
    <label>IsException</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/Invoiced_Sales__c.object-meta.xml
<CustomObject>
    <description>Invoiced Sales is the official name that SAP sales that have are shipped and counted towards compensation.</description>
    <label>Invoiced Sales</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Invoiced Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>Commissionable Date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Material_Name__c.field-meta.xml
<CustomField>
    <fullName>Material_Name__c</fullName>
    <label>Material Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/Pain_Profile__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about Accounts from the Pain Management Team AEM.</description>
    <label>Pain Profile</label>
    <nameField>
        <displayFormat>Pain-{00000}</displayFormat>
        <label>Pain Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pain Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pain Profiles</relationshipLabel>
    <relationshipName>Pain_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Product_Class__c.field-meta.xml
<CustomField>
    <fullName>Product_Class__c</fullName>
    <label>Product Class</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Product_Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Group__c</fullName>
    <label>Product Sub-Group</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <inlineHelpText>Last 12 Months of Sales</inlineHelpText>
    <label>Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PainProfilesSalesHandlerTest.cls
@istest public class PainProfilesSalesHandlerTest {
    @testsetup
    static void createTestData(){
        
        Account acc = new Account();
        acc.Name = 'Testacc';
        insert acc;
        
        List<Product2> products = new List<Product2>();
        products.add(new Product2(
            Name = 'ASK-05560-TG1',
            ProductCode= 'ASK-05560-TG1',
            Group__c = 'Regional Anesthesia',
            Product_Class__c = '0014 ',
            Product_Group__c = '00140004 ',
            Product_Sub_Group__c = '001400040003 ',
            Product_Line__c = '001400040003000001 '
        ));
        products.add(new Product2(
            Name = 'MT2060L-CPNB',
            ProductCode= 'MT2060L-CPNB',
            Group__c = 'LMA Pain Management',
            Product_Class__c = '0014',
            Product_Group__c = '00140012',
            Product_Sub_Group__c = '001400120001',
            Product_Line__c = '001400120001000001'
        ));
        products.add(new Product2(
            Name = '100382020',
            ProductCode= '100382020',
            Group__c = 'Airway',
            Product_Class__c = '0014',
            Product_Group__c = '00140002',
            Product_Sub_Group__c = '001400020005',
            Product_Line__c = '001400020005000004'
        ));
        products.add(new Product2(
            Name = 'MAD301',
            ProductCode= 'MAD301',
            Group__c = 'LMA Atomization',
            Product_Class__c = '0014',
            Product_Group__c = '00140006',
            Product_Sub_Group__c = '001400060001',
            Product_Line__c = '001400060001000010'
        ));
        insert products;
        
        BaseQuotaException__c bqe = new BaseQuotaException__c(
            Name = 'territory_user_maintenance',
            IsException__c = TRUE
        );
        insert bqe;
        
        List<Invoiced_Sales__c> sales = new List<Invoiced_Sales__c>();
        Invoiced_Sales__c is1 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 100000,
            Quantity__c = 10,
            Product__c = products[0].ID
        );
        sales.add(is1);
        
        Invoiced_Sales__c is2 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 200000,
            Quantity__c = 20,
            Product__c = products[1].ID
        );
        sales.add(is2);
        
        Invoiced_Sales__c is3 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = 'AK-47702-CDC',
            Sales__c = 400000,
            Quantity__c = 40,
            Product__c = products[2].ID
        );
        sales.add(is3);
        
        Invoiced_Sales__c is4 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079-VC-005',
            Sales__c = 825.0,
            Quantity__c = 5.0,
            Product__c = products[3].ID 
        );
        sales.add(is4);
        
        Invoiced_Sales__c is5 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 100000,
            Quantity__c = 10,
            Product__c = products[0].ID
        );
        sales.add(is5);
        
        Invoiced_Sales__c is6 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 200000,
            Quantity__c = 20,
            Product__c = products[1].ID
        );
        sales.add(is6);
        
        Invoiced_Sales__c is7 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = 'AK-47702-CDC',
            Sales__c = 400000,
            Quantity__c = 40,
            Product__c = products[2].ID
        );
        sales.add(is7);
        
        Invoiced_Sales__c is8 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079-VC-005',
            Sales__c = 825.0,
            Quantity__c = 5.0,
            Product__c = products[3].ID 
        );
        sales.add(is8);
        
        Invoiced_Sales__c is11 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 100000,
            Quantity__c = 10,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[0].ID
        );
        sales.add(is11);
        
        Invoiced_Sales__c is12 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 200000,
            Quantity__c = 20,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[1].ID
        );
        sales.add(is12);
        
        Invoiced_Sales__c is13 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = 'AK-47702-CDC',
            Sales__c = 400000,
            Quantity__c = 40,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[2].ID
        );
        sales.add(is13);
        
        Invoiced_Sales__c is14 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today() - 30,
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079-VC-005',
            Sales__c = 825.0,
            Quantity__c = 5.0,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[3].ID 
        );
        sales.add(is14);
        
        Invoiced_Sales__c is15 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 100000,
            Quantity__c = 10,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[0].ID
        );
        sales.add(is15);
        
        Invoiced_Sales__c is16 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079P-VC-005',
            Sales__c = 200000,
            Quantity__c = 20,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[1].ID
        );
        sales.add(is16);
        
        Invoiced_Sales__c is17 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = 'AK-47702-CDC', 
            Sales__c = 400000,
            Quantity__c = 40,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[2].ID
        );
        sales.add(is17);
        
        Invoiced_Sales__c is18 = new Invoiced_Sales__c(
            Account__c = acc.id,
            Business_Unit__c = 'Anesthesia',
            Date__c = Date.Today().addYears(-1),
            SAP_Code__c = acc.SAP_Sold_To__c,
            Material_Name__c = '9079-VC-005',
            Sales__c = 825.0,
            Quantity__c = 5.0,
            Compensation_Profile__c ='Anesthesia Canada',
            Product__c = products[3].ID 
        );
        sales.add(is18);
        insert sales;
    }//end of createData
    
    @isTest static void tstinsalfrmtrg() {
        Test.startTest();
        Account acc = [SELECT Id FROM Account];
        List<Pain_Profile__c> painProfs = new List<Pain_Profile__c>();        
        painProfs.add(new Pain_Profile__c(Account__c = acc.Id));       
        insert painProfs;        
        Test.stopTest();
    }
}