fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <description>Payment Terms</description>
    <inlineHelpText>Payment Terms</inlineHelpText>
    <label>Terms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10CR - HO Corporate Retail</fullName>
            </value>
            <value>
                <fullName>10HO - HO Hardware</fullName>
            </value>
            <value>
                <fullName>10IR - HO Independent Retail</fullName>
            </value>
            <value>
                <fullName>10SI - HO Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>12CR - NSW Corporate Retail</fullName>
            </value>
            <value>
                <fullName>12IR - NSW Independent Retail</fullName>
            </value>
            <value>
                <fullName>12SI - NSW Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>13CR - VIC Corporate Retail</fullName>
            </value>
            <value>
                <fullName>13IR - VIC Independent Retail</fullName>
            </value>
            <value>
                <fullName>13SI - VIC Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>14CR - QLD Corporate Retail</fullName>
            </value>
            <value>
                <fullName>14IR - QLD Independent Retail</fullName>
            </value>
            <value>
                <fullName>14SI - QLD Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>15CR - SA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>15IR - SA Independent Retail</fullName>
            </value>
            <value>
                <fullName>15SI - SA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>16CR - WA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>16IR - WA Independent Retail</fullName>
            </value>
            <value>
                <fullName>16SI - WA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>18CR - Int/Emer Corporate Retail</fullName>
            </value>
            <value>
                <fullName>18IR - Int/Emer Independent Retail</fullName>
            </value>
            <value>
                <fullName>18SI - Int/Emer Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>31IN - Fishers Industrial</fullName>
            </value>
            <value>
                <fullName>31RS - Fishers Reseller</fullName>
            </value>
            <value>
                <fullName>4201 - ACT</fullName>
            </value>
            <value>
                <fullName>4202 - South Eastern Sydney</fullName>
            </value>
            <value>
                <fullName>4203 - Southern NSW</fullName>
            </value>
            <value>
                <fullName>4204 - South Western Sydney</fullName>
            </value>
            <value>
                <fullName>4205 - Western NSW</fullName>
            </value>
            <value>
                <fullName>4206 - Western Syd LHN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>Territory_Key__c</fullName>
    <description>Territory_Key__c is built every day as part of the daily Invoiced Sales ETL. 
Apex: account_Active_Sales
Scheduled Apex: Invoiced_Sales_Maintenance_Scheduler</description>
    <inlineHelpText>List of Territory Numbers that have Sales related to this Account.</inlineHelpText>
    <label>Territory Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <label>Territory Account Assignments</label>
    <nameField>
        <label>Territory Assignments</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Account Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Territory_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <formula>TEXT(Territory__r.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <formula>Territory__r.Sales_Rep_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Account Assignments</relationshipLabel>
    <relationshipName>Territory_Account_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Primary_Territory_User__c.field-meta.xml
<CustomField>
    <fullName>Primary_Territory_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Territory User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Master2</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used to concatenate the Territory Number with the Primary Territory User Full Name.</inlineHelpText>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/CustExpAccRepresentationTool.cls
/*********************************************************************
* Description      : Controller class to fetch data from given account and sent account team contact details for business units with $ sales.
* Test Class       : CustExpAccRepresentationTool_Test
* VisualForce      : N/A
* Author(s)        : Surya Arvan - surya.arvan@teleflex.com

//initial version work item: W-023175 sprint: 2020.05
**********************************************************************/
public class CustExpAccRepresentationTool {
    
    @AuraEnabled
    public static Contact fetchContact(Id conId) {
        return [SELECT Id, Name, Email, AccountId, Account.Name from Contact where Id =: conId];
    }
    
    @AuraEnabled
    public static String sendCXAccRepEmailTemp2Con(Contact conObj){
        
        OrgWideEmailAddress orgEm = [select Id, Address from OrgWideEmailAddress WHERE Address='cx@teleflex.com'];
        
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTargetObjectId(conObj.Id); 
        message.setOrgWideEmailAddressId(orgEm.Id);
        message.setReplyTo('cs@teleflex.com');
        message.setUseSignature(false); 
        message.setBccSender(false); 
        message.setSaveAsActivity(false); 
        EmailTemplate emailTemplate = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where name = 'CE Account Representation'];
        message.setTemplateID(emailTemplate.Id); 
        message.setWhatId(conObj.AccountId); //This is important for the merge fields in template to work
        message.toAddresses = new String[] { conObj.email};
            Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        
        if (results[0].success) 
        {
            return 'The email was sent successfully.'; } else { return 'The email failed to send: ' +  results[0].errors[0].message; }
    }
    
    
    
    /*    @AuraEnabled
public static List < account > fetchAccount(String searchKeyWord) {
String searchKey = searchKeyWord + '%';
List < Account > returnList = new List < Account > ();
List < Account > lstOfAccount = [select id, Name from account where Name LIKE: searchKey];

for (Account acc: lstOfAccount) {
returnList.add(acc);
}
return returnList;
}
*/    
    public Account relatedTo {get; set;}
    public List<Territory_Assignment__c> taObjLst {get; set;}
    
    
    public CustExpAccRepresentationTool(){
        
        if(ApexPages.currentPage().getParameters().get('id') != NULL){
            relatedTo = [SELECT Id, Name, ShippingStreet, ShippingCity, ShippingState, Terms__c,
                         ShippingPostalCode, ShippingCountry, SAP_Sold_To__c,
                         Territory_Key__c,
                         Account.Territory__c
                         FROM Account
                         WHERE id = :ApexPages.currentPage().getParameters().get('id')
                         ];
            
            taObjLst = [SELECT Territory_Number__c, Business_Unit__c, 
                        Territory__r.Territory_Number__c,
                        Territory__r.Sales_Rep__r.Name,
                        Territory__r.Sales_Rep__r.Email,
                        Territory__r.Sales_Rep__r.Phone,
                        Territory__r.Primary_Territory_User__r.Name,
                        Territory__r.Primary_Territory_User__r.Email,
                        Territory__r.Primary_Territory_User__r.Phone
                        FROM Territory_Assignment__c
                        WHERE Account__c =:ApexPages.currentPage().getParameters().get('id')
                       ];  
            
        }
        
    }
    
}