fullSandbox11072023/force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Retail</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Independent Retail</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Resellers</fullName>
            </value>
            <value>
                <fullName>Safety &amp; Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10CR - HO Corporate Retail</fullName>
            </value>
            <value>
                <fullName>10HO - HO Hardware</fullName>
            </value>
            <value>
                <fullName>10IR - HO Independent Retail</fullName>
            </value>
            <value>
                <fullName>10SI - HO Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>12CR - NSW Corporate Retail</fullName>
            </value>
            <value>
                <fullName>12IR - NSW Independent Retail</fullName>
            </value>
            <value>
                <fullName>12SI - NSW Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>13CR - VIC Corporate Retail</fullName>
            </value>
            <value>
                <fullName>13IR - VIC Independent Retail</fullName>
            </value>
            <value>
                <fullName>13SI - VIC Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>14CR - QLD Corporate Retail</fullName>
            </value>
            <value>
                <fullName>14IR - QLD Independent Retail</fullName>
            </value>
            <value>
                <fullName>14SI - QLD Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>15CR - SA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>15IR - SA Independent Retail</fullName>
            </value>
            <value>
                <fullName>15SI - SA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>16CR - WA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>16IR - WA Independent Retail</fullName>
            </value>
            <value>
                <fullName>16SI - WA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>18CR - Int/Emer Corporate Retail</fullName>
            </value>
            <value>
                <fullName>18IR - Int/Emer Independent Retail</fullName>
            </value>
            <value>
                <fullName>18SI - Int/Emer Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>31IN - Fishers Industrial</fullName>
            </value>
            <value>
                <fullName>31RS - Fishers Reseller</fullName>
            </value>
            <value>
                <fullName>4201 - ACT</fullName>
            </value>
            <value>
                <fullName>4202 - South Eastern Sydney</fullName>
            </value>
            <value>
                <fullName>4203 - Southern NSW</fullName>
            </value>
            <value>
                <fullName>4204 - South Western Sydney</fullName>
            </value>
            <value>
                <fullName>4205 - Western NSW</fullName>
            </value>
            <value>
                <fullName>4206 - Western Syd LHN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/Invoiced_Sales_Detail__c.object-meta.xml
<CustomObject>
    <label>Invoiced Sales Detail</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Invoiced Sales Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales Details</relationshipLabel>
    <relationshipName>Invoiced_Sales_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales_Detail__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Invoiced Sales Details</relationshipLabel>
    <relationshipName>Invoiced_Sales_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/Open_Orders__c.object-meta.xml
<CustomObject>
    <label>Open Orders</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Open Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Open Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Open Orders</relationshipLabel>
    <relationshipName>Open_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Back_Order_Qty__c.field-meta.xml
<CustomField>
    <fullName>Back_Order_Qty__c</fullName>
    <label>Back Order Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Back_Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Back_Order_Total__c</fullName>
    <label>Back Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Back_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Back_Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Back Ordered</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Future_Order_Qty__c.field-meta.xml
<CustomField>
    <fullName>Future_Order_Qty__c</fullName>
    <label>Future Order Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Future_Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Future_Order_Total__c</fullName>
    <label>Future Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Open_Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Open_Order_Total__c</fullName>
    <label>Open Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Open Orders</relationshipLabel>
    <relationshipName>Open_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Open_Orders__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <inlineHelpText>Last 12 Months of Sales</inlineHelpText>
    <label>Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/Sales_Accounts__c.object-meta.xml
<CustomObject>
    <label>Sales Account</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Sales Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Accounts</relationshipLabel>
    <relationshipName>Sales_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <formula>Account__r.SAP_Sold_To__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Code</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sales_Accounts__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Sales Accounts</relationshipLabel>
    <relationshipName>Sales_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Anesthesia Canada</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>DTAC</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Military</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Bariatrics</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used to concatenate the Territory Number with the Primary Territory User Full Name.</inlineHelpText>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/open_Orders.cls
public class open_Orders {
    
    public list<Sales_Accounts__c> saList {get; set;}
    public list<Open_Orders__c> ooList {get; set;}
    public map<Id, Decimal> roMap {get; set;}
    public Account acct {get; set;}
    public Territory_Master__c tmaster {get; set;}
    public Id tid {get; set;}
    public string tnumber {get; set;}
    public Id aid {get; set;}
    public String oname {get; set;}
    public boolean recentOrders {get; set;}
    
    public open_Orders(){
        saList = new list<Sales_Accounts__c>();
        ooList = new list<Open_Orders__c>();
        roMap = new map<Id, Decimal>();
        acct = new Account();
        tmaster = new Territory_Master__c();
        set<Id> aSet = new set<Id>();
        recentOrders = FALSE;
        
        if(ApexPages.currentPage().getParameters().get('id') != NULL){
            tid = ApexPages.currentPage().getParameters().get('id');
            tnumber = [SELECT Territory_Number__c FROM Territory_Master__c where Id =:tid].Territory_Number__c;
            tmaster = [SELECT Business_Unit__c FROM Territory_Master__c where Id =:tid];

            if(ApexPages.currentPage().getParameters().get('aid') != NULL){
                aid = ApexPages.currentPage().getParameters().get('aid');
                
                decimal count;
                string account;
                
                for(AggregateResult ar : [SELECT sum(Sales__c ) cnt, Account__c acct 
                                          FROM Invoiced_Sales_Detail__c  
                                          WHERE Account__c =:aid 
                                          AND Territory__c =:tid 
                                          GROUP BY Account__c])
                {
                    count = (decimal) ar.get('cnt');
                    account = (string) ar.get('acct');
                    roMap.put(account, count);
                    
                    recentOrders = TRUE;
                }

                acct = [SELECT Id, Name, SAP_Code__c FROM Account WHERE Id =:aid]; 

                for(Sales_Accounts__c sa : [SELECT Account__c  
                                            FROM Sales_Accounts__c 
                                            WHERE Territory__c =:tid
                                            AND Account__c =:aid])
                {
                    aSet.add(sa.Account__c);
                }
            }
            else{
                for(Sales_Accounts__c sa : [SELECT Account__c  
                                            FROM Sales_Accounts__c 
                                            WHERE Territory__c =:tid])
                {
                    aSet.add(sa.Account__c);
                } 
            }
            
            
            for(Open_Orders__c oo : [SELECT Id, Account__r.Name, Account__r.SAP_Code__c, PO_Number__c, Order_Number__c, Order_Date__c, 
                                     Back_Order_Qty__c, Back_Order_Total__c, Back_Ordered__c, Future_Order_Qty__c, Future_Order_Total__c, 
                                     Open_Order_Total__c, Open_Order_Qty__c, Product__r.Name, Product__r.Description, Product__c, 
                                     Scheduled_Ship_Date__c, Territory_Number__c, Territory__c, Line_Item_Number__c  
                                     FROM Open_Orders__c 
                                     WHERE Account__c =:aSet])
            {
                ooList.add(oo);
            }
        }
        else{
            for(Open_Orders__c oo : [SELECT Id, Account__r.Name, Account__r.SAP_Code__c, PO_Number__c, Order_Number__c, Order_Date__c, 
                                     Back_Order_Qty__c, Back_Order_Total__c, Back_Ordered__c, Future_Order_Qty__c, Future_Order_Total__c, 
                                     Open_Order_Total__c, Open_Order_Qty__c, Product__r.Name, Product__r.Description, Product__c, 
                                     Scheduled_Ship_Date__c, Territory_Number__c, Territory__c, Line_Item_Number__c     
                                     FROM Open_Orders__c WHERE Back_Ordered__c = TRUE 
                                     LIMIT 10000])
            {
                ooList.add(oo);
            }
        }
        if(tnumber != NULL && acct.SAP_Code__c != NULL){
            oname = 'Open-Orders-' + tnumber + '-' + acct.SAP_Code__c;
        }
        else if(tnumber != NULL){
            oname = 'Open-Orders-' + tnumber;
        }
        else{
            oname = 'Open-Orders';
        }
        
    }

}