fullSandbox11072023/force-app/main/default/objects/Account/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/Contract_Customer__c.object-meta.xml
<CustomObject>
    <label>Contract Customer</label>
    <nameField>
        <label>Contract Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition_Rank__c.field-meta.xml
<CustomField>
    <fullName>Condition_Rank__c</fullName>
    <formula>if(Condition__c  = &quot;XIND&quot;, 1,
if(Condition__c  = &quot;XPRI&quot;, 2,
if(Condition__c  = &quot;XSEC&quot;, 3,
if(Condition__c  = &quot;XNAF&quot;, 4,
100
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Condition Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <inlineHelpText>GPO Owner Name</inlineHelpText>
    <label>Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c  &gt;=  TODAY() &amp;&amp; Valid_From__c  &lt;=  TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>if(RIGHT(Objective__c,1) = &quot;1&quot;, &quot;Direct/Rebate&quot;, 
if(RIGHT(Objective__c,1) = &quot;2&quot;, &quot;Direct&quot;, 
if(RIGHT(Objective__c,1) = &quot;3&quot;, &quot;Distributor Netbill&quot;, 
if(RIGHT(Objective__c,1) = &quot;4&quot;, &quot;Specialty Market&quot;, 
if(RIGHT(Objective__c,1) = &quot;5&quot;, &quot;Strategic Accounts&quot;, 
if(RIGHT(Objective__c,1) = &quot;6&quot;, &quot;Rebate Only&quot;, 
&quot;Not Defined&quot;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <label>Sub-Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/Contract_Material__c.object-meta.xml
<CustomObject>
    <label>Contract Material</label>
    <nameField>
        <label>Contract Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c &gt;= TODAY() &amp;&amp; Valid_From__c &lt;= TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Material</relationshipLabel>
    <relationshipName>Contract_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <formula>Agreement__r.Agreement_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Number</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Material</relationshipLabel>
    <relationshipName>Contract_Material</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/Contract_Renewal__c.object-meta.xml
<CustomObject>
    <label>Contract Renewal</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Contract Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Renewals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DNU_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>DNU_Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Condition_Rank__c.field-meta.xml
<CustomField>
    <fullName>Condition_Rank__c</fullName>
    <formula>if(Condition__c = &quot;XIND&quot;, 1, 
if(Condition__c = &quot;XPRI&quot;, 2, 
if(Condition__c = &quot;XSEC&quot;, 3, 
if(Condition__c = &quot;XNAF&quot;, 4, 
100 
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DNU_Condition Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Contract_Customer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DNU_Contract Customer</label>
    <referenceTo>Contract_Customer__c</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Contract_Header__c.field-meta.xml
<CustomField>
    <fullName>Contract_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Header</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/GPO_Contract_Ref__c.field-meta.xml
<CustomField>
    <fullName>GPO_Contract_Ref__c</fullName>
    <label>GPO Contract Ref</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>if(Objective__c = &quot;01&quot;, &quot;Direct/Rebate (01)&quot;, 
if(Objective__c = &quot;02&quot;, &quot;Direct (02)&quot;, 
if(Objective__c = &quot;03&quot;, &quot;Distributor Netbill (03)&quot;, 
if(Objective__c = &quot;04&quot;, &quot;Specialty Market (04)&quot;, 
if(Objective__c = &quot;05&quot;, &quot;Strategic Accounts (05)&quot;, 
if(Objective__c = &quot;06&quot;, &quot;Rebate Only (06)&quot;, 
&quot;Not Defined&quot;))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Sub_Group__c.field-meta.xml
<CustomField>
    <fullName>Sub_Group__c</fullName>
    <label>Sub-Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal_Item__c/Contract_Renewal_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Renewal Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Contract Renewal Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Renewal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal_Item__c/fields/Contract_Material__c.field-meta.xml
<CustomField>
    <fullName>Contract_Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Material</label>
    <referenceTo>Contract_Material__c</referenceTo>
    <relationshipLabel>Contract Renewal Items</relationshipLabel>
    <relationshipName>Contract_Renewal_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal_Item__c/fields/Contract_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Contract_Renewal__c</fullName>
    <label>Contract Renewal</label>
    <referenceTo>Contract_Renewal__c</referenceTo>
    <relationshipLabel>Contract Renewal Items</relationshipLabel>
    <relationshipName>Contract_Renewal_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Renewal Items</relationshipLabel>
    <relationshipName>Contract_Renewal_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal_Item__c/fields/Requested_Renewal_Price__c.field-meta.xml
<CustomField>
    <fullName>Requested_Renewal_Price__c</fullName>
    <label>Requested Renewal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/contract_Renewal_Material_Analysis.cls
/*********************************************************************
* Description      : Class provides details of Materials per contract.
* Test Class       : Contract_Renewal_Test
* VisualForce      : contract_Renewal_Material_Analysis
* Author(s)        : Eric Clay
**********************************************************************/
public class contract_Renewal_Material_Analysis {

    public Contract_Renewal__c cr {get; set;}
    public Account Acct {get; set;}
    public map<String, Contract_Customer__c> ccMap {get; set;}
    public map<Id, list<Contract_Material__c>> cmMap {get; set;}
    public map<String, Decimal> criPrice {get; set;}
    public list<Contract_Customer__c> ccList {get; set;}
    public list<Contract_Material__c> cmList {get; set;}
    public string fname {get; set;}
    public string cid {get; set;}

    public contract_Renewal_Material_Analysis(){
        cmMap = new map<ID, list<Contract_Material__c>>();
        ccMap = new map<String, Contract_Customer__c>();
        criPrice = new map<String, Decimal>();
        ccList = new list<Contract_Customer__c>();
        cmList = new list<Contract_Material__c>();
        cr = new Contract_Renewal__c();
        Acct = new Account();

        set<Id> chIdSet = new set<Id>();
        set<Id> criSet = new set<Id>();
        string aid;

        if(Apexpages.currentPage().getParameters().get('id') != NULL){

            cid = Apexpages.currentPage().getParameters().get('id');
            cr = [SELECT Contract_Header__r.Id, Contract_Header__r.Agreement_Number__c, Contract_Header__r.Description__c
                  FROM Contract_Renewal__c
                  WHERE Id =:cid];

            Id chId = cr.Contract_Header__r.Id;

            fname = cr.Contract_Header__r.Agreement_Number__c + '-Customers-';
            fname += datetime.now().format('MM-dd-yyyy');

            aid = Apexpages.currentPage().getParameters().get('aid');
            for(Contract_Renewal_Item__c cri : [SELECT Id, Product__c, Requested_Renewal_Price__c, Product__r.Name
                                               FROM Contract_Renewal_Item__c
                                               WHERE Contract_Renewal__c =:cid])
            {
                criSet.add(cri.Product__c);
                criPrice.put(cri.Product__r.name, cri.Requested_Renewal_Price__c);
            }
            //system.debug('CRIs: ' + criSet);
            for(Contract_Customer__c cc : [SELECT Id, Agreement__c, Condition__c, Condition_Rank__c, Agreement_Number__c, Agreement__r.Description__c, Agreement__r.GPO_Contract_Ref__c,
                                           Valid_From__c, Valid_To__c, Agreement__r.Objective__c, Agreement__r.Objective_Name__c,
                                           Agreement__r.Owner__c, Agreement__r.Owner_Name__c, Agreement__r.Distribution_Channel__c,
                                           Agreement__r.Group__c, Agreement__r.Sub_Group__c
                                           FROM Contract_Customer__c
                                           WHERE Account__c =:aid])
            {
                //ccList.add(cc);
                ccMap.put(cc.Agreement_Number__c, cc);
                //chIdSet.add(cc.Agreement__c);
            }
            //system.debug('chIdSet: ' + chIdSet);
            for(Contract_Material__c cm : [SELECT Agreement_Number__c, Product__r.Name, Agreement__r.Id,
                                           Agreement__r.Agreement_Number__c, Price__c
                                           FROM Contract_Material__c
                                           WHERE Product__c =:criSet
                                           AND Active__c = TRUE
                                           ORDER BY Product__r.Name])
            {

                if(ccMap.get(cm.Agreement_Number__c) != NULL){
                    cmList.add(cm);
                }

            }


        }

    }
}