fullSandbox11072023/force-app/main/default/objects/Account/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>2 Digit Customer Group Number.</inlineHelpText>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/Contract_Customer__c.object-meta.xml
<CustomObject>
    <label>Contract Customer</label>
    <nameField>
        <label>Contract Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition_Rank__c.field-meta.xml
<CustomField>
    <fullName>Condition_Rank__c</fullName>
    <formula>if(Condition__c  = &quot;XIND&quot;, 1,
if(Condition__c  = &quot;XPRI&quot;, 2,
if(Condition__c  = &quot;XSEC&quot;, 3,
if(Condition__c  = &quot;XNAF&quot;, 4,
100
))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Condition Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition_Record__c.field-meta.xml
<CustomField>
    <fullName>Condition_Record__c</fullName>
    <label>Condition Record #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Key_Temp__c.field-meta.xml
<CustomField>
    <fullName>Key_Temp__c</fullName>
    <formula>Agreement_Number__c &amp; SAP_Code__c &amp; 
IF(MONTH(Valid_To__c) &lt; 10, &quot;0&quot; &amp; TEXT(MONTH(Valid_To__c)), TEXT(MONTH(Valid_To__c))) &amp; &quot;/&quot; &amp;
IF(DAY(Valid_To__c) &lt; 10, &quot;0&quot; &amp; TEXT(DAY(Valid_To__c)), TEXT(DAY(Valid_To__c))) &amp; &quot;/&quot; &amp;
TEXT(YEAR(Valid_To__c)) &amp; 
IF(MONTH(Valid_From__c) &lt; 10, &quot;0&quot; &amp; TEXT(MONTH(Valid_From__c)), TEXT(MONTH(Valid_From__c))) &amp; &quot;/&quot; &amp; 
IF(DAY(Valid_From__c) &lt; 10, &quot;0&quot; &amp; TEXT(DAY(Valid_From__c)), TEXT(DAY(Valid_From__c))) &amp; &quot;/&quot; &amp;
TEXT(YEAR(Valid_From__c))
 &amp; Condition__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key Temp</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c  &gt;=  TODAY() &amp;&amp; Valid_From__c  &lt;=  TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <formula>AND(
Sub_Group__c = &quot;8&quot;,
OR(
RIGHT(GPO_Contract_Ref__c,2) = &quot;-D&quot;,
RIGHT(GPO_Contract_Ref__c,2) = &quot;-M&quot;,
RIGHT(GPO_Contract_Ref__c,2) = &quot;-R&quot;,
AND(RIGHT(GPO_Contract_Ref__c,2) = &quot;-N&quot;, Sales_Org__c = &quot;CA10&quot;),
RIGHT(GPO_Contract_Ref__c,3) = &quot;-VP&quot;
),
Owner__c = &quot;123310&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Filters Contracts based on Group 8, GPO Ref ending in -R, -M, or -D and the owner being 123310 / Teleflex</inlineHelpText>
    <label>Pricing Tier</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/Contract_Material__c.object-meta.xml
<CustomObject>
    <label>Contract Material</label>
    <nameField>
        <label>Contract Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c &gt;= TODAY() &amp;&amp; Valid_From__c &lt;= TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Material</relationshipLabel>
    <relationshipName>Contract_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <formula>Agreement__r.Agreement_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Number</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Director_Price__c.field-meta.xml
<CustomField>
    <fullName>Director_Price__c</fullName>
    <label>Director Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Division_Check__c.field-meta.xml
<CustomField>
    <fullName>Division_Check__c</fullName>
    <formula>CONTAINS(Agreement__r.Divisions__c, Product__r.Division__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Division Check</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Key_Temp__c.field-meta.xml
<CustomField>
    <fullName>Key_Temp__c</fullName>
    <formula>Agreement_Number__c &amp; Material_Name__c &amp; 
IF(MONTH(Valid_To__c) &lt; 10, &quot;0&quot; &amp; TEXT(MONTH(Valid_To__c)), TEXT(MONTH(Valid_To__c))) &amp; &quot;/&quot; &amp;
IF(DAY(Valid_To__c) &lt; 10, &quot;0&quot; &amp; TEXT(DAY(Valid_To__c)), TEXT(DAY(Valid_To__c))) &amp; &quot;/&quot; &amp;
TEXT(YEAR(Valid_To__c)) &amp; 
IF(MONTH(Valid_From__c) &lt; 10, &quot;0&quot; &amp; TEXT(MONTH(Valid_From__c)), TEXT(MONTH(Valid_From__c))) &amp; &quot;/&quot; &amp; 
IF(DAY(Valid_From__c) &lt; 10, &quot;0&quot; &amp; TEXT(DAY(Valid_From__c)), TEXT(DAY(Valid_From__c))) &amp; &quot;/&quot; &amp;
TEXT(YEAR(Valid_From__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key Temp</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>/* Exceptions */
/* Price Equals one of the Tiers and the Tiers equal themselves */
if(
AND(
OR(
Rep_Price__c = RSM_Price__c,
RSM_Price__c = Director_Price__c,
Director_Price__c = VP_Price__c
),
OR(
Price__c = Rep_Price__c,
Price__c = RSM_Price__c,
Price__c = Director_Price__c,
Price__c = VP_Price__c
)
),
Level_Fix__c,

/* Price is between REP and List but RSM and REP equal each other contract is set for RSM */
if(
AND(
Rep_Price__c = RSM_Price__c,
Price__c &gt;= RSM_Price__c
),
Level_Fix__c,

/* Normal */
/* Rep Level */
if(
OR(
Price__c &gt;= Rep_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= Rep_Price__c
)),
1,
/* RSM Level */
if(
OR(
Price__c &gt;= RSM_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= RSM_Price__c
)),
2,
/* DIR Level */
if(
OR(
Price__c &gt;= Director_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= Director_Price__c 
)),
3,
/* VP Level */
if(
OR(
Price__c &gt;= VP_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= VP_Price__c 
)),
4,
Level_Fix__c
))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Level_Fix__c.field-meta.xml
<CustomField>
    <fullName>Level_Fix__c</fullName>
    <label>Level Fix</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Material_Division2__c.field-meta.xml
<CustomField>
    <fullName>Material_Division2__c</fullName>
    <formula>Product__r.Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Material Division2</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Material_Division__c.field-meta.xml
<CustomField>
    <fullName>Material_Division__c</fullName>
    <label>Material Division</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Material_Key__c.field-meta.xml
<CustomField>
    <fullName>Material_Key__c</fullName>
    <externalId>true</externalId>
    <label>Material Key</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Material_Lookup_Key__c.field-meta.xml
<CustomField>
    <fullName>Material_Lookup_Key__c</fullName>
    <externalId>true</externalId>
    <label>Material Lookup Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Material_Name__c.field-meta.xml
<CustomField>
    <fullName>Material_Name__c</fullName>
    <externalId>true</externalId>
    <label>Material Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <formula>Agreement__r.Pricing_Tier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Tier</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Pricing_Tier_Access_Mismatch__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_Access_Mismatch__c</fullName>
    <formula>AND(
Agreement__r.Pricing_Tier_Access__c &lt;&gt; Level__c,
Agreement__r.Pricing_Tier_Access__c &lt; Level__c,
Pricing_Tier__c = TRUE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Tier Access Mismatch</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Director_Price__c.field-meta.xml
<CustomField>
    <fullName>Director_Price__c</fullName>
    <label>Director Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Distribution_Channel__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Channel__c</fullName>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Material_Key__c.field-meta.xml
<CustomField>
    <fullName>Material_Key__c</fullName>
    <externalId>true</externalId>
    <label>Material Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_DataUtility.cls
/*********************************************************************
* Description      : Utility class to deal with methods related to Pricing Portal data & operations.
* Test Class       : PP_DataUtility_Test.apxc
* Author(s)        : Dunte'e Silver - duntee.silver@teleflex.com
* Date         	   : 02/09/2024
* Work Item		   : N/A
**********************************************************************/

public class PP_DataUtility {
    public PP_DataUtility() {

    }

    //Get all active Contract Customer records using a list of SAP Codes/Customer Codes/Account Numbers
    public List<Contract_Customer__c> contractCustomerList(List<String> sapNumList){
        List<Contract_Customer__c> ccList = new List<Contract_Customer__c>();
        ccList = [SELECT Id, Name, Sap_Code__c, Agreement_Number__c, Agreement__c, Condition__c, Condition_Rank__c, Active__c,
                Condition_Record__c, Customer_Group_Name__c, Customer_Group__c, Sales_Org__c, Distribution_Channel__c,
                Key__c, Valid_From__c, Valid_To__c, Agreement__r.Objective__c
                FROM Contract_Customer__c
                WHERE SAP_Code__c IN :sapNumList
                AND Active__c = TRUE];

        return ccList;
    }//end contractCustomerList

    //Get all active Contract Customer records besides rebates (Customer Service)
    //using a list of SAP Codes/Customer Codes/Account Numbers
    public List<Contract_Customer__c> contractCustomerNonRebateList(List<String> sapNumList){
        List<Contract_Customer__c> ccList = new List<Contract_Customer__c>();
        ccList = [SELECT Id, Name, Sap_Code__c, Agreement_Number__c, Agreement__c, Condition__c, Condition_Rank__c, Active__c,
                Condition_Record__c, Customer_Group_Name__c, Customer_Group__c, Sales_Org__c, Distribution_Channel__c,
                Key__c, Valid_From__c, Valid_To__c, Agreement__r.Objective__c
                FROM Contract_Customer__c
                WHERE SAP_Code__c IN :sapNumList
                AND Agreement__r.Objective__c != '06'
                AND Active__c = TRUE];

        return ccList;
    }//end contractCustomerList

    public Contract_Customer__c contractCustomerAgreeFiltList(List<String> sapNumList, List<String> agreeNums){
        Contract_Customer__c ccObj = new Contract_Customer__c();
        ccObj = [SELECT Id, Name, Sap_Code__c, Agreement_Number__c, Agreement__c, Condition__c, Condition_Rank__c, Active__c,
                Condition_Record__c, Customer_Group_Name__c, Customer_Group__c, Sales_Org__c, Distribution_Channel__c,
                Key__c, Valid_From__c, Valid_To__c, Agreement__r.Objective__c
                FROM Contract_Customer__c
                WHERE SAP_Code__c IN :sapNumList
                AND Agreement_Number__c IN :agreeNums
                AND Active__c = TRUE
                ORDER BY condition_rank__c
                LIMIT 1];

        return ccObj;
    }//end contractCustomerList

    //Get all active Contract Material records using a list of Agreement Numbers/Sales Deals numbers
    public List<Contract_Material__c> contractMaterialList(Product2 mcheck, List<String> agreeNums){
        List<Contract_Material__c> cmList = new List<Contract_Material__c>();
        cmList = [SELECT Active__c,Agreement_Number__c,Agreement__c,Condition_Record__c,Director_Price__c,Distribution_Channel__c,
                Division_Check__c,GPO_Contract_Ref__c,Id,Key_Temp__c,Level_Fix__c,Level__c,List_Price__c,Material_Division2__c,
                Material_Division__c,Material_Key__c,Material_Lookup_Key__c,Material_Name__c,Name,Price__c,Pricing_Tier_Access_Mismatch__c,
                Pricing_Tier__c,Process_Tier_Level_Mismatch__c,Product__c,Rep_Price__c,RSM_Price__c,Sales_Org__c,Tier_Level_Name__c,
                Valid_From__c,Valid_To__c,VP_Price__c, Agreement__r.Objective__c
                FROM Contract_Material__c
                WHERE Product__c = :mcheck.Id
                AND Agreement_Number__c IN :agreeNums
                AND Active__c = TRUE
                ORDER BY Price__c];

        return cmList;
    }//end contractCustomerList

}//end of PP_DataUtility class