fullSandbox11072023/force-app/main/default/objects/Account/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Main_GPO__c.field-meta.xml
<CustomField>
    <fullName>Main_GPO__c</fullName>
    <inlineHelpText>Primary group purchasing affiliation.</inlineHelpText>
    <label>Primary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Premier Purchasing Partners</fullName>
            </value>
            <value>
                <fullName>MedAssets Supply Chain Systems</fullName>
            </value>
            <value>
                <fullName>Vizient Inc.</fullName>
            </value>
            <value>
                <fullName>HealthTrust Purchasing Group</fullName>
            </value>
            <value>
                <fullName>ROI</fullName>
            </value>
            <value>
                <fullName>FirstChoice Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Secondary_GPO__c.field-meta.xml
<CustomField>
    <fullName>Secondary_GPO__c</fullName>
    <inlineHelpText>The secondary group purchasing organization.</inlineHelpText>
    <label>Secondary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Dignity</fullName>
            </value>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Vizient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/Contract_Customer__c.object-meta.xml
<CustomObject>
    <label>Contract Customer</label>
    <nameField>
        <label>Contract Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <inlineHelpText>GPO Owner Name</inlineHelpText>
    <label>Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/account_GPO_Builder_Test.cls
@isTest
public class account_GPO_Builder_Test {
    public static String CRON_EXP = '0 0 0 15 3 ?';

    static testmethod void GPO_Builder_Test(){
        
        Account a = new Account(
            Name='Teleflex Test Account 123',
            SAP_Sold_To__c = '102059'
        );
        insert a;
        
        Account a2 = new Account(
            Name='Teleflex Test Account 456',
            SAP_Sold_To__c = '102058',
            Main_GPO__c = 'Test Removal #1',
            Secondary_GPO__c = 'Test Removal #2'
        );
        insert a2;

        //Contract Header Test Records
        Contract_Header__c ch = new Contract_Header__c(
            Name = '50009999',
            Description__c = 'Teleflex Test Contract',
            Agreement_Number__c = 'TestId',
            GPO_Contract_Ref__c = 'TestRef',
            Valid_From__c = System.Today().addMonths(-1),
            Valid_To__c = System.Today().addMonths(1),
            Owner_Name__c = 'Novation',
            Owner__c = 'GPO-008'
        );
        insert ch;
        
        Contract_Customer__c cc = new Contract_Customer__c(
            Account__c = a.Id,
            Agreement__c = ch.Id,
            Name = '50009999-TEST',
            SAP_Code__c= '102059',
            Condition__c = 'XPRI'
        );
        insert cc;
        
        Contract_Customer__c cc2 = new Contract_Customer__c(
            Account__c = a.Id,
            Agreement__c = ch.Id,
            Name = '50009999-TEST',
            SAP_Code__c= '102059',
            Condition__c = 'XSEC'
        );
        insert cc2;
        
        Test.startTest();

        string query = 'SELECT Id, SAP_Sold_To__c FROM Account WHERE Id = \'' + a.Id + '\'';
        account_GPO_Builder buildGPO = new account_GPO_Builder();
        buildGPO.query = query;
        Database.executeBatch(buildGPO);
        
        // Schedule the test job
        String jobId = System.schedule('ScheduleApexClassTest',
                                       CRON_EXP, 
                                       new account_GPO_Builder_Scheduler());
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, 
                            ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
        
    }
}