fullSandbox11072023/force-app/main/default/objects/Account/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <formula>Sales_Org__c + Distribution_Channel__c</formula>
    <label>Sales Org Key</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10CR - HO Corporate Retail</fullName>
            </value>
            <value>
                <fullName>10HO - HO Hardware</fullName>
            </value>
            <value>
                <fullName>10IR - HO Independent Retail</fullName>
            </value>
            <value>
                <fullName>10SI - HO Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>12CR - NSW Corporate Retail</fullName>
            </value>
            <value>
                <fullName>12IR - NSW Independent Retail</fullName>
            </value>
            <value>
                <fullName>12SI - NSW Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>13CR - VIC Corporate Retail</fullName>
            </value>
            <value>
                <fullName>13IR - VIC Independent Retail</fullName>
            </value>
            <value>
                <fullName>13SI - VIC Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>14CR - QLD Corporate Retail</fullName>
            </value>
            <value>
                <fullName>14IR - QLD Independent Retail</fullName>
            </value>
            <value>
                <fullName>14SI - QLD Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>15CR - SA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>15IR - SA Independent Retail</fullName>
            </value>
            <value>
                <fullName>15SI - SA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>16CR - WA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>16IR - WA Independent Retail</fullName>
            </value>
            <value>
                <fullName>16SI - WA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>18CR - Int/Emer Corporate Retail</fullName>
            </value>
            <value>
                <fullName>18IR - Int/Emer Independent Retail</fullName>
            </value>
            <value>
                <fullName>18SI - Int/Emer Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>31IN - Fishers Industrial</fullName>
            </value>
            <value>
                <fullName>31RS - Fishers Reseller</fullName>
            </value>
            <value>
                <fullName>4201 - ACT</fullName>
            </value>
            <value>
                <fullName>4202 - South Eastern Sydney</fullName>
            </value>
            <value>
                <fullName>4203 - Southern NSW</fullName>
            </value>
            <value>
                <fullName>4204 - South Western Sydney</fullName>
            </value>
            <value>
                <fullName>4205 - Western NSW</fullName>
            </value>
            <value>
                <fullName>4206 - Western Syd LHN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/PRF__c.object-meta.xml
<CustomObject>
    <label>PRF</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PRF</relationshipLabel>
    <relationshipName>PRF</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Additional_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Additional_Accounts__c</fullName>
    <label>Additional Accounts</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Only Agreement</fullName>
            </value>
            <value>
                <fullName>Rebate Only Agreement</fullName>
            </value>
            <value>
                <fullName>Direct/Rebate Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PRF</relationshipLabel>
    <relationshipName>PRF</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Data_Driven_Justification__c.field-meta.xml
<CustomField>
    <fullName>Data_Driven_Justification__c</fullName>
    <label>Data Driven Justification</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Eligible_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Distributor__c</fullName>
    <label>Eligible Distributor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Estimated_Annual_Purchases__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Annual_Purchases__c</fullName>
    <label>Estimated Annual Purchases</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/GPO_Affiliation__c.field-meta.xml
<CustomField>
    <fullName>GPO_Affiliation__c</fullName>
    <label>GPO Affiliation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Owner_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Owner_Business_Unit__c</fullName>
    <formula>TEXT(Owner:User.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Preferred_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Start_Date__c</fullName>
    <label>Preferred Start Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Requisition_Date__c.field-meta.xml
<CustomField>
    <fullName>Requisition_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Requisition Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>PRF</relationshipLabel>
    <relationshipName>PRF</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/PRF_Line_Item__c.object-meta.xml
<CustomObject>
    <label>PRF Line Item</label>
    <nameField>
        <displayFormat>PRFLI-{0000000}</displayFormat>
        <label>PRF Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRF Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/Material_Name__c.field-meta.xml
<CustomField>
    <fullName>Material_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>PRF Line Items</relationshipLabel>
    <relationshipName>PRF_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/PRF__c.field-meta.xml
<CustomField>
    <fullName>PRF__c</fullName>
    <label>PRF</label>
    <referenceTo>PRF__c</referenceTo>
    <relationshipName>PRF_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/Rep_Price__c.field-meta.xml
<CustomField>
    <fullName>Rep_Price__c</fullName>
    <label>Rep Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/Requested_Price__c.field-meta.xml
<CustomField>
    <fullName>Requested_Price__c</fullName>
    <label>Requested Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/Sales_Deal_Num__c.field-meta.xml
<CustomField>
    <fullName>Sales_Deal_Num__c</fullName>
    <label>Sales Deal #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF_Line_Item__c/fields/SAP_Sold_to__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_to__c</fullName>
    <label>SAP Sold-to</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Rep_Price__c.field-meta.xml
<CustomField>
    <fullName>Rep_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>ZRST</inlineHelpText>
    <label>Rep Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/RSM_Price__c.field-meta.xml
<CustomField>
    <fullName>RSM_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>ZASD</inlineHelpText>
    <label>RSM Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used to concatenate the Territory Number with the Primary Territory User Full Name.</inlineHelpText>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Name__c.field-meta.xml
<CustomField>
    <fullName>Territory_Name__c</fullName>
    <label>Territory Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_PRF_Export.cls
/*********************************************************************
* Description      : Class handles printing of PRFs
* Coverage         : Classes(PP_Global_Test_Class) 
* Author(s)        : Dun Silver, Eric Clay
**********************************************************************/
public class PP_PRF_Export {
    public PRF__c getPRF(){
        return [SELECT Name, Account__r.Name, Status__c, Account__r.SAP_Sold_To__c, Requisition_Date__c,
                Agreement_Type__c, Account__r.BillingStreet, Eligible_Distributor__c,  Account__r.BillingCity,
                Account__r.BillingState, Account__r.BillingPostalCode, Current_Annual_Purchases__c, Contact__r.name,
                Estimated_Annual_Purchases__c, Contact__r.email, Preferred_Start_Date__c, Owner_Full_Name__c,
                Preferred_End_Date__c, Owner_Business_Unit__c, Data_Driven_Justification__c, Additional_Accounts__c,
                Territory__r.Territory_Number__c, Territory__r.Territory_Name__c, GPO_Affiliation__c, Sales_Org_Key__c
                FROM PRF__c
                WHERE id = :ApexPages.currentPage().getParameters().get('id')
                LIMIT 1];
    }

    public list<PRF_Line_Item__c> getPLI(){
        return [SELECT Material_Name__r.Name, Material_Name__r.Description, Sales_Deal_Num__c, Sales_Deal_Description__c,
                Condition__c, CurrencyIsoCode, List_Price__c, Rep_Price__c, RSM_Price__c, Requested_Price__c,
                Eligible_Price__c, Objective_Name__c, Approval_Flag_Reason__c, Approval_Flag_Checkbox__c, Product_Description__c
                FROM PRF_Line_Item__c
                WHERE PRF__c = :ApexPages.currentPage().getParameters().get('id')];
    }


    public String rxls {
        get {
            string temp_name;
            PRF__c prf;
            prf = [Select PRF_Name__c, Sales_Org_Key__c FROM PRF__c WHERE id = :ApexPages.currentPage().getParameters().get('id') LIMIT 1];
            if(ApexPages.currentPage().getParameters().get('id') != NULL){
                temp_name = 'PRF - ' + prf.PRF_Name__c;
                //temp_name += [Select PRF_Name__c, Sales_Org_Key__c FROM PRF__c WHERE id = :ApexPages.currentPage().getParameters().get('id') LIMIT 1].PRF_Name__c;
                if(prf.Sales_Org_Key__c == 'AU1010' || prf.Sales_Org_Key__c == 'NZ1010'){
                    temp_name += ' - ' + datetime.now().format('dd-MM-yyyy');
                }
                else{
                    temp_name += ' - ' + datetime.now().format('MM-dd-yyyy');
                }
                //temp_name += ' - ' + datetime.now().format('MM-dd-yyyy');
                temp_name = temp_name.replaceAll(',', '');
                temp_name += 'application/vnd.ms-excel#' + temp_name + '.xls';
            }
            return temp_name;
        }
        set; }

    //get approval history info
    public List<ProcessInstanceStep> getApprovalInfo(){

      //list to hold Records
      List<ProcessInstanceStep> appInfo = new List<ProcessInstanceStep>();
      /*
      appInfo = [SELECT Id,TargetObjectid, Status, CreatedDate,
               (SELECT Id, Actor.Name FROM Workitems),
               (SELECT Id, StepStatus, Comments, Actor.Name, OriginalActor.Name, CreatedDate FROM Steps ORDER BY CreatedDate ASC)
               FROM ProcessInstance WHERE TargetObjectId =:ApexPages.currentPage().getParameters().get('id')];
      */
      appInfo = [SELECT Id, StepStatus, Comments, Actor.Name, OriginalActor.Name, CreatedDate,
               ProcessInstance.TargetObjectId, ProcessInstance.Status, ProcessInstance.CreatedDate
               FROM ProcessInstanceStep
               WHERE ProcessInstance.TargetObjectId =:ApexPages.currentPage().getParameters().get('id')
               ORDER BY CreatedDate ASC];

      return appInfo;
    }

}