fullSandbox11072023/force-app/main/default/objects/Account/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Main_GPO__c.field-meta.xml
<CustomField>
    <fullName>Main_GPO__c</fullName>
    <inlineHelpText>Primary group purchasing affiliation.</inlineHelpText>
    <label>Primary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Premier Purchasing Partners</fullName>
            </value>
            <value>
                <fullName>MedAssets Supply Chain Systems</fullName>
            </value>
            <value>
                <fullName>Vizient Inc.</fullName>
            </value>
            <value>
                <fullName>HealthTrust Purchasing Group</fullName>
            </value>
            <value>
                <fullName>ROI</fullName>
            </value>
            <value>
                <fullName>FirstChoice Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Secondary_GPO__c.field-meta.xml
<CustomField>
    <fullName>Secondary_GPO__c</fullName>
    <inlineHelpText>The secondary group purchasing organization.</inlineHelpText>
    <label>Secondary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Dignity</fullName>
            </value>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Vizient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/Contract_Customer__c.object-meta.xml
<CustomObject>
    <label>Contract Customer</label>
    <nameField>
        <label>Contract Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Owner_Name__c</fullName>
    <inlineHelpText>GPO Owner Name</inlineHelpText>
    <label>Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/classes/account_GPO_Builder.cls
global class account_GPO_Builder implements Database.Batchable<sObject> {
    
        public String query;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        if(query == NULL){
            //query = 'SELECT Id, SAP_Sold_To__c FROM Account WHERE Id IN (SELECT Account__c FROM Contract_Customer__c)';
            query = 'SELECT Id, SAP_Sold_To__c FROM Account WHERE SAP_Sold_To__c != NULL';    
        }
        system.debug('Starting Batch: ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        //do stuff here
        
        system.debug('-- Starting Build GPO --');
        string sap_Code;
        string gpoStr;
        string condStr;
        
        map<string, string> priMap = new map<string, string>();
        map<string, string> secMap = new map<string, string>();
        set<string> sapset = new set<string>();
        
        List<Account> accs = (List<Account>)scope;
        system.debug('accs: ' + accs);
        
        for(AggregateResult ar : [SELECT SAP_Code__c, Condition__c, Owner_Name__c  
                                  FROM Contract_Customer__c     
                                  WHERE (Condition__c = 'XPRI' OR Condition__c = 'XSEC') 
                                  AND (NOT Agreement__r.Owner_Name__c LIKE '%Teleflex%') 
                                  AND Account__r.Id =:scope 
                                  GROUP BY ROLLUP(SAP_Code__c, Condition__c, Owner_Name__c)])
        {
            If(ar.get('SAP_Code__c') != NULL && (string) ar.get('Owner_Name__c') != NULL){
                gpoStr = (string) ar.get('Owner_Name__c');
                condStr = (string) ar.get('Condition__c');
                sap_Code = (string) ar.get('SAP_Code__c');
                
                //system.debug('sap_Code: ' + sap_Code);
                
                if(condStr == 'XPRI'){
                    priMap.put(sap_Code, gpoStr);
                }
                else if(condStr == 'XSEC'){
                    secMap.put(sap_Code, gpoStr);
                }
                sapset.add(sap_Code);
                system.debug('priMap' + priMap);
                system.debug('secMap' + secMap);
            }
            
        }
        
        list<Account> auplist = new list<Account>();
        for(Account a : [SELECT Id, Main_GPO__c, Secondary_GPO__c 
                         FROM Account 
                         WHERE Id = :accs 
                         //AND (NOT SAP_Sold_To__c IN :sapset) 
                         AND SAP_Sold_To__c != :sapset 
                         AND (Main_GPO__c != NULL OR Secondary_GPO__c != NULL)])
        {
            system.debug('Removing GPOs for Account:' + a.Id);
            Account newacct = new Account(
                Id = a.Id,
                Main_GPO__c = '',
                Secondary_GPO__c = ''
            );
            auplist.add(newacct);
        }
        
        if(sapset.size() > 0){

            boolean needsUpdate;
            for(Account a : [SELECT Id, SAP_Sold_To__c, Main_GPO__c, Secondary_GPO__c   
                             FROM Account 
                             WHERE SAP_Sold_To__c =:sapset])
            {
                needsUpdate = false;
                account aup = new account();
                
                if(priMap.get(a.SAP_Sold_To__c) != NULL){
                    if(priMap.get(a.SAP_Sold_To__c) != a.Main_GPO__c){
                        aup.Main_GPO__c = priMap.get(a.SAP_Sold_To__c);
                        needsUpdate = true;
                        system.debug('Add Primary: ' + priMap.get(a.SAP_Sold_To__c));
                    }
                }
                else if(a.Main_GPO__c != NULL){
                    aup.Main_GPO__c = '';
                    needsUpdate = true;
                    system.debug('Setting Primary to NULL');
                }

                if(secMap.get(a.SAP_Sold_To__c) != NULL){
                    if(secMap.get(a.SAP_Sold_To__c) != a.Secondary_GPO__c){
                        aup.Secondary_GPO__c = secMap.get(a.SAP_Sold_To__c);
                        needsUpdate = true;
                        system.debug('Add Secondary: ' + secMap.get(a.SAP_Sold_To__c));
                    }
                }
                else if(a.Secondary_GPO__c != NULL){
                    aup.Secondary_GPO__c = '';
                    needsUpdate = true;
                    system.debug('Setting Secondary to NULL');
                }

                if(needsUpdate){
                    aup.Id = a.Id;
                    auplist.add(aup);  
                }
            }

        }
        if(auplist.size() > 0){
            system.debug('Updating Accounts! ' + auplist);
            update auplist;
        }
        
        
    }

    global void finish(Database.BatchableContext BC){
        //UserInfo.getUserEmail();
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob 
                          WHERE Id = :BC.getJobId()];
        
        string emailSubj = 'Maintenance [Build Account GPO Primary Secondary]: ' + a.Status;
        string emailBody = 'The batch Apex job processed ' + a.JobItemsProcessed + ' batches with '+ a.NumberOfErrors + ' failures.';
        
        String obj = 'Contract_Customer__c';
        Global_Maintenance gm = new Global_Maintenance();
        list<String> emailList = gm.getEmailList(obj);
        if(emailList.size() > 0){
            system.debug('Sending Email Now!');
            gm.sendEmailHelper(emailSubj,emailBody,emailList);
        }
        
        /*
        
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {a.CreatedBy.Email};
            mail.setToAddresses(toAddresses);
        mail.setSubject('Build Account GPO Primary Secondary Job: ' + a.Status);
        mail.setPlainTextBody
            ('The batch Apex job processed ' + a.JobItemsProcessed +
             ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); */
    }
}