fullSandbox11072023/force-app/main/default/objects/Account/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>2 Digit Customer Group Number.</inlineHelpText>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Main_GPO__c.field-meta.xml
<CustomField>
    <fullName>Main_GPO__c</fullName>
    <inlineHelpText>Primary group purchasing affiliation.</inlineHelpText>
    <label>Primary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Premier Purchasing Partners</fullName>
            </value>
            <value>
                <fullName>MedAssets Supply Chain Systems</fullName>
            </value>
            <value>
                <fullName>Vizient Inc.</fullName>
            </value>
            <value>
                <fullName>HealthTrust Purchasing Group</fullName>
            </value>
            <value>
                <fullName>ROI</fullName>
            </value>
            <value>
                <fullName>FirstChoice Cooperative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account_Status__c</fullName>
    <formula>CASE(zBlock__c, 
&quot;00&quot;, &quot;Active&quot;, 
&quot;01&quot;, &quot;Credit Block&quot;,
&quot;02&quot;, &quot;Overall Block&quot;,
&quot;Z1&quot;, &quot;Pending Deletion&quot;,
&quot;Z2&quot;, &quot;Finance Block&quot;,
&quot;Z3&quot;, &quot;Pending Review&quot;,
&quot;ERROR&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Account Status</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Secondary_GPO__c.field-meta.xml
<CustomField>
    <fullName>Secondary_GPO__c</fullName>
    <inlineHelpText>The secondary group purchasing organization.</inlineHelpText>
    <label>Secondary GPO</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amerinet</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>HPG</fullName>
            </value>
            <value>
                <fullName>MedAssets</fullName>
            </value>
            <value>
                <fullName>Novation</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Ascension</fullName>
            </value>
            <value>
                <fullName>Dignity</fullName>
            </value>
            <value>
                <fullName>Intralere</fullName>
            </value>
            <value>
                <fullName>Vizient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/Contract_Customer__c.object-meta.xml
<CustomObject>
    <label>Contract Customer</label>
    <nameField>
        <label>Contract Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Customers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Customers</relationshipLabel>
    <relationshipName>Contract_Customers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Customer__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c  &gt;=  TODAY() &amp;&amp; Valid_From__c  &lt;=  TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/Contract_Renewal__c.object-meta.xml
<CustomObject>
    <label>Contract Renewal</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Contract Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Renewals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DNU_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>DNU_Condition</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Contract_Customer__c.field-meta.xml
<CustomField>
    <fullName>Contract_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DNU_Contract Customer</label>
    <referenceTo>Contract_Customer__c</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Contract_Header__c.field-meta.xml
<CustomField>
    <fullName>Contract_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Header</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Renewals</relationshipLabel>
    <relationshipName>Contract_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <formula>if(Customer_Group__c = &quot;01&quot;, &quot;Buying Group/GPO&quot;,
if(Customer_Group__c = &quot;02&quot;, &quot;Dist/Dlr Emg Med Svc&quot;,
if(Customer_Group__c = &quot;03&quot;, &quot;Dist/Dlr Homecare&quot;,
if(Customer_Group__c = &quot;04&quot;, &quot;Dist/Dlr Acute Care&quot;,
if(Customer_Group__c = &quot;05&quot;, &quot;Dist/Dlr Kit Packer&quot;,
if(Customer_Group__c = &quot;06&quot;, &quot;Dist/Dlr Nursing Hm&quot;,
if(Customer_Group__c = &quot;07&quot;, &quot;Dist/Dlr Other&quot;,
if(Customer_Group__c = &quot;08&quot;, &quot;Dist/Dlr Physician&quot;,
if(Customer_Group__c = &quot;09&quot;, &quot;Dist/Dlr Third Party&quot;,
if(Customer_Group__c = &quot;10&quot;, &quot;Dist/Dlr Veterinary&quot;,
if(Customer_Group__c = &quot;11&quot;, &quot;Dist/Dlr Wholesaler&quot;,
if(Customer_Group__c = &quot;12&quot;, &quot;Dom Dist for Export&quot;,
if(Customer_Group__c = &quot;13&quot;, &quot;Emergency Med Svcs&quot;,
if(Customer_Group__c = &quot;14&quot;, &quot;Government&quot;,
if(Customer_Group__c = &quot;15&quot;, &quot;Health Insurance&quot;,
if(Customer_Group__c = &quot;16&quot;, &quot;Hosp-Private&quot;,
if(Customer_Group__c = &quot;17&quot;, &quot;Hosp-Public&quot;,
if(Customer_Group__c = &quot;18&quot;, &quot;Hosp-Rehabilitation&quot;,
if(Customer_Group__c = &quot;19&quot;, &quot;Hosp-University&quot;,
if(Customer_Group__c = &quot;20&quot;, &quot;Hosp-Veteran Affairs&quot;,
if(Customer_Group__c = &quot;21&quot;, &quot;Hosp/Ctr-Veterinary&quot;,
if(Customer_Group__c = &quot;23&quot;, &quot;Industry/Competitor&quot;,
if(Customer_Group__c = &quot;24&quot;, &quot;Institution&quot;,
if(Customer_Group__c = &quot;25&quot;, &quot;Inter-company&quot;,
if(Customer_Group__c = &quot;26&quot;, &quot;International/Export&quot;,
if(Customer_Group__c = &quot;27&quot;, &quot;OEM House Account&quot;,
if(Customer_Group__c = &quot;28&quot;, &quot;Nursing Home&quot;,
if(Customer_Group__c = &quot;29&quot;, &quot;Orig Equip Mfg (OEM)&quot;,
if(Customer_Group__c = &quot;30&quot;, &quot;Other&quot;,
if(Customer_Group__c = &quot;31&quot;, &quot;Outpatient/Surg Ctr&quot;,
if(Customer_Group__c = &quot;32&quot;, &quot;Patient/End-User&quot;,
if(Customer_Group__c = &quot;33&quot;, &quot;Pharmacy&quot;,
if(Customer_Group__c = &quot;34&quot;, &quot;Physician/Doctor&quot;,
if(Customer_Group__c = &quot;35&quot;, &quot;Private Label NonOEM&quot;,
if(Customer_Group__c = &quot;36&quot;, &quot;Sales and Marketing&quot;,
if(Customer_Group__c = &quot;38&quot;, &quot;Sleep Lab&quot;,
if(Customer_Group__c = &quot;39&quot;, &quot;Samples&quot;,
if(Customer_Group__c = &quot;40&quot;, &quot;Canada&quot;,
if(Customer_Group__c = &quot;41&quot;, &quot;Dental/Oral Surgery&quot;,
&quot;&quot;
))))))))))
))))))))))
))))))))))
)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Group Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Renewal__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <label>Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/contract_Renewal_Accounts.cls
/*********************************************************************
* Description      : Class provides detail analysis of Accounts/Contracts.
* Test Class       : Contract_Renewal_Test
* VisualForce      : contract_Renewal_Accounts
* Author(s)        : Eric Clay
**********************************************************************/
public class contract_Renewal_Accounts {

    public Contract_Renewal__c cr {get; set;}
    public list<Contract_Customer__c> alist {get; set;}
    public string fname {get; set;}
    public string cid {get; set;}

    public contract_Renewal_Accounts(){
        //Agreement_Number__c = :Apexpages.currentPage().getParameters().get('id')
        cr = new Contract_Renewal__c();
        alist = new list<Contract_Customer__c>();

        if(Apexpages.currentPage().getParameters().get('Id') != NULL){
            cid = Apexpages.currentPage().getParameters().get('Id');
            cr = [SELECT Contract_Header__r.Agreement_Number__c, Contract_Header__r.Description__c
                  FROM Contract_Renewal__c
                  WHERE Id =:cid];
            System.debug('*** cr *** ' + cr);
            //fname = cr.Contract_Header__r.Agreement_Number__c + '-' + cr.Contract_Header__r.Description__c + '-';
            fname = cr.Contract_Header__r.Agreement_Number__c + '-Customers-';
            fname += datetime.now().format('MM-dd-yyyy');

            for(Contract_Customer__c cc : [SELECT Account__r.Id, Account__r.name, Account__r.SAP_Sold_To__c, Condition__c, Account__r.BillingStreet,
                                           Account__r.BillingCity, Account__r.BillingState, Account__r.BillingCountry, Account__r.BillingPostalCode,
                                           Customer_Group__c, Customer_Group_Name__c, Account__r.SAP_Account_Status__c, Account__r.Type,
                                           Account__r.Secondary_GPO__c, Account__r.Main_GPO__c, Sales__c
                                           FROM Contract_Customer__c
                                           WHERE Active__c = TRUE
                                           AND Agreement_Number__c = :cr.Contract_Header__r.Agreement_Number__c
                                           ORDER BY Account__r.name])
            {
                alist.add(cc);
            }
            System.debug('*** alist *** ' + alist);
        }


    }

}