fullSandbox11072023/force-app/main/default/objects/Account/fields/ERP_Active__c.field-meta.xml
<CustomField>
    <fullName>ERP_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is updated as part of the Daily Data Load from the ERP system. Any Active Customers will have a Value of True (checked).</description>
    <inlineHelpText>When this box is checked, the account is an active customer in the ERP System.</inlineHelpText>
    <label>Active in SAP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/zBlock__c.field-meta.xml
<CustomField>
    <fullName>zBlock__c</fullName>
    <label>zBlock</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Account__c/Territory_Account__c.object-meta.xml
<CustomObject>
    <label>Territory Account</label>
    <nameField>
        <displayFormat>Terr-{0000000}</displayFormat>
        <label>Territory Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Territories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Account__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory Number</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Accounts</relationshipLabel>
    <relationshipName>Territory_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/Territory_User__c.object-meta.xml
<CustomObject>
    <label>Territory User</label>
    <nameField>
        <displayFormat>TU-{0000000}</displayFormat>
        <label>Territory User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Master__c.field-meta.xml
<CustomField>
    <fullName>Territory_Master__c</fullName>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Users</relationshipLabel>
    <relationshipName>Territory_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/Territory_Number__c.field-meta.xml
<CustomField>
    <fullName>Territory_Number__c</fullName>
    <externalId>true</externalId>
    <label>Territory Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/AcctTeamBatchTest.cls
@isTest
public class AcctTeamBatchTest {
    static testMethod void testAcctTeamBatch(){
        
        Territory_Master__c tm = new Territory_Master__c(Name='900130', Territory_Number__c='900130');
        insert tm;
        
        Profile p = [SELECT Id FROM Profile WHERE Id='00eE0000000lT3QIAU'];
        User u = new User(Username='trey.flowers@teleflex.com.testing1',Email='trflowers@teleflex.com',Lastname='User', Firstname='Test', Alias='tuser',emailencodingkey='UTF-8',languagelocalekey='en_US',localesidkey='en_US', profileid=p.Id,timezonesidkey='America/New_York');
        insert u;
        
        Territory_User__c tu = new Territory_User__c(User__c=u.Id,Territory_Master__c=tm.Id);
        insert tu;
        
        Account a = new Account(Name='Test Account ', zBlock__c ='00', ERP_Active__c= true);
        insert a;
        
        Territory_Account__c ta = new Territory_Account__c(Account__c=a.Id, Territory_Master__c=tm.Id);
        insert ta;
        
        //AccountTeamMember check1 = [SELECT UserId FROM AccountTeamMember WHERE AccountId= :a.Id];
        //System.assertEquals(u.Id,check1.UserId);

        //clearAcctTeams clear = new clearAcctTeams();
        //ID batchprocessid1 = Database.executeBatch(clear);
        
        //delete check1;
        
        BatchAcctTeamAssignment assign = new BatchAcctTeamAssignment();
        ID batchprocessid2 = Database.executeBatch(assign);

    }
}