fullSandbox11072023/force-app/main/default/objects/Account/fields/ERP_Active__c.field-meta.xml
<CustomField>
    <fullName>ERP_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is updated as part of the Daily Data Load from the ERP system. Any Active Customers will have a Value of True (checked).</description>
    <inlineHelpText>When this box is checked, the account is an active customer in the ERP System.</inlineHelpText>
    <label>Active in SAP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Last_SAP_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_SAP_Update__c</fullName>
    <label>Last SAP Update</label>
    <type>DateTime</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/zBlock__c.field-meta.xml
<CustomField>
    <fullName>zBlock__c</fullName>
    <label>zBlock</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Customer_Master_Reference__c/Customer_Master_Reference__c.object-meta.xml
<CustomObject>
    <label>Customer Master Reference</label>
    <nameField>
        <label>Customer Master Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Master Reference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Customer_Master_Reference__c/fields/Last_SAP_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_SAP_Update__c</fullName>
    <label>Last SAP Update</label>
    <type>DateTime</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Customer_Master_Reference__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Customer_Master_Reference__c/fields/zBlock__c.field-meta.xml
<CustomField>
    <fullName>zBlock__c</fullName>
    <label>zBlock</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Customer_Master_Reference_Helper_Class.cls
public class Customer_Master_Reference_Helper_Class {
    public static void checkZblock(List<Customer_Master_Reference__c> newTrigger){
        // Ensures that the Account Table is in sync with the Customer Master Reference
        // 27Sept2017 - ESC
        // Test Class: account_Page_Helper_Test (94%)
        map<String, String> zFix = new map<String, String>();
        list<Account> aList = new list<Account>();
        
        for(Customer_Master_Reference__c cmr : newTrigger){
            zFix.put(cmr.SAP_Code__c, cmr.zBlock__c);
        }
        
        for(Account a : [SELECT Id, SAP_Sold_To__c, zBlock__c
                         FROM Account 
                         WHERE SAP_Sold_To__c = :zFix.keySet()])
        {
            if(zFix.containsKey(a.SAP_Sold_To__c) && a.zBlock__c != zFix.get(a.SAP_Sold_To__c)){
                Account updateAcct = new Account(
                    Id = a.Id,
                    zBlock__c = zFix.get(a.SAP_Sold_To__c),
                    Last_SAP_Update__c = datetime.now()
                );
                // Making sure that the account is properly flagged active or not.
                if(zFix.get(a.SAP_Sold_To__c) == '00'){
                    updateAcct.ERP_Active__c = TRUE;
                }
                else{
                    updateAcct.ERP_Active__c = FALSE;
                }
                aList.add(updateAcct);
            }
        }
        if(aList.size() > 0){
            update aList;
        }
    }
}