fullSandbox11072023/force-app/main/default/objects/Account/fields/ERP_Active__c.field-meta.xml
<CustomField>
    <fullName>ERP_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field is updated as part of the Daily Data Load from the ERP system. Any Active Customers will have a Value of True (checked).</description>
    <inlineHelpText>When this box is checked, the account is an active customer in the ERP System.</inlineHelpText>
    <label>Active in SAP</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_by_BU_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_by_BU_Key__c</fullName>
    <label>Sales by BU Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <customHelpPage>Complaints_Help</customHelpPage>
    <label>Complaint</label>
    <nameField>
        <displayFormat>SF{000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the name of the account where the event occurred.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Active_Sales__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>Complaints with No Customer Generic Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Active_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>Accounts with sales are displayed in this window.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Complaints</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Complaint_submitted_within_24_hours_of_T__c.field-meta.xml
<CustomField>
    <fullName>Complaint_submitted_within_24_hours_of_T__c</fullName>
    <label>Submitted w/in 24 Hrs of TFX Aware Date</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <inlineHelpText>Provide the name of a person at the account that can be contacted about this event.</inlineHelpText>
    <label>Contact Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Contact_Title__c.field-meta.xml
<CustomField>
    <fullName>Contact_Title__c</fullName>
    <label>Contact Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Customer_response_letter_requested__c.field-meta.xml
<CustomField>
    <fullName>Customer_response_letter_requested__c</fullName>
    <inlineHelpText>Did the customer request a written response with the complaint investigation results?</inlineHelpText>
    <label>Customer response letter requested?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <inlineHelpText>Use this field if the exact Event Date is known. If the exact Event Date is not known, please use the Estimated Event Date field instead. Do not fill in both the Event Date and the Estimated Event Date- only one field should be used.</inlineHelpText>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Issue_Incident_Description__c.field-meta.xml
<CustomField>
    <fullName>Issue_Incident_Description__c</fullName>
    <description>Describe the alleged quality issue/incident in DETAIL (Explain who, what, where, when, how)</description>
    <inlineHelpText>Describe the alleged quality issue/incident in DETAIL (Explain who, what, where, when, how)</inlineHelpText>
    <label>Issue/Incident Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Lot_Number_Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Lot_Number_Action_Taken__c</fullName>
    <inlineHelpText>Use the drop down list to choose the action taken to find out the lot number and serial number for the complaint product.</inlineHelpText>
    <label>Action Taken to Acquire Lot # / Serial #</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Called</fullName>
            </value>
            <value>
                <fullName>Emailed</fullName>
            </value>
            <value>
                <fullName>Requested on-site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Patient_exposed_to_infectious_disease__c.field-meta.xml
<CustomField>
    <fullName>Patient_exposed_to_infectious_disease__c</fullName>
    <inlineHelpText>i.e. Ebola, MRSA, Hepatitis Note: If yes, please do not return the device but provide images/photos indicating the reported alleged issue</inlineHelpText>
    <label>Patient exposed to infectious disease?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>How_the_product_was_being_used__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Patients_Current_Condition__c.field-meta.xml
<CustomField>
    <fullName>Patients_Current_Condition__c</fullName>
    <inlineHelpText>Select the patient&apos;s condition at the end of the reported event or procedure.</inlineHelpText>
    <label>Patient&apos;s Condition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>How_the_product_was_being_used__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Fine</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Product_List__c.field-meta.xml
<CustomField>
    <fullName>Product_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product_List__c</referenceTo>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Units_with_Alleged_Issue__c.field-meta.xml
<CustomField>
    <fullName>Units_with_Alleged_Issue__c</fullName>
    <label># Units with Alleged Issue</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product_List__c/Product_List__c.object-meta.xml
<CustomObject>
    <label>Complaint Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/classes/complaints_update_test.cls
@isTest
public class complaints_update_test {

    public static testMethod void testOptOut(){
        
        Account a = new account(
            Name = 'Test',
            Sales_by_BU_Key__c = 'Has Sales',
             ERP_Active__c = TRUE
        );
        insert a;
        
        Product_List__c p = new Product_List__c (
            Name = '000-11'
        );
        insert p;
        
        Complaint__c c = new Complaint__c(
            Event_Date__c = date.today(),
            Units_with_Alleged_Issue__c = 1,
            Lot_Number_Action_Taken__c = 'Called',
            Issue_Incident_Description__c = 'Test',
            Patients_Current_Condition__c = 'Fine',
            Patient_exposed_to_infectious_disease__c = 'No',
            Contact_Name__c = 'Test User',
            Contact_Title__c = 'Director',
            Contact_Email__c = 'abc@123.com',
            Account__c = a.Id,
            Product_List__c = p.Id,
            Customer_response_letter_requested__c = 'Yes',
            Complaint_submitted_within_24_hours_of_T__c= 'Yes'
        );
        
        insert c;
        
        PageReference pageRef = new PageReference('/complaints_update?id=' + c.id );
        Test.setCurrentPage(pageRef);
        
        complaints_update controller = new complaints_update();
        
        complaints_update tc = new complaints_update();
        tc.save();
        tc.getComplaints();
        tc.cancel();
        
    }
    
    


    
    

    
    
}