fullSandbox11072023/force-app/main/default/objects/Account/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Central America - North Cone</fullName>
            </value>
            <value>
                <fullName>Southern Cone</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>US Exports</fullName>
            </value>
            <value>
                <fullName>Caribbean</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Order_Transaction__c/LATAM_Order_Transaction__c.object-meta.xml
<CustomObject>
    <label>LATAM Order Transaction</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>LATAM Order Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LATAM Order Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/LATAM_Order_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LATAM Order Transactions</relationshipLabel>
    <relationshipName>LATAM_Order_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Order_Transaction__c/fields/Product_Family1__c.field-meta.xml
<CustomField>
    <fullName>Product_Family1__c</fullName>
    <label>Product Family</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Order_Transaction__c/fields/Quarter1__c.field-meta.xml
<CustomField>
    <fullName>Quarter1__c</fullName>
    <label>Quarter1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Order_Transaction__c/fields/Required_Date__c.field-meta.xml
<CustomField>
    <fullName>Required_Date__c</fullName>
    <label>Required Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Order_Transaction__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_RR_Products__c/LATAM_RR_Products__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rainbow Report Business Units</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/LATAM_RR_Regions__c/LATAM_RR_Regions__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rainbow Report Regions</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Latam_Sales_Transactions__c/Latam_Sales_Transactions__c.object-meta.xml
<CustomObject>
    <description>This object is used to create the Latam Rainbow Report</description>
    <label>LATAM Sales Transaction</label>
    <nameField>
        <displayFormat>RR - {00000}</displayFormat>
        <label>Latam Sales Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LATAM Sales Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Latam_Sales_Transactions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LATAM Sales Transactions</relationshipLabel>
    <relationshipName>LATAM_Sales_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Latam_Sales_Transactions__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Latam_Sales_Transactions__c/fields/Product_Family1__c.field-meta.xml
<CustomField>
    <fullName>Product_Family1__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Cardiac</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>LMA</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Latam_Sales_Transactions__c/fields/Quarter1__c.field-meta.xml
<CustomField>
    <fullName>Quarter1__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Latam_Sales_Transactions__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <label>SAP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Target__c/LATAM_Target__c.object-meta.xml
<CustomObject>
    <description>This object is used when loading the target data for the rainbow report.  Targets should be loaded in thousands (000&apos;s).</description>
    <label>LATAM Sales Goal</label>
    <nameField>
        <displayFormat>RRT-{00000}</displayFormat>
        <label>LATAM Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LATAM Sales Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/LATAM_Target__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LATAM Sales Goals</relationshipLabel>
    <relationshipName>LATAM_Sales_Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Target__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <label>Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Target__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Cardiac</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>LMA</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Target__c/fields/Target_Amount__c.field-meta.xml
<CustomField>
    <fullName>Target_Amount__c</fullName>
    <label>Target Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/LATAM_Target__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Latam_rr_test.cls
@isTest
private class Latam_rr_test {
    static testmethod void myUnitTest() {

        LATAM_RR_Regions__c newLATAM_RR_Region = new LATAM_RR_Regions__c(
            Name = 'Brazil'
        );
        insert newLATAM_RR_Region;
        
        LATAM_RR_Products__c newLATAM_RR_Product = new LATAM_RR_Products__c(
            Name = 'Anesthesia'
        );
        insert newLATAM_RR_Product;
        
        Account a = new Account(
            Name = 'Test Latam__RR Account',
            SAP_Sold_To__c ='111111',
            Sales_Region__c ='Brazil',
            BillingCountry = 'BR'
        );
        insert a;
        system.debug('a:' + a);

        date yearDate = date.today().addDays(-365);//setting as 2018
        string yearStr = string.valueOf(yearDate.year());
        
        LATAM_Target__c lgt = new LATAM_Target__c (
            Account__c = a.id,
            Account_Name__c = a.Name,
            Account_ID__c = a.id,
            Sales_Region__c ='Brazil',
            Product_Family__c = 'Anesthesia',
            Target_Amount__c = 10000,
            Year__c = yearStr
        );
        insert lgt;
        system.debug('lgt:' + lgt);

        Latam_Sales_Transactions__c lst = new Latam_Sales_Transactions__c (
            Account__c = a.id,
            Account_ID__c = a.id,
            Account_Name__c = a.Name,
            Sales_Region__c ='Brazil',
            Product_Family1__c = 'Anesthesia',
            Transaction_Amount__c = 2000,
            Transaction_Date__c = System.Today().addDays(-365),//setting as 2018
            SAP_Code__c = a.SAP_Sold_to__c,
            Quarter1__c = 'Q1'
        );
        insert lst;
        system.debug('lst:' + lst);

        LATAM_Order_Transaction__c  lot = new  LATAM_Order_Transaction__c (
            Account__c = a.id,
            Account_ID__c = a.id,
            Account_Name__c = a.Name,
            Sales_Region__c ='Brazil',
            Product_Family1__c = 'Anesthesia',
            Transaction_Amount__c = 3000,
            Required_Date__c = System.Today().addDays(-365),//setting as 2018
            Quarter1__c = 'Q1'
        );
        insert lot;
        system.debug('lot:' + lot);

        // Start Test
        Test.startTest();
        PageReference pageRef = new PageReference('/apex/Latam_rr');
        Test.setCurrentPage(pageRef);
        Test.setReadOnlyApplicationMode(true);

        LATAM_RR testcontroller = new LATAM_RR();

        testcontroller.getmegamap();
        testcontroller.getaccts();
        testcontroller.getpgs();
        testcontroller.getRegions();


        PageReference pageRef1 = new PageReference('/apex/Latam_rr_Outlook');
        Test.setCurrentPage(pageRef1);
        Test.setReadOnlyApplicationMode(true);

        LATAM_RR_Outlook testcontroller1 = new LATAM_RR_Outlook();
        testcontroller1.getmegamap();
        testcontroller1.getaccts();
        testcontroller1.getpgq();
        testcontroller1.getpgs();
        testcontroller1.getRegions();
        Test.stopTest();

    }
}