fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product_Tracking__c/Product_Tracking__c.object-meta.xml
<CustomObject>
    <description>To support product tracking with Accounts and Marketing Campaigns</description>
    <label>Product Tracking</label>
    <nameField>
        <label>Product Tracking ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Product_Tracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Tracking</relationshipLabel>
    <relationshipName>Product_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product_Tracking__c/fields/Product_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_of_Interest__c</fullName>
    <label>Product of Interest Old</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Product_Family__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1605 Filters</fullName>
            </value>
            <value>
                <fullName>1A</fullName>
            </value>
            <value>
                <fullName>3 Lumen PICC</fullName>
            </value>
            <value>
                <fullName>780 Circuit Kits</fullName>
            </value>
            <value>
                <fullName>AC2 Pumps</fullName>
            </value>
            <value>
                <fullName>AC3 Pumps</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Active Humidification</fullName>
            </value>
            <value>
                <fullName>Acute Double Lumen Catheter</fullName>
            </value>
            <value>
                <fullName>Acute Hemodialysis</fullName>
            </value>
            <value>
                <fullName>Acute Hemodialysis AGB+</fullName>
            </value>
            <value>
                <fullName>Acute Triple Lumen Catheter</fullName>
            </value>
            <value>
                <fullName>Adaptors &amp; Connectors</fullName>
            </value>
            <value>
                <fullName>AE-05</fullName>
            </value>
            <value>
                <fullName>AE-10</fullName>
            </value>
            <value>
                <fullName>AE5</fullName>
            </value>
            <value>
                <fullName>Aerosol Therapy</fullName>
            </value>
            <value>
                <fullName>Airtraq</fullName>
            </value>
            <value>
                <fullName>AKP1A</fullName>
            </value>
            <value>
                <fullName>Alligator Grasper</fullName>
            </value>
            <value>
                <fullName>Ambit Pump</fullName>
            </value>
            <value>
                <fullName>Appliers</fullName>
            </value>
            <value>
                <fullName>Arrow Midline with Chlorag+ard</fullName>
            </value>
            <value>
                <fullName>Arrow PICC (A5)</fullName>
            </value>
            <value>
                <fullName>Arrow PICC with Chlorag+ard</fullName>
            </value>
            <value>
                <fullName>Atomization</fullName>
            </value>
            <value>
                <fullName>Autofuser</fullName>
            </value>
            <value>
                <fullName>Babcock Grasper</fullName>
            </value>
            <value>
                <fullName>Berci Passer</fullName>
            </value>
            <value>
                <fullName>Berman Catheters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product_Tracking__c/fields/Product_of_Interest_GPL__c.field-meta.xml
<CustomField>
    <fullName>Product_of_Interest_GPL__c</fullName>
    <label>Product of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Family_GPL__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Product_of_Interest_GPL</valueSetName>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product_Tracking__c/fields/Product_of_Interest_Sort__c.field-meta.xml
<CustomField>
    <fullName>Product_of_Interest_Sort__c</fullName>
    <label>Product of Interest (Sort)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product_Tracking__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <label>SAP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Product_Tracking_Helper_Class.cls
public class Product_Tracking_Helper_Class {
    
    public static void addAccount(List<Product_Tracking__c> newTrigger){
        // Test Class: account_Page_Helper_Test
        set<String> sapSet = new set<String>();
        map<String, Id> sapMap = new map<String, Id>();
        
        for(Product_Tracking__c pt : newTrigger){
            if(pt.SAP_Code__c != NULL){
                sapSet.add(pt.SAP_Code__c);
            }
        }
        
        if(sapSet.size() > 0){
            for(Account a : [SELECT Id, SAP_Sold_To__c 
                             FROM Account 
                             WHERE SAP_Sold_To__c =:sapSet])
            {
                sapMap.put(a.SAP_Sold_To__c , a.Id);
            }
            for(Product_Tracking__c pt : newTrigger){
                if(sapMap.get(pt.SAP_Code__c) != NULL){
                    pt.Account__c = sapMap.get(pt.SAP_Code__c);
                }
            }
        }
    }
    // Added Support for Global Picklist - Archana 20Jun2017
    public static void setProductOfInterest(List<Product_Tracking__c> newTrigger, Map<Id,Product_Tracking__c> oldTrigger,String type){        
        // Test Class: account_Page_Helper_Test 
        list<Product_Tracking__c> updateProductTracking = new list<Product_Tracking__c>();
        string poiList;
        string poi;
        boolean upd;
        
        for(Product_Tracking__c P : newTrigger){
            
            system.debug('Starting Product of Interest Class');
            upd = FALSE;
            if(type == 'insert' && (P.Product_of_Interest__c != NULL || P.Product_of_Interest_GPL__c != NULL)){
                upd = TRUE;
            }
            // Check to see if the automation has never run or the values have changed.
            else if( 
                type == 'update' &&
                P.Product_of_Interest_GPL__c != NULL &&
                (oldTrigger.get(P.Id).Product_of_Interest_GPL__c != P.Product_of_Interest_GPL__c
                 || P.Product_of_Interest_Sort__c == NULL))
            {
                upd = TRUE;
                system.debug('Lets update!');
            }
            else if(
                type == 'update' &&
                P.Product_of_Interest__c != NULL &&
                (oldTrigger.get(P.Id).Product_of_Interest__c != P.Product_of_Interest__c
                 || P.Product_of_Interest_Sort__c == NULL))
            {
                upd = TRUE;
                system.debug('Lets update!');
            }
            if(upd){
                // Prioritize the New Field over the old
                if(P.Product_of_Interest_GPL__c != NULL){
                    Product_Tracking__c uPOI = new Product_Tracking__c(
                        Id = P.Id,
                        Product_of_Interest_Sort__c = P.Product_of_Interest_GPL__c
                    );
                    updateProductTracking.add(uPOI);
                }
                else{
                    // Let's Alphabitize
                    poiList = P.Product_of_Interest__c;
                    List<String> sortedvalue = poiList.split(';');
                    sortedvalue.sort();
                    
                    poi = '';
                    for(string s : sortedvalue){
                        if(poi == ''){
                            poi = s;
                        }
                        else{
                            poi = poi + ', ' + s;
                        }
                    }
                    // Make sure it will fit...
                    poi = poi.left(255);
                    
                    // DML
                    Product_Tracking__c uPOI = new Product_Tracking__c(
                        Id = P.Id,
                        Product_of_Interest_Sort__c = poi
                    );
                    updateProductTracking.add(uPOI);
                }
                
            }//end of if(upd)
            
            if(updateProductTracking.size() > 0){
                system.debug('Updating Product of Interest Sort!');
                
                try {
                    update updateProductTracking;
                }
                catch (Exception e) {
                    System.debug('The following exception has occurred: ' + e.getMessage());
                }
                
            }//end of if updateProductTracking.size
            
            
        }//end of for loop
        system.debug('END Product of Interest Class');
    }//End of setProductOfInterest - Archana
    
}//End of class