fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>Territory_Key__c</fullName>
    <description>Territory_Key__c is built every day as part of the daily Invoiced Sales ETL. 
Apex: account_Active_Sales
Scheduled Apex: Invoiced_Sales_Maintenance_Scheduler</description>
    <inlineHelpText>List of Territory Numbers that have Sales related to this Account.</inlineHelpText>
    <label>Territory Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/MANTA_Proctorship_Request__c.object-meta.xml
<CustomObject>
    <label>MANTA Proctorship Request</label>
    <nameField>
        <displayFormat>MPR-{00000}</displayFormat>
        <label>MANTA Proctorship Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MANTA Proctorship Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Case_Initiator__c.field-meta.xml
<CustomField>
    <fullName>Case_Initiator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Initiator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MANTA_Proctorship_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Estimated_of_Cases__c.field-meta.xml
<CustomField>
    <fullName>Estimated_of_Cases__c</fullName>
    <label>Estimated # of Cases</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MANTA Proctorship Requests</relationshipLabel>
    <relationshipName>MANTA_Proctorship_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Proctor__c.field-meta.xml
<CustomField>
    <fullName>Proctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MANTA_Proctorship_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/MANTARequestCaseDataRecsBatch_Test.cls
@IsTest
public class MANTARequestCaseDataRecsBatch_Test {
    
    
    @isTest static void testBatch() {
        
        Profile p = [select id from profile where name='System Administrator'];
        
        User u = new User(
            alias = 'uflex76',
            email='unit.test@unit.teleflex.com',
            emailencodingkey='UTF-8',
            firstname='Adam',
            lastname='Franks',
            languagelocalekey='en_US',
            localesidkey='en_GB',
            profileid = p.Id,
            timezonesidkey='Europe/London',
            username='unit.test@unit.teleflex.com'
        );
        insert u;
        
        Account acc = new Account();
        acc.Name = 'CXTestAcc';
        acc.SAP_Sold_To__c = '123456';
        acc.SAP_Code__c='123456';
        acc.Territory_Key__c='123456;234567';
        insert acc;
        
        MANTA_Proctorship_Request__c mantaProcReqObj = new MANTA_Proctorship_Request__c();
        mantaProcReqObj.Case_Date__c = System.Today() - 10;
        mantaProcReqObj.Case_Initiator__c = u.Id;
        mantaProcReqObj.Proctor__c = u.Id;
        mantaProcReqObj.Case_Type__c = 'TVAR';
        mantaProcReqObj.Estimated_of_Cases__c = 3.0;
        mantaProcReqObj.Hospital__c = acc.Id;
        mantaProcReqObj.Status__c = 'Accepted';
        insert mantaProcReqObj;
        
   Test.startTest();
     MANTARequestCaseDataRecsBatch batch = new  MANTARequestCaseDataRecsBatch();
        database.executebatch(batch,200);  
    
    String sch='0 0 0 ? * * *';
		String jobId = System.schedule('MANTARequestCaseDataRecsBatchSchdl Schedule', sch , batch);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        System.assertEquals(0, ct.TimesTriggered);
    
    Test.stopTest();
        List<MANTA_Proctorship_Request__c> mntaProcReqObj = [SELECT Id from MANTA_Proctorship_Request__c];
        system.assertEquals(1, mntaProcReqObj.size());
    }
    
 
}