fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/Contract_Partnership__c.object-meta.xml
<CustomObject>
    <label>Contract Partnership</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Contract Partnership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Partnerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Relationship that is valid but for whatever reason we need to have filtered out.</inlineHelpText>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Sale_to__c.field-meta.xml
<CustomField>
    <fullName>Sale_to__c</fullName>
    <label>Sold-to</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Partnership__c/fields/Ship_to__c.field-meta.xml
<CustomField>
    <fullName>Ship_to__c</fullName>
    <label>Ship-to</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Contract_Partnership_Helper_Class.cls
public class Contract_Partnership_Helper_Class {
    
    public static void validateAccount(List<Contract_Partnership__c> newTrigger){
        map<String, Boolean> accountCheck = new map<String, Boolean>();
        
        for(Contract_Partnership__c cp : newTrigger){
            accountCheck.put(cp.Ship_to__c, FALSE);
            accountCheck.put(cp.Sale_to__c, FALSE);
        }
        
        System.debug('*** accountCheck.size() *** ' + accountCheck.size() );
        System.debug('*** accountCheck *** ' + accountCheck );
        List<Account> accountList = new List<Account>();
        if(accountCheck.size() > 0 ){
            System.debug('*** Contract_Partnership_Helper_Class validateAccount accountList.size > 0 ***');
            accountList = [SELECT Id, SAP_Sold_To__c 
                         FROM Account
                         WHERE SAP_Sold_To__c =:accountCheck.keySet()];
        
            for(Account a : accountList)
            {
                accountCheck.put(a.SAP_Sold_To__c, TRUE);
            }
            
            for(Contract_Partnership__c cp : newTrigger){
                if(accountCheck.get(cp.Ship_to__c) == FALSE){
                    cp.Ship_to__c = NULL;
                    cp.Disabled__c = TRUE;
                }
                else if(accountCheck.get(cp.Sale_to__c) == FALSE){
                    cp.Sale_to__c = NULL;
                    cp.Disabled__c = TRUE;
                }
                else{
                    cp.Disabled__c = FALSE;
                }
            }
            
        }//end if   
        
    }//end validateAccount
}//end class