fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <inlineHelpText>Nightly Data Load Populates this...</inlineHelpText>
    <label>SAP Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/SAP_Sold_To__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sold_To__c</fullName>
    <externalId>true</externalId>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory_Key__c.field-meta.xml
<CustomField>
    <fullName>Territory_Key__c</fullName>
    <description>Territory_Key__c is built every day as part of the daily Invoiced Sales ETL. 
Apex: account_Active_Sales
Scheduled Apex: Invoiced_Sales_Maintenance_Scheduler</description>
    <inlineHelpText>List of Territory Numbers that have Sales related to this Account.</inlineHelpText>
    <label>Territory Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/FOCUS_Profile__c/FOCUS_Profile__c.object-meta.xml
<CustomObject>
    <label>FOCUS Profile</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>FOCUS Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FOCUS Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/FOCUS_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FOCUS Profiles</relationshipLabel>
    <relationshipName>FOCUS_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/FOCUS_Profile__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/FOCUS_Profile__c/fields/End_Customer__c.field-meta.xml
<CustomField>
    <fullName>End_Customer__c</fullName>
    <label>End Customer #</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/FOCUS_Profile__c/fields/Stage_of_Action__c.field-meta.xml
<CustomField>
    <fullName>Stage_of_Action__c</fullName>
    <label>Stage of Action</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Focus_Profile_Apxt_Helper_Test.cls
@isTest
public class Focus_Profile_Apxt_Helper_Test {
    
     static testmethod void createData() {
        
        Account acc = new Account();
        acc.Name = 'CXTestAcc';
        acc.SAP_Sold_To__c = '123456';
        acc.SAP_Code__c='123456';
        acc.Territory_Key__c='123456;234567';
        insert acc;
         
         Focus_Profile__c fpObj = new Focus_Profile__c();
         fpObj.Account__c = acc.Id;
         fpObj.Current_Status__c = 'test status';
         fpObj.Stage_of_Action__c = 'Stage of Action';
         fpObj.End_Customer__c = acc.SAP_Sold_To__c;
         insert fpObj;

         fpObj.Account__c = acc.Id;
         fpObj.Current_Status__c = 'test status';
         fpObj.Stage_of_Action__c = 'Stage of Action';
         fpObj.End_Customer__c = acc.SAP_Sold_To__c;
         update fpObj;

     }

}