fullSandbox11072023/force-app/main/default/objects/Account/fields/Target_Profiles_Count__c.field-meta.xml
<CustomField>
    <fullName>Target_Profiles_Count__c</fullName>
    <description>This field is to store the number of Target profiles an account have.</description>
    <label>Target Profiles Count</label>
    <summaryForeignKey>Target_Profile__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10CR - HO Corporate Retail</fullName>
            </value>
            <value>
                <fullName>10HO - HO Hardware</fullName>
            </value>
            <value>
                <fullName>10IR - HO Independent Retail</fullName>
            </value>
            <value>
                <fullName>10SI - HO Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>12CR - NSW Corporate Retail</fullName>
            </value>
            <value>
                <fullName>12IR - NSW Independent Retail</fullName>
            </value>
            <value>
                <fullName>12SI - NSW Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>13CR - VIC Corporate Retail</fullName>
            </value>
            <value>
                <fullName>13IR - VIC Independent Retail</fullName>
            </value>
            <value>
                <fullName>13SI - VIC Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>14CR - QLD Corporate Retail</fullName>
            </value>
            <value>
                <fullName>14IR - QLD Independent Retail</fullName>
            </value>
            <value>
                <fullName>14SI - QLD Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>15CR - SA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>15IR - SA Independent Retail</fullName>
            </value>
            <value>
                <fullName>15SI - SA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>16CR - WA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>16IR - WA Independent Retail</fullName>
            </value>
            <value>
                <fullName>16SI - WA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>18CR - Int/Emer Corporate Retail</fullName>
            </value>
            <value>
                <fullName>18IR - Int/Emer Independent Retail</fullName>
            </value>
            <value>
                <fullName>18SI - Int/Emer Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>31IN - Fishers Industrial</fullName>
            </value>
            <value>
                <fullName>31RS - Fishers Reseller</fullName>
            </value>
            <value>
                <fullName>4201 - ACT</fullName>
            </value>
            <value>
                <fullName>4202 - South Eastern Sydney</fullName>
            </value>
            <value>
                <fullName>4203 - Southern NSW</fullName>
            </value>
            <value>
                <fullName>4204 - South Western Sydney</fullName>
            </value>
            <value>
                <fullName>4205 - Western NSW</fullName>
            </value>
            <value>
                <fullName>4206 - Western Syd LHN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/Target_Profile__c.object-meta.xml
<CustomObject>
    <label>Target Profile</label>
    <nameField>
        <displayFormat>TP-{00000}</displayFormat>
        <label>Target Profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Target Profile Pre-Hospital</relationshipLabel>
    <relationshipName>Target_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Account_Saturation_Range__c.field-meta.xml
<CustomField>
    <fullName>Account_Saturation_Range__c</fullName>
    <label>Account Saturation %</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Actual_IO_Potential_eaches__c.field-meta.xml
<CustomField>
    <fullName>Actual_IO_Potential_eaches__c</fullName>
    <formula>Actual_IO_Potential_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IO Potential (eaches)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/IO_Potential_Range__c.field-meta.xml
<CustomField>
    <fullName>IO_Potential_Range__c</fullName>
    <label>Segment</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Last_Year_Eaches__c.field-meta.xml
<CustomField>
    <fullName>Last_Year_Eaches__c</fullName>
    <inlineHelpText>Needles Only</inlineHelpText>
    <label>Last Year Eaches (Needles)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Protocol_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Ranking__c</fullName>
    <description>Protocol Ranking</description>
    <inlineHelpText>Protocol Ranking. See help --&gt;</inlineHelpText>
    <label>Protocol Ranking</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Account&apos;s Billing State/Province</description>
    <formula>Account__r.BillingState</formula>
    <inlineHelpText>Account&apos;s Billing State/Province</inlineHelpText>
    <label>State</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/X12_Month_Rolling_Sales_eaches__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Sales_eaches__c</fullName>
    <description>12 Month&apos;s Rolling Sales in eaches</description>
    <inlineHelpText>Needles Only</inlineHelpText>
    <label>12M Needle Rolling Sales (eaches)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <label>Territory Account Assignments</label>
    <nameField>
        <label>Territory Assignments</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Account Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Territory_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <formula>Territory__r.Sales_Rep_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Account Assignments</relationshipLabel>
    <relationshipName>Territory_Account_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used to concatenate the Territory Number with the Primary Territory User Full Name.</inlineHelpText>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/TPRecordsController.cls
public With Sharing class TPRecordsController {
    public List<Target_Profile__c> targetProfs {get;set;}
    
    public TPRecordsController(){
        string potentialRange;
        potentialRange = ApexPages.currentPage().getParameters().get('pr');
        string saturantionRange;
        saturantionRange = ApexPages.currentPage().getParameters().get('sr');
        Id userId;
        userId = UserInfo.getUserId();
        Set<Id> accountIds;
        accountIds = new Set<Id>();
        string additionalWhereCriteria;
        
        List<Territory_Master__c> territories = [SELECT Id FROM Territory_Master__c WHERE Sales_Rep__c=:userId];
        //system.debug('territories:'+territories);
        If(territories != null && territories.size() > 0){
            List<Territory_Assignment__c> territoryAssignments = [SELECT Id, account__c FROM Territory_Assignment__c WHERE territory__c IN:territories AND Account__r.Target_Profiles_Count__c!=0];
            //system.debug('territoryAssignments:'+territoryAssignments);
            If(territoryAssignments != null && territoryAssignments.size() > 0){
                for(Territory_Assignment__c ta:territoryAssignments){
                    accountIds.add(ta.account__c);
                }
                //system.debug('accountIds:'+accountIds);
            }
            if(accountIds.size()>0){
                additionalWhereCriteria = ' AND Account__c IN:accountIds';
            }
        }
        String queryStr;
        queryStr = 'SELECT Id,Name,Account__r.Name,State__c,Protocol_Ranking__c,';
        queryStr += 'Last_Year_Eaches__c,X12_Month_Rolling_Sales_eaches__c,Actual_IO_Potential_eaches__c ';
        queryStr += 'FROM Target_Profile__c ';
        queryStr += 'WHERE IO_potential_Range__c=:potentialRange ';
        queryStr += 'AND Account_Saturation_Range__c =:saturantionRange';
        if(string.isNotBlank(additionalWhereCriteria)){
            queryStr += additionalWhereCriteria;
        }
        targetProfs = database.query(queryStr);
    }
}