fullSandbox11072023/force-app/main/default/objects/Account/fields/Target_Profiles_Count__c.field-meta.xml
<CustomField>
    <fullName>Target_Profiles_Count__c</fullName>
    <description>This field is to store the number of Target profiles an account have.</description>
    <label>Target Profiles Count</label>
    <summaryForeignKey>Target_Profile__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10CR - HO Corporate Retail</fullName>
            </value>
            <value>
                <fullName>10HO - HO Hardware</fullName>
            </value>
            <value>
                <fullName>10IR - HO Independent Retail</fullName>
            </value>
            <value>
                <fullName>10SI - HO Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>12CR - NSW Corporate Retail</fullName>
            </value>
            <value>
                <fullName>12IR - NSW Independent Retail</fullName>
            </value>
            <value>
                <fullName>12SI - NSW Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>13CR - VIC Corporate Retail</fullName>
            </value>
            <value>
                <fullName>13IR - VIC Independent Retail</fullName>
            </value>
            <value>
                <fullName>13SI - VIC Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>14CR - QLD Corporate Retail</fullName>
            </value>
            <value>
                <fullName>14IR - QLD Independent Retail</fullName>
            </value>
            <value>
                <fullName>14SI - QLD Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>15CR - SA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>15IR - SA Independent Retail</fullName>
            </value>
            <value>
                <fullName>15SI - SA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>16CR - WA Corporate Retail</fullName>
            </value>
            <value>
                <fullName>16IR - WA Independent Retail</fullName>
            </value>
            <value>
                <fullName>16SI - WA Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>18CR - Int/Emer Corporate Retail</fullName>
            </value>
            <value>
                <fullName>18IR - Int/Emer Independent Retail</fullName>
            </value>
            <value>
                <fullName>18SI - Int/Emer Safety &amp; Industrial</fullName>
            </value>
            <value>
                <fullName>31IN - Fishers Industrial</fullName>
            </value>
            <value>
                <fullName>31RS - Fishers Reseller</fullName>
            </value>
            <value>
                <fullName>4201 - ACT</fullName>
            </value>
            <value>
                <fullName>4202 - South Eastern Sydney</fullName>
            </value>
            <value>
                <fullName>4203 - Southern NSW</fullName>
            </value>
            <value>
                <fullName>4204 - South Western Sydney</fullName>
            </value>
            <value>
                <fullName>4205 - Western NSW</fullName>
            </value>
            <value>
                <fullName>4206 - Western Syd LHN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/Target_Profile__c.object-meta.xml
<CustomObject>
    <label>Target Profile</label>
    <nameField>
        <displayFormat>TP-{00000}</displayFormat>
        <label>Target Profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Profile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Target Profile Pre-Hospital</relationshipLabel>
    <relationshipName>Target_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/Account_Saturation_Range__c.field-meta.xml
<CustomField>
    <fullName>Account_Saturation_Range__c</fullName>
    <label>Account Saturation %</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Target_Profile__c/fields/IO_Potential_Range__c.field-meta.xml
<CustomField>
    <fullName>IO_Potential_Range__c</fullName>
    <label>Segment</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/Territory_Assignment__c.object-meta.xml
<CustomObject>
    <label>Territory Account Assignments</label>
    <nameField>
        <label>Territory Assignments</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Account Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Territory_Assignment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <formula>Territory__r.Sales_Rep_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Assignment__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory_Master__c</referenceTo>
    <relationshipLabel>Territory Account Assignments</relationshipLabel>
    <relationshipName>Territory_Account_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/Territory_Master__c.object-meta.xml
<CustomObject>
    <label>Territory Master</label>
    <nameField>
        <label>Territory Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Territory_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Territory_Master__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <inlineHelpText>Field used to concatenate the Territory Number with the Primary Territory User Full Name.</inlineHelpText>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/TP_Dashboard.cls
public With Sharing class TP_Dashboard {
    public transient List<Target_Profile__c> recssaturation33eachesAPlus {get; private set;}
    public transient List<Target_Profile__c> recssaturation3366eachesAPlus {get; private set;}
    public transient List<Target_Profile__c> recssaturation66eachesAPlus {get; private set;}
    public transient List<Target_Profile__c> recssaturation33eachesA {get; private set;}
    public transient List<Target_Profile__c> recssaturation3366eachesA {get; private set;}
    public transient List<Target_Profile__c> recssaturation66eachesA {get; private set;}
    public transient List<Target_Profile__c> recssaturation33eachesB {get; private set;}
    public transient List<Target_Profile__c> recssaturation3366eachesB {get; private set;}
    public transient List<Target_Profile__c> recssaturation66eachesB {get; private set;}
    public transient List<Target_Profile__c> recssaturation33eachesC {get; private set;}
    public transient List<Target_Profile__c> recssaturation3366eachesC {get; private set;}
    public transient List<Target_Profile__c> recssaturation66eachesC {get; private set;}
   /* public transient List<Target_Profile__c> recssaturation33eachesMD {get; private set;}
    public transient List<Target_Profile__c> recssaturation3366eachesMD {get; private set;}
    public transient List<Target_Profile__c> recssaturation66eachesMD {get; private set;}*/
    public transient Integer recssaturation33eachesAPlusTotal {get; private set;}
    public transient Integer recssaturation3366eachesAPlusTotal {get; private set;}
    public transient Integer recssaturation66eachesAPlusTotal {get; private set;}
    public transient Integer recssaturation33eachesATotal {get; private set;}
    public transient Integer recssaturation3366eachesATotal {get; private set;}
    public transient Integer recssaturation66eachesATotal {get; private set;}
    public transient Integer recssaturation33eachesBTotal {get; private set;}
    public transient Integer recssaturation3366eachesBTotal {get; private set;}
    public transient Integer recssaturation66eachesBTotal {get; private set;}
    public transient Integer recssaturation33eachesCTotal {get; private set;}
    public transient Integer recssaturation3366eachesCTotal {get; private set;}
    public transient Integer recssaturation66eachesCTotal {get; private set;}
  /*  public transient Integer recssaturation33eachesMDTotal {get; private set;} 
    public transient Integer recssaturation3366eachesMDTotal {get; private set;}
    public transient Integer recssaturation66eachesMDTotal {get; private set;}*/
    
    public TP_Dashboard() {
        String queryStr = 'SELECT Id,Name,Account__r.Name FROM Target_Profile__c WHERE ';
        Id userId = UserInfo.getUserId();
        Set<Id> accountIds = new Set<Id>();
            
        List<Territory_Master__c> territories = [SELECT Id FROM Territory_Master__c WHERE Sales_Rep__c=:userId];
        //system.debug('territories:'+territories);
        If(territories != null && territories.size() > 0){
            List<Territory_Assignment__c> territoryAssignments = [SELECT Id, account__c FROM Territory_Assignment__c WHERE territory__c IN:territories AND Account__r.Target_Profiles_Count__c!=0];
            //system.debug('territoryAssignments:'+territoryAssignments);
            If(territoryAssignments != null && territoryAssignments.size() > 0){
                for(Territory_Assignment__c ta:territoryAssignments){
                    accountIds.add(ta.account__c);
                }
                //system.debug('accountIds:'+accountIds);
            }
            if(accountIds.size()>0){
                queryStr += 'Account__c IN:accountIds AND ';
            }
        }
        String saturation33eachesAPlusAllQuery = queryStr+'IO_potential_Range__c=\'A+\' AND Account_Saturation_Range__c = \'<33%\' ';
        List<Target_Profile__c> recssaturation33eachesAPlusAll = database.query(saturation33eachesAPlusAllQuery);
        recssaturation33eachesAPlusTotal = recssaturation33eachesAPlusAll.Size();
        recssaturation33eachesAPlus = getRecords(recssaturation33eachesAPlusAll);
        
        String saturation3366eachesAPlusAllQuery = queryStr+'IO_potential_Range__c=\'A+\' AND Account_Saturation_Range__c = \'33%-66%\' ';
        List<Target_Profile__c> recssaturation3366eachesAPlusAll = database.query(saturation3366eachesAPlusAllQuery);
        recssaturation3366eachesAPlusTotal = recssaturation3366eachesAPlusAll.Size();
        recssaturation3366eachesAPlus = getRecords(recssaturation3366eachesAPlusAll);
        
        String saturation66eachesAPlusAllQuery = queryStr+'IO_potential_Range__c=\'A+\' AND Account_Saturation_Range__c = \'>66%\' ';
        List<Target_Profile__c> recssaturation66eachesAPlusAll = database.query(saturation66eachesAPlusAllQuery);
        recssaturation66eachesAPlusTotal = recssaturation66eachesAPlusAll.Size();
        recssaturation66eachesAPlus = getRecords(recssaturation66eachesAPlusAll);
        
        String saturation33eachesAAllQuery = queryStr+'IO_potential_Range__c=\'A\' AND Account_Saturation_Range__c = \'<33%\' ';
        List<Target_Profile__c> recssaturation33eachesAAll = database.query(saturation33eachesAAllQuery);
        recssaturation33eachesATotal = recssaturation33eachesAAll.Size();
        recssaturation33eachesA = getRecords(recssaturation33eachesAAll);
        
        String saturation3366eachesAAllQuery = queryStr+'IO_potential_Range__c=\'A\' AND Account_Saturation_Range__c = \'33%-66%\' ';
        List<Target_Profile__c> recssaturation3366eachesAAll = database.query(saturation3366eachesAAllQuery);
        recssaturation3366eachesATotal = recssaturation3366eachesAAll.Size();
        recssaturation3366eachesA = getRecords(recssaturation3366eachesAAll);
        
        String saturation66eachesAAllQuery = queryStr+'IO_potential_Range__c=\'A\' AND Account_Saturation_Range__c = \'>66%\' ';
        List<Target_Profile__c> recssaturation66eachesAAll = database.query(saturation66eachesAAllQuery);
        recssaturation66eachesATotal = recssaturation66eachesAAll.Size();
        recssaturation66eachesA = getRecords(recssaturation66eachesAAll);
        
        
        String saturation33eachesBAllQuery = queryStr+'IO_potential_Range__c=\'B\' AND Account_Saturation_Range__c = \'<33%\' ';
        List<Target_Profile__c> recssaturation33eachesBAll = database.query(saturation33eachesBAllQuery);
        recssaturation33eachesBTotal = recssaturation33eachesBAll.Size();
        recssaturation33eachesB = getRecords(recssaturation33eachesBAll);
        
        String saturation3366eachesBAllQuery = queryStr+'IO_potential_Range__c=\'B\' AND Account_Saturation_Range__c = \'33%-66%\' ';
        List<Target_Profile__c> recssaturation3366eachesBAll = database.query(saturation3366eachesBAllQuery);
        recssaturation3366eachesBTotal = recssaturation3366eachesBAll.Size();
        recssaturation3366eachesB = getRecords(recssaturation3366eachesBAll);
        
        String saturation66eachesBAllQuery = queryStr+'IO_potential_Range__c=\'B\' AND Account_Saturation_Range__c = \'>66%\' ';
        List<Target_Profile__c> recssaturation66eachesBAll = database.query(saturation66eachesBAllQuery);
        recssaturation66eachesBTotal = recssaturation66eachesBAll.Size();
        recssaturation66eachesB = getRecords(recssaturation66eachesBAll);
        
        
        String saturation33eachesCAllQuery = queryStr+'IO_potential_Range__c=\'C\' AND Account_Saturation_Range__c = \'<33%\' ';
        List<Target_Profile__c> recssaturation33eachesCAll = database.query(saturation33eachesCAllQuery);
        recssaturation33eachesCTotal = recssaturation33eachesCAll.Size();
        recssaturation33eachesC = getRecords(recssaturation33eachesCAll);
        
       

        
       
        String saturation3366eachesCAllQuery = queryStr+'IO_potential_Range__c=\'C\' AND Account_Saturation_Range__c = \'33%-66%\' ';
        List<Target_Profile__c> recssaturation3366eachesCAll = database.query(saturation3366eachesCAllQuery);
        recssaturation3366eachesCTotal = recssaturation3366eachesCAll.Size();
        recssaturation3366eachesC = getRecords(recssaturation3366eachesCAll);
        
        
        String saturation66eachesCAllQuery = queryStr+'IO_potential_Range__c=\'C\' AND Account_Saturation_Range__c = \'>66%\' ';
        List<Target_Profile__c> recssaturation66eachesCAll = database.query(saturation66eachesCAllQuery);
        recssaturation66eachesCTotal = recssaturation66eachesCAll.Size();
        recssaturation66eachesC = getRecords(recssaturation66eachesCAll);
        
     /*   String saturation33eachesMDAllQuery = queryStr+'IO_potential_Range__c=\'MD\' AND Account_Saturation_Range__c = \'<33%\' ';
        List<Target_Profile__c> recssaturation33eachesMDAll = database.query(saturation33eachesMDAllQuery);
        recssaturation33eachesMDTotal = recssaturation33eachesMDAll.Size();
        recssaturation33eachesMD = getRecords(recssaturation33eachesMDAll);
        
        String saturation3366eachesMDAllQuery = queryStr+'IO_potential_Range__c=\'MD\' AND Account_Saturation_Range__c = \'33%-66%\' ';
        List<Target_Profile__c> recssaturation3366eachesMDAll = database.query(saturation3366eachesMDAllQuery);
        recssaturation3366eachesMDTotal = recssaturation3366eachesMDAll.Size();
        recssaturation3366eachesMD = getRecords(recssaturation3366eachesMDAll);
        
       
         String saturation66eachesMDAllQuery = queryStr+'IO_potential_Range__c=\'MD\' AND Account_Saturation_Range__c = \'>66%\' ';
        List<Target_Profile__c> recssaturation66eachesMDAll = database.query(saturation66eachesMDAllQuery);
        recssaturation66eachesMDTotal = recssaturation66eachesMDAll.Size();
        recssaturation66eachesMD = getRecords(recssaturation66eachesMDAll);*/
        
    }//end of constructor
    public List<Target_Profile__c> getRecords(List<Target_Profile__c> allRecord){
        List<Target_Profile__c> recsToDisplay = new List<Target_Profile__c>();
        If(allRecord.Size() > 5)
        {
            for(integer i=0; i<5; i++){
                recsToDisplay.add(allRecord[i]);
            }
        }
        else{
            recsToDisplay.addAll(allRecord);
        }
        System.debug('recsToDisplay:'+recsToDisplay+'|All:'+allRecord);
        return recsToDisplay;
    }
}