fullSandbox11072023/force-app/main/default/objects/Complaint__c/Complaint__c.object-meta.xml
<CustomObject>
    <customHelpPage>Complaints_Help</customHelpPage>
    <label>Complaint</label>
    <nameField>
        <displayFormat>SF{000000}</displayFormat>
        <label>Complaint Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <formula>Product_List__r.Description__c</formula>
    <label>Product Description</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Product_List__c.field-meta.xml
<CustomField>
    <fullName>Product_List__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product_List__c</referenceTo>
    <relationshipName>Complaints</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <inlineHelpText>If this complaint is rejected, please indicate the reason for the rejection.</inlineHelpText>
    <label>Rejection Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Complaint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product_List__c/Product_List__c.object-meta.xml
<CustomObject>
    <label>Complaint Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/classes/complaints_update.cls
public class complaints_update {
    private final Complaint__c complaints;
    
    public complaints_update(){
        complaints = [SELECT Id, Name, Product_Description__c, Product_List__r.Name, Status__c, Rejection_Reason__c FROM Complaint__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
    }
    public Complaint__c getComplaints() {
        return complaints;
    }
    public PageReference save() {
        update complaints;
        
        PageReference redir = New Pagereference('/' + ApexPages.currentPage().getParameters().get('id'));
        redir.setRedirect(true); 
        return redir;
    }
    
    public PageReference cancel() {
        
        PageReference redir = New Pagereference('/' + ApexPages.currentPage().getParameters().get('id'));
        redir.setRedirect(true); 
        return redir;
    }
    
    
}