fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/Sample_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Sample Request Line Item</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Sample Request Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/fields/Confirm_Transfer_of_Stock__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Transfer_of_Stock__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field is used to confirm transfer of field stock to another person.  Only the person the stock is being transferred to can check this box.</description>
    <inlineHelpText>Field is used to confirm transfer of field stock to another person.  Only the person the stock is being transferred to can check this box.</inlineHelpText>
    <label>Confirm Transfer of Stock</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/fields/Sample_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Sample_Request_Status__c</fullName>
    <formula>TEXT(Sample_Request__r.Status__c)</formula>
    <label>Sample Request Status</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/fields/Shipping_Info__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Info__c</fullName>
    <formula>NOT(ISBLANK(Shipping_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Shipping Info</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/fields/Shipping_Priority__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Priority__c</fullName>
    <label>Shipping Priority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/fields/Shipping_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Tracking__c</fullName>
    <label>Shipping Tracking</label>
    <type>Url</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/fields/Shipping_Tracking_Number_Count__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Tracking_Number_Count__c</fullName>
    <label>Shipping Tracking Number Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item__c/fields/Transferred_To__c.field-meta.xml
<CustomField>
    <fullName>Transferred_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transferred To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sample_Request_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item_Class_CS__c/Sample_Request_Line_Item_Class_CS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to control methods within the Sample_Request_Line_Item_Class.</description>
    <label>Sample_Request_Line_Item_Class_CS</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Sample_Request_Line_Item_Class_CS__c/fields/Execute__c.field-meta.xml
<CustomField>
    <fullName>Execute__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field controls whether the method executes.</description>
    <inlineHelpText>Field controls whether the method executes.</inlineHelpText>
    <label>Execute</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Sample_Request_Line_Item_Class.cls
/*********************************************************************
* Test Class Coverage: Invoiced_Sales_Tracking_Class_Test
* Author(s)          : Dunte'e Silver
**********************************************************************/
public class Sample_Request_Line_Item_Class {
    /* Method use to lockdown a Purchase Order record after it has been unlocked after full approval.
    Using apex because a validation rule can be tricked by passing another value along w/ the allowed values. */
    public static void manuallyLockSampleRequestLineItems(List<Sample_Request_Line_Item__c> newTrigger,List<Sample_Request_Line_Item__c> oldTrigger){
        //system.debug('*** EXECUTING manuallyLockPo method ***');
        //Custom setting value that controls execution of this method
        Sample_Request_Line_Item_Class_CS__c   customSettingSrliClass = Sample_Request_Line_Item_Class_CS__c.getValues('manuallyLockSampleRequestLineItems');
        //System.debug('*** customSettingSrliClass.Execute__c *** ' + customSettingSrliClass.Execute__c);
        //start if control method
        if(customSettingSrliClass!=null && customSettingSrliClass.Execute__c!=null && customSettingSrliClass.Execute__c){
            system.debug('*** IN Sample_Request_Line_Item_Class ***');
            system.debug('*** EXECUTING Sample_Request_Line_Item_Class method ***');
            Set<String> allowedFields = new Set<String>{'Id','LastmodifiedbyId','LastModifieddate','SystemModstamp','Transferred_To__c',
                'Transferred_To__c', 'Confirm_Transfer_of_Stock__c', 'Shipping_Tracking_Numbers__c', 'Shipping_Tracking__c', 'Shipping_Date__c',
                'Shipping_Carrier__c','Shipping_Priority__c','Shipping_Tracking_Number_Count__c',' Shipping_Info__c'
                };

            for(Integer index = 0; index < newTrigger.size(); index++) {
                if(oldTrigger[index].Sample_Request_Status__c  == 'Ready' && newTrigger[index].Sample_Request_Status__c  == 'Ready') {
                    //compare old values vs new values to see what fields changed
                    sObject beforeRecord = oldTrigger[index].clone(true, false, false, false);
                    sObject afterRecord = newTrigger[index].clone(true, false, false, false);
                    Map<String, Object> oldValues = beforeRecord.getPopulatedFieldsAsMap();
                    Map<String, Object> newValues = afterRecord.getPopulatedFieldsAsMap();
                    system.debug('*** oldValues1 *** ' + oldValues);
                    system.debug('*** newValues1 *** ' + newValues);
                    oldValues.keySet().removeAll(allowedFields);
                    newValues.keySet().removeAll(allowedFields);
                    if(oldTrigger[index] != newTrigger[index]){
                        system.debug('*** oldTrigger *** ' + oldTrigger[index]);
                        system.debug('*** newTrigger *** ' + newTrigger[index]);
                    }//end if
                    //Error is any field other than allowed fields are modified.
                    if(oldValues != newValues){
                        Trigger.new[index].addError('Only specific fields can be modified when a Sample Request has been approved.  ' +
                                                    'Fields related to tracking information and transfer of stock.');
                    }//end oldValues != newValues   
                }//end of if oldTrigger
            }//end of outter for loop
        }
        //end if control method
        
    }//end manuallyLockSampleRequestLineItems
    
}//end of Sample_Request_Line_Item_Class