fullSandbox11072023/force-app/main/default/objects/Opportunity/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/PRF__c.object-meta.xml
<CustomObject>
    <label>PRF</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/InApproval__c.field-meta.xml
<CustomField>
    <fullName>InApproval__c</fullName>
    <formula>OR(
ISPICKVAL(Status__c, &apos;PRF In Process&apos;), 
ISPICKVAL(Status__c, &apos;Waiting for Contracts Approval&apos;), 
ISPICKVAL(Status__c, &apos;Waiting For RSM Approval&apos;),
ISPICKVAL(Status__c, &apos;Waiting on Approval&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>InApproval</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Owner_Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Owner_Business_Unit__c</fullName>
    <formula>TEXT(Owner:User.Business_Unit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Business Unit</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>PRF</relationshipLabel>
    <relationshipName>PRF</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/Price_Quote__c.object-meta.xml
<CustomObject>
    <description>Used for Pricing portal instead of standard quotes object</description>
    <label>Price Quote</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Price Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/BusinessUnit__c.field-meta.xml
<CustomField>
    <fullName>BusinessUnit__c</fullName>
    <label>Business Unit 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Customer_comments__c.field-meta.xml
<CustomField>
    <fullName>Customer_comments__c</fullName>
    <label>Customer comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Discounted_Total__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Total__c</fullName>
    <description>Field is used to show amount of discount for Interventional Capital/Cardiac Service.</description>
    <formula>Grand_Total__c - (Grand_Total__c * Discount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Field is used to show amount of discount for Interventional Capital/Cardiac Service.</inlineHelpText>
    <label>Discounted Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <defaultValue>TODAY() + 90</defaultValue>
    <description>Expiration date of the quote</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/InApproval__c.field-meta.xml
<CustomField>
    <fullName>InApproval__c</fullName>
    <description>If( OR(ISPICKVAL(Status__c, &apos;PRF In Process&apos;), ISPICKVAL(Status__c, &apos;Waiting for Contracts Approval&apos;), ISPICKVAL(Status__c, &apos;Waiting For RSM Approval&apos;) ), true, false  )</description>
    <formula>OR(
ISPICKVAL(Status__c, &apos;PRF In Process&apos;), 
ISPICKVAL(Status__c, &apos;Waiting for Contracts Approval&apos;), 
ISPICKVAL(Status__c, &apos;Waiting For RSM Approval&apos;),
ISPICKVAL(Status__c, &apos;Waiting on Approval&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>InApproval</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Internal_Comments_Only__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments_Only__c</fullName>
    <label>Internal Comments Only</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/No_Opp__c.field-meta.xml
<CustomField>
    <fullName>No_Opp__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Do not create an Opportunity</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/One_Time_Purchase__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Purchase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>One Time Purchase</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/PRF__c.field-meta.xml
<CustomField>
    <fullName>PRF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRF</label>
    <referenceTo>PRF__c</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Price_Quote_Name__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote_Name__c</fullName>
    <formula>Name &amp; &quot; - &quot; &amp;  SUBSTITUTE(Account_Name__r.Name, &quot;,&quot;, &quot;&quot;)  &amp; &quot; - &quot; &amp; SUBSTITUTE(Contact_Name__r.Full_Name__c, &quot;,&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Quote Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Quote_Description__c.field-meta.xml
<CustomField>
    <fullName>Quote_Description__c</fullName>
    <label>Quote Description</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <color>#0B6FCE</color>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#78C953</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Ready for Approval</fullName>
                <color>#E27001</color>
                <label>Ready for Approval</label>
            </value>
            <value>
                <fullName>PRF In Process</fullName>
                <color>#A845DC</color>
                <label>PRF In Process</label>
            </value>
            <value>
                <fullName>Waiting on Approval</fullName>
                <color>#F3D904</color>
                <label>Waiting on Approval</label>
            </value>
            <value>
                <fullName>Waiting for Contracts Approval</fullName>
                <color>#A53711</color>
                <label>Waiting for Contracts Approval</label>
            </value>
            <value>
                <fullName>Waiting For RSM Approval</fullName>
                <color>#66E9BD</color>
                <label>Waiting For RSM Approval</label>
            </value>
            <value>
                <fullName>Waiting on Director Level Approval</fullName>
                <color>#0B24BE</color>
                <label>Waiting on Director Level Approval</label>
            </value>
            <value>
                <fullName>Waiting on VP Level Approval</fullName>
                <color>#419249</color>
                <label>Waiting on VP Level Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#B6E32E</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <color>#33CC00</color>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Field is used by the LATAM busines unit to assist in determining the purpose of the Price Quote.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa General Sales</fullName>
            </value>
            <value>
                <fullName>Special Sales</fullName>
            </value>
            <value>
                <fullName>Sales Per Each</fullName>
            </value>
            <value>
                <fullName>ASK Agreement</fullName>
            </value>
            <value>
                <fullName>Trade-in</fullName>
            </value>
            <value>
                <fullName>Tender</fullName>
                <isActive>false</isActive>
                <label>Tender</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Price_Quote_Edit.cls
public class PP_Price_Quote_Edit {
    private Price_Quote__c pq;

    public PP_Price_Quote_Edit(){
        pq = new Price_Quote__c();

        if(ApexPages.currentPage().getParameters().get('pqid') != NULL){
            pq = [SELECT Price_Quote_Name__c, Quote_Description__c, Expiration_Date__c, Internal_Comments_Only__c, Customer_comments__c, Status__c,
                  No_Opp__c,Opportunity__c, One_Time_Purchase__c,PRF__c,InApproval__c,Opportunity__r.Price_Quote__c, Shipping__c, Tax__c, Discount__c,
                  Discounted_Total__c, Discount_Type__c, Type__c, Sales_Org_Key__c, BusinessUnit__c, Owner_Business_Unit__c
                  FROM Price_Quote__c
                  WHERE Id = :ApexPages.currentPage().getParameters().get('pqid')];
        }
        system.debug('pq.Status__c ***** ' + pq.Status__c);
    }

    public Price_Quote__c getpq(){
        return pq;
    }

    public PageReference save() {

        pq = new Price_Quote__c(
            Id = ApexPages.currentPage().getParameters().get('pqid'),
            Quote_Description__c = pq.Quote_Description__c,
            Expiration_Date__c = pq.Expiration_Date__c,
            Customer_comments__c = pq.Customer_comments__c,
            Internal_Comments_Only__c = pq.Internal_Comments_Only__c,
            No_Opp__c = pq.No_Opp__c,
            One_Time_Purchase__c = pq.One_Time_Purchase__c,
            Opportunity__c = pq.Opportunity__c,
            Shipping__c = pq.Shipping__c,
            Tax__c = pq.Tax__c,
            Discount__c = pq.Discount__c,
            Discount_Type__c = pq.Discount_Type__c,
            Type__c = pq.Type__c
        );

        //Logic for ASK Agreements
        if(pq.Type__c == 'ASK Agreement'){
            pq.One_Time_Purchase__c = true;
        }
        //end of ASK Agreement logic
        //
        try{
            update pq;
        }
        catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
        PageReference redir = New Pagereference('/apex/PP_Price_Quote?pqid=' + ApexPages.currentPage().getParameters().get('pqid'));
        redir.setRedirect(true);
        return redir;


        /*
         * We do not need this update anymore, the trigger handles all of this updates between PQ and Opp - ESC - 30Jun2016
        system.debug('pq.Opportunity__c ***** ' + pq.Opportunity__c);
        if(pq.Opportunity__c != NULL){
            system.debug('CHECKING ***** ' + pq.Opportunity__c);
            Opportunity opp = [SELECT Id, Name, Price_Quote__c FROM Opportunity WHERE Id =:pq.Opportunity__c];

            if(opp.Price_Quote__c != pq.Id){

                // Do we delete the old lines from the old Opp
            }
            pq.Opportunity__c = opp.Id;
            opp.Price_Quote__c = pq.Id;
            try{
                update pq;
                update opp;
            }
            catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
                return null;
            }
            PageReference redir = New Pagereference('/apex/PP_Price_Quote?pqid=' + ApexPages.currentPage().getParameters().get('pqid'));
            redir.setRedirect(true);
            return redir;

        }
        else{
            try{
                update pq;
            }
            catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
                return null;
            }
            PageReference redir = New Pagereference('/apex/PP_Price_Quote?pqid=' + ApexPages.currentPage().getParameters().get('pqid'));
            redir.setRedirect(true);
            return redir;
        }
        */

    }//end save method

    public PageReference cancel() {

        PageReference redir = New Pagereference('/apex/PP_Price_Quote?pqid=' + ApexPages.currentPage().getParameters().get('pqid'));
        redir.setRedirect(true);
        return redir;
    }



}