fullSandbox11072023/force-app/main/default/objects/Canada_Profile__c/Canada_Profile__c.object-meta.xml
<CustomObject>
    <label>Canada Profile</label>
    <nameField>
        <displayFormat>CAN-{00000}</displayFormat>
        <label>Canada Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canada Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Canada_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Canada Profiles</relationshipLabel>
    <relationshipName>Canada_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/Pain_Profile__c.object-meta.xml
<CustomObject>
    <description>Used to hold information about Accounts from the Pain Management Team AEM.</description>
    <label>Pain Profile</label>
    <nameField>
        <displayFormat>Pain-{00000}</displayFormat>
        <label>Pain Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pain Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Pain_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pain Profiles</relationshipLabel>
    <relationshipName>Pain_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/CanadaProfilesBatch.cls
global class CanadaProfilesBatch implements database.Batchable<sObject>, Schedulable
{
    //start method of the batch
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //List<Pain_Profile__c> painLst  = new List<pain_profile__c>();
    
    String query = 'SELECT id,Account__c from Canada_Profile__c';
        return Database.getQueryLocator(query);}
    
    global void execute(Database.BatchableContext BC, List<Canada_Profile__c> scope){
  
    
    for(Canada_Profile__c CanObj : scope)
    {
       /*Dummy Update*/
    }
    system.debug('Canada Profiles list ' + scope.size()); 
    update scope;
    }
    global void finish(Database.BatchableContext BC)
    {
        system.debug('CanadaProfilesUpdate completed!');
    }
    global void execute(SchedulableContext sc)
    {
        CanadaProfilesBatch b = new  CanadaProfilesBatch ();
        
        database.executebatch(b,200);
    }
}