fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/Survey_Education__c.object-meta.xml
<CustomObject>
    <label>Survey - Education</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Survey - Education  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey - Education</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Clinical_Medical_Affairs__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Medical_Affairs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clinical &amp; Medical Affairs</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Continuing_Education__c.field-meta.xml
<CustomField>
    <fullName>Continuing_Education__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Continuing Education</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Course_material_structure_facilitated_le__c.field-meta.xml
<CustomField>
    <fullName>Course_material_structure_facilitated_le__c</fullName>
    <inlineHelpText>5 = Very Satisfied
4 = Satisfied
3 = Neutral
2 = Unsatisfied
1 = Very Unsatisfied</inlineHelpText>
    <label>Course material/structure facilitated le</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Ease_of_coordinating_your_education_prog__c.field-meta.xml
<CustomField>
    <fullName>Ease_of_coordinating_your_education_prog__c</fullName>
    <inlineHelpText>5 = Very Satisfied
4 = Satisfied
3 = Neutral
2 = Unsatisfied
1 = Very Unsatisfied</inlineHelpText>
    <label>Ease of coordinating your education prog</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Education_program_will_Improve_your_Prac__c.field-meta.xml
<CustomField>
    <fullName>Education_program_will_Improve_your_Prac__c</fullName>
    <label>Education program will Improve your Prac</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch_2__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch_2__c</fullName>
    <inlineHelpText>Catches: Please rate the attendee&apos;s knowledge acquisition as a result of the education program</inlineHelpText>
    <label>Multi-Catch 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch_3__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch_3__c</fullName>
    <inlineHelpText>Catches: Based on attendee&apos;s feedback</inlineHelpText>
    <label>Multi-Catch 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch_4__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch_4__c</fullName>
    <inlineHelpText>Catches: Would you like more information regarding any of the following</inlineHelpText>
    <label>Multi-Catch 4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch__c</fullName>
    <inlineHelpText>Catches: Please rate your education program experience</inlineHelpText>
    <label>Multi-Catch</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Other_More_Info__c.field-meta.xml
<CustomField>
    <fullName>Other_More_Info__c</fullName>
    <label>Other - More Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Professionalism_and_expertise_of_speaker__c.field-meta.xml
<CustomField>
    <fullName>Professionalism_and_expertise_of_speaker__c</fullName>
    <inlineHelpText>5 = Very Satisfied
4 = Satisfied
3 = Neutral
2 = Unsatisfied
1 = Very Unsatisfied</inlineHelpText>
    <label>Professionalism and expertise of speaker</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Program_Increased_Attendees_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Program_Increased_Attendees_Knowledge__c</fullName>
    <inlineHelpText>5 = Very Satisfied
4 = Satisfied
3 = Neutral
2 = Unsatisfied
1 = Very Unsatisfied</inlineHelpText>
    <label>Program Increased Attendees Knowledge</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Punctuality_and_preparedness_of_speaker__c.field-meta.xml
<CustomField>
    <fullName>Punctuality_and_preparedness_of_speaker__c</fullName>
    <inlineHelpText>5 = Very Satisfied
4 = Satisfied
3 = Neutral
2 = Unsatisfied
1 = Very Unsatisfied</inlineHelpText>
    <label>Punctuality and preparedness of speaker</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Teaching_methods_met_the_learning_needs__c.field-meta.xml
<CustomField>
    <fullName>Teaching_methods_met_the_learning_needs__c</fullName>
    <inlineHelpText>5 = Very Satisfied
4 = Satisfied
3 = Neutral
2 = Unsatisfied
1 = Very Unsatisfied</inlineHelpText>
    <label>Teaching methods met the learning needs</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/survey_education_Helper_Class.cls
public class survey_education_Helper_Class {
    public static void fixMultiSelects(list<Survey_Education__c> newTrigger){

        string multiString;
        for(Survey_Education__c se : newTrigger){
            // Test Class Coverage: survey_education_Helper_Class_Test
            //Multi_Catch__c
            if(se.Multi_Catch__c != NULL){ // Please Rate your education program experience 
                multiString = se.Multi_Catch__c;
                multiString = multiString.replace('=', ',');
                multiString = multiString.replace('Very Satisfied', '5,');
                multiString = multiString.replace('Very Unsatisfied', '1,');
                multiString = multiString.replace('Unsatisfied', '2,');
                multiString = multiString.replace('Satisfied', '4,');
                multiString = multiString.replace('Neutral', '3,');
                List<String> newDesc = multiString.split(',', -2);
                system.debug('newDesc: ' + newDesc);
                
                map<String, String> qaMap = new map<String, String>();
                string qstring;
                string numstring;
                boolean flip = true;

                for(string s : newDesc){
                    numstring = NULL;
                    if(flip){
                        qstring = s.trim();
                        qstring = qstring.left(4);
                        flip = false;
                    }
                    else{
                        numstring = s;
                        numstring = numstring.trim();
                        if(numstring != NULL && numstring != ''){
                            qaMap.put(qstring,numstring);                                
                        }
                        flip = true;
                    }
                }
                system.debug('qaMap: ' + qaMap);
                
                if(qaMap.size() > 0){
                    if(qaMap.get('Ease') != NULL){
                        se.Ease_of_coordinating_your_education_prog__c = integer.valueof(qaMap.get('Ease'));
                    }
                    if(qaMap.get('Punc') != NULL){
                        se.Punctuality_and_preparedness_of_speaker__c = integer.valueof(qaMap.get('Punc'));
                    }
                    if(qaMap.get('Prof') != NULL){
                        se.Professionalism_and_expertise_of_speaker__c = integer.valueof(qaMap.get('Prof'));
                    }
                    if(qaMap.get('Teac') != NULL){
                        se.Teaching_methods_met_the_learning_needs__c = integer.valueof(qaMap.get('Teac'));
                    }
                    if(qaMap.get('Cour') != NULL){
                        se.Course_material_structure_facilitated_le__c = integer.valueof(qaMap.get('Cour'));
                    }
                }
            }
            //Multi_Catch_2__c 
            if(se.Multi_Catch_2__c != NULL){
                multiString = se.Multi_Catch_2__c;
                multiString = multiString.replace('=', ',');
                multiString = multiString.replace('Strongly Agree', '5');
                multiString = multiString.replace('Strongly Disagree', '1');
                multiString = multiString.replace('Disagree', '2');
                multiString = multiString.replace('Agree', '4');
                multiString = multiString.replace('Unknown', '3');
                List<String> newDesc = multiString.split(',', -2);
                
                boolean flip = true;
                integer mc2;

                for(string s : newDesc){
                    if(flip){
                        flip = false;
                    }
                    else{
                        mc2 = integer.valueof(s.trim());
                        se.Program_Increased_Attendees_Knowledge__c = mc2;
                    }
                }
            } // END Multi_Catch_2__c
            // Start Multi_Catch_3__c
            if(se.Multi_Catch_3__c != NULL){
                multiString = se.Multi_Catch_3__c;
                multiString = multiString.replace('=', ',');
                List<String> newDesc = multiString.split(',', -2);
                
                boolean flip = true;
                //integer mc2;
                
                for(string s : newDesc){
                    if(flip){
                        flip = false;
                    }
                    else{
                        //mc2 = integer.valueof(s.trim());
                        se.Education_program_will_Improve_your_Prac__c = s.trim();
                    }
                }
            } // END Multi_Catch_3__c
            // Start Multi_Catch_4__c
            if(se.Multi_Catch_4__c != NULL){
                multiString = se.Multi_Catch_4__c;
                multiString = multiString.replace('\r\n', ' ');
                
                system.debug('multiString: ' + multiString);
                if(multiString.contains('Clinical & Medical Affairs')){
                    se.Clinical_Medical_Affairs__c = TRUE;
                }
                if(multiString.contains('Continuing Education')){
                    se.Continuing_Education__c = TRUE;
                }
                if(multiString.contains('Sales')){
                    se.Sales__c = TRUE;
                }
                /*if(multiString.contains('Other')){
                    se.Other_More_Info__c = 'Other';
                } */                
            } // Start Multi_Catch_4__c

             


                
            
        } // End FOR/LOOP
        
    }

}