fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/Survey_Education__c.object-meta.xml
<CustomObject>
    <label>Survey - Education</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Survey - Education  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey - Education</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch_2__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch_2__c</fullName>
    <inlineHelpText>Catches: Please rate the attendee&apos;s knowledge acquisition as a result of the education program</inlineHelpText>
    <label>Multi-Catch 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch_3__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch_3__c</fullName>
    <inlineHelpText>Catches: Based on attendee&apos;s feedback</inlineHelpText>
    <label>Multi-Catch 3</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch_4__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch_4__c</fullName>
    <inlineHelpText>Catches: Would you like more information regarding any of the following</inlineHelpText>
    <label>Multi-Catch 4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Survey_Education__c/fields/Multi_Catch__c.field-meta.xml
<CustomField>
    <fullName>Multi_Catch__c</fullName>
    <inlineHelpText>Catches: Please rate your education program experience</inlineHelpText>
    <label>Multi-Catch</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/survey_education_Helper_Class_Test.cls
@istest
public class survey_education_Helper_Class_Test {
    public static testMethod void survey_education_Test() {
        Survey_Education__c se = new Survey_Education__c(
            Multi_Catch__c = 'Ease of coordinating your education program = Very Satisfied Punctuality and preparedness of speaker = Satisfied Professionalism and expertise of speaker = Neutral Teaching methods met the learning needs = Unsatisfied Course material/structure facilitated learning process = Very Unsatisfied',
            Multi_Catch_2__c = 'The education program increased the knowledge and confidence of the majority of the attendees = Strongly Agree',
            Multi_Catch_3__c = 'Do you believe this education program was effective to improve your clinical practice? = No',
            Multi_Catch_4__c = 'Clinical & Medical Affairs Continuing Education Sales Other'
        );
        insert se;
        
        update se;
 
        
        
    }
}