fullSandbox11072023/force-app/main/default/objects/Quick_Disable__c/Quick_Disable__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Quick Disable/Enable APEX Classes using this Custom Setting. If the setting does not exist the functionality will fire by default.</description>
    <label>Quick Disable</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Quick_Disable__c/fields/Enable__c.field-meta.xml
<CustomField>
    <fullName>Enable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/case_TriggerHelperClass.cls
public class case_TriggerHelperClass {

    private static boolean run = true;
        
    public static boolean qe(){
        // Checks to make sure that there is a custom setting named "Quick Disabled" and under
		// Manage a setting for 'Case' with 'Enabled' checkbox set to true. Disable the checkbox to
		// disable this trigger.
    	Quick_Disable__c qd = Quick_Disable__c.getInstance('Case');
        
        if (qd.Enable__c){
            return true;
        }
        else {
            return false;
        }
    }
    
    public static boolean runOnce(){
        if(run){
            run = false;
            return true;
        }
        else{
            return run;
        }
    }
    
    
    
}