fullSandbox11072023/force-app/main/default/objects/Lead_Settings__c/Lead_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Leading Routing - These settings are used to change the record type and for routing leads to the appropriate queue.</description>
    <label>Lead Settings</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Lead_Settings__c/fields/LeadQuequeId__c.field-meta.xml
<CustomField>
    <fullName>LeadQuequeId__c</fullName>
    <label>LeadQuequeId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lead_Settings__c/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <label>LeadSource</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/leadRoutingCustomSetHandler.cls
public with sharing class leadRoutingCustomSetHandler {
  
    public static String getLeadSource(String leadSource){
            String custSetldSource='';
             if(leadSource!=null){
           Lead_Settings__c lds=Lead_Settings__c.getValues(leadSource);
              custSetldSource =lds.LeadSource__c;
            
        }
        return custSetldSource;
    }
        public static String getQuequeId(String leadSource){
            String leadQId='';
           if(leadSource!=null)  {     
            Lead_Settings__c lds=Lead_Settings__c.getInstance(leadSource);
            leadQId =lds.LeadQuequeId__c;
            }
                   
            return leadQId;
        }
    
}