fullSandbox11072023/force-app/main/default/objects/Coaching__c/Coaching__c.object-meta.xml
<CustomObject>
    <label>Coaching</label>
    <nameField>
        <label>Coaching Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coachings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Pre_Call_Plan_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Pre_Call_Plan_Comments__c</fullName>
    <label>BS_Pre_Call_Plan_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Pre_Call_Plan_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Pre_Call_Plan_RepProfLvl__c</fullName>
    <label>BS_Pre_Call_Plan_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Pre_Call_Plan_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Pre_Call_Plan_RSM_Comments__c</fullName>
    <label>BS_Pre_Call_Plan_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Pre_Call_Plan_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Pre_Call_Plan_RSMProfLvl__c</fullName>
    <label>BS_Pre_Call_Plan_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Rep_Ove_Prof_Lvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Rep_Ove_Prof_Lvl__c</fullName>
    <label>BS_Rep_Ove_Prof_Lvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Acc_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Acc_Comments__c</fullName>
    <label>BS_Researches_Acc_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Acc_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Acc_RepProfLvl__c</fullName>
    <label>BS_Researches_Acc_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Acc_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Acc_RSM_Comments__c</fullName>
    <label>BS_Researches_Acc_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Acc_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Acc_RSMProfLvl__c</fullName>
    <label>BS_Researches_Acc_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Sales_Data_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Sales_Data_Comments__c</fullName>
    <label>BS_Researches_Sales_Data_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Sales_Data_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Sales_Data_RepProfLvl__c</fullName>
    <label>BS_Researches_Sales_Data_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Sales_Data_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Sales_Data_RSM_Comments__c</fullName>
    <label>BS_Researches_Sales_Data_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Researches_Sales_Data_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Researches_Sales_Data_RSMProfLvl__c</fullName>
    <label>BS_Researches_Sales_Data_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_RSM_Ove_Prof_Lvl__c.field-meta.xml
<CustomField>
    <fullName>BS_RSM_Ove_Prof_Lvl__c</fullName>
    <label>BS_RSM_Ove_Prof_Lvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Pri_Call_Objs_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Pri_Call_Objs_Comments__c</fullName>
    <label>BS_Wri_Actn_Pri_Call_Objs_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Pri_Call_Objs_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Pri_Call_Objs_RepProfLvl__c</fullName>
    <label>BS_Wri_Actn_Pri_Call_Objs_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Pri_Call_Objs_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Pri_Call_Objs_RSM_Comments__c</fullName>
    <label>BS_Wri_Actn_Pri_Call_Objs_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Pri_Call_Objs_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Pri_Call_Objs_RSMProfLvl__c</fullName>
    <label>BS_Wri_Actn_Pri_Call_Objs_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Sec_FallBk_Objs_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Sec_FallBk_Objs_Comments__c</fullName>
    <label>BS_Wri_Actn_Sec_FallBk_Objs_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Sec_FallBk_Objs_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Sec_FallBk_Objs_RepProfLvl__c</fullName>
    <label>BS_Wri_Actn_Sec_FallBk_Objs_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Sec_FallBk_Objs_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Sec_FallBk_Objs_RSM_Comments__c</fullName>
    <label>BS_Wri_Actn_Sec_FallBk_Objs_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/BS_Wri_Actn_Sec_FallBk_Objs_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>BS_Wri_Actn_Sec_FallBk_Objs_RSMProfLvl__c</fullName>
    <label>BS_Wri_Actn_Sec_FallBk_Objs_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_4P_Que_Comments__c.field-meta.xml
<CustomField>
    <fullName>Discover_4P_Que_Comments__c</fullName>
    <label>Discover_4P_Que_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_4P_Que_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Discover_4P_Que_RepProfLvl__c</fullName>
    <label>Discover_4P_Que_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_4P_Que_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>Discover_4P_Que_RSM_Comments__c</fullName>
    <label>Discover_4P_Que_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_4P_Que_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Discover_4P_Que_RSMProfLvl__c</fullName>
    <label>Discover_4P_Que_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_Prep_High_Comments__c.field-meta.xml
<CustomField>
    <fullName>Discover_Prep_High_Comments__c</fullName>
    <label>Discover_Prep_High_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_Prep_High_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Discover_Prep_High_RepProfLvl__c</fullName>
    <label>Discover_Prep_High_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_Prep_High_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>Discover_Prep_High_RSM_Comments__c</fullName>
    <label>Discover_Prep_High_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_Prep_High_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Discover_Prep_High_RSMProfLvl__c</fullName>
    <label>Discover_Prep_High_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_Rep_Ove_Prof_Lvl__c.field-meta.xml
<CustomField>
    <fullName>Discover_Rep_Ove_Prof_Lvl__c</fullName>
    <label>Discover_Rep_Ove_Prof_Lvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Discover_RSM_Ove_Prof_Lvl__c.field-meta.xml
<CustomField>
    <fullName>Discover_RSM_Ove_Prof_Lvl__c</fullName>
    <label>Discover_RSM_Ove_Prof_Lvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Engage_Insight_Comments__c.field-meta.xml
<CustomField>
    <fullName>Engage_Insight_Comments__c</fullName>
    <label>Engage_Insight_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Engage_Insight_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Engage_Insight_RepProfLvl__c</fullName>
    <label>Engage_Insight_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Engage_Insight_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>Engage_Insight_RSM_Comments__c</fullName>
    <label>Engage_Insight_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Engage_Insight_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Engage_Insight_RSMProfLvl__c</fullName>
    <label>Engage_Insight_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_BS_Researches_Acc_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_BS_Researches_Acc_Completed__c</fullName>
    <label>is_BS_Researches_Acc_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_BS_Researches_Sales_Data_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_BS_Researches_Sales_Data_Completed__c</fullName>
    <label>is_BS_Researches_Sales_Data_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_BS_Wri_Actn_Pri_Call_Objs_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_BS_Wri_Actn_Pri_Call_Objs_Completed__c</fullName>
    <label>is_BS_Wri_Actn_Pri_Call_Objs_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_BS_Wri_Actn_Sec_FallBk_Objs_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_BS_Wri_Actn_Sec_FallBk_Objs_Completed__c</fullName>
    <label>is_BS_Wri_Actn_Sec_FallBk_Objs_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_Discover_4P_Que_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_Discover_4P_Que_Completed__c</fullName>
    <label>is_Discover_4P_Que_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_Discover_Prep_High_Imp_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_Discover_Prep_High_Imp_Completed__c</fullName>
    <label>is_Discover_Prep_High_Imp_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_Engage_Insight_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_Engage_Insight_Completed__c</fullName>
    <label>is_Engage_Insight_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_Magnify_Needs_Completed__c.field-meta.xml
<CustomField>
    <fullName>is_Magnify_Needs_Completed__c</fullName>
    <label>is_Magnify_Needs_Completed</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_Pos_Sols_Completed_1__c.field-meta.xml
<CustomField>
    <fullName>is_Pos_Sols_Completed_1__c</fullName>
    <label>is_Pos_Sols_Completed_1</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/is_Pos_Sols_Completed_2__c.field-meta.xml
<CustomField>
    <fullName>is_Pos_Sols_Completed_2__c</fullName>
    <label>is_Pos_Sols_Completed_2</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Magnify_Needs_Comments__c.field-meta.xml
<CustomField>
    <fullName>Magnify_Needs_Comments__c</fullName>
    <label>Magnify_Needs_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Magnify_Needs_RepProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Magnify_Needs_RepProfLvl__c</fullName>
    <label>Magnify_Needs_RepProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Magnify_Needs_RSM_Comments__c.field-meta.xml
<CustomField>
    <fullName>Magnify_Needs_RSM_Comments__c</fullName>
    <label>Magnify_Needs_RSM_Comments</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Coaching__c/fields/Magnify_Needs_RSMProfLvl__c.field-meta.xml
<CustomField>
    <fullName>Magnify_Needs_RSMProfLvl__c</fullName>
    <label>Magnify_Needs_RSMProfLvl</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/CoachingSectionsCompHandler_Test.cls
@isTest
private class CoachingSectionsCompHandler_Test {
    
    static testMethod void runPositiveTestCases(){
        
        
        UserRole userRoleTest = new UserRole(DeveloperName = 'MyCustomRole', Name = 'Teleflex Global IT');
        insert userRoleTest;
        
        
        
        User usr = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'test',
            Email = 'test@teleflex.com',
            Username = 'test@teleflex.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = userRoleTest.Id
        );
        
        insert usr;
        
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Coaching__c coachingObjTest = new Coaching__c();
            //coachingObjTest.NAME = 'Test Coaching Name';
            
            coachingObjTest.is_BS_Researches_Acc_Completed__c = 'Y';
            coachingObjTest.is_BS_Researches_Sales_Data_Completed__c = 'Y';
            coachingObjTest.is_BS_Wri_Actn_Pri_Call_Objs_Completed__c = 'Y';
            coachingObjTest.is_BS_Wri_Actn_Sec_FallBk_Objs_Completed__c = 'Y';
            coachingObjTest.BS_Pre_Call_Plan_Comments__c = 'Y';
            coachingObjTest.BS_Pre_Call_Plan_RSM_Comments__c = 'Y';
            coachingObjTest.BS_Researches_Acc_Comments__c = 'Y';
            coachingObjTest.BS_Researches_Acc_RSM_Comments__c = 'Y';
            coachingObjTest.BS_Researches_Sales_Data_Comments__c = 'Y';
            coachingObjTest.BS_Researches_Sales_Data_RSM_Comments__c = 'Y';
            coachingObjTest.BS_Wri_Actn_Pri_Call_Objs_Comments__c = 'Y';
            coachingObjTest.BS_Wri_Actn_Pri_Call_Objs_RSM_Comments__c = 'Y';
            coachingObjTest.BS_Wri_Actn_Sec_FallBk_Objs_Comments__c = 'Y';
            coachingObjTest.BS_Wri_Actn_Sec_FallBk_Objs_RSM_Comments__c = 'Y';
            coachingObjTest.BS_Pre_Call_Plan_RepProfLvl__c = 0;
            coachingObjTest.BS_Researches_Acc_RepProfLvl__c = 0;
            coachingObjTest.BS_Researches_Sales_Data_RepProfLvl__c = 0;
            coachingObjTest.BS_Wri_Actn_Pri_Call_Objs_RepProfLvl__c = 0;
            coachingObjTest.BS_Wri_Actn_Sec_FallBk_Objs_RepProfLvl__c = 0;
            coachingObjTest.BS_Pre_Call_Plan_RSMProfLvl__c = 0;
            coachingObjTest.BS_Researches_Acc_RSMProfLvl__c = 0;
            coachingObjTest.BS_Researches_Sales_Data_RSMProfLvl__c = 0;
            coachingObjTest.BS_Wri_Actn_Pri_Call_Objs_RSMProfLvl__c = 0;
            coachingObjTest.BS_Wri_Actn_Sec_FallBk_Objs_RSMProfLvl__c = 0;
            coachingObjTest.BS_Rep_Ove_Prof_Lvl__c = 0;
            coachingObjTest.BS_RSM_Ove_Prof_Lvl__c = 0;
            
            coachingObjTest.is_Engage_Insight_Completed__c = 'Y';
            coachingObjTest.Engage_Insight_Comments__c = 'Y';
            coachingObjTest.Engage_Insight_RSM_Comments__c = 'Y';
            coachingObjTest.Engage_Insight_RepProfLvl__c = 0;
            coachingObjTest.Engage_Insight_RSMProfLvl__c = 0;
            
            coachingObjTest.is_Discover_Prep_High_Imp_Completed__c = 'Y';
            coachingObjTest.is_Discover_4P_Que_Completed__c = 'Y';
            coachingObjTest.Discover_Prep_High_Comments__c = 'Y';
            coachingObjTest.Discover_Prep_High_RSM_Comments__c = 'Y';
            coachingObjTest.Discover_4P_Que_Comments__c = 'Y';
            coachingObjTest.Discover_4P_Que_RSM_Comments__c = 'Y';
            coachingObjTest.Discover_Prep_High_RepProfLvl__c = 0;
            coachingObjTest.Discover_4P_Que_RepProfLvl__c = 0;
            coachingObjTest.Discover_Prep_High_RSMProfLvl__c = 0;
            coachingObjTest.Discover_4P_Que_RSMProfLvl__c = 0;
            coachingObjTest.Discover_Rep_Ove_Prof_Lvl__c = 0;
            coachingObjTest.Discover_RSM_Ove_Prof_Lvl__c = 0;
            
            coachingObjTest.is_Magnify_Needs_Completed__c = 'Y';
            coachingObjTest.Magnify_Needs_Comments__c = 'Y';
            coachingObjTest.Magnify_Needs_RSM_Comments__c = 'Y';
            coachingObjTest.Magnify_Needs_RepProfLvl__c = 0;
            coachingObjTest.Magnify_Needs_RSMProfLvl__c = 0;
            
            coachingObjTest.is_Pos_Sols_Completed_1__c = 'Y';
            coachingObjTest.is_Pos_Sols_Completed_2__c = 'Y';
            coachingObjTest.Pos_Sols_Comments_1__c = 'Y';
            coachingObjTest.Pos_Sols_RSM_Comments_1__c = 'Y';
            coachingObjTest.Pos_Sols_Comments_2__c = 'Y';
            coachingObjTest.Pos_Sols_RSM_Comments_2__c = 'Y';
            coachingObjTest.Pos_Sols_RepProfLvl_1__c = 0;
            coachingObjTest.Pos_Sols_RepProfLvl_2__c = 0;
            coachingObjTest.Pos_Sols_RSMProfLvl_1__c = 0;
            coachingObjTest.Pos_Sols_RSMProfLvl_2__c = 0;
            coachingObjTest.Pos_Sols_Rep_Ove_Prof_Lvl__c = 0;
            coachingObjTest.Pos_Sols_RSM_Ove_Prof_Lvl__c = 0;
            
            coachingObjTest.is_Gain_Commitment_Completed_1__c = 'Y';
            coachingObjTest.is_Gain_Commitment_Completed_2__c = 'Y';
            coachingObjTest.is_Gain_Commitment_Completed_3__c = 'Y';
            coachingObjTest.Gain_Commitment_Comments_1__c = 'Y';
            coachingObjTest.Gain_Commitment_RSM_Comments_1__c = 'Y';
            coachingObjTest.Gain_Commitment_Comments_2__c = 'Y';
            coachingObjTest.Gain_Commitment_RSM_Comments_2__c = 'Y';
            coachingObjTest.Gain_Commitment_Comments_3__c = 'Y';
            coachingObjTest.Gain_Commitment_RSM_Comments_3__c = 'Y';
            coachingObjTest.Gain_Commitment_RepProfLvl_1__c = 0;
            coachingObjTest.Gain_Commitment_RepProfLvl_2__c = 0;
            coachingObjTest.Gain_Commitment_RepProfLvl_3__c = 0;
            coachingObjTest.Gain_Commitment_RSMProfLvl_1__c = 0;
            coachingObjTest.Gain_Commitment_RSMProfLvl_2__c = 0;
            coachingObjTest.Gain_Commitment_RSMProfLvl_3__c = 0;
            coachingObjTest.Gain_Commitment_Rep_Ove_Prof_Lvl__c = 0;
            coachingObjTest.Gain_Commitment_RSM_Ove_Prof_Lvl__c = 0;
            
            coachingObjTest.Rep_Comments_Strengths__c = 'Y';
            coachingObjTest.Rep_Comments_Area_Of_Impvmnt__c = 'Y';
            coachingObjTest.Rep_Comments_Core_Vals__c = 'Y';
            
            coachingObjTest.Manager_Comments_Strengths__c = 'Y';
            coachingObjTest.Manager_Comments_Area_Of_Impvmnt__c = 'Y';
            coachingObjTest.Manager_Comments_Core_Vals__c = 'Y';
            
            coachingObjTest.Director_Comments_Strengths__c = 'Y';
            coachingObjTest.Director_Comments_Area_Of_Impvmnt__c = 'Y';
            coachingObjTest.Director_Comments_Core_Vals__c = 'Y';
            
            coachingObjTest.Total_Rep_Ove_Prof_Lvl__c = 0;
            coachingObjTest.Total_RSM_Ove_Prof_Lvl__c = 0;
            
            insert coachingObjTest;
            
            
            
            
            Test.startTest();
            
            
            CoachingSectionsCompHandler.FormVisibilityWrapper formVisibilityWrapperTest = CoachingSectionsCompHandler.getUserInfoForCoachingForm();
            
            String dirEmail = CoachingSectionsCompHandler.getDirEmailAndNotify(coachingObjTest.ID);
            
            Coaching__c thisTstCoachObj = CoachingSectionsCompHandler.getCoachingDetail(coachingObjTest.ID);
            Coaching__c thisTstSaveCoachObj = CoachingSectionsCompHandler.saveCoachingDetail(coachingObjTest.ID, coachingObjTest);
            Coaching__c thisTstCoachObj_v2 = CoachingSectionsCompHandler.getCoachingDetail_v2(coachingObjTest.ID);
            Coaching__c thisTstSaveCoachObj_v2 = CoachingSectionsCompHandler.saveCoachingDetail_v2(coachingObjTest.ID, coachingObjTest);
            
            Test.stopTest();  
            
            System.assertEquals(coachingObjTest.BS_Pre_Call_Plan_Comments__c , thisTstCoachObj.BS_Pre_Call_Plan_Comments__c);
        }  
    }
    
    static testMethod void runPositiveTestCases1(){
        
        UserRole userRoleTest = new UserRole(DeveloperName = 'MyCustomRoleMgr', Name = 'Anesthesia RSM - Central');
        insert userRoleTest;
        
        
        
        User usr = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'TFX Sales Manager Wave User'].Id,
            LastName = 'test',
            Email = 'test@teleflex.com',
            Username = 'test@teleflex.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = userRoleTest.Id
        );
        
        insert usr;
        
        Test.startTest();
        System.runAs ( new User(Id = usr.Id) ) {
            CoachingSectionsCompHandler.FormVisibilityWrapper formVisibilityWrapperTest = CoachingSectionsCompHandler.getUserInfoForCoachingForm();
            
        }
        Test.stopTest();
    }
    
    
    static testMethod void runPositiveTestCases2(){
        
        UserRole userRoleTest = new UserRole(DeveloperName = 'MyCustomRolePrsdnt', Name = 'Anesthesia President');
        insert userRoleTest;
        
        
        
        User usr = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'TFX Sales Manager Wave User'].Id,
            LastName = 'test',
            Email = 'test@teleflex.com',
            Username = 'test@teleflex.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = userRoleTest.Id
        );
        
        insert usr;
        
        Test.startTest();
        System.runAs ( new User(Id = usr.Id) ) {
            CoachingSectionsCompHandler.FormVisibilityWrapper formVisibilityWrapperTest = CoachingSectionsCompHandler.getUserInfoForCoachingForm();
            
        }
        Test.stopTest();
    }
    
    static testMethod void runPositiveTestCases3(){
        
        UserRole userRoleTest = new UserRole(DeveloperName = 'MyCustomRolePrsdnt', Name = 'Customer Service Rep');
        insert userRoleTest;
        
        
        
        User usr = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'TFX Sales Manager Wave User'].Id,
            LastName = 'test',
            Email = 'test@teleflex.com',
            Username = 'test@teleflex.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = userRoleTest.Id
        );
        
        insert usr;
        
        Test.startTest();
        System.runAs ( new User(Id = usr.Id) ) {
            CoachingSectionsCompHandler.FormVisibilityWrapper formVisibilityWrapperTest = CoachingSectionsCompHandler.getUserInfoForCoachingForm();
            
        }
        Test.stopTest();
    }
    
    static testMethod void runPositiveTestCases4(){
        
        UserRole userRoleTest = new UserRole(DeveloperName = 'MyCustomRolePrsdnt', Name = 'Anesthesia Director of Sales');
        insert userRoleTest;
        
        
        
        User usr = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'TFX Sales Manager Wave User'].Id,
            LastName = 'test',
            Email = 'test@teleflex.com',
            Username = 'test@teleflex.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = userRoleTest.Id
        );
        
        insert usr;
        
        Test.startTest();
        System.runAs ( new User(Id = usr.Id) ) {
            CoachingSectionsCompHandler.FormVisibilityWrapper formVisibilityWrapperTest = CoachingSectionsCompHandler.getUserInfoForCoachingForm();
            
        }
        Test.stopTest();
    }
    
}