fullSandbox11072023/force-app/main/default/objects/Contact/fields/Credentials__c.field-meta.xml
<CustomField>
    <fullName>Credentials__c</fullName>
    <description>Medical Credentials</description>
    <inlineHelpText>Medical Credentials</inlineHelpText>
    <label>Credentials</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BSN</fullName>
            </value>
            <value>
                <fullName>CCEMT</fullName>
            </value>
            <value>
                <fullName>Certified Registered Nurse Anesthetists</fullName>
            </value>
            <value>
                <fullName>CRNA</fullName>
            </value>
            <value>
                <fullName>CRT</fullName>
            </value>
            <value>
                <fullName>CST</fullName>
            </value>
            <value>
                <fullName>CT Tech</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>Doctor of Veterinary Medicine</fullName>
            </value>
            <value>
                <fullName>DVM</fullName>
            </value>
            <value>
                <fullName>EMT</fullName>
            </value>
            <value>
                <fullName>EMT-P</fullName>
            </value>
            <value>
                <fullName>FTO</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>Infection Control Personnel</fullName>
            </value>
            <value>
                <fullName>M.H.S. RRT</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MD, FACS</fullName>
            </value>
            <value>
                <fullName>Medical Doctor</fullName>
            </value>
            <value>
                <fullName>MHA</fullName>
            </value>
            <value>
                <fullName>MICT, ASN</fullName>
            </value>
            <value>
                <fullName>MPH</fullName>
            </value>
            <value>
                <fullName>MSN</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>NP</fullName>
            </value>
            <value>
                <fullName>NREMT</fullName>
            </value>
            <value>
                <fullName>NREMT-P</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Other/None</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Position_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Job_Title__c</fullName>
    <label>Position/Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abdominal Transplant Surgeon</fullName>
            </value>
            <value>
                <fullName>Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>ALS Provider</fullName>
            </value>
            <value>
                <fullName>Anesthesia Director</fullName>
            </value>
            <value>
                <fullName>Anesthesia Tech</fullName>
            </value>
            <value>
                <fullName>Anesthesiologist</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Asst Chief</fullName>
            </value>
            <value>
                <fullName>Bariatric Surgeon</fullName>
            </value>
            <value>
                <fullName>Bio Med</fullName>
            </value>
            <value>
                <fullName>BLS Provider</fullName>
            </value>
            <value>
                <fullName>Buyer/Purchasing Staff</fullName>
            </value>
            <value>
                <fullName>Captain</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Director</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Manager</fullName>
            </value>
            <value>
                <fullName>Category Manager</fullName>
            </value>
            <value>
                <fullName>CCL Manager</fullName>
            </value>
            <value>
                <fullName>CCL Scheduler</fullName>
            </value>
            <value>
                <fullName>Central Supply</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Chief Nursing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of CV</fullName>
            </value>
            <value>
                <fullName>Chief of General Surgery</fullName>
            </value>
            <value>
                <fullName>Chief of GYN</fullName>
            </value>
            <value>
                <fullName>CLABSI Team</fullName>
            </value>
            <value>
                <fullName>Clinical Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Preferred_language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_language__c</fullName>
    <label>Preferred language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English (American)</fullName>
            </value>
            <value>
                <fullName>English (Australian)</fullName>
            </value>
            <value>
                <fullName>English (New Zealand)</fullName>
            </value>
            <value>
                <fullName>French (Canada)</fullName>
            </value>
            <value>
                <fullName>French (France)</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hebrew (right to left)</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Portuguese (Brazil)</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Simplified Chinese (China)</fullName>
            </value>
            <value>
                <fullName>Spanish (Latin America)</fullName>
            </value>
            <value>
                <fullName>Traditional Chinese (Hong Kong/Taiwan)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/Education_Record__c.object-meta.xml
<CustomObject>
    <description>OnControl and EZIO Training Records</description>
    <label>Education Record</label>
    <nameField>
        <label>IS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Education_Record__c/fields/CEM__c.field-meta.xml
<CustomField>
    <fullName>CEM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CEM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Education_RecordsCEM</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/CEM__c.field-meta.xml
<CustomField>
    <fullName>CEM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible CEM</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Clinical</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Clinical_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Credentials__c.field-meta.xml
<CustomField>
    <fullName>Credentials__c</fullName>
    <inlineHelpText>What are their current credentials?</inlineHelpText>
    <label>Credentials</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACLS</fullName>
            </value>
            <value>
                <fullName>ACNP</fullName>
            </value>
            <value>
                <fullName>ADN</fullName>
            </value>
            <value>
                <fullName>APRN</fullName>
            </value>
            <value>
                <fullName>ASCP</fullName>
            </value>
            <value>
                <fullName>BLS</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BSN</fullName>
            </value>
            <value>
                <fullName>CCEMTP</fullName>
            </value>
            <value>
                <fullName>CCRN</fullName>
            </value>
            <value>
                <fullName>CCT</fullName>
            </value>
            <value>
                <fullName>CEN</fullName>
            </value>
            <value>
                <fullName>CFRN</fullName>
            </value>
            <value>
                <fullName>Chief Medical Officer</fullName>
            </value>
            <value>
                <fullName>CIC</fullName>
            </value>
            <value>
                <fullName>CMSRN</fullName>
            </value>
            <value>
                <fullName>CNCC</fullName>
            </value>
            <value>
                <fullName>C-NPT</fullName>
            </value>
            <value>
                <fullName>CNRN</fullName>
            </value>
            <value>
                <fullName>CPEN</fullName>
            </value>
            <value>
                <fullName>CPNP</fullName>
            </value>
            <value>
                <fullName>CPUI</fullName>
            </value>
            <value>
                <fullName>CRNA</fullName>
            </value>
            <value>
                <fullName>CRNI</fullName>
            </value>
            <value>
                <fullName>CRRT</fullName>
            </value>
            <value>
                <fullName>CTEN</fullName>
            </value>
            <value>
                <fullName>DNP</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>ED.D</fullName>
            </value>
            <value>
                <fullName>EMT</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <inlineHelpText>What is their preferred mailing address?</inlineHelpText>
    <label>Mailing Address</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State/Province</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Mailing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip__c</fullName>
    <label>Mailing Zip/Postal Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Profile__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Education_Record_Utility_Test.cls
@isTest
public class Education_Record_Utility_Test {
  
    Public static List<Education_Record__c> createTestRecords(Integer numEducRecs) {
        
	  List<Account> accts = new List<Account>();
		 for(Integer i=0;i<numEducRecs;i++) {
             
            Account a = new Account(name='TestAccount'+i);
            accts.add(a); 
        }

        insert accts;

        List<Contact> cons = new List<Contact>();

        for (Integer i=0;i<numEducRecs;i++) {

            Account acct = accts[i];           
			
            Contact c = (new Contact(firstname='Test'+i,
									lastname='Test'+i,
                                    email = 'abc@123.com'+i, 
                                    Position_Job_Title__c='Administrator'+i,
                                    Credentials__c='RN'+i,
                                    Preferred_language__c='English (American)'+i,
									AccountId=acct.Id));
            cons.add(c);

            }

        insert cons;

  	    List<Education_Record__c> edrecs = new List<Education_Record__c>();

        for (Integer i=0;i<numEducRecs;i++) {

            Account acct1 = accts[i];   
            
			Contact con1 = cons[i];
            
            Profile__c profTest = new Profile__c(
                
                First_Name__c = 'Prof1',
                Name = 'Last1',
                //	CEM__c = ManagerTest.Id,
                Phone_Number__c = '9192223333',
                Mailing_Address__c = '123 Test St',
                Mailing_City__c = 'Raleigh',
                Mailing_State__c = 'NC',
                Mailing_Zip__c = '27610',
                Mailing_Country__c = 'US',
                E_mail_Address__c = 'andreina.mendoza@teleflex.com',
                Hourly_Rate__c = 50,
                Status__c = 'Active' // Another Fix 25Oct2016 - ESC
            );
            insert profTest;
            
            Education_Record__c er = (new Education_Record__c(
                Name='Education Record Test'+i,
                recordtypeid='012E000000095BM',
                Account_Facility__c=acct1.Id,
                Contact_Name__c = con1.id,
                Hotel_Requested__c = 'No', // This is what fixes all the validation rule errors - ESC
                Clinical_Educator__c = profTest.id 
            ));
            edrecs.add(er);
            
        }

        insert edrecs;
        return edrecs;

    }
    

}