fullSandbox11072023/force-app/main/default/objects/Contact/fields/Credentials__c.field-meta.xml
<CustomField>
    <fullName>Credentials__c</fullName>
    <description>Medical Credentials</description>
    <inlineHelpText>Medical Credentials</inlineHelpText>
    <label>Credentials</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BSN</fullName>
            </value>
            <value>
                <fullName>CCEMT</fullName>
            </value>
            <value>
                <fullName>Certified Registered Nurse Anesthetists</fullName>
            </value>
            <value>
                <fullName>CRNA</fullName>
            </value>
            <value>
                <fullName>CRT</fullName>
            </value>
            <value>
                <fullName>CST</fullName>
            </value>
            <value>
                <fullName>CT Tech</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>Doctor of Veterinary Medicine</fullName>
            </value>
            <value>
                <fullName>DVM</fullName>
            </value>
            <value>
                <fullName>EMT</fullName>
            </value>
            <value>
                <fullName>EMT-P</fullName>
            </value>
            <value>
                <fullName>FTO</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>Infection Control Personnel</fullName>
            </value>
            <value>
                <fullName>M.H.S. RRT</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MD, FACS</fullName>
            </value>
            <value>
                <fullName>Medical Doctor</fullName>
            </value>
            <value>
                <fullName>MHA</fullName>
            </value>
            <value>
                <fullName>MICT, ASN</fullName>
            </value>
            <value>
                <fullName>MPH</fullName>
            </value>
            <value>
                <fullName>MSN</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>NP</fullName>
            </value>
            <value>
                <fullName>NREMT</fullName>
            </value>
            <value>
                <fullName>NREMT-P</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Other/None</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Position_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Job_Title__c</fullName>
    <label>Position/Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abdominal Transplant Surgeon</fullName>
            </value>
            <value>
                <fullName>Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>ALS Provider</fullName>
            </value>
            <value>
                <fullName>Anesthesia Director</fullName>
            </value>
            <value>
                <fullName>Anesthesia Tech</fullName>
            </value>
            <value>
                <fullName>Anesthesiologist</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Asst Chief</fullName>
            </value>
            <value>
                <fullName>Bariatric Surgeon</fullName>
            </value>
            <value>
                <fullName>Bio Med</fullName>
            </value>
            <value>
                <fullName>BLS Provider</fullName>
            </value>
            <value>
                <fullName>Buyer/Purchasing Staff</fullName>
            </value>
            <value>
                <fullName>Captain</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Director</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Manager</fullName>
            </value>
            <value>
                <fullName>Category Manager</fullName>
            </value>
            <value>
                <fullName>CCL Manager</fullName>
            </value>
            <value>
                <fullName>CCL Scheduler</fullName>
            </value>
            <value>
                <fullName>Central Supply</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Chief Nursing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of CV</fullName>
            </value>
            <value>
                <fullName>Chief of General Surgery</fullName>
            </value>
            <value>
                <fullName>Chief of GYN</fullName>
            </value>
            <value>
                <fullName>CLABSI Team</fullName>
            </value>
            <value>
                <fullName>Clinical Director</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Preferred_language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_language__c</fullName>
    <label>Preferred language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English (American)</fullName>
            </value>
            <value>
                <fullName>English (Australian)</fullName>
            </value>
            <value>
                <fullName>English (New Zealand)</fullName>
            </value>
            <value>
                <fullName>French (Canada)</fullName>
            </value>
            <value>
                <fullName>French (France)</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hebrew (right to left)</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Portuguese (Brazil)</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Simplified Chinese (China)</fullName>
            </value>
            <value>
                <fullName>Spanish (Latin America)</fullName>
            </value>
            <value>
                <fullName>Traditional Chinese (Hong Kong/Taiwan)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Duplicate_Contact__c/Duplicate_Contact__c.object-meta.xml
<CustomObject>
    <label>Duplicate Contact</label>
    <nameField>
        <displayFormat>DC-{0000000000}</displayFormat>
        <label>Duplicate Contact#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Duplicate Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Duplicate_Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Duplicate Contacts</relationshipLabel>
    <relationshipName>Duplicate_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Duplicate_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Duplicate Contacts</relationshipLabel>
    <relationshipName>Duplicate_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Duplicate_Contact__c/fields/Contact_Owner__c.field-meta.xml
<CustomField>
    <fullName>Contact_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Duplicate_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/BatchContactManagement_Test.cls
@isTest
public class BatchContactManagement_Test {
    
    static List<Account> testAcclst;
    static List<Contact> testConlst;
    static List<Contact> testConlstAcc;
    
    public static testMethod void TestcaseOne() { 
        
        testAcclst = loadAccount(10);
        insert testAcclst;
        
        testConlstAcc = createContactWithAccount(10,testAcclst);
        insert testConlstAcc;
        
        
        testConlst = createContactWithoutAccount(10);
        insert testConlst;
        
        
        BatchContactManagement b = new BatchContactManagement();
        Database.executeBatch(b);
        
        
    }
    
    public static testMethod void TestcaseTwo() { 
        
        testAcclst = loadAccount(10);
        insert testAcclst;
        
        testConlstAcc = createContactWithAccount(10,testAcclst);
        insert testConlstAcc;
        
        
        testConlst = createContactWithoutAccount(10);
        insert testConlst;
        
        findDuplicateContactsBatch b = new findDuplicateContactsBatch();
        Database.executeBatch(b);
        
        Duplicate_Contact__c dupRow = new Duplicate_Contact__c();
        dupRow.Contact__c = testConlstAcc[1].Id;
        dupRow.Account__c = testAcclst[1].Id;
        dupRow.Contact_Owner__c = userInfo.getUserId();
        insert dupRow;
        deleteDuplicateContactsBatch del = new deleteDuplicateContactsBatch();
        Database.executeBatch(del);
        
        
        
    }
    
    // Create a list of account records specified in the size...
    public static List<Account> loadAccount(Integer size){
        List<Account> accts = new List<Account> ();
        Id recId = Schema.SObjectType.Account.RecordTypeInfosByName.get('North American Customer').RecordTypeId;
        
        for(Integer i=0;i<size;i++){
            Account acc  = new Account(name='Test Account' + String.valueOf(i), Industry='Other', BillingCity='San Francisco', RecordTypeId = recId,
                                       BillingStreet='Ellis Street, CA', Website= 'www.domain.net');
            accts.add(acc);
        }
        return accts;
    }
    
    
    public static List<Contact> createContactWithAccount(Integer size, List<account> acclst){
        List<Contact> conts = new List<Contact> ();
        for(Integer i=0;i<size;i++){
            Contact con = New Contact(FirstName ='Test',
                                      email = 'abc@123.com',LastName = 'Test Contact', Position_Job_Title__c='Administrator',Credentials__c='RN',Preferred_language__c='English (American)',accountId = acclst[i].Id);
            conts.add(con);
        }
        Contact con = New Contact(FirstName ='Test1',
                                  email = 'abc@123.com',LastName = 'Test Contact', Position_Job_Title__c='Administrator',Credentials__c='RN',Preferred_language__c='English (American)',accountId = acclst[1].Id);
        return conts;    
    }
    
    public static List<Contact> createContactWithoutAccount(Integer size){
        List<Contact> conts = new List<Contact> ();
        for(Integer i=0;i<size;i++){
            Contact con = New Contact(FirstName ='Test',
                                      email = 'abc@123.com',LastName = 'Test Contact',Position_Job_Title__c='Administrator',
Credentials__c='RN',
Preferred_language__c='English (American)');
            conts.add(con);
        }
        return conts;    
    }
}