fullSandbox11072023/force-app/main/default/objects/Contact/fields/Credentials__c.field-meta.xml
<CustomField>
    <fullName>Credentials__c</fullName>
    <description>Medical Credentials</description>
    <inlineHelpText>Medical Credentials</inlineHelpText>
    <label>Credentials</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BSN</fullName>
            </value>
            <value>
                <fullName>CCEMT</fullName>
            </value>
            <value>
                <fullName>Certified Registered Nurse Anesthetists</fullName>
            </value>
            <value>
                <fullName>CRNA</fullName>
            </value>
            <value>
                <fullName>CRT</fullName>
            </value>
            <value>
                <fullName>CST</fullName>
            </value>
            <value>
                <fullName>CT Tech</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>Doctor of Veterinary Medicine</fullName>
            </value>
            <value>
                <fullName>DVM</fullName>
            </value>
            <value>
                <fullName>EMT</fullName>
            </value>
            <value>
                <fullName>EMT-P</fullName>
            </value>
            <value>
                <fullName>FTO</fullName>
            </value>
            <value>
                <fullName>ICP</fullName>
            </value>
            <value>
                <fullName>Infection Control Personnel</fullName>
            </value>
            <value>
                <fullName>M.H.S. RRT</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MD, FACS</fullName>
            </value>
            <value>
                <fullName>Medical Doctor</fullName>
            </value>
            <value>
                <fullName>MHA</fullName>
            </value>
            <value>
                <fullName>MICT, ASN</fullName>
            </value>
            <value>
                <fullName>MPH</fullName>
            </value>
            <value>
                <fullName>MSN</fullName>
            </value>
            <value>
                <fullName>MSO</fullName>
            </value>
            <value>
                <fullName>NP</fullName>
            </value>
            <value>
                <fullName>NREMT</fullName>
            </value>
            <value>
                <fullName>NREMT-P</fullName>
            </value>
            <value>
                <fullName>Nurse Practitioner</fullName>
            </value>
            <value>
                <fullName>Other/None</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Position_Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Position_Job_Title__c</fullName>
    <label>Position/Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abdominal Transplant Surgeon</fullName>
            </value>
            <value>
                <fullName>Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>ALS Provider</fullName>
            </value>
            <value>
                <fullName>Anesthesia Director</fullName>
            </value>
            <value>
                <fullName>Anesthesia Tech</fullName>
            </value>
            <value>
                <fullName>Anesthesiologist</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Asst Chief</fullName>
            </value>
            <value>
                <fullName>Bariatric Surgeon</fullName>
            </value>
            <value>
                <fullName>Bio Med</fullName>
            </value>
            <value>
                <fullName>BLS Provider</fullName>
            </value>
            <value>
                <fullName>Buyer/Purchasing Staff</fullName>
            </value>
            <value>
                <fullName>Captain</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Director</fullName>
            </value>
            <value>
                <fullName>Cardiopulmonary Manager</fullName>
            </value>
            <value>
                <fullName>Category Manager</fullName>
            </value>
            <value>
                <fullName>CCL Manager</fullName>
            </value>
            <value>
                <fullName>CCL Scheduler</fullName>
            </value>
            <value>
                <fullName>Central Supply</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Chief Nursing Officer</fullName>
            </value>
            <value>
                <fullName>Chief of CV</fullName>
            </value>
            <value>
                <fullName>Chief of General Surgery</fullName>
            </value>
            <value>
                <fullName>Chief of GYN</fullName>
            </value>
            <value>
                <fullName>CLABSI Team</fullName>
            </value>
            <value>
                <fullName>Clinical Director</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/fields/Preferred_language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_language__c</fullName>
    <label>Preferred language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English (American)</fullName>
            </value>
            <value>
                <fullName>English (Australian)</fullName>
            </value>
            <value>
                <fullName>English (New Zealand)</fullName>
            </value>
            <value>
                <fullName>French (Canada)</fullName>
            </value>
            <value>
                <fullName>French (France)</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Hebrew (right to left)</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Portuguese (Brazil)</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Simplified Chinese (China)</fullName>
            </value>
            <value>
                <fullName>Spanish (Latin America)</fullName>
            </value>
            <value>
                <fullName>Traditional Chinese (Hong Kong/Taiwan)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>Standard contact record type for all Teleflex contacts</description>
    <label>Contact</label>
</RecordType>

fullSandbox11072023/force-app/main/default/classes/OptOut_Test.cls
@isTest
public class OptOut_Test {
    public static testMethod void testOptOut(){
        PageReference pageRef = Page.OptOut;
        Test.setCurrentPage(pageRef);
        
        Account a = new account(
            Name = 'Test'
        );
        insert a;
        
        Contact c = new contact(
            FirstName='Test',
            Lastname = 'Test',
            Email = 'abc@123.com',
            Position_Job_Title__c='Administrator',
            Credentials__c='RN',
            Preferred_language__c='English (American)',
            AccountID = a.Id
        );
        insert c;
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('email', 'abc@123.com');
        
        OptOut controller = new OptOut();
        String nextPage = controller.save().getUrl();
        
        
        
    }
}