fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/Business_Metrics__c.object-meta.xml
<CustomObject>
    <label>Business Metrics</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Business_Unit_Key__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Key__c</fullName>
    <label>Business Unit Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <formula>if(
AND(
ISPICKVAL(Type__c, &quot;Custom URL&quot;),
NOT(ISBLANK(Custom_URL__c))
), Custom_URL__c,
if(
AND(
ISPICKVAL(Type__c, &quot;Report&quot;),
NOT(ISBLANK(Report_Id__c))
), &quot;/&quot; &amp;  Report_Id__c,
NULL
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Link</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Need Help?</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Leading Indicators</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
            <value>
                <fullName>Sales Reporting</fullName>
            </value>
            <value>
                <fullName>Open Orders</fullName>
            </value>
            <value>
                <fullName>Leads</fullName>
            </value>
            <value>
                <fullName>Opportunities</fullName>
            </value>
            <value>
                <fullName>Daily Sales</fullName>
            </value>
            <value>
                <fullName>Customer Service Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Sorting_Order__c.field-meta.xml
<CustomField>
    <fullName>Sorting_Order__c</fullName>
    <label>Sorting Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/Invoiced_Sales__c.object-meta.xml
<CustomObject>
    <description>Invoiced Sales is the official name that SAP sales that have are shipped and counted towards compensation.</description>
    <label>Invoiced Sales</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Invoiced Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoiced Sales</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Invoiced_Sales__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoiced Sales</relationshipLabel>
    <relationshipName>Invoiced_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Business_Metrics_Page_Class.cls
public class Business_Metrics_Page_Class {
    
    public map<String, list<Business_Metrics__c>> megaMap {get; set;}
    public list<String> buList {get; set;}
    
    public Business_Metrics_Page_Class(){
        megaMap = new map<String, list<Business_Metrics__c>>();
        buList = new list<String>();
        set<String> buSet = new set<String>();
        Id userId = UserInfo.getUserId();
        String buKey;
        for(User u : [SELECT Business_Unit_Key__c 
                     FROM User
                     WHERE Id = :UserInfo.getUserId()])
        {
            buKey = u.Business_Unit_Key__c;
        }
        
        for(Business_Metrics__c BMX : [SELECT Id, Name, Section__c, Link__c, Business_Unit_Key__c 
                                      FROM Business_Metrics__c 
                                      WHERE (Business_Unit_Key__c like :'%'+buKey+'%' OR Business_Unit_Key__c like 'All')
                                      ORDER BY Section__c, Sorting_Order__c])
        {
            system.debug('Business_Unit_Key__c: ' + BMX.Business_Unit_Key__c);
            if(megaMap.containsKey(BMX.Section__c)){
                megaMap.get(BMX.Section__c).add(BMX);
            }
            else{
                megaMap.put(BMX.Section__c, new list<Business_Metrics__c>{BMX});
            }
            buSet.add(BMX.Section__c);
        }
        buList.addAll(buSet);
        /*
         if(isVPSMap.containsKey(is.Account__c)){
                    isVPSMap.get(is.Account__c).add(is);
                }
                else{
                    isVPSMap.put(is.Account__c, new list<Invoiced_Sales__c>{is});    
                }*/
        
    }

}