fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/Business_Metrics__c.object-meta.xml
<CustomObject>
    <label>Business Metrics</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Surgical Disposables</fullName>
            </value>
            <value>
                <fullName>Surgical Instruments</fullName>
            </value>
            <value>
                <fullName>Alternate Care</fullName>
            </value>
            <value>
                <fullName>Anesthesia</fullName>
            </value>
            <value>
                <fullName>Interventional Capital</fullName>
            </value>
            <value>
                <fullName>EMS</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Respiratory</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>National Accounts</fullName>
            </value>
            <value>
                <fullName>Surgical Percuvance</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Commercial Operations</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Business_Unit_Key__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Key__c</fullName>
    <label>Business Unit Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <label>Report Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Metrics__c/fields/Report_Label_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Label_Name__c</fullName>
    <label>Report Label Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/Business_Unit__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Drives Account Pages and Business Unit Lookup</description>
    <label>Business Unit</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Business_Unit__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/Business_Metrics_Helper_Class.cls
public class Business_Metrics_Helper_Class {
    
    public static void setBUKey(List<Business_Metrics__c> newTrigger){
        
        String buKeyList;
        String buKey;
        String buSet;
        Map<String,Business_Unit__c> buMap = Business_Unit__c.getAll();
        for(Business_Metrics__c bmx : newTrigger){
            buKey = NULL;
            if(bmx.Business_Unit__c != NULL){
                buKeyList = bmx.Business_Unit__c;
                List<String> buValues = buKeyList.split(';');

                for(string s : buValues){
                    if(s == 'All'){
                        buSet = 'All';
                    }
                    else if(buMap.containsKey(s)){
                        buSet = buMap.get(s).Key__c;
                    }
                    else{
                        buSet = NULL;
                    }
                    //system.debug('s: ' + s);
                    if(buSet != NULL){
                        if(buKey == NULL){
                            buKey = buSet;
                        }
                        else{
                            buKey = buKey + ', ' + buSet;
                        } 
                    }
                    
                }
                bmx.Business_Unit_Key__c = buKey;
            }
        }
    }
    
    public static void setReportURL(List<Business_Metrics__c> newTrigger){

        set<String> reportSet = new set<String>();
        for(Business_Metrics__c bmx : newTrigger){
            if(bmx.Report_Label_Name__c != NULL){
                reportSet.add(bmx.Report_Label_Name__c);                
            }
        }
        if(reportSet.size() > 0){
            map<String, Id> reportMap = new map<String, Id>();
            for(Report r : [SELECT Id, DeveloperName 
                            FROM Report 
                            WHERE DeveloperName = :reportSet])
            {
                reportMap.put(r.DeveloperName, r.Id);
            }
            for(Business_Metrics__c bmx : newTrigger){
                if(reportMap.containsKey(bmx.Report_Label_Name__c)){
                    bmx.Report_Id__c = reportMap.get(bmx.Report_Label_Name__c);
                }
                else{
                    bmx.Report_Id__c = NULL;
                }
            }
        }
    }

}