fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_10__c.field-meta.xml
<CustomField>
    <fullName>Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_20__c.field-meta.xml
<CustomField>
    <fullName>Division_20__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 20</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_30__c.field-meta.xml
<CustomField>
    <fullName>Division_30__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 30</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_40__c.field-meta.xml
<CustomField>
    <fullName>Division_40__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 40</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_50__c.field-meta.xml
<CustomField>
    <fullName>Division_50__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 50</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_60__c.field-meta.xml
<CustomField>
    <fullName>Division_60__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 60</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/Contract_Material__c.object-meta.xml
<CustomObject>
    <label>Contract Material</label>
    <nameField>
        <label>Contract Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <formula>Agreement__r.Agreement_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Number</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement_Number_Text__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number_Text__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Material</relationshipLabel>
    <relationshipName>Contract_Material</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <inlineHelpText>10 - Respiratory and Anesthesia (TFX Only), 
20 - Surgical, 
30 - Surgical, 
40 - Vascular, 
50 - Anesthesia (Arrow Only), 
60 - Cardiac</inlineHelpText>
    <label>Division</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Contract_Header_Build_Divisions_Batch.cls
/*********************************************************************
* Description      : Controller Class for Pricing Portal Contract Process.
* Test Class       : PP_Build_Contract_Divisions_Test
* Author(s)        : Eric Clay
**********************************************************************/
global class PP_Contract_Header_Build_Divisions_Batch Implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query;

        query = 'SELECT Id, Agreement_Number__c, Division_10__c, Division_20__c, Division_30__c, Division_40__c, ';
        query += 'Division_50__c, Division_60__c FROM Contract_Header__c';

        system.debug('Starting Batch: ' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){

        // Setup

        string div;
        string anum;
        boolean updateCH;

        list<Contract_Header__c> chList = (list<Contract_Header__c>)scope;
        list<Contract_Header__c> chUpdate = new list<Contract_Header__c>();

        set<String> chSet = new set<String>();

        map<String, Boolean> divMap = new map<String, Boolean>();

        // Start Work

        // Create a set of Agreement Numbers to use to filter our Contract Material aggregate
        for(Contract_Header__c ch : chList){
            chSet.add(ch.Agreement_Number__c);
            divMap.put(ch.Agreement_Number__c + '10', FALSE);
            divMap.put(ch.Agreement_Number__c + '20', FALSE);
            divMap.put(ch.Agreement_Number__c + '30', FALSE);
            divMap.put(ch.Agreement_Number__c + '40', FALSE);
            divMap.put(ch.Agreement_Number__c + '50', FALSE);
            divMap.put(ch.Agreement_Number__c + '60', FALSE);
        }

        // Aggregate Product Division in to a map
        for(AggregateResult ar : [SELECT Product__r.Division__c prod, Agreement_Number_Text__c
                                  FROM Contract_Material__c
                                  WHERE Agreement_Number_Text__c =:chSet
                                  GROUP BY Product__r.Division__c, Agreement_Number_Text__c])
        {
            div = (string) ar.get('prod');
            anum = (string) ar.get('Agreement_Number_Text__c');
            divMap.put(anum + div, TRUE);
        }
        system.debug('divMap: ' + divMap);

        // Finish up...
        for(Contract_Header__c ch : chList){
            updateCH = FALSE;
            Contract_Header__c newCH = new Contract_Header__c(
                Id = ch.Id
            );
            if(divMap.get(ch.Agreement_Number__c + '10') != ch.Division_10__c){
                newCH.Division_10__c = divMap.get(ch.Agreement_Number__c + '10');
                updateCH = TRUE;
            }
            if(divMap.get(ch.Agreement_Number__c + '20') != ch.Division_20__c){
                newCH.Division_20__c = divMap.get(ch.Agreement_Number__c + '20');
                updateCH = TRUE;
            }
            if(divMap.get(ch.Agreement_Number__c + '30') != ch.Division_30__c){
                newCH.Division_30__c = divMap.get(ch.Agreement_Number__c + '30');
                updateCH = TRUE;
            }
            if(divMap.get(ch.Agreement_Number__c + '40') != ch.Division_40__c){
                newCH.Division_40__c = divMap.get(ch.Agreement_Number__c + '40');
                updateCH = TRUE;
            }
            if(divMap.get(ch.Agreement_Number__c + '50') != ch.Division_50__c){
                newCH.Division_50__c = divMap.get(ch.Agreement_Number__c + '50');
                updateCH = TRUE;
            }
            if(divMap.get(ch.Agreement_Number__c + '60') != ch.Division_60__c){
                newCH.Division_60__c = divMap.get(ch.Agreement_Number__c + '60');
                updateCH = TRUE;
            }

            if(updateCH){
                chUpdate.add(newCH);
            }
        }
        if(chUpdate.size() > 0){
            system.debug('-- Updating CH with CM Divisions --' + chUpdate);
            update chUpdate;
        }


    }


    global void finish(Database.BatchableContext BC){
        //UserInfo.getUserEmail();
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob WHERE Id =
                          :BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {a.CreatedBy.Email};
            mail.setToAddresses(toAddresses);
        mail.setSubject('Build Contracts Headers Finished: ' + a.Status);
        mail.setPlainTextBody
            ('The batch Apex job processed ' + a.JobItemsProcessed +
             ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

}