fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c  &gt;=  TODAY() &amp;&amp; Valid_From__c  &lt;=  TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Parent_Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Contract_Name__c</fullName>
    <formula>if(
OR(
RIGHT(GPO_Contract_Ref__c,2) = &quot;-T&quot;,
RIGHT(GPO_Contract_Ref__c,2) = &quot;-R&quot;,
RIGHT(GPO_Contract_Ref__c,2) = &quot;-M&quot;,
RIGHT(GPO_Contract_Ref__c,2) = &quot;-D&quot;
),
UPPER(TRIM(LEFT(Description__c,LEN(Description__c)-2))),
NULL
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Contract Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <formula>AND(
Sub_Group__c = &quot;8&quot;,
OR(
RIGHT(GPO_Contract_Ref__c,2) = &quot;-D&quot;,
RIGHT(GPO_Contract_Ref__c,2) = &quot;-M&quot;,
RIGHT(GPO_Contract_Ref__c,2) = &quot;-R&quot;,
AND(RIGHT(GPO_Contract_Ref__c,2) = &quot;-N&quot;, Sales_Org__c = &quot;CA10&quot;),
RIGHT(GPO_Contract_Ref__c,3) = &quot;-VP&quot;
),
Owner__c = &quot;123310&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Filters Contracts based on Group 8, GPO Ref ending in -R, -M, or -D and the owner being 123310 / Teleflex</inlineHelpText>
    <label>Pricing Tier</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/Contract_Material__c.object-meta.xml
<CustomObject>
    <label>Contract Material</label>
    <nameField>
        <label>Contract Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Material</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c &gt;= TODAY() &amp;&amp; Valid_From__c &lt;= TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <label>Agreement</label>
    <referenceTo>Contract_Header__c</referenceTo>
    <relationshipLabel>Contract Material</relationshipLabel>
    <relationshipName>Contract_Materials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Agreement_Number_Text__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number_Text__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>/* Exceptions */
/* Price Equals one of the Tiers and the Tiers equal themselves */
if(
AND(
OR(
Rep_Price__c = RSM_Price__c,
RSM_Price__c = Director_Price__c,
Director_Price__c = VP_Price__c
),
OR(
Price__c = Rep_Price__c,
Price__c = RSM_Price__c,
Price__c = Director_Price__c,
Price__c = VP_Price__c
)
),
Level_Fix__c,

/* Price is between REP and List but RSM and REP equal each other contract is set for RSM */
if(
AND(
Rep_Price__c = RSM_Price__c,
Price__c &gt;= RSM_Price__c
),
Level_Fix__c,

/* Normal */
/* Rep Level */
if(
OR(
Price__c &gt;= Rep_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= Rep_Price__c
)),
1,
/* RSM Level */
if(
OR(
Price__c &gt;= RSM_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= RSM_Price__c
)),
2,
/* DIR Level */
if(
OR(
Price__c &gt;= Director_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= Director_Price__c 
)),
3,
/* VP Level */
if(
OR(
Price__c &gt;= VP_Price__c,
AND(
Price__c &lt;= List_Price__c,
Price__c &gt;= VP_Price__c 
)),
4,
Level_Fix__c
))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Material_Name__c.field-meta.xml
<CustomField>
    <fullName>Material_Name__c</fullName>
    <externalId>true</externalId>
    <label>Material Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <formula>Agreement__r.Pricing_Tier__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pricing Tier</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Material</relationshipLabel>
    <relationshipName>Contract_Material</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Material__c/fields/Tier_Level_Name__c.field-meta.xml
<CustomField>
    <fullName>Tier_Level_Name__c</fullName>
    <description>CASE(Level__c, 
1, &quot;REP&quot;, 
2, &quot;RSM&quot;,
3, &quot;DIR&quot;,
4, &quot;VP&quot;,
&quot;Out of Range&quot;
)</description>
    <formula>IF( AND(Level__c = 1,CONTAINS(Agreement__r.GPO_Contract_Ref__c, &quot;-N&quot;),Sales_Org__c = &quot;CA10&quot; ),&quot;National Tier&quot;,
IF(
Level__c = 1, &quot;REP&quot;,
IF(
Level__c = 2, &quot;RSM&quot;,
IF(
Level__c = 3, &quot;DIR&quot;,
IF(
Level__c = 4, &quot;VP&quot;,&quot;Out of Range&quot;
)
)
)
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tier Level Name</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org_Key__c</fullName>
    <label>Active Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/PRF__c.object-meta.xml
<CustomObject>
    <label>PRF</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipLabel>PRF</relationshipLabel>
    <relationshipName>PRF</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/PRF__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/Price_Quote__c.object-meta.xml
<CustomObject>
    <description>Used for Pricing portal instead of standard quotes object</description>
    <label>Price Quote</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Price Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/PRF__c.field-meta.xml
<CustomField>
    <fullName>PRF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PRF</label>
    <referenceTo>PRF__c</referenceTo>
    <relationshipLabel>Price Quotes</relationshipLabel>
    <relationshipName>Price_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Price_Quote__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Pricing_Tiers.cls
global without sharing class PP_Pricing_Tiers {

    //global list<String> tierHeaderList {get; set;} // Used to store the final list of pricing levels in order: REP1, REP2, RSM1, etc.
    //global set<String> tierHeaderNames2 {get; set;} // Stores the major header names: REP, RSM, DIR
    //global map<String, Integer> tierLevels {get; set;} // Used to store how many levels REP, RSM, DIR go in order to span columns appropriately

    //public string testSub {get { return 'Hi'; } set;}
    //global static string salesOrg {get; set;}
    //tierHeaderNames = new set<String>();
    //tierLevels = new map<String, Integer>();
    /*
    list<String> rankSortOrder = new list<String>();
    rankSortOrder.add('REP');
    rankSortOrder.add('RSM');
    rankSortOrder.add('DIR');*/

    //get active sales org key of User
    public String myActiveSalesOrg { get{
      try{
        myActiveSalesOrg = [SELECT Active_Sales_Org_Key__c
                          FROM Contract_User__c
                          WHERE User__c = :UserInfo.getUserId()
                          LIMIT 1].Active_Sales_Org_Key__c;

        if(myActiveSalesOrg == '' || myActiveSalesOrg == NULL){
            myActiveSalesOrg = 'US6010';
        }
      }
      catch(Exception e){
        System.debug('*** Exception occured in PP_Pricing_Tiers myActiveSalesOrg: ' + e);
      }

      return myActiveSalesOrg;
    } set;}
    
    public String pqSalesOrgKey { get{
      try{
          System.debug('*** ApexPages.currentPage().getParameters().get(pqid) *** ' + ApexPages.currentPage().getParameters().get('pqid'));
          if(ApexPages.currentPage().getParameters().get('pqid') != null && ApexPages.currentPage().getParameters().get('pqid') != ''){
              System.debug('*** Setting pqSalesOrgKey using PQ ID in PP_Pricing_Tiers class ***');
              pqSalesOrgKey = [SELECT Id, Sales_Org_Key__c
                               FROM Price_Quote__c
                               WHERE Id = :ApexPages.currentPage().getParameters().get('pqid')
                               LIMIT 1].Sales_Org_Key__c;
          }
          else if(ApexPages.currentPage().getParameters().get('id') != null && ApexPages.currentPage().getParameters().get('id') != ''){
                  System.debug('*** Setting pqSalesOrgKey using PRF ID in PP_Pricing_Tiers class ***');
                  pqSalesOrgKey = [SELECT Id, Sales_Org_Key__c
                                   FROM PRF__c
                                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')
                                   LIMIT 1].Sales_Org_Key__c;
              }
          else if(ApexPages.currentPage().getParameters().get('pqid') != ''){
              System.debug('*** Setting pqSalesOrgKey to user active key PP_Pricing_Tiers class ***');
              pqSalesOrgKey = [SELECT Active_Sales_Org_Key__c
                          FROM Contract_User__c
                          WHERE User__c = :UserInfo.getUserId()
                          LIMIT 1].Active_Sales_Org_Key__c;
          }
          else{
              if(ApexPages.currentPage().getParameters().get('pqid') == '' || ApexPages.currentPage().getParameters().get('pqid') == null){
                  System.debug('*** Setting pqSalesOrgKey to US6010 in PP_Pricing_Tiers class ***');
                  pqSalesOrgKey = 'US6010';
              }
          }
          System.debug('*** pqSalesOrgKey PP_Pricing_Tiers class *** ' + pqSalesOrgKey);
          
      }
      catch(Exception e){
        System.debug('*** Exception occured in PP_Pricing_Tiers class pqSalesOrgKey: ' + e);
      }

      return pqSalesOrgKey;
    } set;}
    
    public without sharing class tiers{
        public string Name {get; set;} // Agreement Number
        public string chDesc {get; set;} // Contract Description
        public string chGPORef {get; set;} // Contract GPO Ref

        // Contract Price
        public decimal Price {get; set;} // Contract Price
        public id chId {get; set;} // Contract Header id
        public id cmId {get; set;} // Contract Material id

        public string TierHeaderNames {get; set;} // REP, RSM, DIR
        public string TierName {get; set;} // REP1, REP2, RSM1, etc.
        public decimal TierLevel {get; set;} // 1,2,3
        public string Product_Name {get; set;} // Product Name

        public string chKey {get; set;} // Parent Contract Description - Name of the Contract minus the level (-R1, -R2, -M1, etc.)

    }
    //Product Id's
    /*
    public list<String> getTierHeaderNames(map<String, tiers> tMap){
        
        System.debug('*** Starting getTierHeaderNames ***');
        list<String> returnList = new list<String>();
        list<String> rankSortOrder = new list<String>();
        rankSortOrder.add('REP');
        rankSortOrder.add('RSM');
        rankSortOrder.add('DIR');
        map<String, Boolean> mapCheck = new map<String, Boolean>();
        for(tiers t : tMap.values()){
            mapCheck.put(t.TierHeaderNames, TRUE);
        }


        for(String s : rankSortOrder){
            if(mapCheck.containsKey(s)){
                returnList.add(s);
            }
            for (Integer i = 0; i < 5; i++) { // Should only be 3 but just in case we do 5 passes
                if(buildHeaders.contains(s+string.valueOf(i))){
                    tierHeaderNames.add(s);
                    if(tierLevels.containsKey(s)){
                        tierLevels.put(s, 1+tierLevels.get(s));
                    }
                    else{
                        tierLevels.put(s, 1);
                    }
                    tierHeaderList.add(s+string.valueOf(i));
                }
                //system.debug('tierLevels: ' + tierLevels);
            }
        }

        System.debug('*** Starting getTierHeaderNames ***');
        System.debug('*** returnList *** ' + returnList);
        return returnList;
    }
	*/
    public list<String> getTierHeaderLevels(map<String, tiers> tMap){
        System.debug('*** Starting getTierHeaderLevels ***');
        list<String> returnList = new list<String>();
        set<String> buildHeaders = new set<String>();
        list<String> rankSortOrder = new list<String>();
        rankSortOrder.add('National Tier');
        rankSortOrder.add('REP');
        rankSortOrder.add('RSM');
        rankSortOrder.add('DIR');
        rankSortOrder.add('VP');
		
        map<String, Boolean> mapCheck = new map<String, Boolean>();
        for(tiers t : tMap.values()){
            mapCheck.put(t.TierName, TRUE);
            System.debug('*** t *** ' + t);
        }

        for(String s : rankSortOrder){
            for (Integer i = 0; i <= mapCheck.size(); i++) { // Should only be 3 but just in case we do 5 passes
                if(mapCheck.containsKey(s+string.valueOf(i))){
                    returnList.add(s+string.valueOf(i));
                }
            }
        }
        return returnList;
    }

    public map<String, tiers> getTiers(list<product2> plist, integer level){
      System.debug('*** Starting getTiers ***');
      //System.debug('*** pqid *** ' + ApexPages.currentPage().getParameters().get('pqid')); 
      System.debug('*** level *** ' + level);  
        system.debug('*** plist Count: *** ' + plist.size());
        system.debug('*** plist *** ' + plist );
        system.debug('*** pqSalesOrgKey IN getTiers PP_Pricing_Tiers class *** ' + pqSalesOrgKey );
        //null value check
        if(pqSalesOrgKey == null || pqSalesOrgKey == 'null'){
            system.debug('*** Setting pqSalesOrgKey IN getTiers PP_Pricing_Tiers class 2nd null check *** ');
            pqSalesOrgKey = 'US6010';
        }
        
        string strPlist = '';
        if(plist.size() > 0){
            strPlist = plist[0].id;
        }
        map<String, tiers> tierMap = new map<String, tiers>();
        set<String> buildHeaders = new set<String>(); // Temporary list of pricing levels - Used to build tierHeaderList
        map<String, Integer> tierLevels = new map<String, Integer>();
        integer tierLevel = 1;
        integer debugLoop = 1;
        string tierRankName;
        string prevTierName;
        string prevMaterialName;

        string salesOrg = pqSalesOrgKey.left(4);
        System.debug('*** salesOrg *** ' + salesOrg);  
        for(Contract_Material__c cm : [SELECT Id, Level__c, Material_Name__c, Price__c, Product__c,
                                       Agreement_Number_Text__c, Tier_Level_Name__c, Agreement__c,
                                       Agreement__r.Description__c, Agreement__r.Parent_Contract_Name__c,
                                       Agreement__r.GPO_Contract_Ref__c
                                       FROM Contract_Material__c
                                       WHERE Product__c IN :plist
                                       AND Active__c = TRUE
                                       AND Agreement__r.Pricing_Tier__c = TRUE
                                       AND Level__c <= :level
                                       AND Sales_Org__c =:salesOrg
                                       ORDER BY Material_Name__c, Level__c ASC, Price__c DESC])
        {
            //system.debug('Starting CM [' + debugLoop + ']');
            // Determine what tier and level
            System.debug('*** cm *** ' + cm);
            if(
                prevTierName == NULL || // First Record
                prevMaterialName != cm.Material_Name__c || // Material Changed
                prevTierName != cm.Tier_Level_Name__c // Tier Changed
            ){
                tierLevel = 1;
            }
            // Set the Tier Name to something like 'REP1' or 'RSM2', etc.
            tierRankName = cm.Tier_Level_Name__c + string.valueOf(tierLevel);

            // Add to the Tiers Map - Will have to re-order to ensure that the order is REP, RSM, DIR, VP
            buildHeaders.add(tierRankName);

            // Create the abstract record
            tiers newTier = new tiers();

            newTier.Name = cm.Agreement_Number_Text__c; // Agreement Number
            newTier.chId = cm.Agreement__c; // Contract Header ID
            newTier.chDesc = cm.Agreement__r.Description__c; // Contract Description
            newTier.cmId = cm.Id; // Contract Material ID
            newTier.TierLevel = cm.Level__c; // 1,2,3
            newTier.TierName = tierRankName; // REP1, RSM2, etc.
            newTier.Price = cm.Price__c; // Price
            newTier.Product_Name = cm.Material_Name__c;
            newTier.chKey = cm.Agreement__r.Parent_Contract_Name__c; // Name of the Contract minus the level (-R1, -R2, -M1, etc.)
            //Below if statement fixes Out of Range error when searching for products
            if(cm.Tier_Level_Name__c != 'Out of Range'){
                System.debug('*** Out of Range *** ');
                newTier.TierHeaderNames = cm.Tier_Level_Name__c;
            }
             // REP, RSM, DIR
            newTier.chGPORef = cm.Agreement__r.GPO_Contract_Ref__c; // GPO Reference
            system.debug('*** cm.Tier_Level_Name__c *** ' + cm.Tier_Level_Name__c);
            system.debug('*** newTier[' + debugLoop + ']: *** ' + newTier);
            
            // Add to the Map
            tierMap.put(tierRankName + '-' + cm.Material_Name__c,newTier);

            // Cleanup for the next loop
            prevMaterialName = cm.Material_Name__c;
            prevTierName = cm.Tier_Level_Name__c;
            ++tierLevel;

            // Debug
            ++debugLoop;

        }
        //plist
        //if(plist.size() > 0){
            // Re-Order the headers so that REP, RSM, and DIR go in order and not the order that the data added to the set.
            // Otherwise you might get REP1, RSM1, RSM2, REP2, REP3
            list<String> tierHeaderList = new list<String>();
            list<String> rankSortOrder = new list<String>();
        	rankSortOrder.add('National Tier');
            rankSortOrder.add('REP');
            rankSortOrder.add('RSM');
            rankSortOrder.add('DIR');
        	rankSortOrder.add('VP');
			
            for(String s : rankSortOrder){
                for (Integer i = 0; i <= buildHeaders.size(); i++) { // Should only be 3 but just in case we do 5 passes
                    if(buildHeaders.contains(s+string.valueOf(i))){
                        /*
                        tierHeaderNames.add(s);
                        if(tierLevels.containsKey(s)){
                            tierLevels.put(s, 1+tierLevels.get(s));
                        }
                        else{
                            tierLevels.put(s, 1);
                        }*/
                        tierHeaderList.add(s+string.valueOf(i));
                    }//end if buildHeaders
                }
            }
			System.debug('*** tierHeaderList.size() *** ' + tierHeaderList.size() );
        	System.debug('*** tierHeaderList *** ' + tierHeaderList);
            // Ensure that each level of pricing has a value even if it is zero so that there are no nulls in the map when iterating/looping
            for(product2 p : plist){
                for(String s : tierHeaderList){
                    // Logic that when a value is not present a zero price value is inserted. In the VF we will replace the zero (0) with a dash (-)
                    System.debug('*** s *** ' + s);
                    System.debug('*** s.left(3) *** ' + s.left(3) ); 
                    if(!tierMap.containsKey(s + '-' + p.Name)){
						System.debug('*** INSIDE !tierMap.containsKey(s) ***'); 
                        system.debug('*** p.Name: ' + p.Name);
                        tiers newTier = new tiers();
                        newTier.TierName = s + '-' + p.Name;
                        newTier.Price = 0;
                        newTier.Name = 'None'; // Agreement Number
                        newTier.Product_Name = p.Name;
                        newTier.chDesc = 'None'; // Contract Description
                        newTier.TierLevel = decimal.valueOf(s.right(1)); // 1,2,3
                        newTier.TierName = s; // REP1, RSM2, etc.
                        newTier.chKey = 'None'; // Name of the Contract minus the level (-R1, -R2, -M1, etc.)
                        if(s.containsIgnoreCase('National Tier') || s == 'VP'){
                            newTier.TierHeaderNames = s; // National Tier, VP
                        }
                        else{
                            newTier.TierHeaderNames = s.left(3); // REP, RSM, DIR
                        }
                        newTier.chGPORef = 'None'; // GPO Reference
                        system.debug('*** newTier: ' + newTier);
                        tierMap.put(s + '-' + p.Name, newTier);
                    }
                }
            }
        //}
        System.debug('*** tierMap.size() *** ' + tierMap.size() );
        System.debug('*** tierMap *** ' + tierMap);
        System.debug('*** Ending getTiers ***');
        return tierMap;
    }
}