fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Account_Count__c.field-meta.xml
<CustomField>
    <fullName>Account_Count__c</fullName>
    <description>Roll-up of all the related &apos;Contract Customer&apos; records used to determine limits when displaying in Visualforce.</description>
    <inlineHelpText>Roll-up of all the related &apos;Contract Customer&apos; records used to determine limits when displaying in Visualforce.</inlineHelpText>
    <label>Account Count</label>
    <summaryForeignKey>Contract_Customer__c.Agreement__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>if((Valid_To__c  &gt;=  TODAY() &amp;&amp; Valid_From__c  &lt;=  TODAY()), TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Agreement_Number__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Number__c</fullName>
    <externalId>true</externalId>
    <label>Agreement Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_10__c.field-meta.xml
<CustomField>
    <fullName>Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_20__c.field-meta.xml
<CustomField>
    <fullName>Division_20__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 20</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_30__c.field-meta.xml
<CustomField>
    <fullName>Division_30__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 30</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_40__c.field-meta.xml
<CustomField>
    <fullName>Division_40__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 40</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_50__c.field-meta.xml
<CustomField>
    <fullName>Division_50__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 50</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_60__c.field-meta.xml
<CustomField>
    <fullName>Division_60__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 60</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Material_Count__c.field-meta.xml
<CustomField>
    <fullName>Material_Count__c</fullName>
    <description>Roll-up of all the related &apos;Contract Material&apos; records used to determine limits when displaying in Visualforce.</description>
    <inlineHelpText>Roll-up of all the related &apos;Contract Material&apos; records used to determine limits when displaying in Visualforce.</inlineHelpText>
    <label>Material Count</label>
    <summaryForeignKey>Contract_Material__c.Agreement__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/IDN_Picklist__c/IDN_Picklist__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IDN Matrix Drop Down on the Pricing Portal. Use &apos;Active&apos; checkbox to toggle visibility.</description>
    <label>IDN Picklist</label>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/IDN_Picklist__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_IDN_Matrix.cls
/*********************************************************************
* Description      : Controller Class for Pricing Portal IDN Matrix.
* Test Class       : PP_IDN_Matrix_Test
* VisualForce      : PP_IDN_Matrix
* Author(s)        : Eric Clay
**********************************************************************/
public with sharing class PP_IDN_Matrix {

    public list<Contract_Header__c> getIDNlist(){
        try {
            return [Select Owner__c, Owner_Name__c, Agreement_Number__c, Description__c, Group_Name__c,
                    Division_10__c, Division_20__c, Division_30__c, Division_40__c, Division_50__c,
                    Division_60__c, Material_Count__c, Account_Count__c, Valid_From__c, Valid_To__c
                    FROM Contract_Header__c
                    WHERE Active__c = TRUE
                    AND Owner__c = :ApexPages.currentPage().getParameters().get('oid')];
        }
        catch(Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }

    public List<IDN_PickList__c> getItems() {
        try {
            return [SELECT Key__c, Name, Active__c FROM IDN_PickList__c WHERE Active__c = TRUE AND Sales_Org_Key__c = :PP_Menu.salesPrefix ORDER BY Name];
        }
        catch(Exception e){
            system.debug('Exception: ' + e);
            return NULL;
        }
    }

    public String ownerName {
        get {
            String owner_name = '';
            try{
                if(ApexPages.currentPage().getParameters().get('oid') != NULL){
                    owner_name = [Select Owner_Name__c
                                  FROM Contract_Header__c
                                  WHERE Owner_Name__c != NULL
                                  AND Active__c = TRUE
                                  AND Owner__c = :ApexPages.currentPage().getParameters().get('oid')
                                  LIMIT 1].Owner_Name__c;
                }
                return owner_name;
            }
            catch(Exception e){
                system.debug('Exception: ' + e);
                return NULL;
            }
        }
        set; }

    public String ownerID {
        get {
            string owner_id;
            if(ApexPages.currentPage().getParameters().get('oid') != NULL){
                owner_id = ApexPages.currentPage().getParameters().get('oid');
            }
            return owner_id;
        }
        set; }

}