fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/Contract_Header__c.object-meta.xml
<CustomObject>
    <label>Contract Header</label>
    <nameField>
        <label>Contract Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Headers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Contract_Detail__c.field-meta.xml
<CustomField>
    <fullName>Contract_Detail__c</fullName>
    <label>Contract Detail</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Division_10__c.field-meta.xml
<CustomField>
    <fullName>Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_Header__c/fields/Pricing_Tier_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_Access__c</fullName>
    <inlineHelpText>Pulls from the max level from Contract Material through a trigger.
1 = “Pricing Tier 1 - Rep&quot; 
2 = “Pricing Tier 2 - Manager&quot; 
3 = “Pricing Tier 3 - Director&quot; 
4 = “Pricing Tier 4 - VP&quot;</inlineHelpText>
    <label>Pricing Tier Access</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <inlineHelpText>This only drives material visibility</inlineHelpText>
    <label>Active Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT - Austria</fullName>
            </value>
            <value>
                <fullName>AU - Australia</fullName>
            </value>
            <value>
                <fullName>BE - Belgium</fullName>
            </value>
            <value>
                <fullName>BR - Brazil</fullName>
            </value>
            <value>
                <fullName>CA - Canada</fullName>
            </value>
            <value>
                <fullName>CL - Chile</fullName>
            </value>
            <value>
                <fullName>CO - Colombia</fullName>
            </value>
            <value>
                <fullName>CZ - Czech</fullName>
            </value>
            <value>
                <fullName>DE - Germany</fullName>
            </value>
            <value>
                <fullName>ES - Spain</fullName>
            </value>
            <value>
                <fullName>IE - Ireland</fullName>
            </value>
            <value>
                <fullName>LA - Latin America</fullName>
            </value>
            <value>
                <fullName>MX - Mexico</fullName>
            </value>
            <value>
                <fullName>NL - Netherlands</fullName>
            </value>
            <value>
                <fullName>NZ - New Zealand</fullName>
            </value>
            <value>
                <fullName>PL - Poland</fullName>
            </value>
            <value>
                <fullName>PT - Portugal</fullName>
            </value>
            <value>
                <fullName>SK - Slovakia</fullName>
            </value>
            <value>
                <fullName>UK - United Kingdom</fullName>
            </value>
            <value>
                <fullName>US - Teleflex</fullName>
                <default>true</default>
                <label>US - Teleflex</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/AT_Material__c.field-meta.xml
<CustomField>
    <fullName>AT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Austria sales org access.</description>
    <inlineHelpText>Austria sales org access.</inlineHelpText>
    <label>AT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/AU_Material__c.field-meta.xml
<CustomField>
    <fullName>AU_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AU Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/BE_Material__c.field-meta.xml
<CustomField>
    <fullName>BE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Belgium sales org access.</description>
    <inlineHelpText>Belgium sales org access.</inlineHelpText>
    <label>BE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/BR_Material__c.field-meta.xml
<CustomField>
    <fullName>BR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Brazil</description>
    <inlineHelpText>Brazil</inlineHelpText>
    <label>BR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Material__c.field-meta.xml
<CustomField>
    <fullName>CA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CH_Material__c.field-meta.xml
<CustomField>
    <fullName>CH_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Switzerland sales org access.</description>
    <inlineHelpText>Switzerland sales org access.</inlineHelpText>
    <label>CH Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Material__c.field-meta.xml
<CustomField>
    <fullName>CL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CO_Material__c.field-meta.xml
<CustomField>
    <fullName>CO_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CO Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CZ_Material__c.field-meta.xml
<CustomField>
    <fullName>CZ_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Czech sales org access.</description>
    <inlineHelpText>Czech sales org access.</inlineHelpText>
    <label>CZ Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/DE_Material__c.field-meta.xml
<CustomField>
    <fullName>DE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Grants access to DE10 Sales Org.</description>
    <inlineHelpText>Grants access to DE10 Sales Org.</inlineHelpText>
    <label>DE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_10__c.field-meta.xml
<CustomField>
    <fullName>Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Respiratory and Anesthesia (TFX only)</inlineHelpText>
    <label>US Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/ES_Material__c.field-meta.xml
<CustomField>
    <fullName>ES_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Spain sales org access.</description>
    <inlineHelpText>Spain sales org access.</inlineHelpText>
    <label>ES Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/FR_Material__c.field-meta.xml
<CustomField>
    <fullName>FR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>France sales org access.</description>
    <inlineHelpText>France sales org access.</inlineHelpText>
    <label>FR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/GR_Material__c.field-meta.xml
<CustomField>
    <fullName>GR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Greece sales org access.</description>
    <inlineHelpText>Greece sales org access.</inlineHelpText>
    <label>GR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/IE_Material__c.field-meta.xml
<CustomField>
    <fullName>IE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ireland sales org access.</description>
    <inlineHelpText>Ireland sales org access.</inlineHelpText>
    <label>IE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/IT_Material__c.field-meta.xml
<CustomField>
    <fullName>IT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Italy sales org access.</description>
    <inlineHelpText>Italy sales org access.</inlineHelpText>
    <label>IT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Material__c.field-meta.xml
<CustomField>
    <fullName>LA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Material__c.field-meta.xml
<CustomField>
    <fullName>MX_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/NL_Material__c.field-meta.xml
<CustomField>
    <fullName>NL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Netherlands sales org access.</description>
    <inlineHelpText>Netherlands sales org access.</inlineHelpText>
    <label>NL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/NZ_Material__c.field-meta.xml
<CustomField>
    <fullName>NZ_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NZ Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/PL_Material__c.field-meta.xml
<CustomField>
    <fullName>PL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Poland sales org access.</description>
    <inlineHelpText>Poland sales org access.</inlineHelpText>
    <label>PL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Pricing_Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Portal_Access__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Pricing Portal Access</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Pricing_Tier_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_Access__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>1 = “Pricing Tier 1 - Rep&quot;
2 = “Pricing Tier 2 - Manager&quot;
3 = “Pricing Tier 3 - Director&quot;
4 = “Pricing Tier 4 - VP&quot;</inlineHelpText>
    <label>Pricing Tier Access</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/PT_Material__c.field-meta.xml
<CustomField>
    <fullName>PT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Portugal sales org access.</description>
    <inlineHelpText>Portugal sales org access.</inlineHelpText>
    <label>PT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/SA_Material__c.field-meta.xml
<CustomField>
    <fullName>SA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>South Africa sales org access.</description>
    <inlineHelpText>South Africa sales org access.</inlineHelpText>
    <label>SA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/SK_Material__c.field-meta.xml
<CustomField>
    <fullName>SK_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Slovakia sales org access.</description>
    <inlineHelpText>Slovakia sales org access.</inlineHelpText>
    <label>SK Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/UK_Material__c.field-meta.xml
<CustomField>
    <fullName>UK_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Grants access to UK10 Sales Org.</description>
    <inlineHelpText>Grants access to UK10 Sales Org.</inlineHelpText>
    <label>UK Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Update_Type__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Field used by APEX to filter Sales Org updates vs. User Updates.</description>
    <inlineHelpText>Field used by APEX to filter Sales Org updates vs. User Updates.</inlineHelpText>
    <label>Update Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/US_Material__c.field-meta.xml
<CustomField>
    <fullName>US_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>US Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_GPO_Matrix_Test.cls
/*********************************************************************
* Description      : Test Class for Pricing Portal GPO Matrix.
* Coverage         : Class(PP_GPO_Matrix)
* Author(s)        : Dun Silver, Eric Clay
**********************************************************************/
@isTest
private class PP_GPO_Matrix_Test {
    static testMethod void PP_GPO_Matrix_UnitTest() {
      //String ownerId = UserInfo.getUserId();
      //PageReference gpo = Page.PP_GPO_Matrix;
      //Test.setCurrentPage(gpo);
      //gpo.getParameters().put('oid','GPO-008');

      //Created the contract user to fix the test failure issue
      //User userinfo = [SELECT Id, Name FROM User WHERE Id = :UserInfo.getUserId()];
      //Contract_User__c cUser = testDataFactoryPP.createPricingPortalUser(userinfo.Name, userinfo.Id, 'US - Teleflex', 'US6010', 4);
      //Insert cUser;
      
      //////////////////
      //createUser(String firstName, String lastName, String approvalRole, String bu)
      User u = testDataFactoryPP.createUser('Adam','Franks','Sales VP','Anesthesia');
      insert u;

      User u1 = testDataFactoryPP.createUser('Testfn1','Testln1','Sales Rep','Anesthesia');
      insert u1;
      
      User u2 = testDataFactoryPP.createUser('Testfn2','Testln2','Sales Manager','Anesthesia');
      insert u2;
      
      User u3 = testDataFactoryPP.createUser('Testfn3','Testln3','Sales Director','Anesthesia');
      insert u3;
      
      User u4 = testDataFactoryPP.createUser('Testfn4','Testln4','Sales VP','Anesthesia');
      insert u4;
        
      System.runAs(u){
        Contract_User__c cu = new Contract_User__c(
            Name = 'Adam Franks',
            User__c = u.id,
            Active_Region__c = 'US - Teleflex',
            US_Material__c = TRUE,
            CA_Material__c = TRUE,
            MX_Material__c = TRUE,
            LA_Material__c = TRUE,
            CL_Material__c = TRUE,
            AU_Material__c = TRUE,
            NZ_Material__c = TRUE,
            Pricing_Portal_Access__c = TRUE,
            Pricing_Tier_Access__c = 1,
            CO_Material__c = TRUE,
            BR_Material__c = TRUE,
            DE_Material__c = TRUE,
            UK_Material__c = TRUE,
            AT_Material__c  = TRUE,
            BE_Material__c = TRUE,
            CH_Material__c = TRUE,
            CZ_Material__c = TRUE,
            ES_Material__c = TRUE,
            FR_Material__c = TRUE,
            GR_Material__c = TRUE,
            IT_Material__c = TRUE,
            NL_Material__c = TRUE,
            PL_Material__c = TRUE,
            SK_Material__c = TRUE,
            PT_Material__c = TRUE,
            IE_Material__c = TRUE,
            SA_Material__c = TRUE,
            Update_Type__c = NULL
            //Division_10__c = TRUE
        );
        insert cu;
        system.debug('CU:' + cu);
      
        Contract_Header__c ch1 = testDataFactoryPP.createContractHeader('50009064', '123310','R','US60');
        insert ch1;
        
        Contract_Header__c ch2 = testDataFactoryPP.createContractHeader('50009065', '123310','R','US60');
        insert ch2;
        
        Contract_Header__c ch3 = testDataFactoryPP.createContractHeader('50009066', '123310','M','US60');
        insert ch3;
        
        Contract_Header__c ch4 = testDataFactoryPP.createContractHeader('50009067', '123310','D','US60');
        insert ch4;

        Contract_Header__c ch5 = testDataFactoryPP.createContractHeader('50009067', 'GPO-255','D','US60');
        insert ch5;

        ch1 = new Contract_Header__c(Id = ch1.Id, Contract_Detail__c = NULL);
        update ch1;
        //createProduct2(String prodName, String salesOrg, String distChan, String matStatus)
        Product2 p1 = testDataFactoryPP.createProduct2('000-11', 'US60','10','40');
        insert p1;
        
        Product2 p2 = testDataFactoryPP.createProduct2('353535', 'US60','10','40');
        insert p2;
        
        //createContractMaterial(String agreeHeaderId, String agreeNum, String prodName, String prodId, String salesOrg, String div, String distChannel)
        Contract_Material__c cm1 = testDataFactoryPP.createContractMaterial(ch1.Id, ch1.Name, p2.Name, p2.Id, 'US60','10','10');
        insert cm1;
        
        Contract_Material__c cm2 = testDataFactoryPP.createContractMaterial(ch1.Id, ch1.Name, p1.Name, p1.Id, 'US60','10','10');
        insert cm2;

        PageReference pageRefpre = new PageReference('/apex/PP_GPO_Matrix?oid=' + ch5.Owner__c);
        system.debug('Price Quote Page' + pageRefpre);
        Test.setCurrentPage(pageRefpre);

        System.currentPageReference().getParameters().put('oid', ch5.Owner__c);

        PP_GPO_Matrix PPGPOMatrix = new PP_GPO_Matrix();
        String ownerIds=PPGPOMatrix.ownerID;
        String ownerNames=PPGPOMatrix.ownerName;
        PPGPOMatrix.oid();
        PPGPOMatrix.getItems();
        PPGPOMatrix.getEmeaGpos();
        PPGPOMatrix.getCheckChEmea();
        PPGPOMatrix.getTiers();
        PPGPOMatrix.getTiersEmea();
        PPGPOMatrix.getCheckCH();
        PPGPOMatrix.backToGpoMatrix();
        PPGPOMatrix.refreshPageSize();

        PPGPOMatrix.td3 = 'Testing td3';
        PPGPOMatrix.cd = 'Testing cd';
        Map<String, String> sampleMap = new Map<String, String>();
        sampleMap.put(ch1.GPO_Contract_Ref__c, PPGPOMatrix.td3);

        String td3 = PPGPOMatrix.td3;
        String cd = PPGPOMatrix.cd;
        PPGPOMatrix.htmlMap = sampleMap;
        Map<String, String> testmap = PPGPOMatrix.htmlMap;
        System.assertEquals(sampleMap, testMap);
        //test NULL Contract_Detail__c
        //chRec.Contract_Detail__c = NULL;
        //UPDATE chRec;
        PageReference gpo1 = Page.PP_GPO_Matrix;
        gpo1.getParameters().put('oid','GPO-008');
        Test.setCurrentPage(gpo1);
        PP_GPO_Matrix PPGPOMatrix1 = new PP_GPO_Matrix();
        ownerIds = PPGPOMatrix1.ownerID;
        ownerNames = PPGPOMatrix1.ownerName;
        PPGPOMatrix1.oid();
        PPGPOMatrix1.getItems();
        PPGPOMatrix1.getTiers();
        PPGPOMatrix1.getCheckCH();
        PPGPOMatrix1.getTiers();

        //test with NULL oid
        PageReference gpo2 = Page.PP_GPO_Matrix;
        gpo2.getParameters().put('oid', NULL);
        Test.setCurrentPage(gpo2);
        PP_GPO_Matrix PPGPOMatrix2 = new PP_GPO_Matrix();
        ownerIds = PPGPOMatrix2.ownerID;
        ownerNames = PPGPOMatrix2.ownerName;
        PPGPOMatrix2.oid();
        PPGPOMatrix2.getItems();
        PPGPOMatrix2.getTiers();
        PPGPOMatrix2.getCheckCH();
        PPGPOMatrix2.getTiers();
      }//end system.runas

    }// end of PP_GPO_Matrix_UnitTest

    //Start Testing EMEA User
    static testMethod void PP_GPO_Matrix_UnitTestEmea() {
      //String ownerId = UserInfo.getUserId();
      //PageReference gpo = Page.PP_GPO_Matrix;
      //Test.setCurrentPage(gpo);
      //gpo.getParameters().put('oid','GPO-008');

      //Created the contract user to fix the test failure issue
      //User userinfo = [SELECT Id, Name FROM User WHERE Id = :UserInfo.getUserId()];
      //Contract_User__c cUser = testDataFactoryPP.createPricingPortalUser(userinfo.Name, userinfo.Id, 'US - Teleflex', 'US6010', 4);
      //Insert cUser;
      
      //////////////////
      //createUser(String firstName, String lastName, String approvalRole, String bu)
      User u = testDataFactoryPP.createUser('Adam','Franks','Sales VP','EMEA');
      insert u;

      User u1 = testDataFactoryPP.createUser('Testfn1','Testln1','Sales Rep','EMEA');
      insert u1;
      
      User u2 = testDataFactoryPP.createUser('Testfn2','Testln2','Sales Manager','EMEA');
      insert u2;
      
      User u3 = testDataFactoryPP.createUser('Testfn3','Testln3','Sales Director','EMEA');
      insert u3;
      
      User u4 = testDataFactoryPP.createUser('Testfn4','Testln4','Sales VP','EMEA');
      insert u4;
        
      System.runAs(u){
        Contract_User__c cu = new Contract_User__c(
            Name = 'Adam Franks',
            User__c = u.id,
            Active_Region__c = 'DE - Germany',
            DE_Material__c = TRUE,
            Update_Type__c = NULL
            //Division_10__c = TRUE
        );
        insert cu;
        system.debug('CU:' + cu);
      
        Contract_Header__c ch1 = testDataFactoryPP.createContractHeader('50009064', '123310','R','DE10');
        insert ch1;
        
        Contract_Header__c ch2 = testDataFactoryPP.createContractHeader('50009065', '123310','R','DE10');
        insert ch2;
        
        Contract_Header__c ch3 = testDataFactoryPP.createContractHeader('50009066', '123310','M','DE10');
        insert ch3;
        
        Contract_Header__c ch4 = testDataFactoryPP.createContractHeader('50009067', '123310','D','DE10');
        insert ch4;

        //createProduct2(String prodName, String salesOrg, String distChan, String matStatus)
        Product2 p1 = testDataFactoryPP.createProduct2('000-11', 'DE10','10','40');
        insert p1;
        
        Product2 p2 = testDataFactoryPP.createProduct2('353535', 'DE10','10','40');
        insert p2;
        
        //createContractMaterial(String agreeHeaderId, String agreeNum, String prodName, String prodId, String salesOrg, String div, String distChannel)
        Contract_Material__c cm1 = testDataFactoryPP.createContractMaterial(ch1.Id, ch1.Name, p2.Name, p2.Id, 'DE10','10','10');
        insert cm1;
        
        Contract_Material__c cm2 = testDataFactoryPP.createContractMaterial(ch1.Id, ch1.Name, p1.Name, p1.Id, 'DE10','10','10');
        insert cm2;

        //Contract_Header__c chRec = TestDataFactory.createContractHeader('50010878');
        //insert chRec;
        //System.debug('-------chRec-----'+chRec.Active__c);
        PP_GPO_Matrix PPGPOMatrix = new PP_GPO_Matrix();
        String ownerIds=PPGPOMatrix.ownerID;
        String ownerNames=PPGPOMatrix.ownerName;
        PPGPOMatrix.oid();
        PPGPOMatrix.getItems();
        PPGPOMatrix.getEmeaGpos();
        PPGPOMatrix.getCheckChEmea();
        PPGPOMatrix.getTiers();
        PPGPOMatrix.getTiersEmea();
        PPGPOMatrix.getCheckCH();
        PPGPOMatrix.backToGpoMatrix();
        PPGPOMatrix.refreshPageSize();

        //test NULL Contract_Detail__c
        //chRec.Contract_Detail__c = NULL;
        //UPDATE chRec;
        PageReference gpo1 = Page.PP_GPO_Matrix;
        gpo1.getParameters().put('oid','DE-11111');
        Test.setCurrentPage(gpo1);
        PP_GPO_Matrix PPGPOMatrix1 = new PP_GPO_Matrix();
        ownerIds = PPGPOMatrix1.ownerID;
        ownerNames = PPGPOMatrix1.ownerName;
        PPGPOMatrix1.oid();
        PPGPOMatrix1.getItems();
        PPGPOMatrix1.getTiers();
        PPGPOMatrix1.getCheckCH();
        PPGPOMatrix1.getTiers();

        //test with NULL oid
        PageReference gpo2 = Page.PP_GPO_Matrix;
        gpo2.getParameters().put('oid', NULL);
        Test.setCurrentPage(gpo2);
        PP_GPO_Matrix PPGPOMatrix2 = new PP_GPO_Matrix();
        ownerIds = PPGPOMatrix2.ownerID;
        ownerNames = PPGPOMatrix2.ownerName;
        PPGPOMatrix2.oid();
        PPGPOMatrix2.getItems();
        PPGPOMatrix2.getTiers();
        PPGPOMatrix2.getCheckCH();
        PPGPOMatrix2.getTiers();
      }//end system.runas

    }// end of PP_GPO_Matrix_UnitTest
    //End Testing for EMEA User
}//end of PP_GPO_Matrix_Test