fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/Cross_Reference__c.object-meta.xml
<CustomObject>
    <label>Cross Reference</label>
    <nameField>
        <displayFormat>Xref-{00000000}</displayFormat>
        <label>Cross Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product_Code__c</fullName>
    <externalId>true</externalId>
    <label>Competitor Product Code</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product_Description__c</fullName>
    <label>Competitor Product Description</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFX Cross 1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Competitive Cross References</relationshipLabel>
    <relationshipName>Cross_References</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/TFX_Product__c.field-meta.xml
<CustomField>
    <fullName>TFX_Product__c</fullName>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TFX Product</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/TFX_Product_Description__c.field-meta.xml
<CustomField>
    <fullName>TFX_Product_Description__c</fullName>
    <formula>Product__r.Description</formula>
    <label>TFX Cross 1 Description</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org__c</fullName>
    <label>Sales Org</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/CrossReferenceFix.cls
global class CrossReferenceFix implements Database.Batchable<sObject> {
    public String query;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Product2> scope){
        Map<String,String> usSixtyProds = new Map<String,String>();
        List<Cross_Reference__c> crossRefToUpdate = new List<Cross_Reference__c>();
        List<Cross_Reference__c> crossRef = new List<Cross_Reference__c>();
        //List<Product2> sixtyList = [SELECT Id, Name FROM Product2 WHERE Sales_Org_Key__c = 'US6010' AND Class__c LIKE '%Anesthesia%'];
        List<String> sixtyListNames = new List<String>();
        Cross_Reference__c crossObj;
        for(Product2 curr : scope){
            sixtyListNames.add(curr.Name);
            usSixtyProds.put(curr.Name,curr.Id);
        }
        
        crossRef = [SELECT Competitor_Product_Code__c, Competitor_Product_Description__c, Id, Product__c, TFX_Product_Description__c, TFX_Product__c, Product__r.Sales_Org__c
                    FROM Cross_Reference__c
                    Where (Product__r.Sales_Org__c = 'US10' 
                           OR Product__r.Sales_Org__c = 'US30')
                    AND TFX_Product__c IN :sixtyListNames];
        
        for(Cross_Reference__c curr : crossRef){
            if(usSixtyProds.get(curr.TFX_Product__c) != NULL ){
                curr.Product__c = usSixtyProds.get(curr.TFX_Product__c);
                crossRefToUpdate.add(curr);	
            }
        }
        
        if(crossRefToUpdate.size() > 0 ){
            Database.update(crossRefToUpdate,false);
        }
        
        //update scope;
    }
    
    global void finish(Database.BatchableContext BC){
        // UserInfo.getUserEmail();
        // Get the ID of the AsyncApexJob representing this batch job from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email, CreatedBy.Admin_SMS_Notification__c 
                          FROM AsyncApexJob WHERE Id =
                          :BC.getJobId()];
        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        list<string> emailList = new list<string>();
        emailList.add(a.CreatedBy.Email);
        
        if(a.CreatedBy.Admin_SMS_Notification__c != NULL){
            emailList.add(a.CreatedBy.Admin_SMS_Notification__c);
        }
        mail.setToAddresses(emailList);
        mail.setSubject('Batch Tickle Completed: ' + a.Status);
        mail.setPlainTextBody
            ('The batch Apex job processed ' + a.JobItemsProcessed +
             ' batches with '+ a.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}