fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/Cross_Reference__c.object-meta.xml
<CustomObject>
    <label>Cross Reference</label>
    <nameField>
        <displayFormat>Xref-{00000000}</displayFormat>
        <label>Cross Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross References</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Code_Cleansed__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Code_Cleansed__c</fullName>
    <formula>SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
SUBSTITUTE( 
Competitor_Product_Code__c 
, &quot;(&quot;, &quot;&quot;) 
, &quot;)&quot;, &quot;&quot;) 
, &quot; &quot;, &quot;&quot;) 
, &quot;-&quot;, &quot;&quot;) 
, &quot;/&quot;, &quot;&quot;) 
, &quot;\\&quot;, &quot;&quot;) 
, &quot;_&quot;, &quot;&quot;) 
, &quot;.&quot;, &quot;&quot;) 
, &quot;#&quot;, &quot;&quot;) 
, &quot;!&quot;, &quot;&quot;) 
, &quot;@&quot;, &quot;&quot;) 
, &quot;$&quot;, &quot;&quot;) 
, &quot;%&quot;, &quot;&quot;) 
, &quot;^&quot;, &quot;&quot;) 
, &quot;&amp;&quot;, &quot;&quot;) 
, &quot;*&quot;, &quot;&quot;) 
, &quot;+&quot;, &quot;&quot;) 
, &quot;[&quot;, &quot;&quot;) 
, &quot;]&quot;, &quot;&quot;) 
, &quot;:&quot;, &quot;&quot;) 
, &quot;;&quot;, &quot;&quot;) 
, &quot;,&quot;, &quot;&quot;) 
, &quot;?&quot;, &quot;&quot;) 
, &quot;|&quot;, &quot;&quot;) 
, &quot;{&quot;, &quot;&quot;) 
, &quot;}&quot;, &quot;&quot;) 
, &quot;=&quot;, &quot;&quot;) 
, &quot;~&quot;, &quot;&quot;) 
, &quot;`&quot;, &quot;&quot;)</formula>
    <label>Competitor Code Cleansed</label>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <label>Competitor</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product_Code__c</fullName>
    <externalId>true</externalId>
    <label>Competitor Product Code</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Competitor_Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Product_Description__c</fullName>
    <label>Competitor Product Description</label>
    <type>TextArea</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Key_Difference__c.field-meta.xml
<CustomField>
    <fullName>Key_Difference__c</fullName>
    <label>Key Difference</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Percent_Match__c.field-meta.xml
<CustomField>
    <fullName>Percent_Match__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Percent Match</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TFX Cross 1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Competitive Cross References</relationshipLabel>
    <relationshipName>Cross_References</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project__c/Cross_Reference_Project__c.object-meta.xml
<CustomObject>
    <label>Cross Reference Project</label>
    <nameField>
        <label>Cross Reference Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cross Reference Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project_Item__c/Cross_Reference_Project_Item__c.object-meta.xml
<CustomObject>
    <label>Cross Reference Project Item</label>
    <nameField>
        <displayFormat>XRI-{00000000}</displayFormat>
        <label>Cross Reference Project Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Reference Project Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project_Item__c/fields/Competitive_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Competitive_Product_Code__c</fullName>
    <label>Competitive Product Code</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project_Item__c/fields/Cross_Reference_1__c.field-meta.xml
<CustomField>
    <fullName>Cross_Reference_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cross Reference 2</label>
    <referenceTo>Cross_Reference__c</referenceTo>
    <relationshipLabel>Cross Reference Project Items (Cross Reference 1)</relationshipLabel>
    <relationshipName>Cross_Reference_Project_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project_Item__c/fields/Cross_Reference_2__c.field-meta.xml
<CustomField>
    <fullName>Cross_Reference_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cross Reference 3</label>
    <referenceTo>Cross_Reference__c</referenceTo>
    <relationshipLabel>Cross Reference Project Items (Cross Reference 2)</relationshipLabel>
    <relationshipName>Cross_Reference_Project_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project_Item__c/fields/Cross_Reference_3__c.field-meta.xml
<CustomField>
    <fullName>Cross_Reference_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cross Reference 4</label>
    <referenceTo>Cross_Reference__c</referenceTo>
    <relationshipLabel>Cross Reference Project Items (Cross Reference 3)</relationshipLabel>
    <relationshipName>Cross_Reference_Project_Items3</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project_Item__c/fields/Cross_Reference__c.field-meta.xml
<CustomField>
    <fullName>Cross_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cross Reference 1</label>
    <referenceTo>Cross_Reference__c</referenceTo>
    <relationshipLabel>Cross Reference Project Items</relationshipLabel>
    <relationshipName>Cross_Reference_Project_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Cross_Reference_Project_Item__c/fields/Cross_Reference_Project__c.field-meta.xml
<CustomField>
    <fullName>Cross_Reference_Project__c</fullName>
    <label>Cross Reference Project</label>
    <referenceTo>Cross_Reference_Project__c</referenceTo>
    <relationshipLabel>Cross Reference Project Items</relationshipLabel>
    <relationshipName>Cross_Reference_Project_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Each_per_Case__c.field-meta.xml
<CustomField>
    <fullName>Each_per_Case__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Each per Case</description>
    <inlineHelpText>Each per Case</inlineHelpText>
    <label>Each per Case</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/bulkXRefController.cls
public with sharing class bulkXRefController {
    public List<Cross_Reference__c> xRef;
    private ApexPages.StandardController controller {get; set;}    
    private Cross_Reference_Project__c proj;
    
    public bulkXRefController(ApexPages.StandardController controller) {
        this.controller = controller;
        this.proj = (Cross_Reference_Project__c)controller.getRecord();
    }

    @remoteAction
    public static Boolean pullXref(String dirtyInput, String projectId) {
        List<String> lines = dirtyInput.split('\n');
        Set<String> cleansedLines = new Set<String>();
        List<Cross_Reference_Project_Item__c> newItems = new List<Cross_Reference_Project_Item__c>();
        Set<String> cleansedExisting = new Set<String>();
        List<Cross_Reference_Project_Item__c > lst_CR = [SELECT Id, Competitive_Product_Code__c FROM Cross_Reference_Project_Item__c WHERE Cross_Reference_Project__c =:projectId];
        for(Cross_Reference_Project_Item__c ei: lst_CR){
            cleansedExisting.add(ei.Competitive_Product_Code__c);
        }
        /*for(Cross_Reference_Project_Item__c ei: [SELECT Id, Competitive_Product_Code__c FROM Cross_Reference_Project_Item__c WHERE Cross_Reference_Project__c =:projectId]){
            cleansedExisting.add(ei.Competitive_Product_Code__c);
        }*/
        string c;
        for(String a: lines){
            a = a.trim();
            a = a.toUpperCase();
            c = a.replaceAll('[^A-Za-z0-9]', '');
            if(cleansedExisting.isEmpty() == true || cleansedExisting.contains(c) == false){
                if(cleansedLines.isEmpty() == true || cleansedLines.contains(c) == false){
                    if(c != ''){
                         cleansedLines.add(c);
                    }
                }
            }
        }
        
        for(String b: cleansedLines){
            newItems.add(new Cross_Reference_Project_Item__c(Competitive_Product_Code__c = b, Cross_Reference_Project__c = projectId));
        }

        insert newItems; 

        return true;
    }

    @remoteAction
    public static List<Cross_Reference_Project_Item__c> pullItems(String projectId){
        List<Cross_Reference_Project_Item__c> items = [SELECT Id, Competitive_Product_Code__c, Cross_Reference__c, Cross_Reference_1__c, Cross_Reference_2__c, Cross_Reference_3__c, Cross_Reference__r.Competitor_Product_Code__c, Cross_Reference__r.Competitor_Product_Description__c, Cross_Reference__r.Product__r.Name, Cross_Reference_Project__c FROM Cross_Reference_Project_Item__c WHERE Cross_Reference_Project__c =:projectId];
        
        return items;
    }

    @remoteAction
    public static List<Cross_Reference__c> pullRelationships(String projectId){
        List<Cross_Reference_Project_Item__c> items = [SELECT Id, Competitive_Product_Code__c FROM Cross_Reference_Project_Item__c WHERE Cross_Reference_Project__c =:projectId];
        Set<String> competitorCodes = new Set<String>();
        string product, comp_product;
        for(Cross_Reference_Project_Item__c i: items){
            comp_product = i.Competitive_Product_Code__c;
            product = comp_product.replaceAll('[^A-Z a-z 0-9]', '');
            
            if(!competitorCodes.contains(product)) {
                competitorCodes.add(product);
            }
        }
        List<Cross_Reference__c> rel = [SELECT Id, Product__R.Name, Product__r.Description, Competitor_Product_Code__c, Competitor_Product_Description__c, Competitor_Name__c, Percent_Match__c, Key_Difference__c FROM Cross_Reference__c WHERE Competitor_Code_Cleansed__c in :competitorCodes AND (Status__c = 'Active' OR Status__c = '')];

        return rel;
    }

    @remoteAction
    public static List<Cross_Reference__c> pullDescriptors(String projectId, String xrefId){
        List<Cross_Reference__c> tmpXref = new List<Cross_Reference__c>();
        Set<String> selectedXrefs = new Set<String>();
        if(xrefId != ''){
            tmpXref = [SELECT Id, Product__R.Name, Product__r.Description, Product__r.Each_per_Case__c, Competitor_Product_Code__c, Competitor_Product_Description__c, Competitor_Name__c, Percent_Match__c, Key_Difference__c FROM Cross_Reference__c WHERE Id = :xrefId];
            
        }else{
            List<Cross_Reference_Project_Item__c> tmpItems = pullItems(projectId);
            for(Cross_Reference_Project_Item__c i: tmpItems){
                if(i.Cross_Reference__c != null){
                    selectedXrefs.add(i.Cross_reference__c);
                }
                if(i.Cross_Reference_1__c != null){
                    selectedXrefs.add(i.Cross_reference_1__c);
                }
                if(i.Cross_Reference_2__c != null){
                    selectedXrefs.add(i.Cross_reference_2__c);
                }
                if(i.Cross_Reference_3__c != null){
                    selectedXrefs.add(i.Cross_reference_3__c);
                }
            }
            tmpXref = [SELECT Id, Product__R.Name, Product__r.Description, Product__r.Each_per_Case__c, Competitor_Product_Code__c, Competitor_Product_Description__c, Competitor_Name__c, Percent_Match__c, Key_Difference__c FROM Cross_Reference__c WHERE Id IN :selectedXrefs];
            
        }
        return tmpXref;
    }

    @remoteAction
    public static boolean commitChange(String product, String xrefId, String xrefId1, String xrefId2, String xrefId3, String projectId){
        List<Cross_Reference_Project_Item__c> item = [SELECT Id, Cross_Reference__c FROM Cross_Reference_Project_Item__c WHERE Competitive_Product_Code__c = :product AND Cross_Reference_Project__c = :projectId];
        if(item.isEmpty() == false && xrefId != ''){
            item[0].Cross_Reference__c = xrefId;
            if(xrefId1 != ''){
                item[0].Cross_Reference_1__c = xrefId1;
            }else{
                item[0].Cross_Reference_1__c = null;
            }
            if(xrefId2 != ''){
                item[0].Cross_Reference_2__c = xrefId2;
            }else{
                item[0].Cross_Reference_2__c = null;
            }
            if(xrefId3 != ''){
                item[0].Cross_Reference_3__c = xrefId3;
            }else{
                item[0].Cross_Reference_3__c = null;
            }
            update item;
        }
        return null;
    }

    @remoteAction
    public static boolean removeRecord(String product){
        List<Cross_Reference_Project_Item__c> item = [SELECT Id, Cross_Reference__c FROM Cross_Reference_Project_Item__c WHERE Competitive_Product_Code__c = :product];
        if(item.isEmpty() == false){
            delete item;
        }
        return null;
    }
}