fullSandbox11072023/force-app/main/default/objects/Lab__c/Lab__c.object-meta.xml
<CustomObject>
    <label>Lab</label>
    <nameField>
        <label>Lab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Lab__c/fields/Attended_Hemorrhage__c.field-meta.xml
<CustomField>
    <fullName>Attended_Hemorrhage__c</fullName>
    <label>Attended Hemorrhage</label>
    <summaryFilterItems>
        <field>Lab_Participant__c.Status_for_Hemorrhage__c</field>
        <operation>equals</operation>
        <value>Attended</value>
    </summaryFilterItems>
    <summaryForeignKey>Lab_Participant__c.Lab__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab__c/fields/Lab_Key__c.field-meta.xml
<CustomField>
    <fullName>Lab_Key__c</fullName>
    <externalId>true</externalId>
    <label>Lab Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab__c/recordTypes/Lab.recordType-meta.xml
<RecordType>
    <fullName>Lab</fullName>
    <active>true</active>
    <label>Lab</label>
</RecordType>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/Lab_Participant__c.object-meta.xml
<CustomObject>
    <label>Lab Participant</label>
    <nameField>
        <label>Lab Participant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lab Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <label>Affiliation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hospital ED/ICU/Rapid Response/Flight/Other</fullName>
            </value>
            <value>
                <fullName>EMS/Prehospital -  Ground or Air Ambulance</fullName>
            </value>
            <value>
                <fullName>Interventional Radiology/Oncology/Pathology</fullName>
            </value>
            <value>
                <fullName>Anesthesia/Pain Management</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Attended__c.field-meta.xml
<CustomField>
    <fullName>Attended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attended Airway</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Attended_EZIO__c.field-meta.xml
<CustomField>
    <fullName>Attended_EZIO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attended EZIO</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Attended_Hemorrhage__c.field-meta.xml
<CustomField>
    <fullName>Attended_Hemorrhage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attended Hemorrhage</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Atteneded_Interventional__c.field-meta.xml
<CustomField>
    <fullName>Atteneded_Interventional__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Atteneded Interventional</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Lab__c.field-meta.xml
<CustomField>
    <fullName>Lab__c</fullName>
    <label>Lab</label>
    <referenceTo>Lab__c</referenceTo>
    <relationshipLabel>Lab Participants</relationshipLabel>
    <relationshipName>Lab_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Lab_Time_2__c.field-meta.xml
<CustomField>
    <fullName>Lab_Time_2__c</fullName>
    <description>Used for labs when EZIO and Airway are offered - this time defines the time selected for the Airway lab.</description>
    <inlineHelpText>For labs when EZIO and Airway are offered - this time defines the time selected for the Airway lab.</inlineHelpText>
    <label>EZ-IO Track</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Lab_Time__c.field-meta.xml
<CustomField>
    <fullName>Lab_Time__c</fullName>
    <label>Airway Track</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Lab_Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Lab_Unique_ID__c</fullName>
    <externalId>true</externalId>
    <label>Lab Unique ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <label>Mailing Zip Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Lab_Participant__c/recordTypes/Lab.recordType-meta.xml
<RecordType>
    <fullName>Lab</fullName>
    <active>true</active>
    <label>Lab</label>
</RecordType>

fullSandbox11072023/force-app/main/default/classes/EmailLabattendeesTest.cls
@isTest
public class EmailLabattendeesTest {
    @testSetup
    public static Void CreateData() {
        Lab__c lab = new Lab__c(
            Name = 'UNC Lab',
            Lab_Key__c = 'UNC Lab'
        );
        insert lab;
        Lab_Participant__c lp = new Lab_Participant__c(
            Name = 'test',
            Lab__c = lab.Id,
            Lab_Time__c = '7pm',
            Lab_Time_2__c = '7:35pm',
            Email__c = '123321@1232222.com',
            Mailing_Zip_Code__c = '27614',
            Address__c = '123 Mainstreet Raleigh, NC 98989 US',
            Affiliation__c = 'EMS',
            Lab_Unique_ID__c = '123123',
            Attended__c = true,
            Attended_EZIO__c = true,
            Attended_Hemorrhage__c= true,
            Atteneded_Interventional__c= true
        );
        insert lp;
    }
    
    @isTest
    static void test_method() {
        Lab_Participant__c participant = [SELECT Id, Email__c
                                          FROM Lab_Participant__c];
        Test.startTest();
        EmailLabAttendeesController.sendPdf(new List<Id>{participant.Id});
        Test.stopTest();
    }
}