fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Price_Quote__c.field-meta.xml
<CustomField>
    <fullName>Active_Price_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Price Quote</label>
    <referenceTo>Price_Quote__c</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Division_10__c.field-meta.xml
<CustomField>
    <fullName>CA_Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Division_20__c.field-meta.xml
<CustomField>
    <fullName>CA_Division_20__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Division 20</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Division_30__c.field-meta.xml
<CustomField>
    <fullName>CA_Division_30__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Division 30</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Division_40__c.field-meta.xml
<CustomField>
    <fullName>CA_Division_40__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Division 40</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Division_50__c.field-meta.xml
<CustomField>
    <fullName>CA_Division_50__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Division 50</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Division_60__c.field-meta.xml
<CustomField>
    <fullName>CA_Division_60__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Division 60</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Material__c.field-meta.xml
<CustomField>
    <fullName>CA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Division_10__c.field-meta.xml
<CustomField>
    <fullName>CL_Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Division_20__c.field-meta.xml
<CustomField>
    <fullName>CL_Division_20__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Division 20</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Division_30__c.field-meta.xml
<CustomField>
    <fullName>CL_Division_30__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Division 30</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Division_40__c.field-meta.xml
<CustomField>
    <fullName>CL_Division_40__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Division 40</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Division_50__c.field-meta.xml
<CustomField>
    <fullName>CL_Division_50__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Division 50</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Division_60__c.field-meta.xml
<CustomField>
    <fullName>CL_Division_60__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Division 60</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Material__c.field-meta.xml
<CustomField>
    <fullName>CL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Create_Quotes__c.field-meta.xml
<CustomField>
    <fullName>Create_Quotes__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Create Quotes</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Currency_Preference__c.field-meta.xml
<CustomField>
    <fullName>Currency_Preference__c</fullName>
    <label>Currency Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_10__c.field-meta.xml
<CustomField>
    <fullName>Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Respiratory and Anesthesia (TFX only)</inlineHelpText>
    <label>US Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_20__c.field-meta.xml
<CustomField>
    <fullName>Division_20__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Division 20-Surgical</inlineHelpText>
    <label>US Division 20</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_30__c.field-meta.xml
<CustomField>
    <fullName>Division_30__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Division 30-Surgical</inlineHelpText>
    <label>US Division 30</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_40__c.field-meta.xml
<CustomField>
    <fullName>Division_40__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Division 40-Vascular &amp; Interventional</inlineHelpText>
    <label>US Division 40</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_50__c.field-meta.xml
<CustomField>
    <fullName>Division_50__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Division 50- Anesthesia (Arrow Only)</inlineHelpText>
    <label>US Division 50</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_60__c.field-meta.xml
<CustomField>
    <fullName>Division_60__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Division 60- Cardiac, Interventional Access</inlineHelpText>
    <label>US Division 60</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Division_10__c.field-meta.xml
<CustomField>
    <fullName>LA_Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Division_20__c.field-meta.xml
<CustomField>
    <fullName>LA_Division_20__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Division 20</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Division_30__c.field-meta.xml
<CustomField>
    <fullName>LA_Division_30__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Division 30</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Division_40__c.field-meta.xml
<CustomField>
    <fullName>LA_Division_40__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Division 40</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Division_50__c.field-meta.xml
<CustomField>
    <fullName>LA_Division_50__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Division 50</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Division_60__c.field-meta.xml
<CustomField>
    <fullName>LA_Division_60__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Division 60</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Material__c.field-meta.xml
<CustomField>
    <fullName>LA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Division_10__c.field-meta.xml
<CustomField>
    <fullName>MX_Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Division_20__c.field-meta.xml
<CustomField>
    <fullName>MX_Division_20__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Division 20</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Division_30__c.field-meta.xml
<CustomField>
    <fullName>MX_Division_30__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Division 30</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Division_40__c.field-meta.xml
<CustomField>
    <fullName>MX_Division_40__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Division 40</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Division_50__c.field-meta.xml
<CustomField>
    <fullName>MX_Division_50__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Division 50</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Division_60__c.field-meta.xml
<CustomField>
    <fullName>MX_Division_60__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Division 60</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Material__c.field-meta.xml
<CustomField>
    <fullName>MX_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Pricing_Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Portal_Access__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Pricing Portal Access</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Stationary_Preference__c.field-meta.xml
<CustomField>
    <fullName>Stationary_Preference__c</fullName>
    <label>Stationary Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard Teleflex</fullName>
                <default>true</default>
                <label>Standard Teleflex</label>
            </value>
            <value>
                <fullName>Anesthesia/Respiratory</fullName>
            </value>
            <value>
                <fullName>Cardiac Care</fullName>
            </value>
            <value>
                <fullName>Interventional</fullName>
            </value>
            <value>
                <fullName>Specialty Markets</fullName>
            </value>
            <value>
                <fullName>Surgical</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
            <value>
                <fullName>Vascular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/US_Material__c.field-meta.xml
<CustomField>
    <fullName>US_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>US Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User_Administration__c.field-meta.xml
<CustomField>
    <fullName>User_Administration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Administration</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/View_Margin__c.field-meta.xml
<CustomField>
    <fullName>View_Margin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>View Margin</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_User_Administration.cls
/*********************************************************************
* Description      : Controller Class for Pricing Portal PP_User_Administration.
* Test Class       : PP_User_Administration_Test
* VisualForce      : PP_User_Administration
* Author(s)        : Eric Clay, Dun Silver
**********************************************************************/
public class PP_User_Administration {

    private final Contract_User__c cUser;
    public List<SelectOption> paginationSizeOptions{get;set;}
    public List<Contract_User__c> uList {get;set;}
    Public Integer size{get;set;}
    Public Integer noOfRecords{get; set;}

    public PP_User_Administration(){
        if(ApexPages.currentPage().getParameters().get('id') != NULL){
            try{
                cUser = [Select Name, Pricing_Portal_Access__c, Active_Price_Quote__c, Create_Quotes__c, Currency_Preference__c,
                         Division_10__c, Division_20__c, Division_30__c, Division_40__c, Division_50__c, Division_60__c,
                         CA_Division_10__c, CA_Division_20__c, CA_Division_30__c, CA_Division_40__c, CA_Division_50__c, CA_Division_60__c,
                         MX_Division_10__c, MX_Division_20__c, MX_Division_30__c, MX_Division_40__c, MX_Division_50__c, MX_Division_60__c,
                         LA_Division_10__c, LA_Division_20__c, LA_Division_30__c, LA_Division_40__c, LA_Division_50__c, LA_Division_60__c,
                         CL_Division_10__c, CL_Division_20__c, CL_Division_30__c, CL_Division_40__c, CL_Division_50__c, CL_Division_60__c,
                         Stationary_Preference__c, User_Administration__c, View_Margin__c,
                         US_Material__c, MX_Material__c, LA_Material__c, CA_Material__c, CL_Material__c, Active_Region__c
                         FROM Contract_User__c
                         WHERE id = :ApexPages.currentPage().getParameters().get('id')
                         LIMIT 1];
            }
            catch(Exception e){
                system.debug('Exception: ' + e);
            }

        }//end of if

        size=100;
        paginationSizeOptions = new List<SelectOption>();
        paginationSizeOptions.add(new SelectOption('5','5'));
        paginationSizeOptions.add(new SelectOption('10','10'));
        paginationSizeOptions.add(new SelectOption('20','20'));
        paginationSizeOptions.add(new SelectOption('50','50'));
        paginationSizeOptions.add(new SelectOption('100','100'));
    }

		public ApexPages.StandardSetController setCon {get {
				try{
						System.debug('Running Product Search Query');
						if(setCon == null) {
							System.debug('*** In setCon if ***');
							setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
							[SELECT Id, Name, Pricing_Portal_Access__c, Active_Price_Quote__c, Create_Quotes__c, Currency_Preference__c,
							Division_10__c, Division_20__c, Division_30__c, Division_40__c, Division_50__c, Division_60__c,
							CA_Division_10__c, CA_Division_20__c, CA_Division_30__c, CA_Division_40__c, CA_Division_50__c, CA_Division_60__c,
							MX_Division_10__c, MX_Division_20__c, MX_Division_30__c, MX_Division_40__c, MX_Division_50__c, MX_Division_60__c,
							LA_Division_10__c, LA_Division_20__c, LA_Division_30__c, LA_Division_40__c, LA_Division_50__c, LA_Division_60__c,
							CL_Division_10__c, CL_Division_20__c, CL_Division_30__c, CL_Division_40__c, CL_Division_50__c, CL_Division_60__c,
							Stationary_Preference__c, User_Administration__c, View_Margin__c,
							Business_Unit__c
							FROM Contract_User__c
							ORDER BY Name]));

						 setCon.setPageSize(size);
						 noOfRecords = setCon.getResultSize();


						System.debug('*** setCon *** ' + setCon);
						System.debug('*** noOfRecords *** ' + noOfRecords);
					}//end of if
						return setCon;

				}
				catch(Exception e){
						Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,''+'No products found... ' + e));
						return null;
				}

		} set;}

		//Changes the size of pagination
    public PageReference refreshPageSize() {
        try{
            setCon.setPageSize(size);
            return null;
        }
        catch(Exception e){
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,''+'Error detected: ' + e));
            return null;
        }
    }//end of refreshPageSize

    public Contract_User__c getu(){
        return cUser;
    }

    public List<Contract_User__c> getulist1(){
      uList = (List<Contract_User__c>) setCon.getRecords();
			System.debug('*** uList.size() *** ' + uList.size() );
      return (List<Contract_User__c>) setCon.getRecords();
    }

    public PageReference save() {
      cUser.Update_Type__c = 'updateUSR';
      system.debug('cUser:' + cUser);
      update cUser;

      PageReference redir = New Pagereference('/apex/PP_User_Administration');
      redir.setRedirect(true);
      return redir;
    }//end of save

    public PageReference cancel() {
      PageReference redir = New Pagereference('/apex/PP_User_Administration');
      redir.setRedirect(true);
      return redir;
    }

    public String uid {
	    get {
	    	return ApexPages.currentPage().getParameters().get('id');
	    }
    	set;
		}

    public boolean getva(){
      return [SELECT User_Administration__c
              FROM Contract_User__c
              WHERE User__c = :UserInfo.getUserId()
              LIMIT 1].User_Administration__c;
    }

    public PageReference GroupCheck() {

        list<GroupMember> addUser = new list<GroupMember>();

        map<String, Id> gMap = new map<String, Id>();
        for(Group g : [SELECT Name, Id FROM GROUP WHERE Name = 'Pricing Portal' OR Name like '%Division%']){
            gMap.put(g.Name, g.Id);
            //system.debug('g.name:' + g.name + ' g.Id ' + g.id);
        }

        for(Contract_User__c cu : [SELECT User__r.id, Pricing_Portal_Access__c,
                                   Division_10__c, Division_20__c, Division_30__c, Division_40__c, Division_50__c, Division_60__c,
                                   CA_Division_10__c, CA_Division_20__c, CA_Division_30__c, CA_Division_40__c, CA_Division_50__c, CA_Division_60__c,
                                   MX_Division_10__c, MX_Division_20__c, MX_Division_30__c, MX_Division_40__c, MX_Division_50__c, MX_Division_60__c,
                                   LA_Division_10__c, LA_Division_20__c, LA_Division_30__c, LA_Division_40__c, LA_Division_50__c, LA_Division_60__c,
                                   CL_Division_10__c, CL_Division_20__c, CL_Division_30__c, CL_Division_40__c, CL_Division_50__c, CL_Division_60__c
                                   FROM Contract_User__c
                                   WHERE Not User__r.Profile.Name Like 'Chatter%'])
        {

            //system.debug('List of Groups:' + ' 10: ' + cu.Division_10__c + ' 20: ' + cu.Division_20__c + ' 30: ' + cu.Division_30__c + ' 40: ' + cu.Division_40__c + ' 50: ' + cu.Division_50__c + ' 60: ' + cu.Division_60__c);
            //system.debug('List of Maps:' + ' 10: ' + gMap.get('Division 10') + ' 20: ' + gMap.get('Division 20') + ' 30: ' + gMap.get('Division 30') + ' 40: ' + gMap.get('Division 40') + ' 50: ' + gMap.get('Division 50') + ' 60: ' + gMap.get('Division 60'));

            String uId = cu.User__r.id;
            system.debug('uId: ' + uId);

            // 10
            if(cu.Division_10__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('US Division 10'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // 20
            if(cu.Division_20__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('US Division 20'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // 30
            if(cu.Division_30__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('US Division 30'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // 40
            if(cu.Division_40__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('US Division 40'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // 50
            if(cu.Division_50__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('US Division 50'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // 60
            if(cu.Division_60__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('US Division 60'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CA Division 10
            if(cu.CA_Division_10__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CA Division 10'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CA Division 20
            if(cu.CA_Division_20__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CA Division 20'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CA Division 30
            if(cu.CA_Division_30__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CA Division 30'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CA Division 40
            if(cu.CA_Division_40__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CA Division 40'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CA Division 50
            if(cu.CA_Division_50__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CA Division 50'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CA Division 60
            if(cu.CA_Division_60__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CA Division 60'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // Latin America
            // LA Division 10
            if(cu.LA_Division_10__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('LA Division 10'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // LA Division 20
            if(cu.LA_Division_20__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('LA Division 20'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // LA Division 30
            if(cu.LA_Division_30__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('LA Division 30'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // LA Division 40
            if(cu.LA_Division_40__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('LA Division 40'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // LA Division 50
            if(cu.LA_Division_50__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('LA Division 50'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // LA Division 60
            if(cu.LA_Division_60__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('LA Division 60'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            //Mexico
            //MX Division 10
            if(cu.MX_Division_10__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('MX Division 10'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // MX Division 20
            if(cu.MX_Division_20__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('MX Division 20'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // MX Division 30
            if(cu.MX_Division_30__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('MX Division 30'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // MX Division 40
            if(cu.MX_Division_40__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('MX Division 40'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // MX Division 50
            if(cu.MX_Division_50__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('MX Division 50'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // MX Division 60
            if(cu.MX_Division_60__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('MX Division 60'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }

            //Chile
            // CL Division 10
            if(cu.CL_Division_10__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CL Division 10'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CL Division 20
            if(cu.CL_Division_20__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CL Division 20'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CL Division 30
            if(cu.CL_Division_30__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CL Division 30'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CL Division 40
            if(cu.CL_Division_40__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CL Division 40'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CL Division 50
            if(cu.CL_Division_50__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CL Division 50'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            // CL Division 60
            if(cu.CL_Division_60__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('CL Division 60'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }

            // Pricing Portal
            if(cu.Pricing_Portal_Access__c){
                GroupMember addGroupMember = new GroupMember(GroupId = gMap.get('Pricing Portal'), UserOrGroupId = uId);
                addUser.add(addGroupMember);
            }
            system.debug('addUser: ' + addUser.size());
        }

        if(addUser.size() > 0){
            insert addUser;
        }

        PageReference redir = New Pagereference('/apex/PP_User_Administration');
        redir.setRedirect(true);
        return redir;
    }


}