fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <inlineHelpText>This only drives material visibility</inlineHelpText>
    <label>Active Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT - Austria</fullName>
            </value>
            <value>
                <fullName>AU - Australia</fullName>
            </value>
            <value>
                <fullName>BE - Belgium</fullName>
            </value>
            <value>
                <fullName>BR - Brazil</fullName>
            </value>
            <value>
                <fullName>CA - Canada</fullName>
            </value>
            <value>
                <fullName>CL - Chile</fullName>
            </value>
            <value>
                <fullName>CO - Colombia</fullName>
            </value>
            <value>
                <fullName>CZ - Czech</fullName>
            </value>
            <value>
                <fullName>DE - Germany</fullName>
            </value>
            <value>
                <fullName>ES - Spain</fullName>
            </value>
            <value>
                <fullName>IE - Ireland</fullName>
            </value>
            <value>
                <fullName>LA - Latin America</fullName>
            </value>
            <value>
                <fullName>MX - Mexico</fullName>
            </value>
            <value>
                <fullName>NL - Netherlands</fullName>
            </value>
            <value>
                <fullName>NZ - New Zealand</fullName>
            </value>
            <value>
                <fullName>PL - Poland</fullName>
            </value>
            <value>
                <fullName>PT - Portugal</fullName>
            </value>
            <value>
                <fullName>SK - Slovakia</fullName>
            </value>
            <value>
                <fullName>UK - United Kingdom</fullName>
            </value>
            <value>
                <fullName>US - Teleflex</fullName>
                <default>true</default>
                <label>US - Teleflex</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org_Key__c</fullName>
    <label>Active Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_10__c.field-meta.xml
<CustomField>
    <fullName>Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Respiratory and Anesthesia (TFX only)</inlineHelpText>
    <label>US Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Pricing_Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Portal_Access__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Pricing Portal Access</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/US_Material__c.field-meta.xml
<CustomField>
    <fullName>US_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>US Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Update_Sales_Org_Test.cls
/*********************************************************************
* Description      : Test coverage for Pricing Portal PP_Update_Sales_Org.
* Coverage         : Classes(PP_Update_Sales_Org)
* Author(s)        : Dun Silver, Eric Clay
**********************************************************************/
@isTest
public class PP_Update_Sales_Org_Test {
    @istest static void Test_User_Update(){
        Profile p = [select id from profile where name='System Administrator'];
        User u = new User(
            alias = 'uflex76',
            email='unit.test@unit.teleflex.com',
            emailencodingkey='UTF-8',
            firstname='Adam',
            lastname='Franks',
            languagelocalekey='en_US',
            localesidkey='en_GB',
            profileid = p.Id,
            timezonesidkey='Europe/London',
            username='unit.test@unit.teleflex.com'
        );
        insert u;

        

        System.runAs(u){
            Contract_User__c cu = new Contract_User__c(
                Name = 'Adam Franks',
                User__c = u.id,
                Active_Region__c = 'US - Teleflex/Arrow',
                US_Material__c = TRUE,
                Pricing_Portal_Access__c = FALSE
                //Division_10__c = TRUE
            );
            insert cu;
            system.debug('CU:' + cu);
        
            PageReference pageRef = new PageReference('/apex/PP_Update_Sales_Org?so=US');
            system.debug('User Edit Page' + pageRef);
            Test.setCurrentPage(pageRef);
            PP_Update_Sales_Org sotest = new PP_Update_Sales_Org();
            sotest.updateSalesOrg3();

            PageReference pageRef1 = new PageReference('/apex/PP_Update_Sales_Org?so=CA');
            system.debug('User Edit Page' + pageRef1);
            Test.setCurrentPage(pageRef1);
            PP_Update_Sales_Org sotest1 = new PP_Update_Sales_Org();
            sotest1.updateSalesOrg3();

            PageReference pageRef2 = new PageReference('/apex/PP_Update_Sales_Org?so=LA');
            system.debug('User Edit Page' + pageRef2);
            Test.setCurrentPage(pageRef2);
            PP_Update_Sales_Org sotest2 = new PP_Update_Sales_Org();
            sotest2.updateSalesOrg3();

            PageReference pageRef3 = new PageReference('/apex/PP_Update_Sales_Org?so=MX');
            system.debug('User Edit Page' + pageRef3);
            Test.setCurrentPage(pageRef3);
            PP_Update_Sales_Org sotest3 = new PP_Update_Sales_Org();
            sotest3.updateSalesOrg3();

            PageReference pageRef4 = new PageReference('/apex/PP_Update_Sales_Org?so=CL');
            system.debug('User Edit Page' + pageRef4);
            Test.setCurrentPage(pageRef4);
            PP_Update_Sales_Org sotest4 = new PP_Update_Sales_Org();
            sotest4.updateSalesOrg3();

            cu.Active_Region__c = 'US - Teleflex/Arrow';
            UPDATE cu;
            System.assertNotEquals('CL1010', cu.Active_Sales_Org_Key__c);
        }
    }

}