fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org_Key__c</fullName>
    <label>Active Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request__c/Sample_Request__c.object-meta.xml
<CustomObject>
    <label>Sample Request</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Sample Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Sample_Request__c/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <label>Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Sample_Request__c/fields/TerritoryManager__c.field-meta.xml
<CustomField>
    <fullName>TerritoryManager__c</fullName>
    <label>Territory Manager</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/sample_Requests_Helper_Class.cls
public class sample_Requests_Helper_Class {
    public static void fixSalesOrg(List<Sample_Request__c> newTrigger){
        // Should only happen if the record is created from the mobile?
        set<Id> oIds = new set<Id>();
        for(Sample_Request__c sr : newTrigger){
            if(sr.Sales_Org_Key__c == NULL){
                oIds.add(sr.OwnerId);
            }
        }
        if(oIds.size() > 0){
            map<Id, String> oMap = new map<Id, String>();
            for(Contract_User__c cu : [SELECT User__c, Active_Sales_Org_Key__c
                                       FROM Contract_User__c
                                       WHERE User__c = :oIds])
            {
                if(cu.Active_Sales_Org_Key__c != NULL){
                    oMap.put(cu.User__c, cu.Active_Sales_Org_Key__c);
                }
            }
            if(oMap.size() > 0){
                for(Sample_Request__c sr : newTrigger){
                    if(sr.Sales_Org_Key__c == NULL && oMap.containsKey(sr.OwnerId)){
                        sr.Sales_Org_Key__c = oMap.get(sr.OwnerId);
                    }
                }
            }
        }
    }

    //method to reassign approver
    public static void assignToTerritoryManager(Sample_Request__c sr){
      System.debug('*** Starting assignToTerritoryManager in sample_Requests_Helper_Class ***');
      //hold manager Id for approval
      Id approverId = null;
      List<User> userRec = new List<User>();
      List<User> updateUser = new List<User>();

      approverId = sr.TerritoryManager__c;

      userRec = [SELECT Id, RCEM__c FROM User WHERE Id =: sr.OwnerId LIMIT 1];

      //check is userRec retrieved
      if(userRec.size() > 0 ){
        //Set RCEM User Record
        User u = new User(
          Id = userRec[0].RCEM__c,
          RCEM__c = sr.TerritoryManager__c
        );
        updateUser.add(u);

        try{
          update updateUser;
        }catch(Exception e){
          System.debug('*** Error e *** ' + e);
        }//end try/catch block

      }else{
        System.debug('*** userRec.size NOT > 0 *** ');
      }//end else

    }//end assignToTerritoryManager

    //method to reassign approver
    public static void removeTerritoryManager(Sample_Request__c sr){
      System.debug('*** Starting assignToTerritoryManager in sample_Requests_Helper_Class ***');
      //hold manager Id for approval
      Id approverId = null;
      List<User> userRec = new List<User>();
      List<User> updateUser = new List<User>();

      approverId = sr.TerritoryManager__c;

      userRec = [SELECT Id, RCEM__c FROM User WHERE Id =: sr.OwnerId LIMIT 1];

      //check is userRec retrieved
      if(userRec.size() > 0 ){
        //Set RCEM User Record
        User u = new User(
          Id = userRec[0].RCEM__c,
          RCEM__c = NULL
        );
        updateUser.add(u);

        try{
          update updateUser;
        }catch(Exception e){
          System.debug('*** Error e *** ' + e);
        }//end try/catch block

      }else{
        System.debug('*** userRec.size NOT > 0 *** ');
      }//end else

    }//end assignToTerritoryManager

}