fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Active_Sales_Org_Key__c</fullName>
    <label>Active Sales Org Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <inlineHelpText>This is the unconverted Cost from SAP</inlineHelpText>
    <label>Cost Raw</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Cost_Formula__c.field-meta.xml
<CustomField>
    <fullName>Cost_Formula__c</fullName>
    <formula>IF(
OR(
Cost_Price_Unit__c  = 0,
ISBLANK(Cost_Price_Unit__c)
),
0,
/* Default */
((Cost__c / Cost_Price_Unit__c)- Transfer_Price__c )* Qty_Sales_Unit__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Cost_Price__c.field-meta.xml
<CustomField>
    <fullName>Cost_Price__c</fullName>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Cost_Price_Unit__c.field-meta.xml
<CustomField>
    <fullName>Cost_Price_Unit__c</fullName>
    <label>Cost Price Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Qty_Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Qty_Sales_Unit__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty/Sales Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Org_Key__c.field-meta.xml
<CustomField>
    <fullName>Sales_Org_Key__c</fullName>
    <externalId>true</externalId>
    <label>Sales Org Key</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Sales_Unit__c.field-meta.xml
<CustomField>
    <fullName>Sales_Unit__c</fullName>
    <defaultValue>&quot;EA&quot;</defaultValue>
    <label>Sales Unit</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Transfer_Price__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Price__c</fullName>
    <inlineHelpText>ZTRP</inlineHelpText>
    <label>Transfer Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Margin_Calculator.cls
/*********************************************************************
* Description      : Controller Class for Margin Calculator.
* Test Class       : PP_Margin_Calculator_Test
* VisualForce      : PP_Margin_Calculator
* Author(s)        : Dun Silver
**********************************************************************/
public with sharing class PP_Margin_Calculator {

    Public String prodSrch {get;set;}
    Public String price {get;set;}
    Public List<Product2> prodRet {get;set;}
    Public Boolean priceListTable {get;set;}
    list<Double> prodPrice = new list<Double>();
    Public Double newCost {get;set;}
    Public Integer convUnit = 1000;
    Public Decimal grossMargin  {get; set;}

    //get active sales org key of User
    public String myActiveSalesOrg { get{

      try{
        myActiveSalesOrg = [SELECT Active_Sales_Org_Key__c
                          FROM Contract_User__c
                          WHERE User__c = :UserInfo.getUserId()
                          LIMIT 1].Active_Sales_Org_Key__c;

        if(myActiveSalesOrg == '' || myActiveSalesOrg == NULL){
            myActiveSalesOrg = 'US6010';
        }
      }
      catch(Exception e){
        System.debug('Exception occured in PP_Margin_Calculator myActiveSalesOrg: ' + e);
      }

      return myActiveSalesOrg;
    } set;}

    public pagereference getURL(){
        system.debug('In PP_Margin_Calculator getURL Method!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!');
        PageReference marginCalculator = New Pagereference('/apex/PP_Margin_Calculator?pid='+prodSrch+'&price='+price);
        marginCalculator.setRedirect(true);
        return marginCalculator;
    }

    Public PP_Margin_Calculator(){
        system.debug('*** In PP_Margin_Calculator Method PP_Margin_Calculator Class ***');
        prodRet = new List<Product2>();
        priceListTable = False;
        prodSrch = ApexPages.currentPage().getParameters().get('pid');
        price = ApexPages.currentPage().getParameters().get('price');
        //check for values in URL variables
        if(prodSrch == '' && price == ''){
            priceListTable = False;
            apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Please enter a Material Number and Price...'));
        }
        else{
            if(prodSrch == '' || price == ''){
                priceListTable = False;
                if(prodSrch == ''){
                    apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Please enter a Material Number...'));
                }

                if(price == ''){
                    apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Please enter a price...'));
                }

            }
            else{
                if(prodSrch <> null && price <> null){
                    priceListTable = False;
                    //prodRet = [SELECT Name,Description,Cost__c,Sales_Unit__c,Qty_Sales_Unit__c,Transfer_Price__c FROM PRODUCT2 WHERE Name = :prodSrch LIMIT 1];

                    System.debug('prodSrch ===================================== ' + prodSrch);
                    prodRet = [SELECT Name,Description,Cost__c,Sales_Unit__c,Qty_Sales_Unit__c,Transfer_Price__c, Sales_Org_Key__c, Cost_Price_Unit__c,
                                Cost_Formula__c, Cost_Price__c
                              FROM PRODUCT2
                              WHERE Name = :prodSrch AND Sales_Org_Key__c =:myActiveSalesOrg LIMIT 1];
                    System.debug('prodRet ===================================== ' + prodRet);
                    if(prodRet.size()>0 ){
                        System.debug('IM IN IF =====================================');
                        //check if list has values
                        System.debug('prodRet ===================================== ' + prodRet);
                        //System.debug('myDecimal ===================================== ' + myDecimal);
                        priceListTable = True; //set Boolean to true due to list having value

                        if(prodRet[0].Qty_Sales_Unit__c == 0){
                            prodRet[0].Qty_Sales_Unit__c = 1;
                        }

                        //logic to check Cost Price Unit value
                        if(prodRet[0].Cost_Price_Unit__c == NULL){
                            convUnit = 1000;
                        }else{
                            convUnit = Integer.valueOf(prodRet[0].Cost_Price_Unit__c);
                        }

                        system.debug('*** prodRet[0].Cost__c *** ' + prodRet[0].Cost__c);
                        system.debug('*** convUnit *** ' + convUnit);
                        system.debug('*** prodRet[0].Transfer_Price__c *** ' + prodRet[0].Transfer_Price__c);
                        Decimal convertedCost = 0;
                        newCost = (prodRet[0].Cost__c/convUnit) - prodRet[0].Transfer_Price__c;
                        newCost *= prodRet[0].Qty_Sales_Unit__c;
                        system.debug('*** newCost *** ' + newCost);
                        if(!price.isNumeric() ){
                          priceListTable = False;
                          apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Please enter a numeric value for price...'));
                        }
                        else{
                          Decimal myDecimal = decimal.valueOf(price);
                          if(myDecimal == 0){
                              priceListTable = False;
                              apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Please enter a price other than 0...'));
                          }
                          else if(myDecimal == NULL){
                            priceListTable = False;
                            apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Invalid Price Entered...'));
                          }
                          else{
                              grossMargin = ((myDecimal - newCost)/(myDecimal)).setScale(3) *100;
                              grossMargin = grossMargin.stripTrailingZeros();
                          }
                      }
                    }
                    else{
                        System.debug('IM IN ELSE =====================================');
                        priceListTable = False;
                        apexPages.addmessage(new apexpages.message(apexpages.severity.Error, 'Material not found...'));
                    }
                    System.debug('THE END =====================================');

                }
            }
        }
    }
}