fullSandbox11072023/force-app/main/default/objects/Contract_User__c/Contract_User__c.object-meta.xml
<CustomObject>
    <description>This is the Contract User object renamed to Pricing Portal User.</description>
    <label>Pricing Portal Users</label>
    <nameField>
        <label>Contract User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Portal Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Active_Region__c.field-meta.xml
<CustomField>
    <fullName>Active_Region__c</fullName>
    <inlineHelpText>This only drives material visibility</inlineHelpText>
    <label>Active Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AT - Austria</fullName>
            </value>
            <value>
                <fullName>AU - Australia</fullName>
            </value>
            <value>
                <fullName>BE - Belgium</fullName>
            </value>
            <value>
                <fullName>BR - Brazil</fullName>
            </value>
            <value>
                <fullName>CA - Canada</fullName>
            </value>
            <value>
                <fullName>CL - Chile</fullName>
            </value>
            <value>
                <fullName>CO - Colombia</fullName>
            </value>
            <value>
                <fullName>CZ - Czech</fullName>
            </value>
            <value>
                <fullName>DE - Germany</fullName>
            </value>
            <value>
                <fullName>ES - Spain</fullName>
            </value>
            <value>
                <fullName>IE - Ireland</fullName>
            </value>
            <value>
                <fullName>LA - Latin America</fullName>
            </value>
            <value>
                <fullName>MX - Mexico</fullName>
            </value>
            <value>
                <fullName>NL - Netherlands</fullName>
            </value>
            <value>
                <fullName>NZ - New Zealand</fullName>
            </value>
            <value>
                <fullName>PL - Poland</fullName>
            </value>
            <value>
                <fullName>PT - Portugal</fullName>
            </value>
            <value>
                <fullName>SK - Slovakia</fullName>
            </value>
            <value>
                <fullName>UK - United Kingdom</fullName>
            </value>
            <value>
                <fullName>US - Teleflex</fullName>
                <default>true</default>
                <label>US - Teleflex</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/AT_Material__c.field-meta.xml
<CustomField>
    <fullName>AT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Austria sales org access.</description>
    <inlineHelpText>Austria sales org access.</inlineHelpText>
    <label>AT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/AU_Material__c.field-meta.xml
<CustomField>
    <fullName>AU_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AU Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/BE_Material__c.field-meta.xml
<CustomField>
    <fullName>BE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Belgium sales org access.</description>
    <inlineHelpText>Belgium sales org access.</inlineHelpText>
    <label>BE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/BR_Material__c.field-meta.xml
<CustomField>
    <fullName>BR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Brazil</description>
    <inlineHelpText>Brazil</inlineHelpText>
    <label>BR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CA_Material__c.field-meta.xml
<CustomField>
    <fullName>CA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CH_Material__c.field-meta.xml
<CustomField>
    <fullName>CH_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Switzerland sales org access.</description>
    <inlineHelpText>Switzerland sales org access.</inlineHelpText>
    <label>CH Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CL_Material__c.field-meta.xml
<CustomField>
    <fullName>CL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CO_Material__c.field-meta.xml
<CustomField>
    <fullName>CO_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CO Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/CZ_Material__c.field-meta.xml
<CustomField>
    <fullName>CZ_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Czech sales org access.</description>
    <inlineHelpText>Czech sales org access.</inlineHelpText>
    <label>CZ Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/DE_Material__c.field-meta.xml
<CustomField>
    <fullName>DE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Grants access to DE10 Sales Org.</description>
    <inlineHelpText>Grants access to DE10 Sales Org.</inlineHelpText>
    <label>DE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Division_10__c.field-meta.xml
<CustomField>
    <fullName>Division_10__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Respiratory and Anesthesia (TFX only)</inlineHelpText>
    <label>US Division 10</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/ES_Material__c.field-meta.xml
<CustomField>
    <fullName>ES_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Spain sales org access.</description>
    <inlineHelpText>Spain sales org access.</inlineHelpText>
    <label>ES Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/FR_Material__c.field-meta.xml
<CustomField>
    <fullName>FR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>France sales org access.</description>
    <inlineHelpText>France sales org access.</inlineHelpText>
    <label>FR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/GR_Material__c.field-meta.xml
<CustomField>
    <fullName>GR_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Greece sales org access.</description>
    <inlineHelpText>Greece sales org access.</inlineHelpText>
    <label>GR Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/IE_Material__c.field-meta.xml
<CustomField>
    <fullName>IE_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ireland sales org access.</description>
    <inlineHelpText>Ireland sales org access.</inlineHelpText>
    <label>IE Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/IT_Material__c.field-meta.xml
<CustomField>
    <fullName>IT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Italy sales org access.</description>
    <inlineHelpText>Italy sales org access.</inlineHelpText>
    <label>IT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/LA_Material__c.field-meta.xml
<CustomField>
    <fullName>LA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/MX_Material__c.field-meta.xml
<CustomField>
    <fullName>MX_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MX Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/NL_Material__c.field-meta.xml
<CustomField>
    <fullName>NL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Netherlands sales org access.</description>
    <inlineHelpText>Netherlands sales org access.</inlineHelpText>
    <label>NL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/NZ_Material__c.field-meta.xml
<CustomField>
    <fullName>NZ_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NZ Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/PL_Material__c.field-meta.xml
<CustomField>
    <fullName>PL_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Poland sales org access.</description>
    <inlineHelpText>Poland sales org access.</inlineHelpText>
    <label>PL Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Pricing_Portal_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Portal_Access__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Pricing Portal Access</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Pricing_Tier_Access__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier_Access__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>1 = “Pricing Tier 1 - Rep&quot;
2 = “Pricing Tier 2 - Manager&quot;
3 = “Pricing Tier 3 - Director&quot;
4 = “Pricing Tier 4 - VP&quot;</inlineHelpText>
    <label>Pricing Tier Access</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/PT_Material__c.field-meta.xml
<CustomField>
    <fullName>PT_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Portugal sales org access.</description>
    <inlineHelpText>Portugal sales org access.</inlineHelpText>
    <label>PT Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/SA_Material__c.field-meta.xml
<CustomField>
    <fullName>SA_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>South Africa sales org access.</description>
    <inlineHelpText>South Africa sales org access.</inlineHelpText>
    <label>SA Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/SK_Material__c.field-meta.xml
<CustomField>
    <fullName>SK_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Slovakia sales org access.</description>
    <inlineHelpText>Slovakia sales org access.</inlineHelpText>
    <label>SK Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/UK_Material__c.field-meta.xml
<CustomField>
    <fullName>UK_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Grants access to UK10 Sales Org.</description>
    <inlineHelpText>Grants access to UK10 Sales Org.</inlineHelpText>
    <label>UK Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Update_Type__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <description>Field used by APEX to filter Sales Org updates vs. User Updates.</description>
    <inlineHelpText>Field used by APEX to filter Sales Org updates vs. User Updates.</inlineHelpText>
    <label>Update Type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/US_Material__c.field-meta.xml
<CustomField>
    <fullName>US_Material__c</fullName>
    <defaultValue>false</defaultValue>
    <label>US Material</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Contract_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Buom__c.field-meta.xml
<CustomField>
    <fullName>Buom__c</fullName>
    <label>Buom</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Each_per_Case__c.field-meta.xml
<CustomField>
    <fullName>Each_per_Case__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Each per Case</description>
    <inlineHelpText>Each per Case</inlineHelpText>
    <label>Each per Case</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <externalId>true</externalId>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Material_Status__c.field-meta.xml
<CustomField>
    <fullName>Material_Status__c</fullName>
    <description>Gives the status of the material</description>
    <label>Material Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/Material_Status_Numeric__c.field-meta.xml
<CustomField>
    <fullName>Material_Status_Numeric__c</fullName>
    <description>SAP: X-distr.chain status</description>
    <inlineHelpText>Saleable Statuses: 40, 60, Z1, Z8, and Z5 when List &gt; Zero.</inlineHelpText>
    <label>Material Status Numeric</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/Product2/fields/UOM__c.field-meta.xml
<CustomField>
    <fullName>UOM__c</fullName>
    <description>Sales Unit of Measure 
CS - Case
EA - Each</description>
    <inlineHelpText>Sales Unit of Measure 
CS - Case
EA - Each</inlineHelpText>
    <label>UOM</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/PP_Margin_Calculator_Test.cls
/*********************************************************************
* Description      : Test coverage for Pricing Portal Margin Calculator.
* Coverage         : Classes(PP_Margin_Calculator)
* Author(s)        : Dun Silver
**********************************************************************/
@isTest
public class PP_Margin_Calculator_Test {

    static testmethod void PP_Margin_Calculator_UnitTest(){

        //createUser(String firstName, String lastName, String approvalRole, String bu)
        User u = testDataFactoryPP.createUser('Adam','Franks','Sales VP','Anesthesia');
        insert u;

        User u1 = testDataFactoryPP.createUser('Testfn1','Testln1','Sales Rep','Anesthesia');
        insert u1;
        
        User u2 = testDataFactoryPP.createUser('Testfn2','Testln2','Sales Manager','Anesthesia');
        insert u2;
        
        User u3 = testDataFactoryPP.createUser('Testfn3','Testln3','Sales Director','Anesthesia');
        insert u3;
        
        User u4 = testDataFactoryPP.createUser('Testfn4','Testln4','Sales VP','Anesthesia');
        insert u4;

        Test.startTest();
        System.runAs(u){
             //create a contract user record
            Contract_User__c cu = new Contract_User__c(
                Name = 'Adam Franks',
                User__c = u.id,
                Active_Region__c = 'US - Teleflex',
                US_Material__c = TRUE,
                CA_Material__c = TRUE,
                MX_Material__c = TRUE,
                LA_Material__c = TRUE,
                CL_Material__c = TRUE,
                AU_Material__c = TRUE,
                NZ_Material__c = TRUE,
                Pricing_Portal_Access__c = TRUE,
                Pricing_Tier_Access__c = 1,
                CO_Material__c = TRUE,
                BR_Material__c = TRUE,
                DE_Material__c = TRUE,
                UK_Material__c = TRUE,
                AT_Material__c  = TRUE,
                BE_Material__c = TRUE,
                CH_Material__c = TRUE,
                CZ_Material__c = TRUE,
                ES_Material__c = TRUE,
                FR_Material__c = TRUE,
                GR_Material__c = TRUE,
                IT_Material__c = TRUE,
                NL_Material__c = TRUE,
                PL_Material__c = TRUE,
                SK_Material__c = TRUE,
                PT_Material__c = TRUE,
                IE_Material__c = TRUE,
                SA_Material__c = TRUE,
                Update_Type__c = NULL
                //Division_10__c = TRUE
            );
            insert cu;
            system.debug('CU:' + cu);

            Product2 prodTest = new Product2(Name = 'AA-10511-1',
                                            ProductCode= 'AA-10511-1',
                                            UOM__c='CS',
                                            Each_per_Case__c=5,
                                            Material_Status__c='MTS',
                                            Material_Status_Numeric__c='30',
                                            Family = 'Hardware',
                                            Material__c='AA-10511-1',
                                            Brand_Name__c='Arrow',
                                            Buom__c='EA',
                                            Class__c='Cardiac Care Specialty',
                                            Cost__c=11587.40,
                                            Cost_Price_Unit__c=1000,
                                            Division__c='60',
                                            Description='TRANSRADIAL ACCESS TRAY',
                                            Group__c='Interventional',
                                            SubGroup__c = 'TransRadial Access',
                                            Qty_Sales_Unit__c=0,
                                            Sales_Unit__c='CS',
                                            Transfer_Price__c=1000.00,
                                            List_Price__c=380.00,
                                            Rep_Price__c=350.00,
                                            RSM_Price__c=330.00,
                                            Sales_Org__c = 'US60',
                                            Distribution_Channel__c = '10',
                                            Sales_Org_Key__c = 'US6010',
                                            Material_Key__c = 'AA-10511-1-US60-10');
            insert prodTest;

            
            PageReference mc = Page.PP_Margin_Calculator;

            mc.getParameters().put('pid','');
            mc.getParameters().put('price','');
            Test.setCurrentPage(mc);
            PP_Margin_Calculator mcController = new PP_Margin_Calculator();

            String activeSalesOrg = mcController.myActiveSalesOrg;
            // Assert the results
            System.assertEquals('US6010', activeSalesOrg); // Replace 'US6010' with your expected result

            mcController.prodSrch = '';
            mcController.price = '';
            mcController.grossMargin = 0;
            mcController.getURL();
            List<Apexpages.Message> msgs = ApexPages.getMessages();
            boolean err = false;
            for(Apexpages.Message msg:msgs){
                if (msg.getDetail().contains('Please enter a Material Number and Price...')){
                    err = true;
                }
            }
            System.assert(err);
            Double myCost = mcController.newCost;
            //String mySalesKey = mcController.myActiveSalesOrg;
            Boolean priceListTable = mcController.priceListTable;
            
            PageReference mc0 = Page.PP_Margin_Calculator;
            mc0.getParameters().put('pid','AA-10511-1');
            mc0.getParameters().put('price','');
            Test.setCurrentPage(mc0);
            PP_Margin_Calculator mcController0 = new PP_Margin_Calculator();
            mcController0.prodSrch = 'AA-10511-1';
            mcController0.price = '';
            mcController0.getURL();
            msgs = ApexPages.getMessages();
            err = false;
            for(Apexpages.Message msg:msgs){
                if (msg.getDetail().contains('Please enter a price...')){
                    err = true;
                }
            }
            system.assert(err);
            mc.getParameters().put('pid','');
            mc.getParameters().put('price','200');
            Test.setCurrentPage(mc);
            mcController = new PP_Margin_Calculator();
            mcController.prodSrch = '';
            mcController.price = '200';

            mcController.priceListTable = True;
            priceListTable = mcController.priceListTable;

            mcController.getURL();
            msgs = ApexPages.getMessages();
            err = false;
            for(Apexpages.Message msg:msgs){
                if (msg.getDetail().contains('Please enter a Material Number...')){
                    err = true;
                }
            }
            system.assert(err);

            PageReference mc1 = Page.PP_Margin_Calculator;
            mc1.getParameters().put('pid','AA-10511-1');
            mc1.getParameters().put('price','0');
            Test.setCurrentPage(mc1);
            PP_Margin_Calculator mcController1 = new PP_Margin_Calculator();
            mcController1.prodSrch = 'AA-10511-1';
            mcController1.price = '0';
            mcController1.getURL();
            msgs = ApexPages.getMessages();
            err = true;
            for(Apexpages.Message msg:msgs){
                if (msg.getDetail().contains('Please enter a price other than 0...')){
                    err = true;
                }
            }
            system.assert(err);

            PageReference mc2 = Page.PP_Margin_Calculator;
            mc2.getParameters().put('pid','AA-10511-1');
            mc2.getParameters().put('price','200');
            Test.setCurrentPage(mc2);
            PP_Margin_Calculator mcController2 = new PP_Margin_Calculator();
            mcController2.getURL();
            //mcController2.newCost;

            PageReference mc3 = Page.PP_Margin_Calculator;
            mc3.getParameters().put('pid','adfdafd');
            mc3.getParameters().put('price','200');
            Test.setCurrentPage(mc3);
            PP_Margin_Calculator mcController3 = new PP_Margin_Calculator();
            mcController3.getURL();
            msgs = ApexPages.getMessages();
            err = false;
            for(Apexpages.Message msg:msgs){
                if (msg.getDetail().contains('Material not found...')){
                    err = true;
                }
            }
            system.assert(err);
        }//end System.runAs
        Test.stopTest();
	}// End of static testmethod void PP_Margin_Calculator_UnitTest()
}