fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/MANTA_Proctorship_Request__c.object-meta.xml
<CustomObject>
    <label>MANTA Proctorship Request</label>
    <nameField>
        <displayFormat>MPR-{00000}</displayFormat>
        <label>MANTA Proctorship Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MANTA Proctorship Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Case_Initiator__c.field-meta.xml
<CustomField>
    <fullName>Case_Initiator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Initiator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MANTA_Proctorship_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MANTA Proctorship Requests</relationshipLabel>
    <relationshipName>MANTA_Proctorship_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/is5daysPastCaseDate__c.field-meta.xml
<CustomField>
    <fullName>is5daysPastCaseDate__c</fullName>
    <formula>IF( Case_Date__c + 5 &lt;  TODAY() , true, false )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>is5daysPastCaseDate</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/isArchived__c.field-meta.xml
<CustomField>
    <fullName>isArchived__c</fullName>
    <formula>IF( Case_Date__c &lt;= (TODAY() - 14) , true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isArchived</label>
    <type>Checkbox</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/isReqHaveCaseRecs__c.field-meta.xml
<CustomField>
    <fullName>isReqHaveCaseRecs__c</fullName>
    <label>isReqHaveCaseRecs</label>
    <summaryForeignKey>MANTA_Case_Data__c.MANTA_Proctorship_Request__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Physician</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MANTA Proctorship Requests</relationshipLabel>
    <relationshipName>MANTA_Proctorship_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Proctor__c.field-meta.xml
<CustomField>
    <fullName>Proctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MANTA_Proctorship_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

fullSandbox11072023/force-app/main/default/objects/MANTA_Proctorship_Request__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

fullSandbox11072023/force-app/main/default/classes/MANTARequestCaseDataRecsBatch.cls
global class MANTARequestCaseDataRecsBatch implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
    
    private List<MANTA_Proctorship_Request__c> notifyTrainersToAddCaseDataRecsLst = new List<MANTA_Proctorship_Request__c>();
    
    /*constructor
    public batchExample(String passedString) {
        System.debug('- Constructor: Begin -');
        System.debug('- Constructor: End -');
    }
	*/
    
    //the "start" method is called at the beginning of a batch Apex job
    //use this method to collect the records (of objects) to be passed to the "execute" method for processing
    public Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('- start: Begin -');
        System.debug('notifyTrainersToAddCaseDataRecsLst.size(): '+notifyTrainersToAddCaseDataRecsLst.size());
        System.debug('- start: End -');
        return Database.getQueryLocator('select id, isReqHaveCaseRecs__c, is5daysPastCaseDate__c, Proctor__c, Proctor__r.Name, Hospital__c, Hospital__r.Name, Case_Date__c, Case_Initiator__r.Name ,Physician__c, Physician__r.Name, Region__c  from MANTA_Proctorship_Request__c where isReqHaveCaseRecs__c=0 and is5daysPastCaseDate__c=true and status__c=\'Accepted\' and isArchived__c=false '); //return the query locator
    }
    

                                        																												
    
    //the "execute" method is called after the "start" method has been invoked and passed a batch of records
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        System.debug('- execute: Begin -');
        for (SObject s : scope) { //for all sObjects in the batch
            MANTA_Proctorship_Request__c m = (MANTA_Proctorship_Request__c)s; //cast the MANTA_Proctorship_Request__c object from the scope
            if(!String.isBlank(m.Proctor__c)){notifyTrainersToAddCaseDataRecsLst.add(m);}
            System.debug('notifyTrainersToAddCaseDataRecsLst.size(): '+notifyTrainersToAddCaseDataRecsLst.size());
        }
        System.debug('- execute: End -');
    }
    
    //the "finish" method is called once all the batches are processed
    public void finish(Database.BatchableContext bc) {
        System.debug('- finish: Begin -');
        System.debug('notifyTrainersToAddCaseDataRecsLst: '+notifyTrainersToAddCaseDataRecsLst);
        
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
        
        OrgWideEmailAddress orgEm = [select Id, Address from OrgWideEmailAddress WHERE Address='manta@teleflex.com'];
        User admUsr = [select id from user where name like '%Surya Arvan%'];
        
        for (MANTA_Proctorship_Request__c mantaObj : notifyTrainersToAddCaseDataRecsLst) {
        
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();

            message.setToAddresses(new String[] {mantaObj.Proctor__c});
            message.setBccAddresses(new String[] {admUsr.Id});
            message.setOrgWideEmailAddressId(orgEm.Id);   
            message.setReplyTo('manta@teleflex.com');
            message.optOutPolicy = 'SEND';
            message.subject = 'Case Data Records not entered yet';
            message.htmlbody = 'Hello '+ mantaObj.Proctor__r.Name+',<br/><br/>'
                +'You are being notified that your Hospital request is pending to be added with Case Data Records.<br/> '
                +'Hospital:'+ mantaObj.Hospital__r.Name+' <br/>'
                +'Region:' + mantaObj.Region__c+' <br/>'
                +'Case Date:' + mantaObj.Case_Date__c+' <br/>'
                +'Physician:' + mantaObj.Physician__r.Name+' <br/>'
                +'Case Initiator:' + mantaObj.Case_Initiator__r.Name+' <br/>';
            
        messages.add(message);
        
        }
        
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            if (results[0].success) {
                System.debug('The email was sent successfully.');
            } else {
                System.debug('The email failed to send: '
                             + results[0].errors[0].message);
            }
        
        
        System.debug('- finish: End -');
    }
    
    global void execute(SchedulableContext sc)
    {
        MANTARequestCaseDataRecsBatch btch = new MANTARequestCaseDataRecsBatch();
		Database.executeBatch(btch);
    }

}